/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogos;

import Conexion.ExeSql;
import Formularios.fmMain;
import java.awt.Color;
import java.awt.Component;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Roberto Lopez
 */
public class jdCompara extends javax.swing.JDialog {
    
    public static Color DARK_GREEN = new Color(0,153,0);
    
    private String RutDoc;
    private String NumDoc;
    private String TipDoc;
    
    private String tipodoc = "FAC";
    private String tipo2 = "FAC";
    private String libro = "V";

     
   
    public jdCompara(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
   //     Comparar();
       
        Calendar c = Calendar.getInstance();
        cbAgno.setSelectedItem(Integer.toString(c.get(Calendar.YEAR))); 
        cbMes.setSelectedIndex((c.get(Calendar.MONTH))); 
        
        
        
        jPanel1.setVisible(false);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        gdp = new javax.swing.JRadioButton();
        fap = new javax.swing.JRadioButton();
        todos = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        gdp1 = new javax.swing.JRadioButton();
        fap1 = new javax.swing.JRadioButton();
        todos1 = new javax.swing.JRadioButton();
        gdp2 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Grilla2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        Grilla3 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbAgno = new javax.swing.JComboBox<String>();
        cbMes = new javax.swing.JComboBox<String>();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbBlanco = new javax.swing.JLabel();
        lbVerde = new javax.swing.JLabel();
        lbRojo = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbAzul = new javax.swing.JLabel();

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Grilla.setAutoCreateRowSorter(true);
        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro.Docto", "Fecha Emision", "Iva", "Diferencia", "estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(4).setMinWidth(0);
            Grilla.getColumnModel().getColumn(4).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ventas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        buttonGroup1.add(gdp);
        gdp.setSelected(true);
        gdp.setText("Factura Afecta Electrónica");
        gdp.setToolTipText("");
        gdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gdpActionPerformed(evt);
            }
        });

        buttonGroup1.add(fap);
        fap.setText("Nota de Crédito Afecta Electrónica");
        fap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fapActionPerformed(evt);
            }
        });

        buttonGroup1.add(todos);
        todos.setText("Nota de Crédito Afecta Electrónica (Sin Derecho A Crédito)");
        todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fap, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gdp, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(todos, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gdp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(todos)
                .addGap(24, 24, 24))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Compras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        buttonGroup1.add(gdp1);
        gdp1.setText("Factura Afecta Electrónica");
        gdp1.setToolTipText("");
        gdp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gdp1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(fap1);
        fap1.setText("Nota de Crédito Afecta Electrónica");
        fap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fap1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(todos1);
        todos1.setText("Factura Afecta Electrónica (Gastos)");
        todos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todos1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(gdp2);
        gdp2.setText("Factura Afecta Parcial");
        gdp2.setToolTipText("");
        gdp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gdp2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gdp1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fap1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gdp2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(todos1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gdp1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gdp2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fap1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(todos1)
                .addContainerGap())
        );

        Grilla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Grilla2);

        Grilla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(Grilla3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        jLabel2.setText("SELECCIONE MES");

        jLabel1.setText("SELECCIONE AÑO");

        cbAgno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        cbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jPanel7.setBackground(new java.awt.Color(255, 0, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setPreferredSize(new java.awt.Dimension(24, 20));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 204, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setPreferredSize(new java.awt.Dimension(24, 16));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setPreferredSize(new java.awt.Dimension(24, 16));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Documentos con diferencia en monto del IVA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Documentos están en el SII pero no están en el ERP Luvaly");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Documentos están en el ERP Luvaly pero no están en el SII");

        lbBlanco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbBlanco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBlanco.setText("0");
        lbBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbVerde.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbVerde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbVerde.setText("0");
        lbVerde.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbRojo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbRojo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRojo.setText("0");
        lbRojo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel9.setBackground(new java.awt.Color(0, 51, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setPreferredSize(new java.awt.Dimension(24, 20));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Documentos sin diferencia en monto del IVA");

        lbAzul.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbAzul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAzul.setText("0");
        lbAzul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAgno, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbAgno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(lbBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanel2.getAccessibleContext().setAccessibleName("");
        jPanel2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GrillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaMouseClicked
        
        if(evt.getClickCount()==2 && !Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString().isEmpty()){
        
            SelCodigo();
        }        
    }//GEN-LAST:event_GrillaMouseClicked

    private void gdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gdpActionPerformed
        
        tipodoc = "FAC";
        tipo2 = "FAC";
        libro = "V";
               
        Comparar();
    }//GEN-LAST:event_gdpActionPerformed

    private void fapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fapActionPerformed
        
        tipodoc = "NCC";
        tipo2 = "NCC";
        libro = "V";
        
        Comparar();
    }//GEN-LAST:event_fapActionPerformed

    private void todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosActionPerformed
        
        tipodoc = "NCC";
        tipo2 = "NCS";
        libro = "V";
               
        Comparar();
    }//GEN-LAST:event_todosActionPerformed

    private void gdp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gdp1ActionPerformed
        
        tipodoc = "FAP";
        tipo2 = "FAE";
        libro = "C";
        
        Comparar();
        
    }//GEN-LAST:event_gdp1ActionPerformed

    private void fap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fap1ActionPerformed
        
        tipodoc = "NCP";
        tipo2 = "NCP";
        libro = "C";
        
        Comparar();
    }//GEN-LAST:event_fap1ActionPerformed

    private void todos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todos1ActionPerformed
         tipodoc = "FAG";
         tipo2 = "FAG";
         libro = "C";
         
         Comparar();
    }//GEN-LAST:event_todos1ActionPerformed

    private void gdp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gdp2ActionPerformed
               
        tipodoc = "FAP";
        tipo2 = "FAR";
        libro = "C";
        
        Comparar();
        
    }//GEN-LAST:event_gdp2ActionPerformed
    
    public void SelCodigo(){
        NumDoc = (String) Grilla.getValueAt(Grilla.getSelectedRow(), 1);
        RutDoc = (String) Grilla.getValueAt(Grilla.getSelectedRow(), 0);
        TipDoc = (String) Grilla.getValueAt(Grilla.getSelectedRow(), 2);
        dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdCompara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdCompara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdCompara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdCompara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdCompara dialog = new jdCompara(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void Comparar() {

        ExeSql Sql = new ExeSql();
        ResultSet Rs, Rs2, Rs3 = null;
       
        double diferencia = 0.00;
        double cant1, cant2 = 0.00; 
        int i = 0;
        int j = 0;
        int k = 0;
        int l = 0;
        
        String cod = "0";
        
        String Query = "";
        String Query2 = "";
        String Query3 = "" ;
               
        DefaultTableModel Modelo1 = (DefaultTableModel) Grilla.getModel();
        DefaultTableModel Modelo2 = (DefaultTableModel) Grilla2.getModel();
        DefaultTableModel Modelo3 = (DefaultTableModel) Grilla3.getModel();
        fmMain.LimpiaGrilla(Modelo1);
        
        try{
            
            if (libro.equals("V")){
            
                Query = "SELECT cl.nrodocto,cl.femision, cl.totaliva, ctc.totaliva AS iva2 FROM conta_libros cl \n"+                        //Documentos que están en ambas tablas
                        "LEFT JOIN ctactecli ctc ON cl.rut = ctc.rut AND cl.nrodocto = ctc.nrodocto AND cl.femision = ctc.femision \n"+    
                        "WHERE cl.agno= "+ cbAgno.getSelectedItem() + "\n"+ 
                        "AND cl.mes = "+ (cbMes.getSelectedIndex()+1) + "\n" +
                        "AND cl.tipo2 IN ('"+tipo2+"')"+
                        "AND ctc.nrodocto IS NOT NULL \n" +
                        "AND ctc.totaliva IS NOT NULL \n"; 
                                               
                        
                     //   "AND cl.totaliva <> ctc.totaliva";
                    
            
                Query2 = "SELECT cl.nrodocto,cl.femision, cl.totaliva FROM conta_libros cl\n" +             //Documentos que están en SII pero no en el ERP (verde)
                         "WHERE NOT EXISTS(SELECT  * FROM  ctactecli ctc WHERE cl.rut = ctc.rut AND cl.nrodocto = ctc.nrodocto AND cl.femision = ctc.femision )\n" +
                         "AND cl.agno = "+ cbAgno.getSelectedItem() + "\n"+ 
                         "AND cl.mes = "+ (cbMes.getSelectedIndex()+1) + "\n" +
                         "AND cl.tipo2 IN ('"+tipo2+"')";
            
            
                Query3 = "SELECT ctc.nrodocto,ctc.femision, ctc.totaliva FROM ctactecli ctc\n" +        //Documentos que están en el ERP pero no en SII
                         "WHERE NOT EXISTS(SELECT  * FROM conta_libros cl WHERE ctc.rut = cl.rut AND ctc.nrodocto = cl.nrodocto AND ctc.femision = cl.femision )\n" +
                         "AND EXTRACT(YEAR FROM ctc.femision) = "+ cbAgno.getSelectedItem() + "\n"+ 
                         "AND EXTRACT(MONTH FROM ctc.femision) = "+ (cbMes.getSelectedIndex()+1) + "\n" +
                         "AND ctc.tipdocto IN ('"+tipodoc+"')";
            
            }else if (libro.equals("C")){
                
                Query = "SELECT cl.nrodocto,cl.femision, cl.totaliva, ctp.totaliva AS iva2 FROM conta_libros cl \n"+                        //Documentos que están en ambas tablas
                        "LEFT JOIN ctacteprv ctp ON cl.rut = ctp.rut AND cl.nrodocto = ctp.nrodocto AND cl.femision = ctp.femision \n"+    
                        "WHERE cl.agno= "+ cbAgno.getSelectedItem() + "\n"+ 
                        "AND cl.mes = "+ (cbMes.getSelectedIndex()+1) + "\n" +
                        "AND cl.tipo2 IN ('"+tipo2+"')"+
                        "AND ctp.nrodocto IS NOT NULL \n" +
                        "AND ctp.totaliva IS NOT NULL \n"; 
                        
                        if (tipo2.equals("FAR")){
          
                            Query = Query + " AND ctp.tipdocto IN ('FAG','FAP') AND cl.totalexento > 0";
                        } 
                        
                        if (tipo2.equals("FAE")){
          
                            Query = Query + " AND ctp.tipdocto IN ('FAG','FAP')";
                        } 
                        
                        
                        //Query = Query + " AND cl.totaliva <> ctp.totaliva";
            
                Query2 = "SELECT cl.nrodocto,cl.femision, cl.totaliva FROM conta_libros cl\n" +             //Documentos que están en SII pero no en el ERP
                         "WHERE NOT EXISTS(SELECT  * FROM  ctacteprv ctp WHERE cl.rut = ctp.rut AND cl.nrodocto = ctp.nrodocto AND cl.femision = ctp.femision )\n" +
                         "AND cl.agno = "+ cbAgno.getSelectedItem() + "\n"+ 
                         "AND cl.mes = "+ (cbMes.getSelectedIndex()+1) + "\n" +
                         "AND cl.tipo2 IN ('"+tipo2+"')";
                         
                         if (tipo2.equals("FAR")){
          
                            Query2 = Query2 + " AND cl.totalexento > 0";
                         }    
            
                Query3 = "SELECT ctp.nrodocto,ctp.femision, ctp.totaliva FROM ctacteprv ctp\n" +        //Documentos que están en el ERP pero no en SII
                         "WHERE NOT EXISTS(SELECT  * FROM conta_libros cl WHERE ctp.rut = cl.rut AND ctp.nrodocto = cl.nrodocto AND ctp.femision = cl.femision )\n" +
                         "AND EXTRACT(YEAR FROM ctp.femision) = " + cbAgno.getSelectedItem() + "\n"+ 
                         "AND EXTRACT(MONTH FROM ctp.femision) = " + (cbMes.getSelectedIndex()+1) + "\n" +
                         "AND ctp.tipdocto IN ('"+tipodoc+"')";
            
                         if (tipo2.equals("FAR")){
          
                            Query3 = Query3 + " AND ctp.totalexento > 0";
                         }    
            
            } 
            
            
            Rs = Sql.Select(Query);
            
            while(Rs.next()){
                  
                cant1 = Rs.getDouble("totaliva");     
                cant2 = Rs.getDouble("iva2");
           
                diferencia = cant1 - cant2;
                
                if (diferencia == 0){
                
                    cod = "4";
                
                }else{
                
                    cod = "0";
                
                }
                
                
                Modelo1.addRow(new Object[]{Rs.getString("nrodocto"),
                                            Rs.getString("femision"),
                                            Math.round(cant1),
                                            Math.round(diferencia),
                                            cod
                });
                
                
                if (cod.equals("0")){
                
                   i++; 
                
                }else if (cod.equals("4")){
                    
                    l++;
                }
                
                                  
            }  
           
    //**********************************************************************************************************//       
            
            
            
            Rs2 = Sql.Select(Query2);
            
            while(Rs2.next()){
            
                
                cant1 = Rs2.getDouble("totaliva");     
              //  cant2 = Rs.getDouble("iva2");
           
             //   diferencia = cant1 - cant2;
                
                diferencia = 0;  
                Modelo2.addRow(new Object[]{Rs2.getString("nrodocto"),
                                            Rs2.getString("femision"),
                                            Math.round(cant1),
                                            Math.round(diferencia)
                });
                
                j++;
            }
            
            Rs3 = Sql.Select(Query3);
            
            while(Rs3.next()){
               
                
                cant1 = Rs3.getDouble("totaliva");     
              //  cant2 = Rs.getDouble("iva2");
           
              //   diferencia = cant1 - cant2;
                
                diferencia = 0;  
                Modelo3.addRow(new Object[]{Rs3.getString("nrodocto"),
                                            Rs3.getString("femision"),
                                            Math.round(cant1),
                                            Math.round(diferencia),
                                            "0"
                });
  
                k++;  
           }

          
           for (int g=0; g<=Modelo2.getRowCount()-1; g++ ){                        //Se cargan Productos que están en mt2 pero no en mt (verde)
               
               Modelo1.addRow(new Object[] { Modelo2.getValueAt(g, 0),
                                             Modelo2.getValueAt(g, 1),
                                             Modelo2.getValueAt(g, 2),
                                             Modelo2.getValueAt(g, 3),
                                             "1"
               });
              
           }
           
           
           Grilla.setDefaultRenderer(Object.class, new Elrender());    
            
            
           for (int h=0; h<=Modelo3.getRowCount()-1; h++ ){                        //Se cargan Productos que están en mt pero no en mt2 (rojo)
               
               Modelo1.addRow(new Object[] { Modelo3.getValueAt(h, 0),
                                             Modelo3.getValueAt(h, 1),
                                             Modelo3.getValueAt(h, 2),
                                             Modelo3.getValueAt(h, 3),
                                             "2"
               });
               
           }
           Grilla.setDefaultRenderer(Object.class, new Elrender()); 
           
              
           Grilla.changeSelection(0, 0 , false, false);
           Grilla2.changeSelection(0, 0 , false, false);
           Grilla3.changeSelection(0, 0 , false, false);
           
           Grilla.getSelectionModel().clearSelection();
           
           fmMain.LimpiaGrilla(Modelo2);
           fmMain.LimpiaGrilla(Modelo3);
           
           lbAzul.setText(""+l);
           lbBlanco.setText(""+i);
           lbVerde.setText(""+j);
           lbRojo.setText(""+k);
                    
        }
        catch (Exception e) {
            System.out.println(e.getMessage());
        } finally{
            Sql.Close();
        }
        
    }
   
    class Elrender extends DefaultTableCellRenderer {
         
        @Override
        public Component getTableCellRendererComponent(JTable tabla, Object valor, boolean isSelected, boolean hasFocus, int fila, int columna) {
        super.getTableCellRendererComponent(tabla,valor,isSelected, hasFocus, fila, columna);
         
            if(tabla.getValueAt(fila,4).equals("1")){
                
                this.setForeground(DARK_GREEN);
            
            }else if(tabla.getValueAt(fila,4).equals("2")){
                
                this.setForeground(Color.red);  
            
            }else if(tabla.getValueAt(fila,4).equals("0")){
                
                this.setForeground(Color.black);  
            
            }else if(tabla.getValueAt(fila,4).equals("4")){
                
                this.setForeground(Color.blue);  
            } 
            
            
            
            return this;
        }
    } 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla;
    private javax.swing.JTable Grilla2;
    private javax.swing.JTable Grilla3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbAgno;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JRadioButton fap;
    private javax.swing.JRadioButton fap1;
    private javax.swing.JRadioButton gdp;
    private javax.swing.JRadioButton gdp1;
    private javax.swing.JRadioButton gdp2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbAzul;
    private javax.swing.JLabel lbBlanco;
    private javax.swing.JLabel lbRojo;
    private javax.swing.JLabel lbVerde;
    private javax.swing.JRadioButton todos;
    private javax.swing.JRadioButton todos1;
    // End of variables declaration//GEN-END:variables
}
