/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Dialogos.jdFechaFeriados;
import Dialogos.jdOC_PendientesFac;
import PanelForm.pfProductosPosicion;
import Formularios.fmMain;
import static Formularios.fmMain.pnPestanas;
import Utilidades.Exporter;
import Utilidades.PanelTab;
import Utilidades.TableCellRendererPosicion;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Cdiaz
 */
public class pfReportePosiciones extends javax.swing.JPanel {
    
    int id_proveedor;
    int inicio = 0;
    /**
     * Creates new form pfCompraVenta
     */
    public pfReportePosiciones() {
        
        initComponents();
        CargaConvenios();
        Date date = new Date();
        dtDesde.setDate(yesterday());
        dtHasta.setDate(date);
        
    }
    
    private Date yesterday() {
    
        final Calendar cal = Calendar.getInstance();
        cal.add(Calendar.DATE, -1);
        return cal.getTime();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        VerProductos = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        dtDesde = new org.jdesktop.swingx.JXDatePicker();
        dtHasta = new org.jdesktop.swingx.JXDatePicker();
        jPanel2 = new javax.swing.JPanel();
        cbConvenio = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btBuscar = new javax.swing.JButton();
        btExcel = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lbcargando = new javax.swing.JLabel();

        VerProductos.setText("Ver Productos");
        VerProductos.setToolTipText("");
        VerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerProductosActionPerformed(evt);
            }
        });
        jPopupMenu1.add(VerProductos);

        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Grilla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        Grilla.setColumnSelectionAllowed(true);
        Grilla.setComponentPopupMenu(jPopupMenu1);
        Grilla.getTableHeader().setReorderingAllowed(false);
        Grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Grilla);
        Grilla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Rango", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        dtDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtDesdeActionPerformed(evt);
            }
        });

        dtHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtHastaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Convenio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        cbConvenio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Funciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btExcel.setText("Excel");
        btExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcelActionPerformed(evt);
            }
        });

        jButton3.setText("Feriado");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lbcargando.setText("Cargando");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btExcel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbcargando)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBuscar)
                    .addComponent(btExcel)
                    .addComponent(jButton3)
                    .addComponent(lbcargando))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dtHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtHastaActionPerformed
        
            //CargaGrillaAgrupados();
        
    }//GEN-LAST:event_dtHastaActionPerformed

    private void dtDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtDesdeActionPerformed
                    //CargaGrillaAgrupados();
        
    }//GEN-LAST:event_dtDesdeActionPerformed

    private void btExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcelActionPerformed
   
        
        if(Grilla.getRowCount()==0){
            fmMain.Mensaje("Nada que exportar");
            return;
        }

//        JFileChooser chooser = new JFileChooser();
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo Excel",".xls");
//        chooser.setFileFilter(filter);
//        chooser.setDialogTitle("Guardar Informe en Excel");
//        chooser.setMultiSelectionEnabled(false);
//        chooser.setAcceptAllFileFilterUsed(false);


        List<JTable> tb=new ArrayList<>();
        List<String> nom=new ArrayList<>();
        tb.add(Grilla);

        String nombre = "";
        if(cbConvenio.getSelectedIndex()>0){
            nombre = ("Posiciones - "+cbConvenio.getSelectedItem().toString());
        }
        else {
            nombre = ("Posiciones (Todos) - ");
        }
        nom.add(nombre);
        String str_convenio="conv";
        String str_proveedor="prov";
        String os = System.getProperty("os.name").toString().toLowerCase();
        System.out.println(os);
        File folder  = new File("c:/temp");
        String file = "";
        if(os.contains("win")){

            if (!folder.exists()){
                folder.mkdir();
            }
            file = "C:/temp/.xls";   
        }
        else{
            
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de excel", "xls");
            chooser.setSelectedFile(new File("/user",""+nombre+".xls"));
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar archivo");
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                file = chooser.getSelectedFile().toString().concat(".xls");
                try {
                    Exporter e = new Exporter(new File(file), tb, nom);
                    if (e.export()) {
                        JOptionPane.showMessageDialog(null, "Los datos fueron exportados en el directorio seleccionado", "Mensaje de Informacion", JOptionPane.INFORMATION_MESSAGE);
                        abrir(file);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Hubo un error " + e.getMessage(), " Error", JOptionPane.ERROR_MESSAGE);
                }
           }


        }
                
            
        try {
            Exporter e = new Exporter(new File(file), tb, nom);

            if(e.export())
            //fmMain.Mensaje("Datos Exportados");
            abrir(file);

        } catch (Exception e) {
            fmMain.Mensaje(e.getMessage());
        }
    }//GEN-LAST:event_btExcelActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        Runnable miRunnable = new Runnable() {
            public void run() {
                try{
                    Grilla.clearSelection();
                    lbcargando.setVisible(true);

 
                    CargaPosicion();
                    lbcargando.setVisible(false);
                    //Grilla.changeSelection(0, 0 , false, false);

                    
                } catch (Exception e) {
                    e.printStackTrace();
                    
                }
                
            }
        };
        Thread hilo = new Thread(miRunnable);
        hilo.start();
        lbcargando.setText("Cargando.....");
        URL urlInfo =  this.getClass().getResource("/Iconos16/wait.gif");
        ImageIcon IconoInfo =  new ImageIcon(urlInfo); 
        lbcargando.setIcon(IconoInfo);
        lbcargando.setForeground(Color.red);
        
        
    }//GEN-LAST:event_btBuscarActionPerformed
    
    public String Query(String fecha) {
        String Query = "select t.pos, count(t.pos) as count , t.fecha\n" +
                            "from \n" +
                            "(select asd.conteo as pos, asd.fecha\n" +
                            "from \n" +
                            "  (select ph.posicion as conteo, resultado.fecha,\n" +
                            "  CASE	\n" +
                            "    when date_part('dow', to_timestamp(to_char(resultado.fecha,'yyyy-MM-dd'),'yyyy-MM-dd')) = 1 then 'Lunes' || ' ' || resultado.fecha \n" +
                            "    when date_part('dow', to_timestamp(to_char(resultado.fecha,'yyyy-MM-dd'),'yyyy-MM-dd')) = 2 then 'Martes' || ' ' || resultado.fecha \n" +
                            "    when date_part('dow', to_timestamp(to_char(resultado.fecha,'yyyy-MM-dd'),'yyyy-MM-dd')) = 3 then 'Miercoles' || ' ' || resultado.fecha \n" +
                            "    when date_part('dow', to_timestamp(to_char(resultado.fecha,'yyyy-MM-dd'),'yyyy-MM-dd')) = 4 then 'Jueves' || ' ' || resultado.fecha \n" +
                            "    when date_part('dow', to_timestamp(to_char(resultado.fecha,'yyyy-MM-dd'),'yyyy-MM-dd')) = 5 then 'Viernes' || ' ' || resultado.fecha \n" +
                            "    when date_part('dow', to_timestamp(to_char(resultado.fecha,'yyyy-MM-dd'),'yyyy-MM-dd')) = 6 then 'Sábado' || ' ' || resultado.fecha \n" +
                            "    when date_part('dow', to_timestamp(to_char(resultado.fecha,'yyyy-MM-dd'),'yyyy-MM-dd')) = 0 then 'Domingo'  || ' ' || resultado.fecha \n" +
                            "  END AS dia,\n" +
                            "\n" +
                            "  case \n" +
                            "  	when date_part('dow', resultado.fecha) = 6 OR date_part('dow', resultado.fecha) = 0\n" +
                            "  	then 'Fin de Semana'\n" +
                            "  	else 'Día de Semana'\n" +
                            "  END as dia_semanacase,\n" +
                            "  case \n" +
                            "    when to_date(to_char(resultado.fecha,'YYYY/MM/DD'),'YYYY/MM/DD') in (select fecha_feriado from feriados)\n" +
                            "    then 'Feriado'\n" +
                            "    else 'No feriado'\n" +
                            "  end as feriado_check\n" +
                            "    \n" +
                            "    from codproducto_rel cre\n" +
                            "right join producto p on p.sku = cre.sku\n" +
                            "left join codchile cc on cc.sku = p.sku or cc.sku = cre.sku_rel\n" +
                            "left join producto_posicion_historico ph on ph.id = cc.idch\n" +
                            "left join par_convenio par on par.codigo = p.convenio\n"+
                            "  left join (select to_timestamp(to_char(generate_series((date '"+fecha+"')/**Rango Inicial**/,(date '"+fecha+"')/**Rango Final**/,interval '1 day'),'yyyy-MM-dd'),'yyyy-MM-dd') as fecha) resultado \n" +
                            "  	on resultado.fecha = to_timestamp(to_char(ph.fecha,'yyyy-MM-dd'),'yyyy-MM-dd')\n" +
       
                            "  where to_timestamp(to_char(ph.fecha,'yyyy-MM-dd'),'yyyy-MM-dd') in (select generate_series((date '"+fecha+"')/**Rango Inicial**/,(date '"+fecha+"')/**Rango Final**/,interval '1 day'))\n" +
                            "  and to_timestamp(to_char(ph.fecha,'yyyy-MM-dd'),'yyyy-MM-dd') not in (select to_timestamp(to_char(fecha_feriado,'yyyy-MM-dd'),'yyyy-MM-dd') from feriados )";
        
        String filtro = String.valueOf(cbConvenio.getSelectedIndex());
        if (!filtro.equals("0"))
            {
            Query = Query + " and ph.convenio = "+String.valueOf(cbConvenio.getSelectedIndex()+1)+"\n";
            }
        else{
            Query = Query + "";
        }
        
        Query = Query + " and p.es_cotiza = 0 and p.publicado is true) as asd\n" +
                    "where asd.dia_semanacase = 'Día de Semana') as t\n" +
                    "group by t.pos, t.fecha\n" +
                    "order by t.pos";
        
        return Query;
    }
    
    public void CargaPosicion() {
        ExeSql sql = new ExeSql();
        ExeSql sql2 = new ExeSql();
        ResultSet rs = null;
        ResultSet rs2 = null;
        
        
        
        //Query 2
        String Fecha_Query = "select distinct on (t.fecha)  t.fecha\n" +
                        "from \n" +
                        "(select asd.conteo as pos, asd.fecha\n" +
                        "from \n" +
                        "  (select ph.posicion as conteo, resultado.fecha,\n" +
                        "  CASE	\n" +
                        "    when date_part('dow', to_timestamp(to_char(resultado.fecha,'yyyy-MM-dd'),'yyyy-MM-dd')) = 1 then 'Lunes' || ' ' || resultado.fecha \n" +
                        "    when date_part('dow', to_timestamp(to_char(resultado.fecha,'yyyy-MM-dd'),'yyyy-MM-dd')) = 2 then 'Martes' || ' ' || resultado.fecha \n" +
                        "    when date_part('dow', to_timestamp(to_char(resultado.fecha,'yyyy-MM-dd'),'yyyy-MM-dd')) = 3 then 'Miercoles' || ' ' || resultado.fecha \n" +
                        "    when date_part('dow', to_timestamp(to_char(resultado.fecha,'yyyy-MM-dd'),'yyyy-MM-dd')) = 4 then 'Jueves' || ' ' || resultado.fecha \n" +
                        "    when date_part('dow', to_timestamp(to_char(resultado.fecha,'yyyy-MM-dd'),'yyyy-MM-dd')) = 5 then 'Viernes' || ' ' || resultado.fecha \n" +
                        "    when date_part('dow', to_timestamp(to_char(resultado.fecha,'yyyy-MM-dd'),'yyyy-MM-dd')) = 6 then 'Sábado' || ' ' || resultado.fecha \n" +
                        "    when date_part('dow', to_timestamp(to_char(resultado.fecha,'yyyy-MM-dd'),'yyyy-MM-dd')) = 0 then 'Domingo'  || ' ' || resultado.fecha \n" +
                        "  END AS dia,\n" +
                        "\n" +
                        "  case \n" +
                        "  	when date_part('dow', resultado.fecha) = 6 OR date_part('dow', resultado.fecha) = 0\n" +
                        "  	then 'Fin de Semana'\n" +
                        "  	else 'Día de Semana'\n" +
                        "  END as dia_semanacase,\n" +
                        "  case \n" +
                        "    when to_date(to_char(resultado.fecha,'YYYY/MM/DD'),'YYYY/MM/DD') in (select fecha_feriado from feriados)\n" +
                        "    then 'Feriado'\n" +
                        "    else 'No feriado'\n" +
                        "  end as feriado_check\n" +
                        "    \n" +
                        "  from producto_posicion_historico ph\n" +
                        "  left join (select to_timestamp(to_char(generate_series((date '"+getDesde()+"')/**Rango Inicial**/,(date '"+getHasta()+"')/**Rango Final**/,interval '1 day'),'yyyy-MM-dd'),'yyyy-MM-dd') as fecha) resultado \n" +
                        "  	on resultado.fecha = to_timestamp(to_char(ph.fecha,'yyyy-MM-dd'),'yyyy-MM-dd')\n" +
                        "    left join codproducto_rel cr on cr.sku_rel = ph.sku\n"+
                        "    inner join codchile ch on ch.sku = ph.sku and ch.idch = ph.id \n"+
                        "  where to_timestamp(to_char(ph.fecha,'yyyy-MM-dd'),'yyyy-MM-dd') in (select generate_series((date '"+getDesde()+"')/**Rango Inicial**/,(date '"+getHasta()+"')/**Rango Final**/,interval '1 day'))\n" +
                        "  and to_timestamp(to_char(ph.fecha,'yyyy-MM-dd'),'yyyy-MM-dd') not in (select to_timestamp(to_char(fecha_feriado,'yyyy-MM-dd'),'yyyy-MM-dd') from feriados )\n";
        
        String filtro2 = String.valueOf(cbConvenio.getSelectedIndex());
        if (!filtro2.equals("0"))
            {
            Fecha_Query = Fecha_Query + " and ph.convenio = "+String.valueOf(cbConvenio.getSelectedIndex()+1)+"\n";
            }
        else{
            Fecha_Query = Fecha_Query + "";
        }
        String[] fila_conteo = new String[]{"0","1","2","3","4","5","6","7","8","9","10",">=11","Suma"};
        
        Fecha_Query = Fecha_Query + " ) as asd\n" +
                                "where asd.dia_semanacase = 'Día de Semana') as t\n" +
                                "group by t.fecha, t.pos\n"; 
        
        
        String Query2 = "SELECT count(*) as conteo, \n" +
                        "CASE \n" + 
                        "WHEN pp.posicion IS NULL \n"+
                        "THEN '0' \n" +
                        "ELSE pp.posicion \n"+
                        "END as posicion \n" +
                        "FROM codchile cc \n"+
                        "LEFT JOIN producto_posicion_historico pp on pp.id = cc.idch and pp.fecha::date between '"+getDesde()+"' and '"+getHasta()+"' \n"+
                        "LEFT JOIN producto p on cc.sku = p.sku \n"+
                        "WHERE p.convenio = "+String.valueOf(cbConvenio.getSelectedIndex()+1)+" \n" +
                        "AND pp.posicion IS NULL \n"+
                        "GROUP BY pp.posicion" ;
        
        DefaultTableModel model = new DefaultTableModel(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
            
        };
        
        model.addColumn("Posición",fila_conteo);
        int conteo_cantidad = 0;
        int promedio_0 = 0; int cant_promedio_0 = 0;
        int promedio_1 = 0; int cant_promedio_1 = 0;
        int promedio_2 = 0; int cant_promedio_2 = 0;
        int promedio_3 = 0; int cant_promedio_3 = 0;
        int promedio_4 = 0; int cant_promedio_4 = 0;
        int promedio_5 = 0; int cant_promedio_5 = 0;
        int promedio_6 = 0; int cant_promedio_6 = 0;
        int promedio_7 = 0; int cant_promedio_7 = 0;
        int promedio_8 = 0; int cant_promedio_8 = 0;
        int promedio_9 = 0; int cant_promedio_9 = 0;
        int promedio_10 = 0; int cant_promedio_10 = 0;
        int promedio_11 = 0; int cant_promedio_11 = 0;
//        int promedio_12 = 0; int cant_promedio_12 = 0;
        try {
            
            rs2 = sql2.Select(Query2);
            rs2.next();
            
            
            rs = sql.Select(Fecha_Query);
            
            for(int i = 0; rs.next();i++){
                String[] conteo_valor = new String[fila_conteo.length];
                conteo_valor[12] = "0";
//                
                int suma = 0;
                
                conteo_valor[0] = rs2.getString("conteo");
                               
                conteo_cantidad = conteo_cantidad + 1;
                
                
                ExeSql sql_grilla = new ExeSql();
                ResultSet rs_grilla = sql_grilla.Select(Query(rs.getString("fecha")));
                
                
                for(int j = 0; rs_grilla.next();j++){
                        
                        int posicion = 0;
                     
                        switch(rs_grilla.getString("pos")){
                            case "1": posicion = 1; break;
                            case "2": posicion = 2; break;
                            case "3": posicion = 3; break;
                            case "4": posicion = 4; break;
                            case "5": posicion = 5; break;
                            case "6": posicion = 6; break;
                            case "7": posicion = 7; break;
                            case "8": posicion = 8; break;
                            case "9": posicion = 9; break;
                            case "10": posicion = 10; break;
                            default: posicion = 11; break;    

                        }
                        
                        if (posicion == 11){
                        
                            if (rs_grilla.getInt("pos") >= posicion) {
                             
                             suma = suma + rs_grilla.getInt("count");   
                             conteo_valor[posicion] = String.valueOf(suma); 
                              
                            }
                            
                        }else{
                        
                              conteo_valor[posicion] = rs_grilla.getString("count"); 
                            
                        
                        }
                        
                        System.out.println(rs_grilla.getString("pos")+": "+rs_grilla.getString("count"));
                        
                        

                }  
                for(int t = 0; t < conteo_valor.length;t++){
                   
                    if(conteo_valor[t]==null){
                        conteo_valor[t]="0";
                    }
                }
                
                for(int o = 0; o < conteo_valor.length-2;o++){

                    suma = suma + Integer.valueOf(conteo_valor[o]);
                }
//                
                  conteo_valor[12] = String.valueOf(suma);
                  model.addColumn(rs.getString("fecha"),conteo_valor);
            }
            
            Grilla.setModel(model);
            for(int j = 1; j < Grilla.getColumnCount(); j++){
                
                if(!Grilla.getValueAt(0, j).toString().equals("0")){
                    promedio_0 = promedio_0 + Integer.valueOf(Grilla.getValueAt(0, j).toString());
                    cant_promedio_0 = cant_promedio_0 + 1;
                }
                if(!Grilla.getValueAt(1, j).toString().equals("0")){
                    promedio_1 = promedio_1 + Integer.valueOf(Grilla.getValueAt(1, j).toString());
                    cant_promedio_1 = cant_promedio_1 + 1;
                }
                if(!Grilla.getValueAt(2, j).toString().equals("0")){
                    promedio_2 = promedio_2 + Integer.valueOf(Grilla.getValueAt(2, j).toString());
                    cant_promedio_2 = cant_promedio_2 + 1;
                }
                if(!Grilla.getValueAt(3, j).toString().equals("0")){
                    promedio_3 = promedio_3 + Integer.valueOf(Grilla.getValueAt(3, j).toString());
                    cant_promedio_3 = cant_promedio_3 + 1;
                }
                if(!Grilla.getValueAt(4, j).toString().equals("0")){
                    promedio_4 = promedio_4 + Integer.valueOf(Grilla.getValueAt(4, j).toString());
                    cant_promedio_4 = cant_promedio_4 + 1;
                }
                if(!Grilla.getValueAt(5, j).toString().equals("0")){
                    promedio_5 = promedio_5 + Integer.valueOf(Grilla.getValueAt(5, j).toString());
                    cant_promedio_5 = cant_promedio_5 + 1;
                }
                if(!Grilla.getValueAt(6, j).toString().equals("0")){
                    promedio_6 = promedio_6 + Integer.valueOf(Grilla.getValueAt(6, j).toString());
                    cant_promedio_6 = cant_promedio_6 + 1;
                }
                if(!Grilla.getValueAt(7, j).toString().equals("0")){
                    promedio_7 = promedio_7 + Integer.valueOf(Grilla.getValueAt(7, j).toString());
                    cant_promedio_7 = cant_promedio_7 + 1;
                }
                if(!Grilla.getValueAt(8, j).toString().equals("0")){
                    promedio_8 = promedio_8 + Integer.valueOf(Grilla.getValueAt(8, j).toString());
                    cant_promedio_8 = cant_promedio_8 + 1;
                }
                if(!Grilla.getValueAt(9, j).toString().equals("0")){
                    promedio_9 = promedio_9 + Integer.valueOf(Grilla.getValueAt(9, j).toString());
                    cant_promedio_9 = cant_promedio_9 + 1;
                }
                if(!Grilla.getValueAt(10, j).toString().equals("0")){
                    promedio_10 = promedio_10 + Integer.valueOf(Grilla.getValueAt(10, j).toString());
                    cant_promedio_10 = cant_promedio_10 + 1;
                }
                if(!Grilla.getValueAt(11, j).toString().equals("0")){
                    promedio_11 = promedio_11 + Integer.valueOf(Grilla.getValueAt(11, j).toString());
                    cant_promedio_11 = cant_promedio_11 + 1;
                }
//                if(!Grilla.getValueAt(12, j).toString().equals("0")){
//                    promedio_12 = promedio_12 + Integer.valueOf(Grilla.getValueAt(12, j).toString());
//                    cant_promedio_12 = cant_promedio_12 + 1;
//                }
            }
            
            int promedio_final_0 = 0;
            if(cant_promedio_0!=0){
                promedio_final_0 = promedio_0 / cant_promedio_0;
            }
            int promedio_final_1 = 0;
            if(cant_promedio_1!=0){
                promedio_final_1 = promedio_1 / cant_promedio_1;
            }
            int promedio_final_2 = 0;
            if(cant_promedio_2!=0){
                promedio_final_2 = promedio_2 / cant_promedio_2;
            }
            int promedio_final_3 = 0;
            if(cant_promedio_3!=0){
                promedio_final_3 = promedio_3 / cant_promedio_3;
            }
            int promedio_final_4 = 0;
            if(cant_promedio_4!=0){
                promedio_final_4 = promedio_4 / cant_promedio_4;
            }
            int promedio_final_5 = 0;
            if(cant_promedio_5!=0){
                promedio_final_5 = promedio_5 / cant_promedio_5;
            }
            int promedio_final_6 = 0;
            if(cant_promedio_6!=0){
                promedio_final_6 = promedio_6 / cant_promedio_6;
            }
            int promedio_final_7 = 0;
            if(cant_promedio_7!=0){
                promedio_final_7 = promedio_7 / cant_promedio_7;
            }
            int promedio_final_8 = 0;
            if(cant_promedio_8!=0){
                promedio_final_8 = promedio_8 / cant_promedio_8;
            }
            int promedio_final_9 = 0;
            if(cant_promedio_9!=0){
                promedio_final_9 = promedio_9 / cant_promedio_9;
            }
            int promedio_final_10 = 0;
            if(cant_promedio_10!=0){
                promedio_final_10 = promedio_10 / cant_promedio_10;
            }
            int promedio_final_11 = 0;
            if(cant_promedio_11!=0){
                promedio_final_11 = promedio_11 / cant_promedio_11;
            }
            int promedio_final_12 = 0;
//            if(cant_promedio_12!=0){
//                promedio_final_12 = promedio_12 / cant_promedio_12;
//            }
            
            model.addColumn("Promedio",new Object[]{
                promedio_final_0,
                promedio_final_1,
                promedio_final_2,
                promedio_final_3,
                promedio_final_4,
                promedio_final_5,
                promedio_final_6,
                promedio_final_7,
                promedio_final_8,
                promedio_final_9,
                promedio_final_10,
                promedio_final_11
//                promedio_final_12
            });
            

            TableColumn primeracolumna = Grilla.getColumnModel().getColumn(0);
            primeracolumna.setMaxWidth(50);
            primeracolumna.setMinWidth(50);
            TableColumn ultimacolumna = Grilla.getColumnModel().getColumn(Grilla.getColumnCount()-1);
            ultimacolumna.setMaxWidth(80);
            ultimacolumna.setMinWidth(80);
        } catch (SQLException ex) {
            Logger.getLogger(pfReportePosiciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Grilla.setDefaultRenderer(Object.class, new TableCellRendererPosicion());
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jdFechaFeriados jdc = new jdFechaFeriados(null, true);
        jdc.setLocationRelativeTo(null);
        jdc.setTitle("Días Hábiles");
        jdc.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void VerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerProductosActionPerformed
        // TODO add your handling code here:
        
        
        if(Grilla.getSelectedColumn()>0 && Grilla.getSelectedColumn()<Grilla.getColumnCount()-1 && Grilla.getSelectedRow()<13){
            String posicion = Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString();
            String fecha = Grilla.getColumnName(Grilla.getSelectedColumn());

//            jdProductosPosicion Pro = new jdProductosPosicion(null, false);
            
            pfProductosPosicion Pro = new pfProductosPosicion();
            pnPestanas.addTab("Productos por posición",Pro);
            PanelTab btc = new PanelTab(pnPestanas,0);
            pnPestanas.setTabComponentAt(pnPestanas.indexOfComponent(Pro), btc);
            pnPestanas.setSelectedIndex(pnPestanas.getTabCount()-1);
            
            String filtro = String.valueOf(cbConvenio.getSelectedIndex());
            int convenio = cbConvenio.getSelectedIndex()+1;
            
            if (posicion.equals(">=11")){
                
                posicion = "11";
            }
            
            
            Pro.SetData(posicion, fecha, String.valueOf(convenio));
            
            
//            Pro.setLocationRelativeTo(null);
//            Pro.setTitle("Productos por posición");
//            Pro.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila válida");
        }
    }//GEN-LAST:event_VerProductosActionPerformed

    private void GrillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaMouseClicked
        System.out.println( Grilla.getValueAt(0, Grilla.getSelectedColumn()).toString().trim());
        System.out.println( Grilla.getColumnName(Grilla.getSelectedColumn()).toString()); 
        System.out.println("Columna seleccionada = "+Grilla.getSelectedColumn());
        System.out.println("Fila seleccionada = "+Grilla.getSelectedRow());
        System.out.println("Columnas = "+Grilla.getColumnCount());
        System.out.println("Filas = "+Grilla.getRowCount());
    }//GEN-LAST:event_GrillaMouseClicked

//    
//    public void CargaGrillaAgrupados(){
//        ExeSql Sql = new ExeSql();
//        ExeSql Sql2 = new ExeSql();
//        ResultSet Rs, Rs2;
//        
//        try{
//              
//            String des = getDesde();
//            String has = getHasta();   
//                     
//            DefaultTableModel TableModel = (DefaultTableModel) Agrupados.getModel();
////            while(TableModel.getRowCount()>0)
////                TableModel.removeRow(13);  
//            
//            String agno_desde= des.substring(0,4);
//            String agno_hasta= has.substring(0,4);
//            
//            String mes_desde= des.substring(5,7);
//            String mes_hasta= has.substring(5,7);
//            
//            String dia_desde= des.substring(8,10);
//            String dia_hasta= has.substring(8,10);
//            
//            int agno_desde_numerico = Integer.valueOf(agno_desde);
//            int agno_hasta_numerico = Integer.valueOf(agno_hasta);
//            
//            int mes_desde_numerico = Integer.valueOf(mes_desde);
//            int mes_hasta_numerico = Integer.valueOf(mes_hasta);
//            
//            int dia_desde_numerico = Integer.valueOf(dia_desde);
//            int dia_hasta_numerico = Integer.valueOf(dia_hasta);
//            
//            System.out.println("Desde: "+mes_desde_numerico);
//            System.out.println("Hasta: "+agno_hasta+mes_hasta);
//            
//            int columnas=0;
//            int filas=0;
//            TableModel.setColumnCount(1);
//            if (Integer.valueOf(agno_desde+mes_desde+dia_desde)<Integer.valueOf(agno_hasta+mes_hasta+dia_hasta))
//                {   
//                    while (agno_desde_numerico < agno_hasta_numerico)
//                        {
//                        for(int x=mes_desde_numerico; x<=12; x++)
//                            {
//                            TableModel.addColumn(x+"-"+agno_desde);
//                            columnas++;
//                            }
//                        agno_desde_numerico++;
//                        mes_desde_numerico=1;
//                         }
//                    
//                     if (agno_desde_numerico == agno_hasta_numerico)
//                        {
//                            
//                        for(int x=dia_desde_numerico; x<=dia_hasta_numerico; x++)
//                            {
//                            TableModel.addColumn(x);
//                            columnas++;
//                            }
//                        }
//                 TableModel.addColumn("PROMEDIO");                      
//                }
//                int t1 = 0;
//                for (int t=1; t<=13; t++)
//                    {
//                    if (t<=11)
//                        {
//                        TableModel.setValueAt(t, t1,0);
//                        }
//                    if (t==12)
//                        {
//                        TableModel.setValueAt(20, t1, 0);
//                        }
//                    if (t==13)
//                        {
//                        TableModel.setValueAt(30, t1, 0);
//                        }
//                    t1++;
//                     }
//            
//                String filtro = String.valueOf(cbConvenio.getSelectedIndex());
//                if (!filtro.equals("0"))
//                    {
//                    filtro = " and convenio="+String.valueOf(cbConvenio.getSelectedIndex()+1);
//                    }
//                else{
//                    filtro = "";
//                }
//                int col=1;
//                int[] promedio = new int[13];
//                for (int r=dia_desde_numerico; r<=dia_hasta_numerico; r++)
//                    {
//                        String Qry = "select posicion, count(*) as cuantos from producto_posicion_historico\n" +
//                                "where dia="+r+" "+filtro+"  \n" +
//                                "group by posicion order by posicion";
//                        Rs = Sql.Select(Qry);
//                        int fil = 0;
//                        while (Rs.next())
//                            {
//                            fil = Rs.getInt("posicion");
//                            if (fil<=11)
//                                {
//                                    fil=fil-1;
//                                }
//                            if (fil==20)
//                                {
//                                  fil=11;  
//                                }
//                            if (fil==30)
//                            {
//                                fil=12;
//                            }
//                            
//                            TableModel.setValueAt(Rs.getInt("cuantos"), fil , col );
//                            promedio[fil]=promedio[fil]+Rs.getInt("cuantos");
//                            TableModel.setValueAt(promedio[fil]/columnas, fil , columnas+1 );
//                                                                             
//                            }
//                        
//                        col++;
//                    }
//                
//           
//            
//            
//        }
//        catch (Exception e){
//            fmMain.Mensaje("Error al cargar Agrupacion: "+e);
//        }
//        finally{
//            Sql.Close();
//        }
//    }

    
    
    
    
     public String getDesde() {
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return( sdf.format( (dtDesde.getDate()).getTime() ) );
    }
     
    public String getHasta() {
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return( sdf.format( (dtHasta.getDate()).getTime() ) );
    }
    
    public void abrir(String file ){
        
       try {
           
           String url = file;
           ProcessBuilder p = new ProcessBuilder();
           p.command("cmd.exe", "/c",url);
           p.start();
           
       } catch (IOException ex) {
           Logger.getLogger(jdOC_PendientesFac.class.getName()).log(Level.SEVERE, null, ex);
       }
        
    }
     
    private void CargaConvenios(){
        
        ResultSet Rs;
        ExeSql Sql = new ExeSql();
        try{
        cbConvenio.removeAllItems();
        cbConvenio.addItem("SELECCIONE CONVENIO PARA FILTRAR");
        Rs = Sql.Select("select convenio\n" +
                        "from par_convenio order by codigo");
                    while(Rs.next())
                        {
                        cbConvenio.addItem(Rs.getString("convenio"));
                        }
        }
        catch(Exception e)
        {
            fmMain.Mensaje("Error al cargar los convenios "+e);
        }
        finally{
            Sql.Close();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla;
    private javax.swing.JMenuItem VerProductos;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btExcel;
    private javax.swing.JComboBox<String> cbConvenio;
    private org.jdesktop.swingx.JXDatePicker dtDesde;
    private org.jdesktop.swingx.JXDatePicker dtHasta;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbcargando;
    // End of variables declaration//GEN-END:variables
}
