/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Formularios.fmMain;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luvaly
 */
public class pf_ManteCarteraClientes extends javax.swing.JPanel {
  DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();  
    /**
     * Creates new form pf_ManteCarteraClientes
     */
    public pf_ManteCarteraClientes() {
  
        initComponents();
        CargaVendedores();
        txOperacion.setText("OPERACION A REALIZAR");
        txOperacion.setBackground(Color.white);
        txOperacion.setForeground(Color.black);
        
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        Grilla_Seleccion.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
        Grilla_Elegidos.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);

        
        
    }
    
    
        
         
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Grilla_Vend = new javax.swing.JTable();
        bt_AgregaCartera = new javax.swing.JButton();
        bt_EliminaCartera = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Grilla_Elegidos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        Grilla_Seleccion = new javax.swing.JTable();
        lbOperacion1 = new javax.swing.JLabel();
        lbOperacion2 = new javax.swing.JLabel();
        lbOperacion3 = new javax.swing.JLabel();
        bt_Grabar = new javax.swing.JButton();
        txOperacion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        bt_Buscar = new javax.swing.JButton();
        txCodigoOC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btCodigoOC = new javax.swing.JButton();

        Grilla_Vend.setAutoCreateRowSorter(true);
        Grilla_Vend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Vendedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla_Vend.getTableHeader().setReorderingAllowed(false);
        Grilla_Vend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Grilla_VendMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Grilla_Vend);
        if (Grilla_Vend.getColumnModel().getColumnCount() > 0) {
            Grilla_Vend.getColumnModel().getColumn(0).setMinWidth(40);
            Grilla_Vend.getColumnModel().getColumn(0).setPreferredWidth(40);
            Grilla_Vend.getColumnModel().getColumn(0).setMaxWidth(150);
            Grilla_Vend.getColumnModel().getColumn(1).setMinWidth(250);
            Grilla_Vend.getColumnModel().getColumn(1).setPreferredWidth(250);
            Grilla_Vend.getColumnModel().getColumn(1).setMaxWidth(300);
        }

        bt_AgregaCartera.setText("Listar Agregar");
        bt_AgregaCartera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AgregaCarteraActionPerformed(evt);
            }
        });

        bt_EliminaCartera.setText("Listar Eliminar");
        bt_EliminaCartera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EliminaCarteraActionPerformed(evt);
            }
        });

        Grilla_Elegidos.setAutoCreateRowSorter(true);
        Grilla_Elegidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut", "Cliente", "Codigo OC"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla_Elegidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Grilla_ElegidosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Grilla_Elegidos);
        if (Grilla_Elegidos.getColumnModel().getColumnCount() > 0) {
            Grilla_Elegidos.getColumnModel().getColumn(0).setMinWidth(100);
            Grilla_Elegidos.getColumnModel().getColumn(0).setPreferredWidth(100);
            Grilla_Elegidos.getColumnModel().getColumn(0).setMaxWidth(150);
            Grilla_Elegidos.getColumnModel().getColumn(1).setMinWidth(250);
            Grilla_Elegidos.getColumnModel().getColumn(1).setPreferredWidth(250);
            Grilla_Elegidos.getColumnModel().getColumn(1).setMaxWidth(300);
        }

        Grilla_Seleccion.setAutoCreateRowSorter(true);
        Grilla_Seleccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut", "Cliente", "CodigoOC"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla_Seleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Grilla_SeleccionMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Grilla_Seleccion);
        if (Grilla_Seleccion.getColumnModel().getColumnCount() > 0) {
            Grilla_Seleccion.getColumnModel().getColumn(0).setMinWidth(100);
            Grilla_Seleccion.getColumnModel().getColumn(0).setPreferredWidth(100);
            Grilla_Seleccion.getColumnModel().getColumn(0).setMaxWidth(100);
            Grilla_Seleccion.getColumnModel().getColumn(1).setMinWidth(250);
            Grilla_Seleccion.getColumnModel().getColumn(1).setPreferredWidth(250);
            Grilla_Seleccion.getColumnModel().getColumn(1).setMaxWidth(300);
        }

        lbOperacion1.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        lbOperacion1.setText("Vendedores");

        lbOperacion2.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        lbOperacion2.setText("Clientes");

        lbOperacion3.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        lbOperacion3.setText("Clientes Seleccionados");

        bt_Grabar.setText("Grabar");
        bt_Grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_GrabarActionPerformed(evt);
            }
        });

        txOperacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txOperacion.setText("Operacion");

        jLabel1.setText("Rut");

        txtRut.setText("Ingrese Rut");
        txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRutKeyPressed(evt);
            }
        });

        bt_Buscar.setText("Buscar");
        bt_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_BuscarActionPerformed(evt);
            }
        });

        txCodigoOC.setText("Ingrese Código OC");
        txCodigoOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCodigoOCActionPerformed(evt);
            }
        });

        jLabel2.setText("Código OC");

        btCodigoOC.setText("Buscar");
        btCodigoOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCodigoOCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbOperacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt_AgregaCartera)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_EliminaCartera))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbOperacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(lbOperacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_Grabar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(txOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(212, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txCodigoOC)
                    .addComponent(txtRut, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCodigoOC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_AgregaCartera, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbOperacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbOperacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbOperacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_Grabar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_EliminaCartera, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txCodigoOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(btCodigoOC, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Grilla_VendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Grilla_VendMouseClicked

    }//GEN-LAST:event_Grilla_VendMouseClicked

    private void Grilla_SeleccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Grilla_SeleccionMouseClicked
        // TODO add your handling code here:
        //Grilla_Seleccion.getValueAt(Grilla_Seleccion.getSelectedRow(), 0).toString().trim()
        int i,w;
        w=0;
        DefaultTableModel Tmodel = (DefaultTableModel) Grilla_Seleccion.getModel();
        DefaultTableModel Tmodel_ele = (DefaultTableModel) Grilla_Elegidos.getModel();
        if(evt.getClickCount()==2 ){
        try{    
            //fmMain.Mensaje(String.valueOf("Fila : " + Grilla_Seleccion.getSelectedRow()));
            Tmodel_ele.addRow(new Object[]{Grilla_Seleccion.getValueAt(Grilla_Seleccion.getSelectedRow(), 0).toString().trim(),Grilla_Seleccion.getValueAt(Grilla_Seleccion.getSelectedRow(), 1).toString().trim(), Grilla_Seleccion.getValueAt(Grilla_Seleccion.getSelectedRow(), 2).toString().trim()});
            
            
            for(i=0; i<=Grilla_Seleccion.getRowCount();i++ ){
              if(Grilla_Seleccion.getValueAt(i, 0).toString().trim().equals(Grilla_Seleccion.getValueAt(Grilla_Seleccion.getSelectedRow(), 0).toString().trim()))  {
               w=i;
               break;
              }
            }
            
            Tmodel.removeRow(w); 
            //Tmodel.removeRow(Grilla_Seleccion.getSelectedRow()); 
            
         
          } catch (Exception e) {
            System.out.println(e);
        } finally{
            
        }
        }
    }//GEN-LAST:event_Grilla_SeleccionMouseClicked

    private void bt_AgregaCarteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AgregaCarteraActionPerformed
        // TODO add your handling code here:
        Agrega_Cartera();
        txOperacion.setText("AGREGAR A CARTERA");
        txOperacion.setBackground(Color.GREEN);
           txOperacion.setForeground(Color.black);
      
    }//GEN-LAST:event_bt_AgregaCarteraActionPerformed

    private void bt_EliminaCarteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EliminaCarteraActionPerformed
        // TODO add your handling code here:
        Elimina_Cartera(Grilla_Vend.getValueAt(Grilla_Vend.getSelectedRow(), 0).toString().trim());
        txOperacion.setText("ELIMINAR DE CARTERA");
        txOperacion.setBackground(Color.red);
        txOperacion.setForeground(Color.white);
        
    }//GEN-LAST:event_bt_EliminaCarteraActionPerformed

    private void Grilla_ElegidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Grilla_ElegidosMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        //Grilla_Seleccion.getValueAt(Grilla_Seleccion.getSelectedRow(), 0).toString().trim()
        
        DefaultTableModel Tmodel = (DefaultTableModel) Grilla_Elegidos.getModel();
        DefaultTableModel Tmodel_ele = (DefaultTableModel) Grilla_Seleccion.getModel();
        if(evt.getClickCount()==2 ){
                try{    
                    //fmMain.Mensaje(String.valueOf(Grilla_Seleccion.getSelectedRow()));
                    Tmodel_ele.addRow(new Object[]{Grilla_Elegidos.getValueAt(Grilla_Elegidos.getSelectedRow(), 0).toString().trim(),Grilla_Elegidos.getValueAt(Grilla_Elegidos.getSelectedRow(), 1).toString().trim()});
                    Tmodel.removeRow(Grilla_Elegidos.getSelectedRow()); 


                  } catch (Exception e) {
                    System.out.println(e);
                } finally{

                }
        }
        
    }//GEN-LAST:event_Grilla_ElegidosMouseClicked

    private void bt_GrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_GrabarActionPerformed
        // TODO add your handling code here:
           DefaultTableModel TableModel = (DefaultTableModel) Grilla_Seleccion.getModel();
           DefaultTableModel TableElegidos = (DefaultTableModel) Grilla_Elegidos.getModel();
           DefaultTableModel TableVend = (DefaultTableModel) Grilla_Vend.getModel();
        grabar();
        TableModel.setRowCount(0);
        TableElegidos.setRowCount(0);
        TableVend.setRowCount(0);
        CargaVendedores();
        fmMain.Mensaje("Clientes grabados correctamente. ");
        txOperacion.setText("OPERACION A REALIZAR");
        txOperacion.setBackground(Color.GREEN);
        txOperacion.setForeground(Color.black);
        txtRut.setText("Ingrese Rut:");
        
        
        
    }//GEN-LAST:event_bt_GrabarActionPerformed

    private void bt_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_BuscarActionPerformed
        // TODO add your handling code here:
        String codigo ="";
        int pos=-1;
     // Busca si el codigo se ha ingresado anteriormente en la grilla
            for (int i=0; i<=Grilla_Seleccion.getRowCount()-1; i++ ){
                codigo= Grilla_Seleccion.getValueAt(i, 0).toString().trim();
                if (codigo.equals(txtRut.getText().trim())){
                    pos = i;
                    break;
                }
            }
            
            // Si existe el codigo en la grilla modificara la cantidad ingresada
            if (pos>=0){
                Grilla_Seleccion.changeSelection(pos, 0 , false, false);
            }
            else{
                fmMain.Mensaje("Rut ingresado: " + txtRut.getText().trim() + " no esta en listado");
            }
        
    }//GEN-LAST:event_bt_BuscarActionPerformed

    private void txtRutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyPressed
        // TODO add your handling code here:
          if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            bt_Buscar.doClick();
        }
    }//GEN-LAST:event_txtRutKeyPressed

    private void txCodigoOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCodigoOCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCodigoOCActionPerformed

    private void btCodigoOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCodigoOCActionPerformed
        String codigo ="";
        int pos=-1;
     // Busca si el codigo se ha ingresado anteriormente en la grilla
            for (int i=0; i<=Grilla_Seleccion.getRowCount()-1; i++ ){
                codigo= Grilla_Seleccion.getValueAt(i, 2).toString().trim();
                if (codigo.equals(txCodigoOC.getText().trim())){
                    pos = i;
                    break;
                }
            }
            
            // Si existe el codigo en la grilla modificara la cantidad ingresada
            if (pos>=0){
                Grilla_Seleccion.changeSelection(pos, 2, false, false);
            }
            else{
                fmMain.Mensaje("Codigo ingresado: " + txCodigoOC.getText().trim() + " no esta en listado");
            }
    }//GEN-LAST:event_btCodigoOCActionPerformed


    
 private void grabar(){
    DefaultTableModel TableModel = (DefaultTableModel) Grilla_Elegidos.getModel();
    ExeSql Sql = new ExeSql();
    ResultSet Rs;
    String Query, qryIns, qryUpd, Sku, Ubicacion,StUsuario ;
    qryIns="";
    Ubicacion ="";
    double cantidad_grilla_ins=0.0;
    boolean grabo = false;
 
    try{ 
        
        if (Grilla_Elegidos.getRowCount() <=0){
            fmMain.Mensaje("Debe seleccionar un cliente");
            return;
        }
        
        for (int i=0; i<=Grilla_Elegidos.getRowCount()-1; i++ ){
            if (txOperacion.getText().trim().equals("ELIMINAR DE CARTERA"))
            {
            qryIns = " delete from cli_cartera_venta_final  where rut_cliente = " + Integer.valueOf(fmMain.SetGuardar(Grilla_Elegidos.getValueAt(i, 0).toString().trim())) + " and \n" +
                                 "  cod_vendedor = " + Integer.valueOf(Grilla_Vend.getValueAt(Grilla_Vend.getSelectedRow(), 0).toString().trim())  + " and \n"+
                                 "  codigo_oc = " + Integer.valueOf(Grilla_Elegidos.getValueAt(i, 2).toString().trim())+";";
            }
            else
            {
            qryIns = " insert into cli_cartera_venta_final (rut_cliente,cod_vendedor,codigo_oc) values (" + Integer.valueOf(fmMain.SetGuardar(Grilla_Elegidos.getValueAt(i, 0).toString().trim())) 
                    + ", " +  Integer.valueOf(Grilla_Vend.getValueAt(Grilla_Vend.getSelectedRow(), 0).toString().trim()) +  ","+ Integer.valueOf(Grilla_Elegidos.getValueAt(i, 2).toString().trim()) +");";
            }
            Sql.ExeSql(qryIns);
        }
                Sql.Commit();
          }
     catch (Exception e) {
            System.out.println(e.getMessage());
            fmMain.Mensaje(e.getMessage());
        } finally{
            Sql.Close();
        }    
    }
    
    private void Agrega_Cartera(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel TableModel = (DefaultTableModel) Grilla_Seleccion.getModel();
        DefaultTableModel TableElegidos = (DefaultTableModel) Grilla_Elegidos.getModel();
        double Sumador = 0.00;
        double Margen  = 0.00;
        String Query ="";    
        
        int ContReg=0;

//         while(TableModel.getRowCount()>0)
//             TableModel.removeRow(0);
        
         TableModel.setRowCount(0);
         TableElegidos.setRowCount(0);
        try {
            Query = " select c.rut,\n" +
                    "        c.nombre,\n" +
                    "        d.codigo_oc\n" +
                    " from cliente c, clicontacto d\n" +
                    " where c.rut = d.rut AND CAST(d.rut as varchar)||d.codigo_oc not in (\n" +
                    "                      select CAST(cv.rut_cliente as varchar)||cv.codigo_oc\n" +
                    "                      from cli_cartera_venta_final cv)\n" +
                    "                      and c.rut is not null \n" +
                    " order by c.rut";
                             
            Rs = Sql.Select(Query);
            
            while (Rs.next()){
                ContReg++;
                        TableModel.addRow(new Object[]{
                                               Rs.getInt("rut"),
                                               Rs.getString("nombre").trim(),
                                               Rs.getString("codigo_oc").trim()});
               }
            
        } catch (Exception e) {
          
        } finally{
            Sql.Close();
        }
        
    }            
   
    
    
     private void Elimina_Cartera(String CodVendedor){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel TableModel = (DefaultTableModel) Grilla_Seleccion.getModel();
           DefaultTableModel TableElegidos = (DefaultTableModel) Grilla_Elegidos.getModel();
        double Sumador = 0.00;
        double Margen  = 0.00;
        String Query ="";    
        
        int ContReg=0;

//         while(TableModel.getRowCount()>0)
//             TableModel.removeRow(0);
        
         TableModel.setRowCount(0);
         TableElegidos.setRowCount(0);
        try {
            Query =" select c.rut,\n" +
                    "       c.nombre,\n" +
                    "       d.codigo_oc\n" +
                    "from cliente c\n" +
                    "	 inner join clicontacto d on d.rut = c.rut\n" +
                    "     inner join personal p on p.vendedor = "+ CodVendedor +"\n" +
                    "     inner join cli_cartera_venta_final cv on cv.rut_cliente = d.rut AND\n" +
                    "     cv.cod_vendedor = p.vendedor AND cv.codigo_oc = d.codigo_oc\n" +
                    "order by c.rut";   
            
            Rs = Sql.Select(Query);
            
            while (Rs.next()){
                ContReg++;
                        TableModel.addRow(new Object[]{
                                               Rs.getInt("rut"),
                                               Rs.getString("nombre").trim(),
                                               Rs.getString("codigo_oc").trim()});
               }
                // Seteado en la primera  posicion.
               Grilla_Seleccion.changeSelection(0, 0 , false, false);
        } catch (Exception e) {
          
        } finally{
            Sql.Close();
        }
        
    }            

     private void CargaVendedores(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel dfTm = (DefaultTableModel) Grilla_Vend.getModel();
        
        fmMain.LimpiaGrilla(dfTm);
        try {
           // Rs = Sql.Select("select * from pg_user where usename <> 'postgres'");
             Rs = Sql.Select("  select p.vendedor, p.usuario\n" +
                " from personal p left join usuario u on u.usuario = p.usuario where p.vendedor >0 and u.activo = true");

            
            while(Rs.next()){
                dfTm.addRow(new Object[]{Rs.getString("vendedor"),Rs.getString("usuario")});
            }
                
        } catch (Exception e) {
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla_Elegidos;
    private javax.swing.JTable Grilla_Seleccion;
    private javax.swing.JTable Grilla_Vend;
    private javax.swing.JButton btCodigoOC;
    private javax.swing.JButton bt_AgregaCartera;
    private javax.swing.JButton bt_Buscar;
    private javax.swing.JButton bt_EliminaCartera;
    private javax.swing.JButton bt_Grabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbOperacion1;
    private javax.swing.JLabel lbOperacion2;
    private javax.swing.JLabel lbOperacion3;
    private javax.swing.JTextField txCodigoOC;
    private javax.swing.JTextField txOperacion;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
