/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogos;

import Conexion.ExeSql;
import Formularios.fmMain;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Roberto Lopez
 */
public class jdCargaLibros extends javax.swing.JDialog {
    
    private String RutDoc;
    private String NumDoc;
    private String TipDoc;
    private String tipodoc = "FAC";
    private String tipo2 = "FAC";
    private String libro = "V";
    
    DefaultTableModel TablaModelo;
    
   
    public jdCargaLibros(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        Calendar c = Calendar.getInstance();
        cbAgno.setSelectedItem(Integer.toString(c.get(Calendar.YEAR))); 
        cbMes.setSelectedIndex((c.get(Calendar.MONTH))); 
        
        CargaTabla();
        
        Grilla.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
            
                if (evt.getClickCount() == 2) {
            
                    Point pnt = evt.getPoint();
                    int row = Grilla.rowAtPoint(pnt);
                    SelCodigo();
                }else {
            
                    //do something else
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        vfae = new javax.swing.JRadioButton();
        vncae = new javax.swing.JRadioButton();
        vncaes = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        cfae = new javax.swing.JRadioButton();
        cncae = new javax.swing.JRadioButton();
        cfaeg = new javax.swing.JRadioButton();
        cfap = new javax.swing.JRadioButton();
        btCargar = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbAgno = new javax.swing.JComboBox<String>();
        cbMes = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro. Docto", "Fecha Emision", "RUT", "Extento", "Afecto", "Iva", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Grilla);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ventas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        buttonGroup1.add(vfae);
        vfae.setSelected(true);
        vfae.setText("Factura Afecta Electrónica");
        vfae.setToolTipText("");
        vfae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vfaeActionPerformed(evt);
            }
        });

        buttonGroup1.add(vncae);
        vncae.setText("Nota de Crédito Afecta Electrónica");
        vncae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vncaeActionPerformed(evt);
            }
        });

        buttonGroup1.add(vncaes);
        vncaes.setText("Nota de Crédito Afecta Electrónica (Sin Derecho A Crédito)");
        vncaes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vncaesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vncae, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vfae, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vncaes, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vfae)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vncae)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vncaes)
                .addGap(33, 33, 33))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Compras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        buttonGroup1.add(cfae);
        cfae.setText("Factura Afecta Electrónica");
        cfae.setToolTipText("");
        cfae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfaeActionPerformed(evt);
            }
        });

        buttonGroup1.add(cncae);
        cncae.setText("Nota de Crédito Afecta Electrónica");
        cncae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cncaeActionPerformed(evt);
            }
        });

        buttonGroup1.add(cfaeg);
        cfaeg.setText("Factura Afecta Electrónica (Gastos)");
        cfaeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfaegActionPerformed(evt);
            }
        });

        buttonGroup1.add(cfap);
        cfap.setText("Factura Afecta Parcial");
        cfap.setToolTipText("");
        cfap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cfae, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cncae, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cfap, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cfaeg, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cfae)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cfap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cncae)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cfaeg)
                .addContainerGap())
        );

        btCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/Cargar.png"))); // NOI18N
        btCargar.setText("Cargar");
        btCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCargarActionPerformed(evt);
            }
        });

        btGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/save.png"))); // NOI18N
        btGuardar.setText("Guardar");
        btGuardar.setEnabled(false);
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        jLabel1.setText("SELECCIONE AÑO");

        cbAgno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        cbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabel2.setText("SELECCIONE MES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAgno, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbAgno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.getAccessibleContext().setAccessibleName("");
        jPanel2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GrillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaMouseClicked
        
        if(evt.getClickCount()==2 && !Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString().isEmpty()){
        
            SelCodigo();
        }        
    }//GEN-LAST:event_GrillaMouseClicked

    private void vfaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vfaeActionPerformed
        if (vfae.isSelected()){                 //LIBRO VENTAS
                        
            tipodoc = "FAC";
            tipo2 = "FAC";
            libro = "V";
                    
        }
    }//GEN-LAST:event_vfaeActionPerformed

    private void vncaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vncaeActionPerformed
        
        if (vncae.isSelected()){
                    
            tipodoc = "NCC";
            tipo2 = "NCC";
            libro = "V";
                    
        }
    }//GEN-LAST:event_vncaeActionPerformed

    private void vncaesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vncaesActionPerformed
        if (vncaes.isSelected()){
                    
            tipodoc = "NCC";
            tipo2 = "NCS";
            libro = "V";
                    
        }
    }//GEN-LAST:event_vncaesActionPerformed

    private void cfaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfaeActionPerformed
        
        if (cfae.isSelected()){              
                    
            tipodoc = "FAP";
            tipo2 = "FAE";
            libro = "C";
                    
        }
        
        
    }//GEN-LAST:event_cfaeActionPerformed

    private void cncaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cncaeActionPerformed
        
        if (cncae.isSelected()){
                    
            tipodoc = "NCP";
            tipo2 = "NCP";
            libro = "C";
                    
        }
        
        
    }//GEN-LAST:event_cncaeActionPerformed

    private void cfaegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfaegActionPerformed
        
        if (cfaeg.isSelected()){
                    
            tipodoc = "FAG";
            tipo2 = "FAG";
            libro = "C";
                   
        }
        
        
    }//GEN-LAST:event_cfaegActionPerformed

    private void cfapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfapActionPerformed
        
        if (cfap.isSelected()){
                    
            tipodoc = "FAP";
            tipo2 = "FAR";
            libro = "C";
                   
        }
        
    }//GEN-LAST:event_cfapActionPerformed

    private void btCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCargarActionPerformed
        
        if (fmMain.OkCancel("¿Desea cargar Documentos del mes ?") == JOptionPane.OK_OPTION) {
            
            String LINE_BREAK = "\n";
            String CELL_BREAK = "\t";
            
            Clipboard CLIPBOARD = Toolkit.getDefaultToolkit().getSystemClipboard();
            
            String pasteString = "";
            String Nro_Docto = "";
            String Fech_Emision = "";
            String Rut = "";
            String Exento = "";
            String Afecto = "";
            String Iva = "";
            String TotalDoc = "";

            TablaModelo = (DefaultTableModel) Grilla.getModel();

            while (TablaModelo.getRowCount() > 0) {
                TablaModelo.removeRow(0);
            }

      
            try {
              
                pasteString = (String) (CLIPBOARD.getContents(this).getTransferData(DataFlavor.stringFlavor));
            
            }catch (Exception e) {
            
                JOptionPane.showMessageDialog(null, "Error", "El elemento copiado es invalido", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            try {
                String[] lines = pasteString.split(LINE_BREAK);
                
                for (int i = 0; i < lines.length; i++) {

                    String[] cells = lines[i].split(CELL_BREAK);
                
                    Nro_Docto = cells[0];
                    Fech_Emision = cells[1];
                    Rut = cells[2];
                    Exento = cells[3];
                    Afecto = cells[4];
                    Iva = cells[5];
                    TotalDoc = cells[6];
                    TotalDoc = fmMain.SetGuardar(TotalDoc);
                    
                    if (Exento.isEmpty()) {
                        Exento = "0";
                    }
                    if (Afecto.isEmpty()) {
                        Afecto = "0";
                    }
                    if (Iva.isEmpty()) {
                        Iva = "0";
                    }
                    if (TotalDoc.isEmpty()) {
                        TotalDoc = "0";
                    }

                    TablaModelo.addRow(new Object[]{Nro_Docto, Fech_Emision, Rut, Exento,Afecto,Iva, TotalDoc});
                    
                }
                
                
               
                
            }catch (Exception e) {
                System.out.println(e.getMessage());
            }
           
            
            btGuardar.setEnabled(true);
            
        }
        
        
        
        
    }//GEN-LAST:event_btCargarActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        //Validaciones
//        try {
//            Rs = Sql.Select("SELECT COUNT(*) AS existe\n"
//                          + "FROM conta_libros\n"
//                          + "WHERE mes=" + cbMes.getSelectedIndex() + "\n"
//                          + "AND agno =" + cbAgno.getSelectedItem());
//            Rs.next();
//            
//            if (Rs.getInt("existe") > 0) {
//                fmMain.Mensaje("Ya existen libros para este mes y año. No se puede Guardar");
//                Sql.Close();
//                return;
//            }
//
//        }catch (Exception e) {
//            System.out.println(e.getMessage());
//        }

        if (fmMain.OkCancel("¿Desea guardar los datos?") == JOptionPane.OK_OPTION) {
            
            try {
                              
                for (int i = 0; i < Grilla.getRowCount(); i++) {
                    
                    String[] parte = Grilla.getValueAt(i, 2).toString().split("-");
                    String rut = parte[0];
                    String sexento = Grilla.getValueAt(i, 3).toString().trim().replaceAll("\\.", "");
                    String safecto = Grilla.getValueAt(i, 4).toString().trim().replaceAll("\\.", "");
                    String siva = Grilla.getValueAt(i, 5).toString().trim().replaceAll("\\.", "");
                    String stotal = Grilla.getValueAt(i, 6).toString().trim().replaceAll("\\.", "");
                    
                    double exento, afecto, iva,total;
                    
                    exento = Double.parseDouble(sexento);
                    afecto = Double.parseDouble(safecto);
                    iva = Double.parseDouble(siva);
                    total = Double.parseDouble(stotal);
                    
                    if (exento < 0){
                    
                        exento = exento * -1;
                    }
                    
                    if (afecto < 0){
                    
                        afecto = afecto * -1;
                    }
                    
                    if (iva < 0){
                    
                        iva = iva * -1;
                    }
                    
                    if (total < 0){
                    
                        total = total * -1;
                    }
                    
                    
                   
                    
                    Sql.ExeSql("INSERT INTO conta_libros\n" +
                              "(nrodocto,femision,rut,totalexento,totalafecto,totaliva,totaldocto,tipdocto,mes,agno,libro,tipo2) VALUES\n" +
                              "(" + Grilla.getValueAt(i, 0).toString().trim() + ",'"
                                  + Grilla.getValueAt(i, 1).toString().trim() +"',"
                                  + rut+ ","
                                  + exento +","
                                  + afecto +","
                                  + iva +","
                                  + total +",'"
                                  + tipodoc +"',"
                                  + (cbMes.getSelectedIndex()+1) +  ","
                                  + cbAgno.getSelectedItem().toString().trim() + ",'"
                                  + libro +"','"
                                  + tipo2 + "')");
                }
                
                Sql.Commit();
                fmMain.Mensaje("Datos Guardados");
                btGuardar.setEnabled(false);
              
                cbMes.setEnabled(true);
                cbAgno.setEnabled(true);
          
            }catch (Exception e) {
            
                fmMain.Mensaje("Error al Guardar: " + e.getMessage());
            
            }finally {
            
                Sql.Close();
            
            }
        }

        
        
    }//GEN-LAST:event_btGuardarActionPerformed
    
    public void SelCodigo(){
        NumDoc = (String) Grilla.getValueAt(Grilla.getSelectedRow(), 1);
        RutDoc = (String) Grilla.getValueAt(Grilla.getSelectedRow(), 0);
        TipDoc = (String) Grilla.getValueAt(Grilla.getSelectedRow(), 2);
        dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdCargaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdCargaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdCargaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdCargaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdCargaLibros dialog = new jdCargaLibros(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void CargaTabla() {
//        ExeSql sql = new ExeSql();
//        ResultSet rs = null;
//        String Query = "select cta.rut, cta.nrodocto, cta.tipdocto, cta.fcreacion, cta.tipdocorigen from ctacteprv as cta\n";
//        if(todos.isSelected()){
//            Query = Query + "where cta.tipdocto = 'GDP' or cta.tipdocto = 'FAP'";
//        }
//        if(gdp.isSelected()){
//            Query = Query + "where cta.tipdocto = 'GDP'";
//        }
//        if(fap.isSelected()){
//            Query = Query + "where cta.tipdocto = 'FAP'";
//        }
//        try {
//            rs = sql.Select(Query);
//            DefaultTableModel model = (DefaultTableModel) Grilla.getModel();
//            while(model.getRowCount()>0){
//                model.removeRow(0);
//            }
//            for(int i = 0; rs.next(); i++){
//                model.addRow(new Object[]{
//                    rs.getString("rut"),
//                    rs.getString("nrodocto"),
//                    rs.getString("tipdocto"),
//                    rs.getString("tipdocorigen"),
//                    rs.getString("fcreacion")
//                });
//            }
//        } 
//        catch (SQLException ex) {
//            Logger.getLogger(jdCompara.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla;
    private javax.swing.JButton btCargar;
    private javax.swing.JButton btGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbAgno;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JRadioButton cfae;
    private javax.swing.JRadioButton cfaeg;
    private javax.swing.JRadioButton cfap;
    private javax.swing.JRadioButton cncae;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton vfae;
    private javax.swing.JRadioButton vncae;
    private javax.swing.JRadioButton vncaes;
    // End of variables declaration//GEN-END:variables
}
