/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogos;

import Conexion.ExeSql;
import Formularios.fmMain;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David Alcaman
 */
public class jdHDRemuneraciones extends javax.swing.JDialog {

    /**
     * Creates new form jdHDRemuneraciones
     */
    public jdHDRemuneraciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cbHD.setSelectedIndex(-1);
        GrillaHD.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            //Se ejecuta automáticamente cada vez que se hace una nueva selección. 
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(GrillaHD.getSelectedRowCount()>0)
                    CargaDetalleHD();
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbHD = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        GrillaHD = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txCtaContable = new javax.swing.JTextField();
        btCtaContable = new javax.swing.JButton();
        txCtaContableCod = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        chkVigente = new javax.swing.JCheckBox();
        chkPago = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbHD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HABERES", "DESCUENTOS" }));
        cbHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHDActionPerformed(evt);
            }
        });

        GrillaHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Vigente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GrillaHD.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(GrillaHD);
        if (GrillaHD.getColumnModel().getColumnCount() > 0) {
            GrillaHD.getColumnModel().getColumn(0).setMinWidth(0);
            GrillaHD.getColumnModel().getColumn(0).setPreferredWidth(0);
            GrillaHD.getColumnModel().getColumn(0).setMaxWidth(0);
            GrillaHD.getColumnModel().getColumn(2).setMinWidth(60);
            GrillaHD.getColumnModel().getColumn(2).setPreferredWidth(60);
            GrillaHD.getColumnModel().getColumn(2).setMaxWidth(60);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel2.setText("Cuenta Contable");

        txCtaContable.setEditable(false);

        btCtaContable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/Go.png"))); // NOI18N
        btCtaContable.setEnabled(false);
        btCtaContable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCtaContableActionPerformed(evt);
            }
        });

        txCtaContableCod.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txCtaContableCod, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txCtaContable, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCtaContable, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txCtaContableCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txCtaContable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btCtaContable, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(30, 30, 30))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        chkVigente.setText("Vigente");
        chkVigente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkVigenteActionPerformed(evt);
            }
        });

        chkPago.setText("Genera Pago");
        chkPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkPago)
                    .addComponent(chkVigente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(chkVigente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkPago)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Haberes y Descuentos");

        btNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Agregar.png"))); // NOI18N
        btNuevo.setText("Nuevo");
        btNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(cbHD, 0, 279, Short.MAX_VALUE))
                            .addComponent(btNuevo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCtaContableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCtaContableActionPerformed
        String Query="";

        if(cbHD.getSelectedItem().toString().trim().equals("HABERES"))
            Query = "select codigo,nombre\n" +
                    "from conta_plan\n" +
                    "where codigo like '3%'\n" +
                    "and nivel in (4) order by nombre";
        else
            Query = "select codigo,nombre\n" +
                    "from conta_plan\n" +
                    "where codigo like '2%' \n" +
                    "and nivel in (4) order by nombre";

        jdAgregaDato Dato = new jdAgregaDato(null, true);
        Dato.setLocationRelativeTo(null);
        Dato.setTitle("Cuenta Contable");
        Dato.CargaDatos(Query);
        Dato.setVisible(true);

        if(!Dato.GetCodigo().isEmpty()){
            ExeSql Sql = new ExeSql();
            String Tipo;
            if(cbHD.getSelectedItem().toString().trim().equals("HABERES"))
                Tipo = "REM_HABERES";
            else
                Tipo = "REM_DESCUENTOS";
            try {
                Sql.ExeSql("update par_general\n" +
                            "set cuenta='"+ Dato.GetCodigo().trim() +"'\n" +
                            "where Codigo=" + GrillaHD.getValueAt(GrillaHD.getSelectedRow(), 0).toString().trim() + " and tipo='" + Tipo + "'");
                Sql.Commit();
                txCtaContableCod.setText(Dato.GetCodigo().trim());
                txCtaContable.setText(Dato.GetNombre().trim());
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }finally{
                Sql.Close();
            }

        }
    }//GEN-LAST:event_btCtaContableActionPerformed
    private void CargaDetalleHD(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        String Tipo="";
        
        btCtaContable.setEnabled(true);
        
        if(cbHD.getSelectedItem().toString().trim().equals("HABERES"))
            Tipo = "REM_HABERES";
        else
            Tipo = "REM_DESCUENTOS";
        
        try {
            Rs = Sql.Select("select p.vigente,p.valor,p.cuenta,c.nombre\n" +
                            "from par_general p\n" +
                            "left join conta_plan c on p.cuenta=c.codigo " +
                            "where p.tipo='"+ Tipo +"'\n" +
                            "and p.codigo=" + GrillaHD.getValueAt(GrillaHD.getSelectedRow(),0).toString().trim());
            if(Sql.GetRowCount()>0){
                Rs.next();
                chkVigente.setSelected(Rs.getBoolean("vigente"));
                chkPago.setSelected(Rs.getBoolean("valor"));
                txCtaContableCod.setText(Rs.getString("cuenta").trim());
                txCtaContable.setText(Rs.getString("nombre").trim());
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
            txCtaContable.setText("");
            txCtaContableCod.setText("");
        } finally{
            Sql.Close();
        }
    }
    
    private void CargaHD(){
        String Query;
        if(cbHD.getSelectedIndex()==-1) return;
        
        if(cbHD.getSelectedItem().toString().trim().equals("HABERES")){
            Query = "select codigo,nombre,vigente\n" +
                    "from par_general\n" +
                    "where tipo='REM_HABERES'\n" +
                    "order by nombre";
        }
        else{
            Query = "select codigo,nombre,vigente\n" +
                    "from par_general\n" +
                    "where tipo='REM_DESCUENTOS'\n" +
                    "order by nombre";    
             }
        if(cbHD.getSelectedIndex()>-1){
            ExeSql Sql = new ExeSql();
            ResultSet Rs;
            DefaultTableModel Model = (DefaultTableModel)GrillaHD.getModel();
            
            try {
                Rs = Sql.Select(Query);
                fmMain.LimpiaGrilla(Model);
                while(Rs.next()){
                    Model.addRow(new Object[]{
                        Rs.getInt("codigo"),
                        Rs.getString("nombre"),
                        Rs.getBoolean("vigente")
                    });
                           
                }
            } catch (Exception e) {
            }finally{
                Sql.Close();
            }
        }
            
            
        
    }
    private void btNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoActionPerformed
        if(fmMain.OkCancel("¿Desea crear un nuevo " + cbHD.getSelectedItem().toString().trim())== JOptionPane.CANCEL_OPTION)
            return;
        
        String NvoHD = JOptionPane.showInputDialog("Nuevo " + cbHD.getSelectedItem().toString().trim());
        NvoHD = NvoHD.toUpperCase();
        String Tipo;
        
        if(cbHD.getSelectedItem().toString().trim().equals("HABERES"))
            Tipo = "REM_HABERES";
        else
            Tipo = "REM_DESCUENTOS";
        
        if(NvoHD!=null || !NvoHD.isEmpty()){
            ExeSql Sql = new ExeSql();
                try {
                    Sql.ExeSql("insert into par_general\n" +
                                "(tipo,nombre)values\n" +
                                "('"+ Tipo +"','"+ NvoHD +"')");
                    Sql.Commit();
                    CargaHD();
                } catch (Exception e) {
                    fmMain.Mensaje(e.getMessage());
                }finally{
                    Sql.Close();
                }
        }
    }//GEN-LAST:event_btNuevoActionPerformed

    private void cbHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHDActionPerformed
        CargaHD();
    }//GEN-LAST:event_cbHDActionPerformed

    private void chkVigenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVigenteActionPerformed
        if(GrillaHD.getSelectedRow()>=0){
            int Estado;
            String Tipo;
            
            if(chkVigente.isSelected())
                Estado=1;
            else
                Estado=0;
            
            if(cbHD.getSelectedItem().toString().trim().equals("HABERES"))
                Tipo= "REM_HABERES";
            else
                Tipo= "REM_DESCUENTOS";
            
            ExeSql Sql = new ExeSql();
            try {
                Sql.ExeSql("update par_general\n" +
                            "set vigente="+ Estado +"\n" +
                            "where tipo='"+ Tipo +"'\n" +
                            "and codigo=" + GrillaHD.getValueAt(GrillaHD.getSelectedRow(),0).toString());
                GrillaHD.setValueAt(chkVigente.isSelected(), GrillaHD.getSelectedRow(), 2);
                Sql.Commit();
            } catch (Exception e) {
                fmMain.Mensaje(e.getMessage());
            } finally{
                Sql.Close();
            }
        }
    }//GEN-LAST:event_chkVigenteActionPerformed

    private void chkPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPagoActionPerformed
        if(GrillaHD.getSelectedRow()>=0){
            int Estado;
            String Tipo;
            
            if(chkPago.isSelected())
                Estado=1;
            else
                Estado=0;
            
            if(cbHD.getSelectedItem().toString().trim().equals("HABERES"))
                Tipo= "REM_HABERES";
            else
                Tipo= "REM_DESCUENTOS";
            
            ExeSql Sql = new ExeSql();
            try {
                Sql.ExeSql("update par_general\n" +
                            "set valor="+ Estado +"\n" +
                            "where tipo='"+ Tipo +"'\n" +
                            "and codigo=" + GrillaHD.getValueAt(GrillaHD.getSelectedRow(),0).toString());
                Sql.Commit();
            } catch (Exception e) {
                fmMain.Mensaje(e.getMessage());
            } finally{
                Sql.Close();
            }
        }
    }//GEN-LAST:event_chkPagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdHDRemuneraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdHDRemuneraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdHDRemuneraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdHDRemuneraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdHDRemuneraciones dialog = new jdHDRemuneraciones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GrillaHD;
    private javax.swing.JButton btCtaContable;
    private javax.swing.JButton btNuevo;
    private javax.swing.JComboBox<String> cbHD;
    private javax.swing.JCheckBox chkPago;
    private javax.swing.JCheckBox chkVigente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txCtaContable;
    private javax.swing.JTextField txCtaContableCod;
    // End of variables declaration//GEN-END:variables
}
