/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Dialogos.jdAutorizaModificacion;
import Dialogos.jdBuscarDocumento;
import Dialogos.jdEditarIngreso;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author infornatica
 */
public class pfModificarIngreso extends javax.swing.JPanel {
    String usuario;//Toma el valor usuario de fmMain
    /**
     * Creates new form pfModificarIngreso
     */

 
    public pfModificarIngreso() {
        initComponents();
//        CargarGrilla();
        textnrodoc.addKeyListener(new KeyAdapter() {//Limita el campo de texto solo para números
            public void keyTyped(KeyEvent e) {
              char c = e.getKeyChar();
              if (!((c >= '0') && (c <= '9') ||
                 (c == KeyEvent.VK_BACK_SPACE) ||
                 (c == KeyEvent.VK_DELETE))) {
                getToolkit().beep();
                e.consume();
              }
            }
          });
        textrut.addKeyListener(new KeyAdapter() {//Limita el campo de texto solo para números
            public void keyTyped(KeyEvent e) {
              char c = e.getKeyChar();
              if (!((c >= '0') && (c <= '9') ||
                 (c == KeyEvent.VK_BACK_SPACE) ||
                 (c == KeyEvent.VK_DELETE))) {
                getToolkit().beep();
                e.consume();
              }
            }
        });
        textrut.addKeyListener(new KeyAdapter() {//Listener
               @Override
               public void keyPressed(KeyEvent e) {
                   if(e.getKeyCode() == KeyEvent.VK_ENTER){
                        CargarModificados();//Carga grilla     
                        CargarDetalle();
                   }
               }

           });
            
        Grilla_Detalle.getModel().addTableModelListener(new TableModelListener() {
            public void tableChanged(TableModelEvent e) {
             // your code goes here, whatever you want to do when something changes in the table
            }
        });
            


        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbTipoDoc = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        textnrodoc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textrut = new javax.swing.JTextField();
        boton_buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla_Detalle = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Grilla_Detalle_Detalle = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        EditarBoton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Buscar Documento: ");

        cbTipoDoc.setFont(new java.awt.Font("Segoe UI Symbol", 1, 11)); // NOI18N
        cbTipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FAP", "GDP" }));

        jLabel3.setText("N° Documento: ");

        textnrodoc.setForeground(new java.awt.Color(0, 0, 255));
        textnrodoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnrodocActionPerformed(evt);
            }
        });

        jLabel4.setText("RUT:");

        textrut.setForeground(new java.awt.Color(0, 0, 255));
        textrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textrutActionPerformed(evt);
            }
        });
        textrut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textrutKeyPressed(evt);
            }
        });

        boton_buscar.setBackground(new java.awt.Color(204, 204, 204));
        boton_buscar.setForeground(new java.awt.Color(0, 51, 255));
        boton_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/search16.png"))); // NOI18N
        boton_buscar.setText("Buscar");
        boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textnrodoc, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textrut, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(textnrodoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(textrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_buscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Modificar Ingreso");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Grilla_Detalle.setAutoCreateRowSorter(true);
        Grilla_Detalle.setBackground(java.awt.SystemColor.controlHighlight);
        Grilla_Detalle.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Grilla_Detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "RUT", "N° Dcto", "Tipo Documento", "Fecha Emisión", "Nombre Proveedor"
            }
        ));
        Grilla_Detalle.setGridColor(new java.awt.Color(0, 0, 0));
        Grilla_Detalle.setMaximumSize(new java.awt.Dimension(100, 64));
        Grilla_Detalle.setMinimumSize(new java.awt.Dimension(74, 64));
        Grilla_Detalle.setPreferredSize(new java.awt.Dimension(76, 64));
        jScrollPane1.setViewportView(Grilla_Detalle);

        Grilla_Detalle_Detalle.setBackground(new java.awt.Color(204, 204, 204));
        Grilla_Detalle_Detalle.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Grilla_Detalle_Detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Fecha Creación", "Proveedor", "RUT Proveedor", "Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla_Detalle_Detalle.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(Grilla_Detalle_Detalle);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        EditarBoton.setBackground(new java.awt.Color(204, 204, 204));
        EditarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Pencil16.png"))); // NOI18N
        EditarBoton.setText("Editar");
        EditarBoton.setEnabled(false);
        EditarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarBotonActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/ok_16.png"))); // NOI18N
        jButton2.setText("Autorizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/erase16.png"))); // NOI18N
        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EditarBoton)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditarBoton)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textnrodocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnrodocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnrodocActionPerformed

    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed
        if(!textnrodoc.getText().equals("") && !textrut.getText().equals("") ){//Si el largo de n°/rut es mayor a 0, se carga tabla
            CargarModificados();//Carga grilla     
            CargarDetalle();
        }
        
        else {
            jdBuscarDocumento BP = new jdBuscarDocumento(null, true);
            BP.setLocationRelativeTo(null);
            BP.setTitle("Buscar Producto");
            BP.setVisible(true);
            if(!"".equals(BP.getNumDoc()) && !"".equals(BP.getRutDoc())){
                textnrodoc.setText(BP.getNumDoc());
                textrut.setText(BP.getRutDoc());
                if(BP.getTipDoc().equals("FAP")){
                    cbTipoDoc.setSelectedIndex(0);
                }
                if(BP.getTipDoc().equals("GDP")){
                    cbTipoDoc.setSelectedIndex(1);
                }
                   
            }
        }
//        if(textnrodoc.getText().toString().equals("") && textrut.getText().length()>0)
    }//GEN-LAST:event_boton_buscarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) Grilla_Detalle.getModel();//Se limpia la grilla
        pfModificarIngreso.LimpiaGrilla(model);
        EditarBoton.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed
    public static boolean isEmpty(JTable jTable) {//Método para chekear si está vacia la tabla
        if (jTable != null && jTable.getModel() != null) {
            return jTable.getModel().getRowCount()<=0?true:false;
        }
        return false;
    }
    private void EditarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarBotonActionPerformed
                   
       
        String rut = Grilla_Detalle.getValueAt(Grilla_Detalle.getSelectedRow(), 0).toString();//Se obtienen valores de grilla
        String nrodocto = Grilla_Detalle.getValueAt(Grilla_Detalle.getSelectedRow(), 1).toString();
        String tipdocto = Grilla_Detalle.getValueAt(Grilla_Detalle.getSelectedRow(), 2).toString();
        String femision = Grilla_Detalle.getValueAt(Grilla_Detalle.getSelectedRow(), 3).toString();
        System.out.println(rut + "/" + nrodocto + "/"+ tipdocto + "/"+femision);

        if(CheckifEditable(rut, nrodocto, tipdocto, femision)==true){//Se chekea si se puede editar
            if(!isEmpty(Grilla_Detalle)){//Si la tabla NO  está vacia
                String rut_ = "";
                int numerodocto = 0;
                String tipodocto = "";
                String fecha = "";
                for(int i = 0; i < Grilla_Detalle.getModel().getRowCount();i++){//Toma los valores de la grilla
                    rut_ = Grilla_Detalle.getValueAt(i, 0).toString();
                    numerodocto = Integer.valueOf(Grilla_Detalle.getValueAt(i, 1).toString());
                    tipodocto = Grilla_Detalle.getValueAt(i, 2).toString();
                    fecha = Grilla_Detalle.getValueAt(i, 3).toString();
                }
                jdEditarIngreso editar = new jdEditarIngreso(null, false);//Crea ventana de Editar
                editar.SetValues(rut_, numerodocto, tipodocto, fecha);//Se le pasan valores
                editar.setUsuario(usuario);//Se pasa usuario por método
                editar.LlenarAntiguos();
                editar.setLocationRelativeTo(null);
                editar.setVisible(true);
            }
            else {
                JOptionPane.showMessageDialog(Grilla_Detalle,"No hay registros en la tabla para editar.");
            }
        }
        else {
            JOptionPane.showMessageDialog(Grilla_Detalle, "El documento no se puede editar.");
        }

    }//GEN-LAST:event_EditarBotonActionPerformed

    private void textrutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textrutKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){//Si se apreta enter se carga grilla
            if(textnrodoc.getText().length()>0 && textrut.getText().length()>0){
                CargarModificados();                
            }
            else {
                JOptionPane.showMessageDialog(Grilla_Detalle, "Ingrese Datos ");
            }        // TODO add your handling code here:
        }
        else if(evt.getKeyCode() == KeyEvent.VK_TAB){
            if(textnrodoc.getText().length()>0 && textrut.getText().length()>0){
                CargarModificados();                
            }
            else {
                JOptionPane.showMessageDialog(Grilla_Detalle, "Ingrese Datos ");
            }        // TODO add your handling code here:
        }
        
        System.out.println(evt.getKeyCode());
    }//GEN-LAST:event_textrutKeyPressed

    private void textrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textrutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textrutActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jdAutorizaModificacion mod = new jdAutorizaModificacion(null, false);//Abre menú autorización
        mod.SetUsuario(usuario);
        mod.setLocationRelativeTo(null);
        mod.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarBoton;
    private javax.swing.JTable Grilla_Detalle;
    private javax.swing.JTable Grilla_Detalle_Detalle;
    private javax.swing.JButton boton_buscar;
    private javax.swing.JComboBox<String> cbTipoDoc;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField textnrodoc;
    private javax.swing.JTextField textrut;
    // End of variables declaration//GEN-END:variables
    public static void LimpiaGrilla(DefaultTableModel dfTm){//Limpia grilla
        while(dfTm.getRowCount()>0)
            dfTm.removeRow(0);
    }
    private void CargarModificados() {//Carga grilla según datos
        try {
            DefaultTableModel model = (DefaultTableModel) Grilla_Detalle.getModel();
            Grilla_Detalle.setDefaultEditor(Object.class, null);
            pfModificarIngreso.LimpiaGrilla(model);
            ExeSql Sql = new ExeSql();
            ResultSet Rs;
            String rut = textrut.getText();
            String numero = textnrodoc.getText();
            String tipo = cbTipoDoc.getSelectedItem().toString();
            String Query = "select distinct on (ct.nrodocto) ct.rut, ct.nrodocto, ct.tipdocto, ct.femision, p.nombre, p.rut as rut_pro\n "
                    + " from ctacteprv ct\n"
                    + " left join ctacteprvdet det on ct.rut = det.rut\n"
                    + " left join proveedor p on ct.rut = p.rut\n"
                    + " where ct.tipdocto = det.tipdocto and ct.nrodocto = det.nrodocto\n"
                    + "and ct.tipdocto = '"+tipo+"' and ct.rut = "+rut+" and ct.nrodocto = "+numero+"";            
            Rs = Sql.Select(Query);
            Rs.last();
            int size = Rs.getRow();
            Rs.beforeFirst();
            if(size > 0){//Si el resultset tiene datos se continua
                JOptionPane.showMessageDialog(Grilla_Detalle, "Documento encontrado.");
                for(int i = 0;Rs.next(); i++){
                    model.addRow(new Object[]{Rs.getInt("rut_pro"),Rs.getString("nrodocto"), Rs.getString("tipdocto"),Rs.getString("femision"),Rs.getString("nombre")});

                }
                Grilla_Detalle.changeSelection(0, 0 , false, false);
                EditarBoton.setEnabled(true);
            }
            else {
                JOptionPane.showMessageDialog(Grilla_Detalle, "No se encontró documento.");
                textnrodoc.setText("");
                textrut.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(pfModificarIngreso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void CargarGrilla() {//Carga grilla completa
        try {
            DefaultTableModel model = (DefaultTableModel) Grilla_Detalle.getModel();
            pfModificarIngreso.LimpiaGrilla(model);
            ExeSql Sql = new ExeSql();
            ResultSet Rs;
            String Query = " select ct.rut, ct.nrodocto, ct.tipdocto, det.sku, ct.femision, pr.nombre\n" +
                            " from ctacteprv ct\n" +
                            " left join ctacteprvdet det on ct.rut = det.rut\n" +
                            " left join proveedor pr on ct.rut = pr.rut\n" +
                            " where ct.tipdocto = det.tipdocto and ct.nrodocto = det.nrodocto";        
            Rs = Sql.Select(Query);
            
            for(int i = 0;Rs.next(); i++){
                model.addRow(new Object[]{Rs.getInt("rut"),Rs.getInt("nrodocto"), Rs.getString("tipdocto"),Rs.getString("femision"),Rs.getString("nombre")}); 
            }
            Grilla_Detalle.changeSelection(0, 0 , false, false);
        } catch (SQLException ex) {
            Logger.getLogger(pfModificarIngreso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void CargarDetalle() {
        DefaultTableModel model = (DefaultTableModel) Grilla_Detalle_Detalle.getModel();
        Grilla_Detalle_Detalle.setDefaultEditor(Object.class, null);
        pfModificarIngreso.LimpiaGrilla(model);
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        String rut = textrut.getText();
        String numero = textnrodoc.getText();
        String tipo = cbTipoDoc.getSelectedItem().toString();
        String Query = "select ct.fcreacion, pr.nombre, pr.rut, ct.usuario\n" +
                        "from ctacteprv ct\n" +
                        "left join proveedor pr on pr.rut =  ct.rut\n" +
                        "where ct.rut = "+rut+" and ct.nrodocto = "+numero+" and tipdocto = '"+tipo+"'";
        try {
            Rs = Sql.Select(Query);
            for(int i = 0;Rs.next(); i++){
                model.addRow(new Object[]{Rs.getString("fcreacion"),Rs.getString("nombre"), Rs.getString("rut"),Rs.getString("usuario")}); 
            }
            Grilla_Detalle_Detalle.changeSelection(0, 0 , false, false);
        } catch (SQLException ex) {
            Logger.getLogger(pfModificarIngreso.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
    }
    public void SetUsuario (String usuario) {//Setter de usuario
        this.usuario = usuario;
    }
    
    public boolean CheckifEditable (String rut, String nrodocto, String tipdocto, String femision) {//Checkea si se puede editar
        boolean editable = true;
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
      
        try {
            String Query = "select autoriza from ctacteprv "
            + "where rut = "+rut+" and tipdocto = '"+tipdocto+"' and nrodocto = "+nrodocto+" and femision = '"+femision+"'";
            Rs= Sql.Select(Query);
            for(int i = 0;Rs.next(); i++){
                if(Rs.getString("autoriza").equals("1")){
                    editable = false;
                }
                else {
                    editable = true;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(pfModificarIngreso.class.getName()).log(Level.SEVERE, null, ex);
        }
        return editable;
    }

}
