/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogos;

import Conexion.ExeSql;
import Formularios.fmMain;
import PanelForm.pfReporteMercadoPublico;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import jxl.Workbook;
import jxl.WorkbookSettings;
import jxl.format.Alignment;
import jxl.format.Border;
import jxl.format.Colour;
import jxl.format.UnderlineStyle;
import jxl.write.BorderLineStyle;
import jxl.write.WritableCellFormat;
import jxl.write.WritableFont;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;

/**
 *
 * @author DavidAlcaman
 */
public class jdAgregados_MP extends javax.swing.JDialog {

    
    private int Convenio=0;
    private String NomConvenio = "";
    private int EntraAgno = 0;
    private int EntraMes = 0;
   
    
    DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    
    Date hoy = new Date();
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
    
    Calendar cal = Calendar.getInstance();
    int year  = cal.get(Calendar.YEAR);
    int month = cal.get(Calendar.MONTH)+1;
    int day = cal.get(Calendar.DAY_OF_MONTH);
    
    
    
    public jdAgregados_MP(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        leftRenderer.setHorizontalAlignment(SwingConstants.LEFT);
        Grilla.getColumnModel().getColumn(2).setCellRenderer(leftRenderer);
        
        
        
        
        Calendar fecha = new GregorianCalendar();
        int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
       
        String anox ="x";
        String mesx ="x";
        
        anox = String.valueOf(año);
        mesx = String.valueOf(mes+1);

        
        cboAgno.setSelectedItem(anox); 
        cboMes.setSelectedItem(mesx); 
        
        
        
        
        int i=0;
        boolean esta = false;
        
        
        if(cboAgno.getItemCount()-1>0){
        
            for (i=0; i<=cboAgno.getItemCount()-1;i++){
            
                cboAgno.setSelectedIndex(i);
                
                if(anox.equals(String.valueOf( cboAgno.getSelectedItem()))){
                   EntraAgno = 1; 
                   break;
                }
                
                
            }
        }
        
       
        
        
        if(cboMes.getItemCount()-1>0){
        
            for (i=0; i<=cboMes.getItemCount()-1;i++){
            
                cboMes.setSelectedIndex(i);
                
                if(mesx.equals(String.valueOf( cboMes.getSelectedItem()))){
                   EntraMes = 1;  
                   break;
                
                }
            }
        }
        
        
       
    }

    
    public void SetDatos(int convenio, String texto){
        Convenio=convenio;
        NomConvenio=texto;
       
        Inicializa();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Grilla_Dias = new javax.swing.JTable();
        cboAgno = new javax.swing.JComboBox<String>();
        cboMes = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        lblAgno = new javax.swing.JLabel();
        rbComer = new javax.swing.JRadioButton();
        rbTodos = new javax.swing.JRadioButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Grilla.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Fecha", "ID Madre", "Convenio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaMouseClicked(evt);
            }
        });
        Grilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GrillaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(70);
            Grilla.getColumnModel().getColumn(1).setPreferredWidth(600);
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(4).setMinWidth(0);
            Grilla.getColumnModel().getColumn(4).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/OCProveedor24.png"))); // NOI18N
        jButton2.setText("Exportar");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Grilla_Dias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Fechas", "Convenio"
            }
        ));
        Grilla_Dias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Grilla_DiasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Grilla_Dias);
        if (Grilla_Dias.getColumnModel().getColumnCount() > 0) {
            Grilla_Dias.getColumnModel().getColumn(1).setMinWidth(0);
            Grilla_Dias.getColumnModel().getColumn(1).setPreferredWidth(0);
            Grilla_Dias.getColumnModel().getColumn(1).setMaxWidth(0);
        }

        cboAgno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", " " }));
        cboAgno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboAgnoMouseClicked(evt);
            }
        });
        cboAgno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAgnoActionPerformed(evt);
            }
        });
        cboAgno.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cboAgnoPropertyChange(evt);
            }
        });

        cboMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cboMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMesActionPerformed(evt);
            }
        });

        jLabel8.setText("MES:");

        lblAgno.setText("AÑO:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAgno)
                    .addComponent(jLabel8))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboMes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboAgno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboAgno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAgno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(0, 119, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        buttonGroup1.add(rbComer);
        rbComer.setText("Nuevos Comercializados");
        rbComer.setToolTipText("");
        rbComer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbComerActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbTodos);
        rbTodos.setSelected(true);
        rbTodos.setText("Todos");
        rbTodos.setToolTipText("");
        rbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rbComer, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                    .addComponent(rbTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(110, 110, 110))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbComer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbTodos))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Inicializa(){
       
        DefaultTableModel model = (DefaultTableModel) Grilla_Dias.getModel();
        
        while(model.getRowCount()>0){
            model.removeRow(0);
        }
        
        
        ExeSql Sql = new ExeSql();
        ResultSet Rs = null;
        
        try {
            
            Rs = Sql.Select("SELECT CAST(a.fecha as date) FROM agregados_mp a\n" +
                             "WHERE a.convenio = "+Convenio+" \n" +
                             "AND EXTRACT (YEAR FROM a.fecha)= " + cboAgno.getSelectedItem().toString() + "\n"+
                             "AND EXTRACT (MONTH FROM a.fecha)= " + cboMes.getSelectedItem().toString() + "\n"+
                             "GROUP BY CAST(a.fecha as date) \n"+
                             "ORDER BY CAST(a.fecha as date)");
            
            
            if (Sql.GetRowCount() > 0){
             
                while (Rs.next()){
                
                    model.addRow(new Object[]{dateFormat.format(Rs.getDate("fecha")), Convenio});
                
                }
             
             
            }

        
        } catch (SQLException ex) {
            Logger.getLogger(jdAgregados_MP.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    }
    
    
    
    private void GrillaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GrillaKeyPressed
       
    }//GEN-LAST:event_GrillaKeyPressed

    private void GrillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaMouseClicked
       
    }//GEN-LAST:event_GrillaMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Exportar();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Grilla_DiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Grilla_DiasMouseClicked
        
        if (evt.getClickCount() == 1) {
        
            CargaAgregados();
        
        }
    }//GEN-LAST:event_Grilla_DiasMouseClicked

    private void cboAgnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboAgnoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cboAgnoMouseClicked

    private void cboAgnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAgnoActionPerformed
        
        System.out.println("EntraAgno ES :"+EntraAgno);
        if (EntraAgno == 1){
           
            System.out.println("ENTRA A Inicializa() Año");
            Inicializa();
        
        }
        
    }//GEN-LAST:event_cboAgnoActionPerformed

    private void cboAgnoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cboAgnoPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_cboAgnoPropertyChange

    private void cboMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMesActionPerformed
         
        System.out.println("EntraMes ES :"+EntraMes);
        if (EntraMes == 1){
           
            System.out.println("ENTRA A Inicializa() Mes");
            Inicializa();
        
        }
    }//GEN-LAST:event_cboMesActionPerformed

    private void rbComerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbComerActionPerformed
        
         DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
        
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(TableModel); 
        
        ArrayList<RowFilter<TableModel,Object>> lista = new ArrayList<RowFilter<TableModel,Object>>();  
        
        //******************************************************************************************************//
        lista.add(RowFilter.numberFilter(RowFilter.ComparisonType.AFTER, 0,3));  //Filtra todos mayores a 0
                                                        
        RowFilter filtroAnd = RowFilter.andFilter(lista); // and de ambos filtros
        sorter.setRowFilter(filtroAnd);
      //**********************************************************************************************************//
                                                        
        Grilla.setRowSorter(sorter);
        
    }//GEN-LAST:event_rbComerActionPerformed

    private void rbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTodosActionPerformed
        
        DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(TableModel);
        ArrayList<RowFilter<TableModel,Object>> lista = new ArrayList<RowFilter<TableModel,Object>>();  
                
        lista.add(RowFilter.regexFilter(""));
        
        
        RowFilter filtroAnd = RowFilter.andFilter(lista); // and de ambos filtros
        sorter.setRowFilter(filtroAnd);
      //**********************************************************************************************************//
        
        Grilla.setRowSorter(sorter);
        
        
        
    }//GEN-LAST:event_rbTodosActionPerformed
    
    
    private void Exportar(){
    
         String NomArchivo = JOptionPane.showInputDialog("Nombre de Archivo: ");
        
        if (NomArchivo.isEmpty() || NomArchivo.trim().equals("")){
        
            fmMain.Mensaje("Debe Ingresar un nombre!");  
            return;
        
        }
        
        
        
        File ruta = null;
        File carpeta = null;
                        
        String sSistemaOperativo = System.getProperty("os.name");               //Determina el Sistema Operativo del Equipo 
            
        if (sSistemaOperativo.contains("Win")){        //Si es Windows
            
            carpeta = new File("C:\\temp\\");  
            
            if (!carpeta.exists()){   //Si la carpeta no existe
            
                carpeta.mkdir();    //Se crea la carpeta 
             
            }
            
            ruta = new File("C:\\temp\\"+NomArchivo.trim()+".xls");          
        
        }
//        else{      //Si es Linux
//           
//            String NombreMetodo = "getUsername";
//            String claseNombre = "com.sun.security.auth.module.UnixSystem";
//            Object usuario = null;
//            
//            if( claseNombre != null ){            //Obtiene el nombre de usuaio de Linux
//                
//                try{
//                    Class<?> NombreClase = Class.forName(claseNombre);
//                    Method metodo = NombreClase.getDeclaredMethod( NombreMetodo );
//                    usuario = NombreClase.newInstance();
//                    
//                    usuario = metodo.invoke(usuario).toString();
//                    
//                }catch (ClassNotFoundException | InstantiationException | IllegalAccessException | IllegalArgumentException |
//                         InvocationTargetException | NoSuchMethodException | SecurityException ex) {
//                    
//                    Logger.getLogger(pfFechaVencimiento.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//            
//            carpeta = new File("/home/"+usuario+"/Escritorio/temp/");  
//            
//            if (!carpeta.exists()){
//               
//                carpeta.mkdir();
//            }
//            
//            ruta = new File("/home/"+usuario+"/Escritorio/temp/"+NomArchivo.trim()+".xls");  
//            
//        }
        
        WorkbookSettings conf = new WorkbookSettings();
        conf.setEncoding("ISO-8859-1");                                     //Se establece la norma ISO de codificación de caracteres
           
        try {
            
            WritableWorkbook libro = Workbook.createWorkbook(ruta,conf);     //Se crea libro de excel
          
            WritableFont Fuente = new WritableFont(WritableFont.ARIAL, 10, WritableFont.BOLD,false, UnderlineStyle.NO_UNDERLINE, Colour.WHITE);
            
            WritableCellFormat format = new WritableCellFormat();               //Alineación para los encabezados
            format.setAlignment(Alignment.CENTRE);
            format.setBackground(Colour.GREY_40_PERCENT);
            format.setFont(Fuente);
            format.setBorder(Border.ALL, BorderLineStyle.THIN,Colour.BLACK); //table border style
            format.setWrap(true);
            
            WritableSheet hoja = libro.createSheet(NomConvenio, 0);     //Se le asigna nombre a la primera hoja(0) del libro excel
                       
            
            hoja.setColumnView(0, 15);     //ID                                //Ancho de la columna (en número de caracteres)
            hoja.setColumnView(1, 80);     //nombre Producto                                
            hoja.setColumnView(2, 20);     //fecha de agregado 
            hoja.setColumnView(3, 15);     //ID Madre
            
            
            
            hoja.setRowView(0,26*20);    //la altura de la fila del encabezado
            
    //********************************  Se agregan contenido a las celdas de la hoja  *******************************************        
        
            
            hoja.addCell(new jxl.write.Label(0,0,"ID",format));                //Se agrega fila con el nombre de los encabezados        
            hoja.addCell(new jxl.write.Label(1,0,"Producto",format));                //Se agrega fila con el nombre de los encabezados        
            hoja.addCell(new jxl.write.Label(2,0,"Fecha",format));
            hoja.addCell(new jxl.write.Label(3,0,"ID Madre",format));
            
            
            
            WritableCellFormat format2 = new WritableCellFormat();               //Alineación para los encabezados
            format2.setAlignment(Alignment.CENTRE);
            
            
            for(int i=0; i < Grilla.getRowCount(); i++){        //Se agregan filas con los datos
            
                int fila = i+1;
                   
                hoja.addCell(new jxl.write.Label(0,fila,Grilla.getValueAt(i,0).toString()));
                hoja.addCell(new jxl.write.Label(1,fila,Grilla.getValueAt(i,1).toString()));
                hoja.addCell(new jxl.write.Label(2,fila,Grilla.getValueAt(i,2).toString(),format2));
                hoja.addCell(new jxl.write.Label(3,fila,Grilla.getValueAt(i,3).toString()));
            
            }
            
            
            
    //***************************************************************************************************************************    
            libro.write();          //Se escriben el contenido en el libro
            libro.close();          //se cierra el libro
            
            fmMain.Mensaje("Archivo : "+NomArchivo.trim()+".xls \n creado con éxito");
            
        } catch (WriteException | IOException ex) {
            Logger.getLogger(pfReporteMercadoPublico.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        
    
    
    
    
    }
    
    
    
    public void CargaAgregados() {
        DefaultTableModel model = (DefaultTableModel) Grilla.getModel();
        
        
        while(model.getRowCount()>0){
            model.removeRow(0);
        }
       
        ExeSql Sql = new ExeSql();
        ResultSet Rs = null;
        
       
        try {
            
            
            String Fecha = Grilla_Dias.getValueAt(Grilla_Dias.getSelectedRow(),0).toString();
            
            Rs = Sql.Select("SELECT a.* FROM agregados_mp a\n" +
                            "WHERE a.convenio = "+Convenio+" \n"+
                            "AND CAST(a.fecha as date) = '"+Fecha+"'");
            
              
            if (Sql.GetRowCount() > 0){
              
                while (Rs.next()) {
                            
                    model.addRow(new Object[]{Rs.getInt("id"), 
                                              Rs.getString("producto"), 
                                              dateFormat.format(Rs.getDate("fecha")), 
                                              Rs.getInt("id_madre"),
                                              Rs.getInt("convenio")  
                                             
                                                  
                    });
                                                    
                }   
                            
              
            }
            
          
            
        } catch (SQLException ex) {
            Logger.getLogger(jdAgregados_MP.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally {
            Sql.Close();
        }
            
    }
    
    
    
    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdAgregados_MP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdAgregados_MP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdAgregados_MP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdAgregados_MP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdAgregados_MP dialog = new jdAgregados_MP(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
    class Elrender extends DefaultTableCellRenderer {
         
        @Override
        public Component getTableCellRendererComponent(JTable tabla, Object valor, boolean isSelected, boolean hasFocus, int fila, int columna) {
        super.getTableCellRendererComponent(tabla,valor,isSelected, hasFocus, fila, columna);

               if(isSelected){
                   
                   this.setBackground(Color.blue);
                   this.setForeground(Color.white);    
                   
                   
               }else{
                
                   this.setForeground(Color.black);  
                   this.setBackground(Color.white);
               
               
               }  
               return this;
        
        }
    } 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla;
    private javax.swing.JTable Grilla_Dias;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboAgno;
    private javax.swing.JComboBox<String> cboMes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAgno;
    private javax.swing.JRadioButton rbComer;
    private javax.swing.JRadioButton rbTodos;
    // End of variables declaration//GEN-END:variables
}

