/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogos;

import Conexion.ExeSql;
import Formularios.fmMain;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Cdiaz
 */
public class jdAsociaCodChilemat extends javax.swing.JDialog {

    public int Asociado = 0;
    
    
    public jdAsociaCodChilemat(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        txRutChilemat.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txCodChilemat = new javax.swing.JTextField();
        txDescChilemat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txSku = new javax.swing.JTextField();
        txNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txUmChilemat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txUM = new javax.swing.JTextField();
        txUnidad = new javax.swing.JTextField();
        btIr = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        txRutChilemat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Codigo Chilemat");

        jLabel2.setText("Descripcion Chilemat");

        jLabel3.setText("Codigo Luvaly");

        jLabel4.setText("Descripcion Luvaly");

        txSku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txSkuKeyPressed(evt);
            }
        });

        txNombre.setEnabled(false);

        jLabel5.setText("UM");

        jLabel6.setText("UM");

        txUM.setEnabled(false);

        txUnidad.setEnabled(false);

        btIr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/Go.png"))); // NOI18N
        btIr.setMargin(new java.awt.Insets(1, 14, 2, 14));
        btIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIrActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/save16.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Cancel16.png"))); // NOI18N
        Cancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txRutChilemat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txDescChilemat)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txSku, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btIr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txUM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txUnidad, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txCodChilemat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txUmChilemat, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txNombre))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(Cancelar)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txCodChilemat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txUmChilemat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txDescChilemat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txSku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btIr, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txRutChilemat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txSkuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSkuKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btIr.doClick();
        }
    }//GEN-LAST:event_txSkuKeyPressed

    private void btIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIrActionPerformed
         carga_producto(); 
    }//GEN-LAST:event_btIrActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        if (Asociado == 0){
        
            ExeSql Sql1 = new ExeSql();
            ExeSql Sql3 = new ExeSql();
            ResultSet Rs1;
       
            
            
            ExeSql Sql2 = new ExeSql();
            
            
                    
            if (txNombre.getText().trim().equals("")){
            
                fmMain.Mensaje("Debe seleccionar un codigo Luvaly");
                return;                        
                    }
            if (txSku.getText().trim().equals("")){
           
                fmMain.Mensaje("Debe seleccionar un codigo Luvaly");
                return;                        
            }
                    
                    
            if(JOptionPane.showConfirmDialog(null, "¿Desea asociar los codigos?") == JOptionPane.YES_OPTION){
            
                try{
                    
                    
                    
                    Sql2.ExeSql("insert into codbar (sku, codbar, usuario, rutprv, fecha) values ('"+txSku.getText().trim()+"',"
                                + " '"+txCodChilemat.getText().trim()+"','"+fmMain.GetUsuario().trim()+"', "+txRutChilemat.getText().trim()+
                                ",CURRENT_DATE)");
                    Sql2.Commit();
                    
                    
                    Rs1 = Sql1.Select("SELECT c.codbar, \n"+
                                          "CASE \n"+
                                          "WHEN p.nombre is null \n"+
                                          "THEN 'nulo' \n"+
                                          "ELSE p.nombre \n"+
                                          "END, \n"+
                                          "CASE \n"+
                                          "WHEN c.rutprv is null \n"+
                                          "THEN 0 \n"+
                                          "ELSE c.rutprv \n"+
                                          "END \n"+
                                          "FROM codbar c \n"+
                                          "LEFT JOIN proveedor p ON c.rutprv = p.rut \n"+
                                          "WHERE c.sku='"+txSku.getText().trim()+"' \n"+
                                          "and codbar = '"+txCodChilemat.getText().trim()+"' \n"+
                                          "and c.rutprv = 96726970");
                         
                    if (Sql1.GetRowCount() == 0){
                        
                        Sql3.ExeSql("insert into codbar (sku, codbar, usuario, rutprv, fecha) values ('"+txSku.getText().trim()+"',"
                                + " '"+txCodChilemat.getText().trim()+"','"+fmMain.GetUsuario().trim()+"', 96726970,CURRENT_DATE)");
                        Sql3.Commit();
                        
                        
                    }
                    
                    
                    dispose();
                
                
                }catch(Exception e){
                 
                    Sql2.Rollback();
                    Sql3.Rollback();
                    fmMain.Mensaje("Error al grabar: "+e);

                }finally{
                 
                    Sql2.Close();
                    Sql3.Close();
                    
                }
            }
        }            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void carga_producto(){
         String codbarfinal = txSku.getText().replace("'", "-");
        txSku.setText(codbarfinal.trim());
        if(!txSku.getText().isEmpty())
             CargaProducto(txSku.getText());
        else if(!txSku.getText().isEmpty())
            txNombre.requestFocus();
        else{
            jdBuscarProductos BP = new jdBuscarProductos(null, true);
            BP.setLocationRelativeTo(null);
            BP.setTitle("Buscar Producto");
            BP.setVisible(true);
            if(!"".equals(BP.GetCodigo()))
                CargaProducto(BP.GetCodigo());
        }
    }
    
    private void CargaProducto(String Codigo){
        ExeSql  Sql = new ExeSql();
        ResultSet Rs, Rs2;
        try{
            Rs = Sql.Select("select p.discontinuado, p.sku,p.nombre,u.unidad,u.um \n" +
                            "from producto p\n" +
                            "left join par_unidad u\n" +
                            "on u.codigo=p.unidad\n" +
                            "where p.sku='" + Codigo + "'");
            Rs.next();
            txSku.setText(Rs.getString("sku"));
            txNombre.setText(Rs.getString("nombre"));
            txUnidad.setText(Rs.getString("unidad"));
            txUM.setText(Rs.getString("um"));
            

            
            if (Rs.getBoolean("discontinuado")==true)
            {
                fmMain.disc=1;
            }
            else
            {
               fmMain.disc=0;
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            }finally{
            Sql.Close();
        }
        
    }
    
    
    
    public void buscar_sku_asociado(String codbar){
        
        ExeSql  Sql = new ExeSql();
        ResultSet Rs;
        try{
            Rs = Sql.Select("select p.sku,p.nombre,p.discontinuado,u.unidad,u.um \n" +
                            "from codbar cb\n" +
                            "left join producto p on cb.sku = p.sku \n" +
                            "left join par_unidad u on u.codigo=p.unidad\n" +
                            "where cb.codbar IN ('" + codbar + "') and cb.rutprv  = "+txRutChilemat.getText().trim());
            
            
            if (Sql.GetRowCount() > 0){
                        
                Rs.next();
                
                
                Asociado = 1;
                
                txSku.setText(Rs.getString("sku"));
                txNombre.setText(Rs.getString("nombre"));
                txUnidad.setText(Rs.getString("unidad"));
                txUM.setText(Rs.getString("um"));
            
                if (Rs.getBoolean("discontinuado")==true){
                
                    fmMain.disc=1;
                
                }else{
               
                    fmMain.disc=0;
                }
                
                           
            }else{
            
            
                Asociado = 0;
            
            }
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            }finally{
            Sql.Close();
        }
        
    
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdAsociaCodChilemat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdAsociaCodChilemat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdAsociaCodChilemat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdAsociaCodChilemat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdAsociaCodChilemat dialog = new jdAsociaCodChilemat(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton btIr;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JTextField txCodChilemat;
    public javax.swing.JTextField txDescChilemat;
    private javax.swing.JTextField txNombre;
    public javax.swing.JTextField txRutChilemat;
    private javax.swing.JTextField txSku;
    private javax.swing.JTextField txUM;
    public javax.swing.JTextField txUmChilemat;
    private javax.swing.JTextField txUnidad;
    // End of variables declaration//GEN-END:variables
}
