/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogos;

import Conexion.ExeSql;
import PanelForm.pfModificarIngreso;
import Utilidades.CargaGrilla;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author infornatica
 */
public final class jdAutorizaModificacion extends javax.swing.JDialog {

    String usuario;
   
    /**
     * Creates new form jdAutorizaModificacion
     */
    public void SetUsuario(String usuario) {
        this.usuario = usuario;
    }
    public jdAutorizaModificacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        LlenarGrillaPendientes("");//Se carga grilla
        
        Grillas_pendientes.addMouseListener(new MouseAdapter(){//Listener para checkear doble click sobre fila
            public void mousePressed(MouseEvent e){
                if (e.getClickCount() == 2){
                    System.out.println(" double click" );
                    if(CheckIfAutorizable()){//Se autoriza solo si el campo autorizado es falso
                        Autorizar();
                    }
                    else {
                        JOptionPane.showMessageDialog(rootPane, "No se puede autorizar documento ya autorizado.");
                    }
                }
            }
        } );
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grillas_pendientes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        ordenarporfecha = new javax.swing.JRadioButton();
        ordenarporautorizado = new javax.swing.JRadioButton();
        todos = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setFocusable(false);

        Grillas_pendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "RUT", "N° Doc", "N°Doc (nuevo)", "Fecha Emisión", "Fecha Emisión (nuevo)", "Usuario", "Tipo", "Autorizado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Grillas_pendientes.setFocusable(false);
        Grillas_pendientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Grillas_pendientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Grillas_pendientes);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("Autorizados");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Pendientes");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addGap(60, 60, 60)
                .addComponent(jRadioButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(ordenarporfecha);
        ordenarporfecha.setText("Ordenar por fecha");
        ordenarporfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarporfechaActionPerformed(evt);
            }
        });

        buttonGroup1.add(ordenarporautorizado);
        ordenarporautorizado.setText("Ordenar por autorizados");
        ordenarporautorizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarporautorizadoActionPerformed(evt);
            }
        });

        buttonGroup1.add(todos);
        todos.setSelected(true);
        todos.setText("Todos");
        todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ordenarporfecha)
                .addGap(18, 18, 18)
                .addComponent(ordenarporautorizado)
                .addGap(18, 18, 18)
                .addComponent(todos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ordenarporfecha)
                    .addComponent(ordenarporautorizado)
                    .addComponent(todos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Filtar:");

        jLabel1.setText("Autorización Modificación");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Cancel16.png"))); // NOI18N
        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Grillas_pendientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Grillas_pendientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Grillas_pendientesMouseClicked

    private void todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosActionPerformed
        LlenarGrillaPendientes("");//Carga tabla con todos los datos
    }//GEN-LAST:event_todosActionPerformed

    private void ordenarporfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarporfechaActionPerformed
        LlenarGrillaPendientes("order by cast(fecha_new as date) desc");//Carga tabla ordenada por fecha
    }//GEN-LAST:event_ordenarporfechaActionPerformed

    private void ordenarporautorizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarporautorizadoActionPerformed
        LlenarGrillaPendientes("order by autorizado desc");//Carga tabla ordenada por autorizados
    }//GEN-LAST:event_ordenarporautorizadoActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        LlenarGrillaPendientes("where autorizado = true order by cast(fecha_new as date) desc");//Carga tabla solo con autorizados
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        LlenarGrillaPendientes("where autorizado = false order by cast(fecha_new as date) desc");//Carga la tabla solo con no autorizados
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(CheckIfAutorizable()){//Si no está autorizado, se borra
            String rut = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 0).toString();
            String nro_old = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 1).toString();
            String nro_new = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 2).toString();
            String fecha_old = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 3).toString();
            String fecha_new = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 4).toString();
            String usuario_ = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 5).toString();
            String tipo = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 6).toString();
            String autorizado = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 7).toString();
            System.out.println(rut+ "/"+nro_old+ "/"+nro_new+ "/"+fecha_old+ "/"+ fecha_new+ "/"+usuario+ "/"+tipo+ "/"+autorizado);
            if(JOptionPane.showConfirmDialog(rootPane, "¿Desea eliminar modificación?")==0){//Se ejecuta si se apreta SI
                try {
                    System.out.println("autorizado");
                    JOptionPane.showMessageDialog(rootPane,"Se ha eliminado");
                    ExeSql Sql = new ExeSql();

                    String Query = "delete from ctacteprvmod\n"

                            + "where rut_proveedor = "+rut+" and tipdocto = '"+tipo+"' and nro_old = "+nro_old+" and nro_new = "+nro_new+" and fecha_old = '"+fecha_old+"' and fecha_new = '"+fecha_new+"' and usuario = '"+usuario_+"'";
                    Sql.ExeSql(Query);
                } catch (SQLException ex) {
                    Logger.getLogger(jdAutorizaModificacion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else {//Se cancela la operación
                System.out.println("ERROR");
                JOptionPane.showMessageDialog(rootPane,"Operación Cancelada");
            }
            LlenarGrillaPendientes("");//Llena la grilla de nuevo
        }
        else {
            JOptionPane.showMessageDialog(rootPane,"No se puede eliminar modificación ya autorizada.");
        }
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdAutorizaModificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdAutorizaModificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdAutorizaModificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdAutorizaModificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdAutorizaModificacion dialog = new jdAutorizaModificacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void LlenarGrillaPendientes (String sql_extra) {//Se llena grilla pendientes y se recibe texto que se agrega a consulta
            DefaultTableModel model = (DefaultTableModel) Grillas_pendientes.getModel();
            Grillas_pendientes.setDefaultEditor(Object.class, null);
            pfModificarIngreso.LimpiaGrilla(model);
            String Query = "select rut_proveedor, nro_old, nro_new, fecha_old, fecha_new, usuario, tipdocto, autorizado "
                    + "from ctacteprvmod \n";
                    Query = Query + sql_extra;
                    
        try {
            ExeSql Sql = new ExeSql();
            ResultSet Rs;
            Rs = Sql.Select(Query);

            for(int i = 0;Rs.next(); i++){
                model.addRow(new Object[]{Rs.getInt("rut_proveedor"),Rs.getString("nro_old"),Rs.getString("nro_new"), Rs.getString("fecha_old"),Rs.getString("fecha_new"),Rs.getString("usuario"),Rs.getString("tipdocto"),Rs.getBoolean("autorizado")});
            }
            Grillas_pendientes.changeSelection(0, 0 , false, false);

            
        }
        catch (SQLException ex) {
            //Logger.getLogger(pfModificarIngreso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
            
    public void Autorizar(){

        String rut = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 0).toString();
        String nro_old = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 1).toString();
        String nro_new = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 2).toString();
        String fecha_old = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 3).toString();
        String fecha_new = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 4).toString();
        String usuario_ = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 5).toString();
        String tipo = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 6).toString();
        String autorizado = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 7).toString();
        System.out.println(rut+ "/"+nro_old+ "/"+nro_new+ "/"+fecha_old+ "/"+ fecha_new+ "/"+usuario+ "/"+tipo+ "/"+autorizado);
        if(JOptionPane.showConfirmDialog(rootPane, "Autorizar")==0){
            try {
                System.out.println("autorizado");
                JOptionPane.showMessageDialog(rootPane,"Modificación Autorizada");
                ExeSql Sql = new ExeSql();
                
                String Query = "update ctacteprvmod "
                        + "set autorizado = true, rut_proveedor = "+rut+", nro_old = "+nro_old+", nro_new = "+nro_new+","
                        + "fecha_old = '"+fecha_old+"', fecha_new = '"+fecha_new+"', fecha_aut = now(), usuario_aut = '"+this.usuario+"'"
                        + "where rut_proveedor = "+rut+" and tipdocto = '"+tipo+"' and  nro_new = "+nro_new+"";
                Sql.ExeSql(Query);
            } catch (SQLException ex) {
                Logger.getLogger(jdAutorizaModificacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            System.out.println("no autorizado");
            JOptionPane.showMessageDialog(rootPane,"Operación Cancelada");
        }
    }
    
    public boolean CheckIfAutorizable () {
        boolean autorizable = false;
        String rut = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 0).toString();
        String nro_old = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 1).toString();
        String nro_new = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 2).toString();
        String fecha_old = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 3).toString();
        String fecha_new = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 4).toString();
        String usuario_ = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 5).toString();
        String tipo = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 6).toString();
        String autorizado = Grillas_pendientes.getValueAt(Grillas_pendientes.getSelectedRow(), 7).toString();
        ExeSql Sql = new ExeSql();
        ResultSet Rs = null;
        String Query = "select autorizado from ctacteprvmod\n"
                + "where rut_proveedor = "+rut+" and nro_old = "+nro_old+" and nro_new = "+nro_new+" and fecha_old = '"+fecha_old+"' and fecha_new = '"+fecha_new+"' \n"
                + "and tipdocto = '"+tipo+"';";
        
        try {
            Rs = Sql.Select(Query);
            while(Rs.next()){
                if(Rs.getBoolean("autorizado")){
                    autorizable = false;
                    break;
                }
                else {
                    autorizable=true;
                    break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(jdAutorizaModificacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        return autorizable;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grillas_pendientes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton ordenarporautorizado;
    private javax.swing.JRadioButton ordenarporfecha;
    private javax.swing.JRadioButton todos;
    // End of variables declaration//GEN-END:variables
}
