/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogos;

import Utilidades.CargaGrillas_Econa;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DavidAlcaman
 */
public class jdBuscarProductos_Econa extends javax.swing.JDialog {

    private String CodigoPro;
    private String NombrePro;
    private boolean Insumos=false;
    private boolean esCotiza=false;
    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
    
    
    public jdBuscarProductos_Econa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        Grilla.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        CodigoPro="";
        NombrePro="";
        
        jCheckBox1.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
                        
            }


        });
    }
public String GetCodigo(){
        return CodigoPro;
        
    }
public String GetNombre(){
        return NombrePro;
        
    }
public void SetInsumo(){
    Insumos=true;
}
public void SetTexto(String Texto){
    txBuscar.setText(Texto);
}

public void SetCotiza(Boolean Cotiza){
    esCotiza = Cotiza;
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txBuscar = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel1.setText("Nombre");

        txBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txBuscarKeyReleased(evt);
            }
        });

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Con Stock");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBuscar)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar)
                    .addComponent(jCheckBox1))
                .addContainerGap())
        );

        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "UM", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaMouseClicked(evt);
            }
        });
        Grilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GrillaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(0).setMinWidth(70);
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(70);
            Grilla.getColumnModel().getColumn(0).setMaxWidth(70);
            Grilla.getColumnModel().getColumn(1).setResizable(false);
            Grilla.getColumnModel().getColumn(1).setPreferredWidth(300);
            Grilla.getColumnModel().getColumn(2).setMinWidth(30);
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(30);
            Grilla.getColumnModel().getColumn(2).setMaxWidth(30);
            Grilla.getColumnModel().getColumn(3).setMinWidth(60);
            Grilla.getColumnModel().getColumn(3).setPreferredWidth(60);
            Grilla.getColumnModel().getColumn(3).setMaxWidth(60);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String TextoBusqueda(){
        String Texto="upper(p.nombre) like '%";
        String Palabras[] = txBuscar.getText().split(" ");
        
        if(Palabras.length>0){
            Texto = Texto + Palabras[0] + "%' ";
            for(int i=1; i< Palabras.length; i++){
            Texto = Texto + "or upper(p.nombre) like '%" + Palabras[i] + "%' ";
        }
        }
        else{
            Texto = Texto + txBuscar.getText() + "%' ";
        }
        return Texto;
    }
    
    
    public void buscar_prod(Boolean cotiza){
                DefaultTableModel tbMd = new DefaultTableModel();
        
        String sql = "select p.sku,p.nombre,u.unidad,i.stock as stock\n" +
                     "from producto p\n" +
                     "left join par_unidad u\n" +
                     "on p.unidad=u.codigo\n" +
                     "left join inventario i\n" +
                     "on p.sku=i.sku\n" ;
        
        if(Insumos)
            sql = sql + "where insumo=true\n";
        else
            sql = sql + "where insumo=false\n";
        
        
        
        
        sql = sql + "and (" + TextoBusqueda() + ") ";
                
        if ( cotiza ){}

        else
            sql = sql  + " and p.es_cotiza <> 1 \n";

        if(jCheckBox1.isSelected()){
            sql = sql + " and i.stock > 0\n";
        }
        

        if ( cotiza ){
            sql = sql  + " order by nombre";
        }    
        else if (!jCheckBox1.isSelected())
            sql = sql  + " order by nombre";
        
            
            

        try {
            CargaGrillas_Econa c = new CargaGrillas_Econa();
            tbMd = c.returndata(sql);
            Grilla.setModel(tbMd);
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(90);//Sku
            Grilla.getColumnModel().getColumn(1).setPreferredWidth(280);//Nombre
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(80);//Unidad
            Grilla.getColumnModel().getColumn(3).setPreferredWidth(80);//Stock

            jScrollPane1.getViewport().add(Grilla);
            Grilla.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        } catch (Exception e) {
        }
    }
    
    
    
    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed


        buscar_prod(esCotiza);

//        DefaultTableModel tbMd = new DefaultTableModel();
//        
//        String sql = "select p.sku,p.nombre,u.unidad,i.stock as stock\n" +
//                     "from producto p\n" +
//                     "left join par_unidad u\n" +
//                     "on p.unidad=u.codigo\n" +
//                     "left join inventario i\n" +
//                     "on p.sku=i.sku\n" ;
//        
//        if(Insumos)
//            sql = sql + "where insumo=true\n";
//        else
//            sql = sql + "where insumo=false\n";
//        
//        
//        
//        
//        sql = sql + "and (" + TextoBusqueda() + ") and p.es_cotiza =0 order by nombre";
//
//        try {
//            CargaGrillas c = new CargaGrillas();
//            tbMd = c.returndata(sql);
//            Grilla.setModel(tbMd);
//            Grilla.getColumnModel().getColumn(0).setPreferredWidth(90);//Sku
//            Grilla.getColumnModel().getColumn(1).setPreferredWidth(280);//Nombre
//            Grilla.getColumnModel().getColumn(2).setPreferredWidth(80);//Unidad
//            Grilla.getColumnModel().getColumn(3).setPreferredWidth(80);//Stock
//
//            jScrollPane1.getViewport().add(Grilla);
//            Grilla.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void GrillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaMouseClicked
        if(evt.getClickCount()==2 && !Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString().isEmpty()){
              SelCodigo();
        }
    }//GEN-LAST:event_GrillaMouseClicked

    private void GrillaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GrillaKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER && !Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString().isEmpty()){
              SelCodigo();
        }
    }//GEN-LAST:event_GrillaKeyPressed

    private void txBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBuscarKeyReleased
        txBuscar.setText(txBuscar.getText().toUpperCase());
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        btBuscar.doClick();
        if(evt.getKeyCode()== KeyEvent.VK_DOWN)
        Grilla.requestFocus();
    }//GEN-LAST:event_txBuscarKeyReleased

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        buscar_prod(esCotiza);

    }//GEN-LAST:event_jCheckBox1ActionPerformed
    private void SelCodigo(){

            CodigoPro = Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString().trim();
            NombrePro = Grilla.getValueAt(Grilla.getSelectedRow(), 1).toString().trim();

        dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdBuscarProductos_Econa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdBuscarProductos_Econa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdBuscarProductos_Econa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdBuscarProductos_Econa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdBuscarProductos_Econa dialog = new jdBuscarProductos_Econa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla;
    public javax.swing.JButton btBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txBuscar;
    // End of variables declaration//GEN-END:variables
}

