/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogos;

import Conexion.ExeSql;
import Formularios.fmMain;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;

import java.io.File;
import java.io.IOException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;





/**
 *
 * @author Roberto López
 */
public class jdEstadoCtaClientes extends javax.swing.JDialog {
    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
    
    public String Rut = "";
    public String Nombre = "";
    public Double TotalDeuda = 0.0;
    
    Calendar fecha = new GregorianCalendar();
    
    int dia = fecha.get(Calendar.DAY_OF_MONTH);
    int año = fecha.get(Calendar.YEAR);
    int mes = fecha.get(Calendar.MONTH);
    
    
    public jdEstadoCtaClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        leftRenderer.setHorizontalAlignment(SwingConstants.LEFT);
        
        Grilla.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        Grilla.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        Grilla.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        Grilla.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
        Grilla.getColumnModel().getColumn(6).setCellRenderer(rightRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmMenuPagos = new javax.swing.JPopupMenu();
        miReversarPago = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();
        btGenerar = new javax.swing.JButton();

        miReversarPago.setText("Solicitar Reversa (Clientes)");
        miReversarPago.setToolTipText("");
        miReversarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miReversarPagoActionPerformed(evt);
            }
        });
        pmMenuPagos.add(miReversarPago);

        jMenuItem1.setText("jMenuItem1");
        pmMenuPagos.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Grilla.setAutoCreateRowSorter(true);
        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo OC", "Orden", "N° Doc", "Fecha Emision", "Fecha Pago", "Monto", "Pagado", "Deuda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.setComponentPopupMenu(pmMenuPagos);
        Grilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                GrillaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(90);
            Grilla.getColumnModel().getColumn(1).setPreferredWidth(90);
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(90);
            Grilla.getColumnModel().getColumn(3).setPreferredWidth(90);
            Grilla.getColumnModel().getColumn(4).setPreferredWidth(90);
            Grilla.getColumnModel().getColumn(5).setPreferredWidth(100);
            Grilla.getColumnModel().getColumn(6).setPreferredWidth(100);
            Grilla.getColumnModel().getColumn(7).setPreferredWidth(100);
        }

        btGenerar.setText("Generar");
        btGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miReversarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miReversarPagoActionPerformed
       
    }//GEN-LAST:event_miReversarPagoActionPerformed

    private void GrillaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GrillaKeyReleased
       
    }//GEN-LAST:event_GrillaKeyReleased

    private void btGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGenerarActionPerformed
        
        Imprimir();
        
        
    }//GEN-LAST:event_btGenerarActionPerformed
    
    
    public void Imprimir(){
        
        String Atencion = "";
        
        File carpeta = null;
        carpeta = new File("C:\\estadocuenta_pdf\\");
            
        if (!carpeta.exists()){
           
            //fmMain.Mensaje("Carpeta NO existe!!");
            carpeta.mkdir();
             
        }
        

        try {
                                
            Map parametro = new HashMap();

            parametro.put("CLIENTE",Nombre.trim());
//          parametro.put("Atencion",Atencion);
            parametro.put("TotalDeuda",fmMain.FormatoNumeroSinDecimal(TotalDeuda));
            parametro.put("ImagenLogo", this.getClass().getResourceAsStream("/Reportes/Logo.jpg"));
            
            
            File f = new File("Reportes/EstadoCta.jrxml");
            JasperReport report = JasperCompileManager.compileReport(f.getAbsolutePath());
            System.out.println("El RESULTADO DE report  ES :"+report+" !!!!!!");

            JasperPrint jprint =  JasperFillManager.fillReport(report, parametro, new JRTableModelDataSource(Grilla.getModel() ));

      
            String fileName = "C:/estadocuenta_pdf/EstadoCuenta_"+Rut.trim()+"_"+dia+mes+año+".pdf";
            JasperExportManager.exportReportToPdfFile(jprint, fileName);

            
            System.out.println("El fileName  ES :"+fileName);
            
            Runtime.getRuntime().exec("cmd /c start "+fileName);
        
           

        }catch (JRException ex) {

            ex.printStackTrace();
            System.out.println ("informes r" + ex.toString ());
            Logger.getLogger(jdEstadoCtaClientes.class.getName()).log(Level.SEVERE, null, ex);

        } catch (IOException ex) {
            Logger.getLogger(jdEstadoCtaClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }
    
    public void MuestraEstadoCli(String rut, String cliente, String Codigo_Oc){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        
        Rut = rut;
        Nombre = cliente;
        
        TotalDeuda = 0.0;
        
        DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
        
        while(TableModel.getRowCount()>0)
              TableModel.removeRow(0);     
        
        try {
            
            
            if (Codigo_Oc.trim().equals("Todos")){
            
                Rs = Sql.Select("select distinct cxc.rut,case when c.nombre is null then 'No Definido' else c.nombre end as nombre, \n" +
                                "cxc.codigo_oc,case when cli.occh is null then '--' else cli.occh end as occh,\n" +
                                "cxc.nrodocto,cxc.femision,cxc.femision + cast((select valor from par_general where tipo='PLAZOSCOBRANZA' and codigo=0) as integer) as fpago ,cxc.monto\n" +
                                ",cxc.pagado,cxc.monto-cxc.pagado as saldo,cxc.id, case cxc.estado when 3 then (clipa.fechapago-cxc.femision) ELSE (CURRENT_DATE-cxc.femision) end  as Dias\n" +
                                "from cli_cuentasxcobrar cxc\n" +
                                "left join cliente c on c.rut=cxc.rut\n" +
                                "left join ctactecli cli on cli.tipdocto=cxc.tipdocto and cli.rut=cxc.rut and cli.nrodocto=cxc.nrodocto\n" +
                                "left join cli_pagos clipa on clipa.cuenta =cxc.id \n" +
                                "where (cxc.monto-cxc.pagado) > 0 and cxc.rut =  "+rut.trim()+"\n" +
                                "order by Dias desc");
            
            }else{
            
                Rs = Sql.Select("select distinct cxc.rut,case when c.nombre is null then 'No Definido' else c.nombre end as nombre, \n" +
                                "cxc.codigo_oc,case when cli.occh is null then '--' else cli.occh end as occh,\n" +
                                "cxc.nrodocto,cxc.femision,cxc.femision + cast((select valor from par_general where tipo='PLAZOSCOBRANZA' and codigo=0) as integer) as fpago ,cxc.monto\n" +
                                ",cxc.pagado,cxc.monto-cxc.pagado as saldo,cxc.id, case cxc.estado when 3 then (clipa.fechapago-cxc.femision) ELSE (CURRENT_DATE-cxc.femision) end  as Dias\n" +
                                "from cli_cuentasxcobrar cxc\n" +
                                "left join cliente c on c.rut=cxc.rut\n" +
                                "left join ctactecli cli on cli.tipdocto=cxc.tipdocto and cli.rut=cxc.rut and cli.nrodocto=cxc.nrodocto\n" +
                                "left join cli_pagos clipa on clipa.cuenta =cxc.id \n" +
                                "where (cxc.monto-cxc.pagado) > 0 and cxc.rut =  "+rut.trim()+" and cxc.codigo_oc = "+Codigo_Oc.trim()+" \n" +
                                "order by Dias desc");
            
            
            
            }
            
            
            while (Rs.next()){
                
                TableModel.addRow(new Object[]{Rs.getString("codigo_oc").trim(), 
                                               Rs.getString("occh").trim(), 
                                               Rs.getString("nrodocto").trim(), 
                                               Rs.getString("femision").trim(), 
                                               Rs.getString("fpago").trim(), 
                                               fmMain.FormatoNumeroSinDecimal(Rs.getDouble("monto")),
                                               fmMain.FormatoNumeroSinDecimal(Rs.getDouble("pagado")),
                                               fmMain.FormatoNumeroSinDecimal(Rs.getDouble("saldo"))
                                                                                              
                                            });
                TotalDeuda = TotalDeuda + Rs.getDouble("saldo");
                
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);  
             Logger.getLogger(jdEstadoCtaClientes.class.getName()).log(Level.SEVERE, null, e);
        } finally{
            Sql.Close();
        }
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdEstadoCtaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdEstadoCtaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdEstadoCtaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdEstadoCtaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdEstadoCtaClientes dialog = new jdEstadoCtaClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla;
    private javax.swing.JButton btGenerar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem miReversarPago;
    private javax.swing.JPopupMenu pmMenuPagos;
    // End of variables declaration//GEN-END:variables
}
