/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogos;

import Conexion.ExeSql;
import Formularios.fmMain;
import PanelForm.pfReporteMercadoPublico;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import jxl.Workbook;
import jxl.WorkbookSettings;
import jxl.format.Alignment;
import jxl.format.Border;
import jxl.format.Colour;
import jxl.format.UnderlineStyle;
import jxl.write.BorderLineStyle;
import jxl.write.WritableCellFormat;
import jxl.write.WritableFont;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;

/**
 *
 * @author DavidAlcaman
 */
public class jdHistorialConveniosCant extends javax.swing.JDialog {

    
    private int Convenio=0;
    private String NomConvenio = "";
    private int EntraAgno = 0;
    private int EntraMes = 0;
    
    int Elige = 0;
    String NomMarca;
   
    
    DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    
    Date hoy = new Date();
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
    
    Calendar cal = Calendar.getInstance();
    int year  = cal.get(Calendar.YEAR);
    int month = cal.get(Calendar.MONTH)+1;
    int day = cal.get(Calendar.DAY_OF_MONTH);
    public static Color DARK_GREEN = new Color(0,153,0);
    public static Color BLACK_GRAY = new Color(102,102,102);
    
    
    public jdHistorialConveniosCant(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        leftRenderer.setHorizontalAlignment(SwingConstants.LEFT);
        //Grilla.getColumnModel().getColumn(2).setCellRenderer(leftRenderer);
       
        DefaultTableCellRenderer headerRenderer4 = new DefaultTableCellRenderer();  
        headerRenderer4.setBackground(new Color(153, 153, 153));  //Celeste Oscuro
        headerRenderer4.setForeground(new Color(255, 255, 255));  //Blanco
        
        
        DefaultTableCellRenderer headerRenderer5 = new DefaultTableCellRenderer();  
        headerRenderer5.setBackground(new Color(0, 153, 0));  //Verde Oscuro
        headerRenderer5.setForeground(new Color(255, 255, 255));  //Blanco
        
        DefaultTableCellRenderer headerRenderer6 = new DefaultTableCellRenderer();  
        headerRenderer6.setBackground(new Color(0, 51, 255));  //Azul
        headerRenderer6.setForeground(new Color(255, 255, 255));  //Blanco
        
        DefaultTableCellRenderer headerRenderer7 = new DefaultTableCellRenderer();  
        headerRenderer7.setBackground(new Color(255, 0, 0));  //Rojo
        headerRenderer7.setForeground(new Color(255, 255, 255));  //Blanco
        
        
       
        Grilla.getColumnModel().getColumn(4).setHeaderRenderer(headerRenderer4);
        Grilla.getColumnModel().getColumn(5).setHeaderRenderer(headerRenderer5);
        Grilla.getColumnModel().getColumn(6).setHeaderRenderer(headerRenderer6);
        Grilla.getColumnModel().getColumn(7).setHeaderRenderer(headerRenderer7);
        
        
        
        Calendar fecha = new GregorianCalendar();
        int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
       
       
    }

    
    public void SetDatos(int convenio, String texto){
        Convenio=convenio;
        NomConvenio=texto;
        
        CargaHistorial();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Grilla.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Total ID Publicadas", "Total ID Luvaly", "Total Productos Luvaly", "Total No Asociadas Sku", "Total ID Habilitados", "Total ID Deshabilitados", "Total ID No Comercializados", "convenio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaMouseClicked(evt);
            }
        });
        Grilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GrillaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(0).setMinWidth(80);
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(0).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(1).setMinWidth(105);
            Grilla.getColumnModel().getColumn(1).setPreferredWidth(105);
            Grilla.getColumnModel().getColumn(1).setMaxWidth(105);
            Grilla.getColumnModel().getColumn(2).setMinWidth(85);
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(85);
            Grilla.getColumnModel().getColumn(2).setMaxWidth(85);
            Grilla.getColumnModel().getColumn(3).setMinWidth(120);
            Grilla.getColumnModel().getColumn(3).setPreferredWidth(120);
            Grilla.getColumnModel().getColumn(3).setMaxWidth(120);
            Grilla.getColumnModel().getColumn(4).setMinWidth(135);
            Grilla.getColumnModel().getColumn(4).setPreferredWidth(135);
            Grilla.getColumnModel().getColumn(4).setMaxWidth(135);
            Grilla.getColumnModel().getColumn(5).setMinWidth(115);
            Grilla.getColumnModel().getColumn(5).setPreferredWidth(115);
            Grilla.getColumnModel().getColumn(5).setMaxWidth(115);
            Grilla.getColumnModel().getColumn(6).setMinWidth(135);
            Grilla.getColumnModel().getColumn(6).setPreferredWidth(135);
            Grilla.getColumnModel().getColumn(6).setMaxWidth(135);
            Grilla.getColumnModel().getColumn(7).setMinWidth(160);
            Grilla.getColumnModel().getColumn(7).setPreferredWidth(160);
            Grilla.getColumnModel().getColumn(7).setMaxWidth(160);
            Grilla.getColumnModel().getColumn(8).setMinWidth(0);
            Grilla.getColumnModel().getColumn(8).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(8).setMaxWidth(0);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void GrillaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GrillaKeyPressed
       
    }//GEN-LAST:event_GrillaKeyPressed

    private void GrillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaMouseClicked
       
        if(evt.getClickCount()==2){
            
            String Marca = Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString().trim();
           
            NomMarca = Marca;
            Elige = 1;
           
            this.dispose();
        }
        
        
        
    }//GEN-LAST:event_GrillaMouseClicked
    
    
    
    public String GetNomMarca(){
        return NomMarca;
    }
    
    
    public int GetElige(){
        return Elige;
    }
    
    
    
    private void Exportar(){
    
//        String NomArchivo = JOptionPane.showInputDialog("Nombre de Archivo: ");
//        
//        if (NomArchivo.isEmpty() || NomArchivo.trim().equals("")){
//        
//            fmMain.Mensaje("Debe Ingresar un nombre!");  
//            return;
//        
//        }
//        
//        
//        
//        File ruta = null;
//        File carpeta = null;
//                        
//        String sSistemaOperativo = System.getProperty("os.name");               //Determina el Sistema Operativo del Equipo 
//            
//        if (sSistemaOperativo.contains("Win")){        //Si es Windows
//            
//            carpeta = new File("C:\\temp\\");  
//            
//            if (!carpeta.exists()){   //Si la carpeta no existe
//            
//                carpeta.mkdir();    //Se crea la carpeta 
//             
//            }
//            
//            ruta = new File("C:\\temp\\"+NomArchivo.trim()+".xls");          
//        
//        }
//
//        
//        WorkbookSettings conf = new WorkbookSettings();
//        conf.setEncoding("ISO-8859-1");                                     //Se establece la norma ISO de codificación de caracteres
//           
//        try {
//            
//            WritableWorkbook libro = Workbook.createWorkbook(ruta,conf);     //Se crea libro de excel
//          
//            WritableFont Fuente = new WritableFont(WritableFont.ARIAL, 10, WritableFont.BOLD,false, UnderlineStyle.NO_UNDERLINE, Colour.WHITE);
//            
//            WritableCellFormat format = new WritableCellFormat();               //Alineación para los encabezados
//            format.setAlignment(Alignment.CENTRE);
//            format.setBackground(Colour.GREY_40_PERCENT);
//            format.setFont(Fuente);
//            format.setBorder(Border.ALL, BorderLineStyle.THIN,Colour.BLACK); //table border style
//            format.setWrap(true);
//            
//            WritableSheet hoja = libro.createSheet(NomConvenio, 0);     //Se le asigna nombre a la primera hoja(0) del libro excel
//                       
//            
//            hoja.setColumnView(0, 15);     //ID                                //Ancho de la columna (en número de caracteres)
//            hoja.setColumnView(1, 80);     //nombre Producto                                
//            hoja.setColumnView(2, 20);     //fecha de agregado 
//            hoja.setColumnView(3, 15);     //ID Madre
//            
//            
//            
//            
//            hoja.setRowView(0,26*20);    //la altura de la fila del encabezado
//            
//    //********************************  Se agregan contenido a las celdas de la hoja  *******************************************        
//        
//            
//            hoja.addCell(new jxl.write.Label(0,0,"ID",format));                //Se agrega fila con el nombre de los encabezados        
//            hoja.addCell(new jxl.write.Label(1,0,"Producto",format));                //Se agrega fila con el nombre de los encabezados        
//            hoja.addCell(new jxl.write.Label(2,0,"Fecha",format));
//            hoja.addCell(new jxl.write.Label(3,0,"ID Madre",format));
//            
//            
//            
//            WritableCellFormat format2 = new WritableCellFormat();               //Alineación para los encabezados
//            format2.setAlignment(Alignment.CENTRE);
//            
//            
//            for(int i=0; i < Grilla.getRowCount(); i++){        //Se agregan filas con los datos
//            
//                int fila = i+1;
//                   
//                hoja.addCell(new jxl.write.Label(0,fila,Grilla.getValueAt(i,0).toString()));
//                hoja.addCell(new jxl.write.Label(1,fila,Grilla.getValueAt(i,1).toString()));
//                hoja.addCell(new jxl.write.Label(2,fila,Grilla.getValueAt(i,2).toString(),format2));
//                hoja.addCell(new jxl.write.Label(3,fila,Grilla.getValueAt(i,3).toString()));
//            
//            }
//            
//            
//            
//    //***************************************************************************************************************************    
//            libro.write();          //Se escriben el contenido en el libro
//            libro.close();          //se cierra el libro
//            
//            fmMain.Mensaje("Archivo : "+NomArchivo.trim()+".xls \n creado con éxito");
//            
//        } catch (WriteException | IOException ex) {
//            Logger.getLogger(pfReporteMercadoPublico.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    
    
    }
    
    
    
    public void CargaHistorial() {
        DefaultTableModel model = (DefaultTableModel) Grilla.getModel();
        
        
        while(model.getRowCount()>0){
            model.removeRow(0);
        }
       
        ExeSql Sql = new ExeSql();
        ResultSet Rs = null;
        
        ExeSql Sql2 = new ExeSql();
        ResultSet Rs2 = null;
        
        
        ExeSql Sql3 = new ExeSql();
        ResultSet Rs3 = null;
        
       
        int asociado = 0;
        
        try {
            
            Rs = Sql.Select("SELECT * FROM historico_cant_id_convenios\n" +
                            "WHERE convenio = "+Convenio+" \n" +
                            "ORDER BY fecha DESC");
              
            if (Sql.GetRowCount() > 0){
              
                while (Rs.next()) {
                           
                    model.addRow(new Object[]{dateFormat.format(Rs.getDate("fecha")),
                                              Rs.getInt("totalid"), 
                                              Rs.getInt("totalidluvaly"), 
                                              Rs.getInt("totalidmadre"), 
                                              Rs.getInt("totalnoasociados"), 
                                              Rs.getInt("totalhabilitados"),
                                              Rs.getInt("totaldeshabilitados"), 
                                              Rs.getInt("totalnocomercializados"),
                                              Convenio
                                                  
                    });
                                                    
                }   
                            
              
            }
          
            Grilla.setDefaultRenderer(Object.class, new jdHistorialConveniosCant.Elrender()); 
            
            
        } catch (SQLException ex) {
            Logger.getLogger(jdHistorialConveniosCant.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally {
            Sql.Close();
        }
            
    }
    
    
    
    class Elrender extends DefaultTableCellRenderer {
         
        @Override
        public Component getTableCellRendererComponent(JTable tabla, Object valor, boolean isSelected, boolean hasFocus, int fila, int columna) {
            
            super.getTableCellRendererComponent(tabla,valor,isSelected, hasFocus, fila, columna);
            
            if(isSelected==true){
                
                this.setForeground(Color.white);
                this.setBackground(Color.BLUE);    
                this.setFont(new Font("Tahoma", Font.BOLD, 11));
                 
            }else{
                  
                this.setForeground(Color.BLACK); 
                this.setBackground(Color.white);   
                    
                this.setFont(new Font("Tahoma", Font.BOLD, 11));
            }
            
            
            if (columna == 0){
                   
                this.setHorizontalAlignment(SwingConstants.CENTER);
                   
                   
            }else{
            
            
                this.setHorizontalAlignment(SwingConstants.RIGHT);
            
            }
            
            
            
            return this;
        }
    }
    
    
    
    
    
    
    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdHistorialConveniosCant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdHistorialConveniosCant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdHistorialConveniosCant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdHistorialConveniosCant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdHistorialConveniosCant dialog = new jdHistorialConveniosCant(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

