/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogos;

import Conexion.ExeSql;
import Formularios.fmMain;
import java.awt.print.PrinterJob;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.PrintService;
import javax.swing.JOptionPane;

/**
 *
 * @author David Alcaman
 */
public class jdImpresoras extends javax.swing.JDialog {
    
    Date hoy = new Date();
    
    int Existe = 0;
    
    
    
    public jdImpresoras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            initComponents();
            
            String name = "";
            
            
            try { 
                InetAddress inetadd = InetAddress.getLocalHost();
            
                name = inetadd.getHostName();
            
                String address = inetadd.getHostAddress();
            
                System.out.println("HostName is : "+name);
                System.out.println("Host Address is: "+address);
            
            
            
            } catch (UnknownHostException ex) {
                Logger.getLogger(fmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
            lbPC.setText(name.trim());
            
            
            PrintService[] services2 = PrinterJob.lookupPrintServices();
            
            
            for (int i = 0; i < services2.length; i++) {
                
                cbFac.addItem(services2[i].getName().toString());
                cbBol.addItem(services2[i].getName().toString());
            }
            
            
            ExeSql Sql = new ExeSql();
            ResultSet Rs;
            
            
//            Rs = Sql.Select("SELECT * FROM indicadores \n" +
//                            "WHERE valor = 1 AND codigo IN ('"+name.trim()+"')");
            
            
            Rs = Sql.Select("SELECT * FROM configuraciones \n" +
                            "WHERE valor = 1 AND codigo IN ('"+name.trim()+"')");
            

            Rs.next();
            
            
            if (Sql.GetRowCount() > 0){
                
                int index = 0;
                
                for(int o = 0; o < cbFac.getItemCount(); o++){
                
                    if(cbFac.getItemAt(o).equals(Rs.getString("nombre"))){
                        index = o;
                        break;
                    }
                }
                
                cbFac.setSelectedIndex(index);
            
            }
            
            
            Rs = Sql.Select("SELECT * FROM configuraciones \n" +
                            "WHERE valor = 2 AND codigo IN ('"+name.trim()+"')");

            Rs.next();
            
            
            if (Sql.GetRowCount() > 0){
                
                int index = 0;
                
                for(int o = 0; o < cbBol.getItemCount(); o++){
                
                    if(cbBol.getItemAt(o).equals(Rs.getString("nombre"))){
                        index = o;
                        break;
                    }
                }
                
                cbBol.setSelectedIndex(index);
            
            }
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(jdImpresoras.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAplicar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btCerrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbFac = new javax.swing.JComboBox();
        cbBol = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        lbPC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Impresoras");

        btAplicar.setText("Aplicar");
        btAplicar.setToolTipText("");
        btAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAplicarActionPerformed(evt);
            }
        });

        jLabel2.setText("Facturas / Guias");

        btCerrar.setText("Cerrar");
        btCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Boletas / Notas Ventas");

        jLabel4.setText("Nombre PC");

        lbPC.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbFac, 0, 205, Short.MAX_VALUE)
                            .addComponent(cbBol, 0, 205, Short.MAX_VALUE)
                            .addComponent(lbPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbPC, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
    
    private void btAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAplicarActionPerformed
        
        ExeSql Sql = new ExeSql(); 
        ExeSql Sql2 = new ExeSql(); 
         ResultSet Rs2 = null;

        try {
   
                
            
            Rs2 = Sql2.Select("SELECT * FROM configuraciones WHERE codigo IN ('" + lbPC.getText().trim()+"')");
            
            
            if (Sql2.GetRowCount() > 0){
            
                Sql.ExeSql("UPDATE configuraciones SET \n" +               
                            "nombre = '"+ cbFac.getSelectedItem().toString().trim()+ "' \n"+
                            "WHERE valor = 1 AND codigo IN ('"+lbPC.getText().trim()+"') \n"+
                            "AND codigo = '"+lbPC.getText().trim()+"'");
                
                Sql.Commit();
                
                
                Sql.ExeSql("UPDATE configuraciones SET \n" +               
                            "nombre = '"+ cbBol.getSelectedItem().toString().trim()+ "'\n"+
                            "WHERE valor = 2 AND codigo IN ('"+lbPC.getText().trim()+"') \n"+
                            "AND codigo = '"+lbPC.getText().trim()+"'");
                
                Sql.Commit();

     
                fmMain.Mensaje("Parámetros Actualizados !");
                dispose();
            
            }else {
            
                
                Sql.ExeSql("INSERT INTO configuraciones(\n"+
                           "codigo, nombre, valor) \n"+
                           "VALUES ('"+lbPC.getText().trim()+"','"+cbFac.getSelectedItem().toString().trim()+"',1)");
                
                Sql.Commit();

                
                
                Sql.ExeSql("INSERT INTO configuraciones(\n"+
                           "codigo, nombre, valor) \n"+
                           "VALUES ('"+lbPC.getText().trim()+"','"+cbBol.getSelectedItem().toString().trim()+"',2)");
                
                Sql.Commit();
            
                fmMain.Mensaje("Parámetros Creados !");
                dispose();
            
            
            }    
                
                
        } catch (SQLException ex) {
        
          Sql.Rollback();
          Logger.getLogger(jdImpresoras.class.getName()).log(Level.SEVERE, null, ex);
        
        } finally{
        
            Sql.Close();
        
        }
      
        
    }//GEN-LAST:event_btAplicarActionPerformed

    
    
    

    private void btCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarActionPerformed
       
        dispose();
    }//GEN-LAST:event_btCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdImpresoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdImpresoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdImpresoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdImpresoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdImpresoras dialog = new jdImpresoras(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAplicar;
    private javax.swing.JButton btCerrar;
    private javax.swing.JComboBox cbBol;
    private javax.swing.JComboBox cbFac;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbPC;
    // End of variables declaration//GEN-END:variables
}
