/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogos;

import Formularios.fmMain;
import java.awt.event.KeyEvent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author DavidAlcaman
 */
public class jdIngresaNumero extends javax.swing.JDialog {

    double Numero, Preciounit, PrecioDesc;
    String TipoDocto="";
    int Tipo = 0;
    int x=500, y=100;
 
    public jdIngresaNumero(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAceptar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        txNumero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txPreciounit = new javax.swing.JTextField();
        txTotalDescuento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbDescuentoUnitario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        btAceptar.setText("Aceptar");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        txNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txNumeroKeyPressed(evt);
            }
        });

        jLabel1.setText("Ingresa la Cantidad");

        jLabel2.setText("Ingresa precio unitario (NETO)");
        jLabel2.setToolTipText("");

        txPreciounit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txPreciounitKeyPressed(evt);
            }
        });

        txTotalDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTotalDescuentoActionPerformed(evt);
            }
        });
        txTotalDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txTotalDescuentoKeyPressed(evt);
            }
        });

        jLabel3.setText("Ingresa Descuento Total (NETO)");
        jLabel3.setToolTipText("");

        jLabel4.setText("Precio Unitario con Descuento (NETO) ");

        lbDescuentoUnitario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDescuentoUnitario.setText("0");
        lbDescuentoUnitario.setToolTipText("");
        lbDescuentoUnitario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCancelar)
                        .addGap(90, 90, 90)
                        .addComponent(btAceptar))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txPreciounit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTotalDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDescuentoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txPreciounit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txTotalDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbDescuentoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAceptar)
                    .addComponent(btCancelar))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public Double GetNumero(){
        return Numero;
       
    }
    
    public Double GetPrecio(){
        return Preciounit;
       
    }
    
    
    public Double GetPrecioDesc(){
        
        return PrecioDesc;
       
    }
    
    
        
    public void SetNumero(double cantidad)
    {
        Numero = cantidad;
        txNumero.setText(String.valueOf(Numero));
    }
    
    public void setTipoDocto(String TipoDocto) {

         this.TipoDocto = TipoDocto;

    }
        
    public void SetPrecio(double nvo_precio)
    {
        Preciounit = nvo_precio;
        txPreciounit.setText(fmMain.SetGuardar(fmMain.FormatoNumero(Preciounit)));
        
        PrecioDesc = 0;
        lbDescuentoUnitario.setText(""+PrecioDesc);
        
        txTotalDescuento.setText("0");
        
    }    
    
    
    
    public void SetTipo(int tipo){
    
       Tipo = tipo;
       
       if (Tipo == 1){
       
           jLabel2.setVisible(true);
           txPreciounit.setVisible(true);
           
           jLabel3.setVisible(true);
           txTotalDescuento.setVisible(true);
           
           jLabel4.setVisible(true);
           lbDescuentoUnitario.setVisible(true);
        
       }else {
       
           jLabel2.setVisible(false);
           txPreciounit.setVisible(false);
           
           jLabel3.setVisible(false);
           txTotalDescuento.setVisible(false);
           
           
           jLabel4.setVisible(false);
           lbDescuentoUnitario.setVisible(false);
           
       
        }
       
    
    }
    
    

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
       Numero=-99;
       dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    
    public void Msje (String Titulo, String Mensaje, int xx , int yy){
            JOptionPane pane = new JOptionPane(Mensaje);  
            JDialog dialog = pane.createDialog(Titulo);  
            dialog.setLocation(xx, yy);  
            dialog.setVisible(true);  
    }
    
    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        if(TipoDocto.equals("FAT"))
        {
            if(Double.valueOf(txNumero.getText()) > Numero)
            {
                Msje("Validacion", "La cantidad no puede ser mayor al numero Original que es: " + Numero, x, y);
                txNumero.requestFocus();
            }
        }
        
        
        if (txNumero.getText().equals("")){
            
            txNumero.setText("0");
            
        }
        
        if (txPreciounit.getText().equals("")){
                Msje("Validacion", "Debe ingresar un valor para Precio Unitario", x, y);
                txPreciounit.requestFocus();
        }

        
        Numero = Double.valueOf(txNumero.getText());
        Preciounit = Double.valueOf(fmMain.SetGuardar(txPreciounit.getText()));
        PrecioDesc = Double.valueOf(fmMain.SetGuardar(lbDescuentoUnitario.getText()));
        
        dispose();
    }//GEN-LAST:event_btAceptarActionPerformed

    private void txNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNumeroKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
            btAceptar.doClick();
    }//GEN-LAST:event_txNumeroKeyPressed

    private void txPreciounitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPreciounitKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPreciounitKeyPressed

    private void txTotalDescuentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txTotalDescuentoKeyPressed

        if(evt.getKeyCode()== KeyEvent.VK_ENTER) {

            if (txTotalDescuento.getText().trim().isEmpty()){

                txTotalDescuento.setText("0");

            }

            int cant = (int) Math.round(Double.parseDouble(txNumero.getText().trim()));

            double descuento = Double.parseDouble(txTotalDescuento.getText().trim());

            double unitario = Double.parseDouble(txPreciounit.getText().trim());

            System.out.println("cant ES :"+cant);

            System.out.println("descuento ES :"+descuento);

            if (descuento > 0){

                unitario = unitario - (descuento/cant);
                
                
                 System.out.println("unitario ES :"+unitario);
                
                if (unitario < 0){
                
                
                    fmMain.Mensaje("Valor no puede ser negativo!!");
                    return;
                
                }
                
                

                txPreciounit.setText(""+fmMain.FormatoNumero2(descuento/cant));
                
                lbDescuentoUnitario.setText(""+fmMain.FormatoNumero2(unitario));

            }

        }

    }//GEN-LAST:event_txTotalDescuentoKeyPressed

    private void txTotalDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTotalDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTotalDescuentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdIngresaNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdIngresaNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdIngresaNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdIngresaNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdIngresaNumero dialog = new jdIngresaNumero(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbDescuentoUnitario;
    private javax.swing.JTextField txNumero;
    private javax.swing.JTextField txPreciounit;
    private javax.swing.JTextField txTotalDescuento;
    // End of variables declaration//GEN-END:variables
}
