/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Dialogos.jdAbrirDocumento;
import Dialogos.jdAbrirFolioAud;
import Dialogos.jdBuscaFolioAud;
import Dialogos.jdBuscaUbicacion;
import Dialogos.jdBuscarProductos;
import Dialogos.jdNoUbicados;
import Dialogos.jdProductosVenc;
import Dialogos.jdSeparablesIngreso;
import Dialogos.jdSeparacionesUbicacion;
import Dialogos.jd_UbicacionProductos;
import static Dialogos.jd_UbicacionProductos.Fecha;
import static Dialogos.jd_UbicacionProductos.Id;
import static Dialogos.jd_UbicacionProductos.convenio;
import static Dialogos.jd_UbicacionProductos.esFecha;
import Formularios.fmMain;
import static Formularios.fmMain.pnPestanas;
import Utilidades.Combo_CodStr;
import Utilidades.ComboCodigos;
import Utilidades.PanelTab;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author luvaly
 */
public class AuditoriaMetro2 extends javax.swing.JPanel {
    
    public boolean booAgregando = false;
    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();   
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    public static Color DARK_GREEN = new Color(0,153,0);
    
    int nuevo = 0; //0 = Abrir   /  1 = Nuevo
    
    int contselec = 0;
    int cant = 0;
    double dcant = 0;
    int Nota = 0;
    int Ncp = 0;
    int GlobalStock = 0;
    int NoEncontrado = 0;
    
    /**
     * Creates new form AsignaUbicacion
     */
 
    public AuditoriaMetro2() {
        initComponents();
        
        lbEstado.setForeground(new Color(0, 153, 51));
        txtUbicacion.setEnabled(false);
        btUbc.setEnabled(false);
        
        txtSku.setEnabled(false);
        txCant.setEnabled(false);
        
        btUbicar.setEnabled(false);
        btReubicar.setEnabled(false);
        
        
        btGuardaFolio.setVisible(false);
        btCancelaFolio.setVisible(false);
        
        btGuardaFolio.setEnabled(false);
        btCancelaFolio.setEnabled(false);
        
        btCerrarFolio.setEnabled(false);
        
        txFolio.setEditable(false);
       
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        MnuProd = new javax.swing.JMenuItem();
        panel = new javax.swing.JPanel();
        btUbicar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Grilla_metro = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSku = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        txCant = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JTextField();
        btUbc = new javax.swing.JButton();
        txNombreUbicacion = new javax.swing.JTextField();
        btNuevoFolio = new javax.swing.JButton();
        btAbreFolio = new javax.swing.JButton();
        btCerrarFolio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla_Aud = new javax.swing.JTable();
        btReubicar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btCancelaFolio = new javax.swing.JButton();
        btGuardaFolio = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txFolio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lbEstado = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        MnuProd.setText("Ver Producto");
        MnuProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuProdActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MnuProd);

        btUbicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Ok.png"))); // NOI18N
        btUbicar.setText("UBICAR AUDITORIA");
        btUbicar.setToolTipText("");
        btUbicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUbicarActionPerformed(evt);
            }
        });

        Grilla_metro.setAutoCreateRowSorter(true);
        Grilla_metro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sku", "Nombre", "Cant"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla_metro.setComponentPopupMenu(jPopupMenu1);
        Grilla_metro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Grilla_metroMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Grilla_metro);
        if (Grilla_metro.getColumnModel().getColumnCount() > 0) {
            Grilla_metro.getColumnModel().getColumn(0).setMinWidth(80);
            Grilla_metro.getColumnModel().getColumn(0).setMaxWidth(80);
            Grilla_metro.getColumnModel().getColumn(1).setMinWidth(460);
            Grilla_metro.getColumnModel().getColumn(1).setMaxWidth(460);
            Grilla_metro.getColumnModel().getColumn(2).setMinWidth(60);
            Grilla_metro.getColumnModel().getColumn(2).setMaxWidth(60);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Sku");

        txtSku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSkuActionPerformed(evt);
            }
        });
        txtSku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSkuKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSkuKeyReleased(evt);
            }
        });

        jLabel3.setText("Nombre");

        txNombre.setEditable(false);
        txNombre.setEnabled(false);
        txNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNombreActionPerformed(evt);
            }
        });
        txNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txNombreKeyPressed(evt);
            }
        });

        txCant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txCant.setText("1");
        txCant.setToolTipText("");
        txCant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txCantKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txCantKeyTyped(evt);
            }
        });

        jLabel1.setText("Cantidad");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtSku, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(234, 234, 234)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txCant, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txNombre))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(17, 17, 17))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Ubicacion");

        txtUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUbicacionActionPerformed(evt);
            }
        });
        txtUbicacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUbicacionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUbicacionKeyReleased(evt);
            }
        });

        btUbc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/search.png"))); // NOI18N
        btUbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUbcActionPerformed(evt);
            }
        });

        txNombreUbicacion.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btUbc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txNombreUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(269, 269, 269))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btUbc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txNombreUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        btNuevoFolio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/Order22.png"))); // NOI18N
        btNuevoFolio.setText("Nuevo Folio");
        btNuevoFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoFolioActionPerformed(evt);
            }
        });

        btAbreFolio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/Open.png"))); // NOI18N
        btAbreFolio.setText("Cargar Folio");
        btAbreFolio.setToolTipText("");
        btAbreFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbreFolioActionPerformed(evt);
            }
        });

        btCerrarFolio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/Movimientos.png"))); // NOI18N
        btCerrarFolio.setText("Cerrar Folio");
        btCerrarFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarFolioActionPerformed(evt);
            }
        });

        Grilla_Aud.setAutoCreateRowSorter(true);
        Grilla_Aud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sku", "Nombre", "Stock Sistema", "Stock Físico", "Reubicados", "Diferencia", "", "Ubc_Origen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla_Aud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Grilla_AudMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Grilla_Aud);
        if (Grilla_Aud.getColumnModel().getColumnCount() > 0) {
            Grilla_Aud.getColumnModel().getColumn(0).setMinWidth(80);
            Grilla_Aud.getColumnModel().getColumn(0).setMaxWidth(80);
            Grilla_Aud.getColumnModel().getColumn(1).setMinWidth(250);
            Grilla_Aud.getColumnModel().getColumn(1).setMaxWidth(390);
            Grilla_Aud.getColumnModel().getColumn(2).setMinWidth(80);
            Grilla_Aud.getColumnModel().getColumn(2).setMaxWidth(80);
            Grilla_Aud.getColumnModel().getColumn(3).setMinWidth(70);
            Grilla_Aud.getColumnModel().getColumn(3).setMaxWidth(70);
            Grilla_Aud.getColumnModel().getColumn(4).setMinWidth(70);
            Grilla_Aud.getColumnModel().getColumn(4).setMaxWidth(70);
            Grilla_Aud.getColumnModel().getColumn(5).setMinWidth(70);
            Grilla_Aud.getColumnModel().getColumn(5).setMaxWidth(70);
            Grilla_Aud.getColumnModel().getColumn(6).setMinWidth(30);
            Grilla_Aud.getColumnModel().getColumn(6).setMaxWidth(30);
            Grilla_Aud.getColumnModel().getColumn(7).setMinWidth(0);
            Grilla_Aud.getColumnModel().getColumn(7).setPreferredWidth(0);
            Grilla_Aud.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        btReubicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Actualiza.png"))); // NOI18N
        btReubicar.setText("REUBICAR");
        btReubicar.setToolTipText("");
        btReubicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReubicarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PRODUCTOS EN UBICACION");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PRODUCTOS EN AUDITORIA");

        btCancelaFolio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Cancel16.png"))); // NOI18N
        btCancelaFolio.setText("Cancela Folio");
        btCancelaFolio.setToolTipText("");
        btCancelaFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelaFolioActionPerformed(evt);
            }
        });

        btGuardaFolio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/save.png"))); // NOI18N
        btGuardaFolio.setText("Guardar Folio");
        btGuardaFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardaFolioActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Folio :");

        txFolio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txFolio.setForeground(new java.awt.Color(0, 0, 255));
        txFolio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txFolio.setText("S/N");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Estado :");

        lbEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEstado.setToolTipText("");
        lbEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lbEstado.setOpaque(true);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(411, 411, 411)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(btNuevoFolio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAbreFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCerrarFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(btGuardaFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelaFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btUbicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btReubicar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btNuevoFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAbreFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCerrarFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btGuardaFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCancelaFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(lbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(btUbicar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btReubicar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private String existe_sku(String Codigo, String ubicacion){
    ExeSql Sql = new ExeSql();
        ResultSet Rs1;
        String Query2 ="";
        String strUbicacion = "";
        
         try{
         
          Query2 = "select * from mt_productos where sku = '" + Codigo + "' and ubicacion = '" + ubicacion + "';";
            Rs1 = Sql.Select(Query2);
                     if (Rs1.next()){
                        return(Rs1.getString("sku"));
                     }   
         }
     catch (Exception e) {
            System.out.println(e.getMessage());
        } finally{
            Sql.Close();
        }          
        return(""); 
    }
    
    
    private void txtSkuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSkuKeyPressed
        
        DefaultTableModel TableModelo = (DefaultTableModel) Grilla_Aud.getModel(); 
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            if (txtSku.getText().isEmpty() || txtSku.getText().equals("") || txtSku.getText().contains(" ") ){
            
                fmMain.Mensaje("Debe ingresar Sku...!");
                txtSku.requestFocus();
                return;
            }
            
            
            
            int encontrado = 0;
          
            carga_producto();
            
            
            if(NoEncontrado == 0){
            
                return;
            
            }
            
            
         
            for (int i = 0; i < Grilla_Aud.getRowCount(); i++) {
                       
                if (Grilla_Aud.getValueAt(i, 0).equals(txtSku.getText().trim())) {
            
                     Grilla_Aud.changeSelection(i, 0, false, false);
                     encontrado = 1;
                     break;
                }else {
                
                    encontrado = 0;
                
                }
            }
            
            
            if (encontrado == 1){
                
                String Folio = txFolio.getText().toString().trim();
                String Sku = Grilla_Aud.getValueAt(Grilla_Aud.getSelectedRow(), 0).toString().trim();
                int Sistema =  Integer.parseInt(Grilla_Aud.getValueAt(Grilla_Aud.getSelectedRow(), 2).toString().trim());
                int StockFisicoActual =  Integer.parseInt(Grilla_Aud.getValueAt(Grilla_Aud.getSelectedRow(), 3).toString().trim());
                int StockFisicoNuevo = Integer.parseInt(txCant.getText());
                int StockReubicado =  Integer.parseInt(Grilla_Aud.getValueAt(Grilla_Aud.getSelectedRow(), 4).toString().trim());
            
                int Total = StockFisicoActual + StockFisicoNuevo;
            
                
                if (Total > Sistema ){
                
                    fmMain.Mensaje("Cantidad supera el Stock del Sistema !!");
                    txtSku.setText("");
                    txNombre.setText("");
                    txtSku.requestFocus();
                    txCant.setText("1");
                    contar();
                    
                    return;
                
                }
                
                
                Grilla_Aud.setValueAt(Total, Grilla_Aud.getSelectedRow(), 3);
                
                int Dif = StockReubicado - Sistema;
                Grilla_Aud.setValueAt(Dif, Grilla_Aud.getSelectedRow(), 5);
                
    //****************************************************************************************************************************//            
                ExeSql Sql3 = new ExeSql();
                               
                try {
            
                    String QryDel = "UPDATE mt_auditoria_ubicaciones SET \n"+
                                    "stock_sistema = " +  Sistema + ", \n" +
                                    "stock_fisico = " +  Total + ", \n" +
                                    "reubicados = " +  StockReubicado + ",\n"+
                                    "diferencia = " +  Dif + ", \n" +
                                    "usuario_mod = '" + fmMain.GetUsuario() + "' \n" +
                                    "WHERE folio = "+Folio+" AND sku = '" + Sku + "' ";
                        
                        
                    Sql3.ExeSql(QryDel);
                    Sql3.Commit();
                       
         
                }catch (SQLException e) {
                
                    System.out.println(e.getMessage());
                    Logger.getLogger(AuditoriaMetro2.class.getName()).log(Level.SEVERE, null, e);
                    Sql3.Rollback();
                
                }finally{
                
                    Sql3.Close();
                
                }
                
        //***************************************************************************************************************************//        
                
                txtSku.setText("");
                txNombre.setText("");
                txtSku.requestFocus();
                txCant.setText("1");
                
                
                contar();
                
                        
            }else{
            
                    fmMain.Mensaje("Producto no pertenece a este Folio !!");
                  
                    
                    ExeSql SqlFolio = new ExeSql();
                    ResultSet RsFolio;
                    
                    
                    String sql = "SELECT distinct folio, \n"+
                                 "case \n"+
                                 "when estado = 0 then 'Abierto' \n"+
                                 "when estado = 1 then 'Cerrado' \n"+
                                 "end as estado \n"+
                                 "FROM mt_auditoria_ubicaciones \n"+
                                 "WHERE sku IN ('"+txtSku.getText().trim()+"') AND (stock_sistema - stock_fisico) > 0 \n"+
                                 "ORDER BY folio desc";
                    
                    
                    
                try {
                    RsFolio = SqlFolio.Select(sql);
                } catch (SQLException ex) {
                    Logger.getLogger(AuditoriaMetro2.class.getName()).log(Level.SEVERE, null, ex);
                }
            
                    if (SqlFolio.GetRowCount() == 0){
            
                        fmMain.Mensaje("No hay pendientes asociados a este Producto !!");
                        txtSku.setText("");
                        txNombre.setText("");
                        txtSku.requestFocus();
                        txCant.setText("1");
                        return;
                    }
                    
                    
                    
                    
                    jdBuscaFolioAud Fol = new jdBuscaFolioAud(null, true);
                    Fol.ShowModal(txtSku.getText().trim());
                    Limpiar();
                    
                    nuevo = 0;
                    
                    
                    DefaultTableModel TableModelo1 = (DefaultTableModel) Grilla_Aud.getModel(); 
                    DefaultTableModel TableModelo2 = (DefaultTableModel) Grilla_metro.getModel(); 
        
                    while (TableModelo.getRowCount() > 0) {
                        TableModelo.removeRow(0);
                    }   
        
        
                    ExeSql Sql = new ExeSql();
                    ResultSet Rs;
        
                    ExeSql SqlLuv = new ExeSql();
                    ResultSet RsLuv;
        
                    String Query ="";
                    String QueryLuv="";
                    String Nombre = "";
        
                    int cont = 0;
                    
                    
                    try{
         
                        Query = "SELECT m.*, p.nombre FROM mt_auditoria_ubicaciones m \n"+
                                "LEFT JOIN producto p ON m.sku = p.sku \n"+
                                "WHERE m.folio = "+Fol.GetNumero()+" \n"+
                                "ORDER BY m.folio desc";
            
                        Rs = Sql.Select(Query);
            
                        if (Sql.GetRowCount() > 0){
            
                            while (Rs.next()){
                        
                        
                                String Sku = Rs.getString("sku");
                    
                                QueryLuv="SELECT sku, nombre FROM producto \n"+ 
                                         "WHERE sku IN ('" + Sku.trim() + "') "; 
                    
                                RsLuv = SqlLuv.Select(QueryLuv);
                    
                                if (SqlLuv.GetRowCount() > 0){
                    
                                    RsLuv.next();
                                    Nombre = RsLuv.getString("nombre");
                                            
                                }
                        
                        
                                int Sistema = Rs.getInt("stock_sistema");
                                int Fisico = Rs.getInt("stock_fisico");
                                int Reubicado = Rs.getInt("reubicados");
                                int Dif = Rs.getInt("diferencia");
                                String UbicaOrigen = Rs.getString("ubica_origen").trim();
                        
                                        
                                TableModelo.addRow(new Object[]{Sku,Nombre,Sistema,Fisico,Reubicado,Dif,false,UbicaOrigen });
                        
                                cont = cont + Dif;
                
                            }
                
                
                            txFolio.setText(Fol.GetNumero());
                            lbEstado.setText(Fol.GetTipo());
                    
                            if(Fol.GetTipo().equals("Abierto")){
                    
                                lbEstado.setForeground(new Color(0, 153, 51));  //Verde
                    
                            }else{
                    
                                lbEstado.setForeground(new Color(255, 0, 0));  //Rojo
                    
                            }
                    
                    
                
                            txtUbicacion.setEnabled(true);
                            btUbc.setEnabled(true);
                
                            txtSku.setEnabled(true);
                            txCant.setEnabled(true);
                            btReubicar.setEnabled(true);
                    
                            while (TableModelo2.getRowCount() > 0) {
                                   TableModelo2.removeRow(0);
                            }
                    
                            System.out.println("El cont ES : "+cont);
                    
                    
                            if (cont >= 0 && lbEstado.getText().equals("Abierto")){
                    
                                btCerrarFolio.setEnabled(true);
                        
                    
                            }else{
                    
                                btCerrarFolio.setEnabled(false);
                    
                            }
                    
                    
                        }   
        
                    }catch (Exception e) {
            
                        System.out.println(e.getMessage());
            
                    } finally{
            
                        Sql.Close();
                    }          
             
            }
        }


    }//GEN-LAST:event_txtSkuKeyPressed

    
    private void contar(){
    
        int cont = 0;
    
        
        for (int i = 0; i < Grilla_Aud.getRowCount(); i++) {
                       
            int Dif =  Integer.parseInt(Grilla_Aud.getValueAt(i, 5).toString().trim());   
            
            cont = cont + Dif;
            
        }
        
        System.out.println("El cont ES : "+cont);
        
        
        if (cont >= 0 && lbEstado.getText().equals("Abierto")){
                    
            btCerrarFolio.setEnabled(true);
                    
        }else {
        
            btCerrarFolio.setEnabled(false);
        
        }
    
    
    }
    
      
    private void txtSkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSkuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSkuActionPerformed

    private void txtSkuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSkuKeyReleased
        
         txtSku.setText( txtSku.getText().toUpperCase());
    }//GEN-LAST:event_txtSkuKeyReleased

    
    private void txNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNombreActionPerformed

    private void MnuProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuProdActionPerformed
        // TODO add your handling code here:
        System.out.println( Grilla_metro.getValueAt(Grilla_metro.getSelectedRow(), 0).toString().trim());
        pfProductos Pro = new pfProductos();
        Pro.setOpaque(false);
        pnPestanas.addTab("Producto", Pro);
        PanelTab btc = new PanelTab(pnPestanas, 0);
        pnPestanas.setTabComponentAt(pnPestanas.indexOfComponent(Pro), btc);
        pnPestanas.setSelectedIndex(pnPestanas.getTabCount() - 1);
        Pro.txSku.requestFocus();
        Pro.CargaProducto(Grilla_metro.getValueAt(Grilla_metro.getSelectedRow(), 0).toString().trim());   
    }//GEN-LAST:event_MnuProdActionPerformed

    private void txNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNombreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNombreKeyPressed

    private void txtUbicacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUbicacionKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
             
            if(txtUbicacion.getText().equals("") || txtUbicacion.getText().isEmpty()){ 
            
                btUbc.doClick();
                
            
            }else {
             
                ExeSql Sql = new ExeSql();
                ResultSet Rs;
                String Query="";
                   
            
                try {
                
                
                    Query="SELECT * FROM mt_codmetro \n"+ 
                           "WHERE codmetro IN ('" + txtUbicacion.getText().trim()  + "') "; 
                
                    Rs = Sql.Select(Query);

                    if (Sql.GetRowCount() > 0){
            
                        Rs.next();
                       
                        txNombreUbicacion.setText(Rs.getString("nombre"));
                                   
                        CargaProductos();
                        
                      
                        
                        if (nuevo == 1){
        
                            btUbicar.setEnabled(true);
                        }
                    
                    }else {
                
                        fmMain.Mensaje("La Ubicación No Existe!!"); 
                        txtUbicacion.setText("");
                        txNombreUbicacion.setText("");
                        return;
                
                    }
           
              
            
                }catch (Exception e) {
            
                    System.out.println(e);
                }finally{
            
                    Sql.Close();
                }
            
            }   
        
        }  
    }//GEN-LAST:event_txtUbicacionKeyPressed

    
    private void CargaProductos(){
    
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
                
        DefaultTableModel TableModelo = (DefaultTableModel) Grilla_metro.getModel();        
        String Query="";
        
        
        while (TableModelo.getRowCount() > 0) {
            TableModelo.removeRow(0);
        }
            
        try {
                
            Query="SELECT mt.sku, p.nombre, mt.cant FROM mt_productos mt \n"+ 
                  "LEFT JOIN producto p ON mt.sku = p.sku \n"+ 
                  "WHERE mt.ubicacion IN ('" + txtUbicacion.getText().trim()  + "') "; 
                
            Rs = Sql.Select(Query);

            if (Sql.GetRowCount() > 0){
            
                while(Rs.next()){
                    
                    
                    if (Rs.getInt("cant") > 0){
                    
                        TableModelo.addRow(new Object[]{Rs.getString("sku"),Rs.getString("nombre"),Rs.getString("cant")});
                    
                    }
                
                }  
                        
                    
            }
           
              
            
        }catch (Exception e) {
            
            System.out.println(e);
        }finally{
            
            Sql.Close();
        }
               
        
        
    
    }
    
    
    private void txtUbicacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUbicacionKeyReleased
        txtUbicacion.setText( txtUbicacion.getText().toUpperCase());
    }//GEN-LAST:event_txtUbicacionKeyReleased

    private void btUbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUbcActionPerformed
        
       jdBuscaUbicacion Ubicacion= new jdBuscaUbicacion(null, true);
        Ubicacion.CargaBodegaOR(1);
        Ubicacion.setVisible(true);
        txtUbicacion.setText(Ubicacion.GetUbicacion());
        txNombreUbicacion.setText(Ubicacion.GetNombreUbicacion());
        
        CargaProductos();
        
        if (nuevo == 1){
        
            btUbicar.setEnabled(true);
        }
         
    }//GEN-LAST:event_btUbcActionPerformed

    private void btUbicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUbicarActionPerformed
        
        DefaultTableModel TableModelo = (DefaultTableModel) Grilla_Aud.getModel(); 
        DefaultTableModel TableModelo2 = (DefaultTableModel) Grilla_metro.getModel(); 
        
        String Dif = "0";
        
        while (TableModelo.getRowCount() > 0) {
            TableModelo.removeRow(0);
        }
        
        for (int i = 0; i < Grilla_metro.getRowCount(); i++) {
        
            
            String Sku = Grilla_metro.getValueAt(i, 0).toString().trim();
            String Nombre = Grilla_metro.getValueAt(i, 1).toString().trim();
            String Cant = Grilla_metro.getValueAt(i, 2).toString().trim();
            
              
            if (!Cant.equals("0")){
              
                Dif = "-"+Cant;
              
            }else {
                
                Dif = "0";
              
            }
            
            TableModelo.addRow(new Object[]{Sku,Nombre,Cant,"0","0",Dif,false, txtUbicacion.getText().trim()});
        
        }
        
        
        Ubicar_Aud();
       
        
        while (TableModelo2.getRowCount() > 0) {
            TableModelo2.removeRow(0);
        }
        
        txtUbicacion.setText("");
        txNombreUbicacion.setText("");
                       
        txtSku.setEnabled(true);
        txCant.setEnabled(true);
        txtSku.requestFocus();
        btUbicar.setEnabled(false);
        btReubicar.setEnabled(true);
        
        
        
    }//GEN-LAST:event_btUbicarActionPerformed
    
    public void Ubicar_Aud(){
           
        ExeSql Sql = new ExeSql();
        ExeSql Sql2 = new ExeSql();
        ExeSql SqlAud = new ExeSql();
        
        ResultSet Rs,Rs1, Rs2, RsAud;
        
       //********************************* 
        
       
       
        
        String Sku = "";
        String Ubicacion = "";
        String QryIns;
        
        String NewCorrelativo;
        
        int stocksistema = 0;
        int stockfisico = 0;
        int stockreubicado = 0;
        int diferencia = 0;
      
       
        try{
                
                Ubicacion = txtUbicacion.getText().toString().trim();
                              
            //************************************************************************************************************ 
                
                  Rs = Sql.Select("select sp_getcorrelativo \n" +
                                  "from sp_getcorrelativo('INV')");   
                        Rs.next();
                        NewCorrelativo  = Rs.getString("sp_getcorrelativo");
                        Rs.close();
                
                
                txFolio.setText(NewCorrelativo);
                lbEstado.setText("Abierto");
                
            //************************************************************************************************************           
                // UBICA PRODUCTOS EN AUDITORIA
                 for (int i = 0; i < Grilla_Aud.getRowCount(); i++) {
                   
                                                 
                        Sku = Grilla_Aud.getValueAt(i, 0).toString().trim();
                        stocksistema =  Integer.parseInt(Grilla_Aud.getValueAt(i, 2).toString().trim());
                        stockfisico = Integer.parseInt(Grilla_Aud.getValueAt(i, 3).toString().trim());
                        stockreubicado = Integer.parseInt(Grilla_Aud.getValueAt(i, 3).toString().trim());
                        diferencia = Integer.parseInt(Grilla_Aud.getValueAt(i, 5).toString().trim());
                            
                        QryIns = "INSERT into mt_auditoria_ubicaciones (ubica_origen,ubicacion,sku,folio,stock_sistema,stock_fisico, \n"+
                                 "reubicados,diferencia) \n" +
                                  "values ('" + Ubicacion + "',' ','" + Sku + "'," + NewCorrelativo  + "," + stocksistema + ", \n " + 
                                  stockfisico + ","+stockreubicado+","+ diferencia + ")";
                        
                        Sql2.ExeSql(QryIns);
                        Sql2.Commit();
                            
                        
                        rebaja_stock(Ubicacion,Sku.trim(),stocksistema);
                     
                }   
                
         
        }catch (SQLException e) {
        
            System.out.println(e.getMessage());
            Logger.getLogger(AuditoriaMetro2.class.getName()).log(Level.SEVERE, null, e);
            Sql2.Rollback();
         
        
        } finally{
            
            Sql2.Close();
            
            
        }          
        
        
        
    }
    
    private void txtUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUbicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUbicacionActionPerformed

    private void Grilla_metroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Grilla_metroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Grilla_metroMouseClicked

    private void btNuevoFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoFolioActionPerformed
       
       // if(fmMain.OkCancel("¿Esta seguro de crear un nuevo folio?") == JOptionPane.OK_OPTION){
            
            
            nuevo = 1;
            
            btNuevoFolio.setEnabled(false);
            btAbreFolio.setEnabled(false);
            btCerrarFolio.setEnabled(false);
            
            btGuardaFolio.setEnabled(true);
            btCancelaFolio.setEnabled(true);
            
            
            
            txtUbicacion.setEnabled(true);
            btUbc.setEnabled(true);
            txtUbicacion.requestFocus();
            
            
            Limpiar();

//            nuevo_folio();
//            // Estado Abierto
            
            txFolio.setText("S/N");
            lbEstado.setText(" ");
            

        //}
    }//GEN-LAST:event_btNuevoFolioActionPerformed

    private void Limpiar(){
    
        txtUbicacion.setText("");
        txNombreUbicacion.setText("");
        txtSku.setText("");
        txNombre.setText("");
        txCant.setText("1");
        
        txtSku.setEnabled(false);
        txCant.setEnabled(false);
        
        DefaultTableModel TableModelo = (DefaultTableModel) Grilla_metro.getModel();        
        DefaultTableModel TableModelo2 = (DefaultTableModel) Grilla_Aud.getModel();        
        
       
        
        
        while (TableModelo.getRowCount() > 0) {
            TableModelo.removeRow(0);
        }
        
        while (TableModelo2.getRowCount() > 0) {
            TableModelo2.removeRow(0);
        }
        
        
    
    }
    
    
    
    
    private void btAbreFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbreFolioActionPerformed
           
        nuevo = 0;
        Abrir_Folio();
        
        if (lbEstado.getText().equals("Cerrado")){
        
            txtUbicacion.setEnabled(false);
            btUbc.setEnabled(false);
            txtSku.setEnabled(false);
            txCant.setEnabled(false);
            btReubicar.setEnabled(false);
        
        
        }


    }//GEN-LAST:event_btAbreFolioActionPerformed

    
    private void Abrir_Folio(){
        
        DefaultTableModel TableModelo = (DefaultTableModel) Grilla_Aud.getModel(); 
        DefaultTableModel TableModelo2 = (DefaultTableModel) Grilla_metro.getModel(); 
        
        while (TableModelo.getRowCount() > 0) {
            TableModelo.removeRow(0);
        }
        
        
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        String Query ="";
        int cont = 0;
        
        
        
        jdAbrirFolioAud ADoc = new jdAbrirFolioAud(null, true);
        
        if(ADoc.ShowModal()==JOptionPane.YES_OPTION){
            
            try{
         
                Query = "SELECT m.*, p.nombre FROM mt_auditoria_ubicaciones m \n"+
                        "LEFT JOIN producto p ON m.sku = p.sku \n"+
                        "WHERE m.folio = "+ADoc.GetNumero()+" \n"+
                        "ORDER BY m.folio desc";
            
                Rs = Sql.Select(Query);
            
                if (Sql.GetRowCount() > 0){
            
                    while (Rs.next()){
                        
                        String Sku = Rs.getString("sku").trim(); 
                        String Nombre = Rs.getString("nombre").trim(); 
                        int Sistema = Rs.getInt("stock_sistema");
                        int Fisico = Rs.getInt("stock_fisico");
                        int Reubicado = Rs.getInt("reubicados");
                        int Dif = Rs.getInt("diferencia");
                        String UbicaOrigen = Rs.getString("ubica_origen").trim();
                        
                                        
                        TableModelo.addRow(new Object[]{Sku,Nombre,Sistema,Fisico,Reubicado,Dif,false,UbicaOrigen });
                        
                        cont = cont + Dif;
                
                    }
                
                
                    txFolio.setText(ADoc.GetNumero());
                    lbEstado.setText(ADoc.GetTipo());
                    
                    if(ADoc.GetTipo().equals("Abierto")){
                    
                        lbEstado.setForeground(new Color(0, 153, 51));  //Verde
                    
                    }else{
                    
                        lbEstado.setForeground(new Color(255, 0, 0));  //Rojo
                    
                    
                    }
                    
                    
                
                    txtUbicacion.setEnabled(true);
                    btUbc.setEnabled(true);
                
                    txtSku.setEnabled(true);
                    txCant.setEnabled(true);
                    btReubicar.setEnabled(true);
                    
                    while (TableModelo2.getRowCount() > 0) {
                           TableModelo2.removeRow(0);
                    }
                    
                    System.out.println("El cont ES : "+cont);
                    
                    
                    if (cont >= 0 && lbEstado.getText().equals("Abierto")){
                    
                        btCerrarFolio.setEnabled(true);
                        
                    
                    }else{
                    
                         btCerrarFolio.setEnabled(false);
                    
                    }
                    
                    
                }   
        
            }catch (Exception e) {
            
                System.out.println(e.getMessage());
            
            } finally{
            
                Sql.Close();
            }          
                
        }
        
        
        
    
    }
    
    
    
    
    
    
    
    
    private void btCerrarFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarFolioActionPerformed
        
        ExeSql Sql3 = new ExeSql();
        String Folio = txFolio.getText().toString().trim();
                               
                try {
            
                    for (int i = 0; i < Grilla_Aud.getRowCount(); i++) {
        
            
                        String Sku = Grilla_Aud.getValueAt(i, 0).toString().trim();
                        
                        String QryDel = "UPDATE mt_auditoria_ubicaciones SET \n"+
                                        "estado =  1 \n" +
                                        "WHERE folio = "+Folio+" AND sku = '" + Sku + "' ";
                    
                    
                        Sql3.ExeSql(QryDel);
                        Sql3.Commit();
                    
                    } 
                    
                    lbEstado.setText("Cerrado");  
                    lbEstado.setForeground(new Color(255, 0, 0));
                    
                    
                    txtUbicacion.setEnabled(false);
                    btUbc.setEnabled(false);
                    txtSku.setEnabled(false);
                    txCant.setEnabled(false);
                    btReubicar.setEnabled(false);
                    
                    btCerrarFolio.setEnabled(false);
                    btAbreFolio.setEnabled(true);
                    btNuevoFolio.setEnabled(true);
                    
                    
         
                }catch (SQLException e) {
                
                    System.out.println(e.getMessage());
                    Logger.getLogger(AuditoriaMetro2.class.getName()).log(Level.SEVERE, null, e);
                    Sql3.Rollback();
                
                }finally{
                
                    Sql3.Close();
                
                }
        
        

    }//GEN-LAST:event_btCerrarFolioActionPerformed

    private void Grilla_AudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Grilla_AudMouseClicked
        
        if(evt.getClickCount()==1){
         
             boolean selecciona = (boolean) Grilla_Aud.getValueAt(Grilla_Aud.getSelectedRow(),6);
             
             if (selecciona){
             
                 
                 contselec++;
             
             }else if (!selecciona) {
             
                 contselec--;
             
             }
             
             
             if (contselec > 0){
             
               System.out.println("HAY ELEMENTOS SELECCIONADOS!!"+contselec);
             
             }else if (contselec == 0){
             
                 System.out.println("NO EXISTEN ELEMENTOS SELECCIONADOS!!"+contselec);
                 
             }
             
         }
        
        
    }//GEN-LAST:event_Grilla_AudMouseClicked

    private void txCantKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCantKeyPressed
       
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           
            if(txCant.getText().isEmpty() || txCant.getText().equals("") || txCant.getText().contains(" ")){
                    
                fmMain.Mensaje("Cantidad no válida !!");
                txCant.requestFocus();
                return;
            
            }
            
            if (txtSku.getText().isEmpty() || txtSku.getText().equals("") || txtSku.getText().contains(" ") ){
            
                fmMain.Mensaje("Debe ingresar Sku !!");
                txtSku.requestFocus();
                return;
            }
            
            
            int encontrado = 0;
            carga_producto();
          
            
            for (int i = 0; i < Grilla_Aud.getRowCount(); i++) {
                       
                if (Grilla_Aud.getValueAt(i, 0).equals(txtSku.getText().trim())) {
            
                     Grilla_Aud.changeSelection(i, 0, false, false);
                     encontrado = 1;
                     break;
                }else {
                
                    encontrado = 0;
                
                }
            }
            
            
            if (encontrado == 1){
                        
                String Folio = txFolio.getText().toString().trim();
                String Sku = Grilla_Aud.getValueAt(Grilla_Aud.getSelectedRow(), 0).toString().trim();
            
                int Sistema =  Integer.parseInt(Grilla_Aud.getValueAt(Grilla_Aud.getSelectedRow(), 2).toString().trim());
                int StockFisicoActual =  Integer.parseInt(Grilla_Aud.getValueAt(Grilla_Aud.getSelectedRow(), 3).toString().trim());
                int StockFisicoNuevo = Integer.parseInt(txCant.getText());
                int StockReubicado =  Integer.parseInt(Grilla_Aud.getValueAt(Grilla_Aud.getSelectedRow(), 4).toString().trim());
            
                int Total = StockFisicoActual + StockFisicoNuevo;  //Va sumando los Sku encontrados
            
                if (Total > Sistema ){
                
                    fmMain.Mensaje("Cantidad supera el Stock del Sistema !!");
                    txtSku.setText("");
                    txNombre.setText("");
                    txtSku.requestFocus();
                    txCant.setText("1");
                    
                    contar();
                    
                    return;
                
                }
                
                                
                Grilla_Aud.setValueAt(Total, Grilla_Aud.getSelectedRow(), 3);
            
                 int Dif = StockReubicado - Sistema;
            
                Grilla_Aud.setValueAt(Dif, Grilla_Aud.getSelectedRow(), 5);
            
                ExeSql Sql3 = new ExeSql();
                               
                try {
            
                    String QryDel = "UPDATE mt_auditoria_ubicaciones SET \n"+
                                    "stock_sistema = " +  Sistema + ", \n" +
                                    "stock_fisico = " +  Total + ", \n" +
                                    "reubicados = " +  StockReubicado + ",\n"+
                                    "diferencia = " +  Dif + ", \n" +
                                    "usuario_mod = '" + fmMain.GetUsuario() + "' \n" +
                                    "WHERE folio = "+Folio+" AND sku = '" + Sku + "' ";
                        
                        
                    Sql3.ExeSql(QryDel);
                    Sql3.Commit();
                    
                    txtSku.setText("");
                    txNombre.setText("");
                    txtSku.requestFocus();
                    txCant.setText("1");
                    
                    
                    contar();
         
                }catch (SQLException e) {
                
                    System.out.println(e.getMessage());
                    Logger.getLogger(AuditoriaMetro2.class.getName()).log(Level.SEVERE, null, e);
                    Sql3.Rollback();
                
                }finally{
                
                    Sql3.Close();
                
                }
                        
            }
        }
        
        
    }//GEN-LAST:event_txCantKeyPressed

    private void txCantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCantKeyTyped
        
        char validar = evt.getKeyChar();    //Código agregado por R. Lopez
        if (Character.isLetter(validar)){   //se valida que solo se ingresen 
           
            evt.consume();                  //números al textfield "txRut"
        }
        
        
    }//GEN-LAST:event_txCantKeyTyped

    private void btReubicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReubicarActionPerformed
     
        int existe = 0;
        int totalsistema = 0;  
        int totalfisicos = 0;  
        int totalubicados = 0;  
        int totaldiferencia = 0;  
        
        
        
        if (contselec == 0){
         
            fmMain.Mensaje("No hay Productos Seleccionados!!");
            return;
         
        }
        
        
        if (txtUbicacion.getText().isEmpty() || txtUbicacion.getText().equals("") || txtUbicacion.getText().equals(" ") ){
            
            fmMain.Mensaje("Debe elegir una ubicación!!");
            return;
        
        }
        
        
        
        DefaultTableModel TableModelo2 = (DefaultTableModel) Grilla_metro.getModel(); 

        
        for (int i = 0; i < Grilla_Aud.getRowCount(); i++) {
        
            boolean agrega = (boolean) Grilla_Aud.getValueAt(i, 6);
           
            totalsistema = Integer.parseInt(Grilla_Aud.getValueAt(i, 2).toString().trim());
            totalfisicos = Integer.parseInt(Grilla_Aud.getValueAt(i, 3).toString().trim());
            totalubicados = Integer.parseInt(Grilla_Aud.getValueAt(i, 4).toString().trim());
            
            String Sku = Grilla_Aud.getValueAt(i, 0).toString().trim();
            String Nombre = Grilla_Aud.getValueAt(i, 1).toString().trim();
            String Fisico = Grilla_Aud.getValueAt(i, 3).toString().trim();    
            
            if(totalsistema > totalubicados ){
            
                totaldiferencia =  totalubicados-totalsistema;
            
            }
          
            if(agrega){
                
                
                System.out.println("totalsistema : "+totalsistema + "  /  totalubicados : "+totalubicados);
                
                
                if (Fisico.equals("0")){
                  
                    fmMain.Mensaje("No se puede reubicar producto con cantidad 0 !");
                    
                }else if(totalsistema <= totalubicados ) {
                
                     fmMain.Mensaje("No hay productos para reubicar !!");
                    
                }else{  
                    
                    
                    
                    for (int j = 0; j < Grilla_metro.getRowCount(); j++) {
                      
                        if (Sku.equals(Grilla_metro.getValueAt(j, 0).toString().trim())){
                        
                            existe = 1;
                            int cant =  Integer.parseInt(Grilla_metro.getValueAt(j, 2).toString().trim()) + Integer.parseInt(Fisico.trim())  ; 
                                                       
                            Grilla_metro.setValueAt(cant, j, 2);
                            break;
                        
                        }else {
                        
                            existe = 0;
                        
                        }
                        
                        
                      
                    }
                    
                    
                    if (existe == 0){       //Si el Sku no está en la Ubicación a reubicar... 
                   
                 
                        TableModelo2.addRow(new Object[]{Sku,Nombre,Fisico}); // ...se agrega
                    
                    }
                    
                    totalubicados = totalubicados + totalfisicos;
                    totaldiferencia = totalubicados-totalsistema;
                    
                    
                    Grilla_Aud.setValueAt(totalfisicos, i, 3);
                    Grilla_Aud.setValueAt(totalubicados, i, 4);
                    Grilla_Aud.setValueAt(totaldiferencia, i, 5);
                    
                    
        //*********************************************************************************************************************//            
            
                    ExeSql Sql3 = new ExeSql();
                    String Folio = txFolio.getText().toString().trim();           
                    try {
            
                        String QryDel = "UPDATE mt_auditoria_ubicaciones SET \n"+
                                        "stock_fisico = " +  totalfisicos + ", \n" +
                                        "reubicados = " +  totalubicados + ",\n"+
                                        "diferencia = " +  totaldiferencia + ", \n" +
                                        "usuario_mod = '" + fmMain.GetUsuario() + "' \n" +
                                        "WHERE folio = "+Folio+" AND sku = '" + Sku + "' ";
                        
                        
                        Sql3.ExeSql(QryDel);
                        Sql3.Commit();
                       
         
                    }catch (SQLException e) {
                
                        System.out.println(e.getMessage());
                        Logger.getLogger(AuditoriaMetro2.class.getName()).log(Level.SEVERE, null, e);
                        Sql3.Rollback();
                
                    }finally{
                
                        Sql3.Close();
                
                    }
                 
                    
        //**********************************************************************************************************************//            
                   
                    
                }
                
                 
                
                Grilla_Aud.setValueAt(false, i, 6);   //deselecciona en Ubicación Auditoría el producto reubicado
                              
               
                ReUbicar_Ubc();
               
                contar();
            }
              
                      
        }
        

        txtSku.setText("");
        txNombre.setText("");
        txCant.setText("1");
       
        
        
        
       // btReubicar.setEnabled(false);
                
        
    }//GEN-LAST:event_btReubicarActionPerformed

    
    private void ReUbicar_Ubc(){
    
        
        ExeSql Sql = new ExeSql();
        ExeSql Sql2 = new ExeSql();
        ResultSet Rs;
        
        
        try {
       

        for (int i = 0; i < Grilla_metro.getRowCount(); i++) {

            String Sku = Grilla_metro.getValueAt(i, 0).toString().trim();
            String Cant = Grilla_metro.getValueAt(i, 2).toString().trim();
            String Ubica = txtUbicacion.getText().trim();
            
            
            Rs = Sql.Select("select * from mt_productos where ubicacion = '" + Ubica + "' and sku = '" + Sku + "'");
            
            if (Sql.GetRowCount() > 0){
            
                String QryDel = "UPDATE mt_productos SET \n"+
                                "cant = " +  Cant + ", \n" +
                                "usuario_mod = '" + fmMain.GetUsuario() + "' \n" +
                                "WHERE ubicacion IN ('"+Ubica+"') AND sku = '" + Sku + "' ";
            
                Sql2.ExeSql(QryDel);
            
                Sql2.Commit();
            
            }else if (Sql.GetRowCount() == 0){
            
                
                String QryDel = "INSERT INTO mt_productos (ubicacion,sku,cant,usuario)\n" +
                                 "VALUES ('"+Ubica+"','" + Sku + "',"+Cant+",'"+fmMain.GetUsuario()+"')";
            
                Sql2.ExeSql(QryDel);
            
                Sql2.Commit();
                
                    
            
            }
        }  
            
        
        } catch (SQLException ex) {
            Sql2.Rollback();
            
            Logger.getLogger(AuditoriaMetro2.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
    
            Sql2.Close();
            
        }
    
    
    }
    
    
    private void btCancelaFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelaFolioActionPerformed
       
        btNuevoFolio.setEnabled(true);
        btAbreFolio.setEnabled(true);
        btCerrarFolio.setEnabled(false);
        btCancelaFolio.setEnabled(false);
        
        revierte();
                
        
    }//GEN-LAST:event_btCancelaFolioActionPerformed

    private void btGuardaFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardaFolioActionPerformed
       
        btNuevoFolio.setEnabled(true);
        btAbreFolio.setEnabled(true);
        
        btGuardaFolio.setEnabled(false);
        btCancelaFolio.setEnabled(false);
        
    }//GEN-LAST:event_btGuardaFolioActionPerformed

    
    private void revierte(){
    
    
        DefaultTableModel TableModelo = (DefaultTableModel) Grilla_Aud.getModel(); 
        DefaultTableModel TableModelo2 = (DefaultTableModel) Grilla_metro.getModel(); 
        
        
        while (TableModelo2.getRowCount() > 0) {
            TableModelo2.removeRow(0);
        }
        
        for (int i = 0; i < Grilla_Aud.getRowCount(); i++) {
        
            
              String Sku = Grilla_Aud.getValueAt(i, 0).toString().trim();
              String Nombre = Grilla_Aud.getValueAt(i, 1).toString().trim();
              String Sistema = Grilla_Aud.getValueAt(i, 2).toString().trim();
              
              
              TableModelo2.addRow(new Object[]{Sku,Nombre,Sistema});
        
        }
        

        txtSku.setText("");
        txtSku.setEnabled(false);
        txCant.setText("1");
        txCant.setEnabled(false);
        
        btReubicar.setEnabled(false);
        
        while (TableModelo.getRowCount() > 0) {
            TableModelo.removeRow(0);
        }
    
    
        revierte_Aud();
    
    
    }
    
    
    
    private void revierte_Aud(){
    
    
        ExeSql Sql = new ExeSql();
        ExeSql Sql2 = new ExeSql();
        ExeSql SqlAud = new ExeSql();
        
        ResultSet Rs,Rs1, Rs2, RsAud;
        
       //********************************* 
        
       
       
        
        String Sku = "";
        String Ubicacion = "";
        String UbicacionDestino = "";
        String StUsuario,QryIns, qryUpd, QryDel,Query,Query2,QueryAud;
        
        int cantidad = 0;
      
       
        try{
                
                UbicacionDestino = txtUbicacion.getText().toString().trim();
                Ubicacion = "TRAN.1000.1";
                StUsuario = fmMain.GetUsuario();
               
            //************************************************************************************************************            
                       
                // UBICA PRODUCTOS DESDE METRO AUDITORIA
                                                                        // AUDITORIA //   
                Query = "select * from mt_productos where ubicacion = '" + Ubicacion + "'";
                Rs = Sql.Select(Query);
                
                if (Sql.GetRowCount() > 0){  //Si ya existe la ubicacion
                
                     while (Rs.next()) {    
                                                 
                        Sku =   Rs.getString("sku").trim();
                        cantidad = Rs.getInt("cant");
                                                                                     
                        QueryAud = "select *  from mt_productos where ubicacion = '" + UbicacionDestino + "' and sku = '" + Sku + "'";
                        RsAud = SqlAud.Select(QueryAud);
                    
                        if (SqlAud.GetRowCount() > 0){  //Si ya existe la ubicacion AUDITORIA, realiza un Update
                                        
                            String QryUpd = "UPDATE mt_productos SET cant = cant + " +  cantidad + ",\n" +
                                            "usuario_mod ='" +fmMain.GetUsuario() + "', fecha_mod = now() " +
                                            "WHERE ubicacion = '" + UbicacionDestino + "' AND sku = '" + Sku + "' ";
                    
                            Sql2.ExeSql(QryUpd);
                            Sql2.Commit();
                
                        }else if (SqlAud.GetRowCount() == 0){  //Si no existe la ubicacion AUDITORIA, realiza un Insert
                            
                                QryIns = "INSERT into mt_productos (ubicacion,sku,usuario,cant, rut, tipdocto, nrodocto,ubica_origen2) \n" +
                                         "values ('" + UbicacionDestino + "','" + Sku + "','" + fmMain.GetUsuario()  + "', " + cantidad + ", \n " + 
                                         "null" + ",'" + "" + "'," + "null,'"+Ubicacion + "')";
                                Sql2.ExeSql(QryIns);
                                Sql2.Commit();
                            
                           
                    
                        }
                        
                        
                        
                        rebaja_stock(Ubicacion,Sku.trim(),cantidad);
                     }  
                }     
                
         
        }catch (SQLException e) {
        
            System.out.println(e.getMessage());
            Logger.getLogger(AuditoriaMetro2.class.getName()).log(Level.SEVERE, null, e);
            Sql2.Rollback();
         
        
        } finally{
            
            Sql2.Close();
            
            
        }          
   
    
    }
    
    
    
    
    private void rebaja_stock (String Ubica, String Sku,double cantidad){
        
        ExeSql Sql3 = new ExeSql();
                               
        try {
            
            String QryDel = "UPDATE mt_productos SET cant = cant - " +  cantidad + "\n" +
                            "WHERE ubicacion IN ('"+Ubica+"') AND sku = '" + Sku + "' ";
            
            Sql3.ExeSql(QryDel);
            
            Sql3.Commit();
            
            
        
        } catch (SQLException ex) {
            Sql3.Rollback();
            
            Logger.getLogger(AuditoriaMetro2.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
    
            Sql3.Close();
            
        }
    
    }
    
    
    
    private void carga_producto(){
        
        String codbarfinal = txtSku.getText().replace("'", "-");
        txtSku.setText(codbarfinal.trim());
        
        if(!txtSku.getText().isEmpty()){
            
            CargaSku(txtSku.getText());
        
        }else {
        
            fmMain.Mensaje("Debe ingresar Sku...!");
            txtSku.requestFocus();
            return;
            

        
        }     

            
    }
    
    
    public void CargaSku(String Codigo) {
        ExeSql Sql = new ExeSql();
        
        ResultSet Rs = null;
        double Margen;
        int revisa_codbar =0;
        int revisa_codchile =0;
        ExeSql luv = new ExeSql();
        ResultSet producto = null;
        
        NoEncontrado=0;
   
        try {
            String Query;
            //Limpia la Lista
            
            Rs = luv.Select("select codbar, sku from codbar where sku='" + Codigo + "' or codbar='"+ Codigo + "'" );        
                    if (Rs.next())
                        {
                        Codigo = Rs.getString("sku").trim();
                        revisa_codbar++;
                        }
            Rs = luv.Select("select idch, sku from codchile where sku='" + Codigo +"' or idch='"+ Codigo + "'" );
                    if (Rs.next())
                        {
                        Codigo = Rs.getString("sku").trim();
                        revisa_codchile++;
                        }
            Rs = luv.Select("select codbar, sku from codbar where sku='" + Codigo + "' or codbar='"+ Codigo + "'" );        
                    if (Rs.next())
                        {
                        Codigo = Rs.getString("sku").trim();
                        revisa_codbar++;
                        }
             
                    
                    
            Query ="select p.sku,p.nombre from producto p \n" +
                   "where p.sku='" + Codigo + "' or p.sku in (select sku from codbar where codbar='" + Codigo + "')";
              
            Rs = luv.Select(Query);

            if(luv.GetRowCount()==0){   
                 fmMain.Mensaje("SKU: " + txtSku.getText().trim() + " no esta en Nuestra Bases de Datos. Comuniquese con Informática");
                 txtSku.setText("");
                 txtSku.requestFocus();
                 NoEncontrado=0;
                 return;
            }      
            
            NoEncontrado = 1;
            Rs.next();
            Codigo = Rs.getString("sku").trim();
            String Nombre = Rs.getString("nombre");
       
            
            if (Nombre.length() > 20) {
                Nombre.substring(0, 20);
            }
            txtSku.setText(Codigo);
            txNombre.setText(Rs.getString("nombre"));
           
        } catch (SQLException ex) {
            System.out.println(ex);
        } finally {
            Sql.Close();
            luv.Close();
        }
    }
    
    
    class Elrender extends DefaultTableCellRenderer {
         
        @Override
        public Component getTableCellRendererComponent(JTable tabla, Object valor, boolean isSelected, boolean hasFocus, int fila, int columna) {
        super.getTableCellRendererComponent(tabla,valor,isSelected, hasFocus, fila, columna);
         
            if( (Boolean)tabla.getValueAt(fila,6) == true)
            {
                  if(isSelected==true){
                    this.setBackground(DARK_GREEN);
                    this.setForeground(Color.white);    
                }else{
                
                    this.setForeground(DARK_GREEN);
                    this.setBackground(Color.white);
                
                }
            }
            else if((Boolean)tabla.getValueAt(fila,6) == false){
            
                
                if(isSelected==true){
                
                    this.setBackground(Color.red);
                    this.setForeground(Color.white);    
                
                }else{
                
                    this.setForeground(Color.red);
                    this.setBackground(Color.white);
                
                }
           
            
            }     
            else {
                 this.setForeground(Color.black);  
            } 
            return this;
        }
    } 
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla_Aud;
    private javax.swing.JTable Grilla_metro;
    private javax.swing.JMenuItem MnuProd;
    private javax.swing.JButton btAbreFolio;
    private javax.swing.JButton btCancelaFolio;
    private javax.swing.JButton btCerrarFolio;
    private javax.swing.JButton btGuardaFolio;
    private javax.swing.JButton btNuevoFolio;
    private javax.swing.JButton btReubicar;
    private javax.swing.JButton btUbc;
    private javax.swing.JButton btUbicar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txCant;
    private javax.swing.JTextField txFolio;
    private javax.swing.JTextField txNombre;
    private javax.swing.JTextField txNombreUbicacion;
    private javax.swing.JTextField txtSku;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
