/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Dialogos.jdBuscaUbicacion;
import Dialogos.jdBuscarProductos;
import Formularios.fmMain;
import Utilidades.ComboCodigos;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David Alcaman
 */
public class pfAjusteStock_Autoriza extends javax.swing.JPanel {
    int Tipo;
    int SelMotivo;
    int Auditoria = 0; //0 = No  /   1 = Si
    
    int Nuevo = 0;
    
    static ArrayList<ArrayList<String>>  Lista  = new ArrayList<ArrayList<String>>();
    
    public pfAjusteStock_Autoriza() {
        initComponents();
        SetTipo(-1);
        CargaMotivos();
        PanUbicacion.setVisible(false);
        PanelAuditoria.setVisible(false);
        
        txtUbicacion.setEditable(false);
        txtUbicacion.setEnabled(true);
        txNombreUbica.setEditable(false);
        txNombreUbica.setEnabled(true);      
        txFolioAud.setText("0");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMenu = new javax.swing.JPanel();
        btNuevo = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btAbrir = new javax.swing.JButton();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jPanel1 = new javax.swing.JPanel();
        btIr = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txSku = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txUnidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txStockActual = new javax.swing.JTextField();
        cbTipo = new javax.swing.JComboBox();
        txCantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btAgregar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cbMotivo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txComentarios = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        lbFolio = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txUsuario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txFecha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();
        btEliminar = new javax.swing.JButton();
        PanUbicacion = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txNombreUbica = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txCantUb = new javax.swing.JTextField();
        PanelAuditoria = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Grilla_Aud = new javax.swing.JTable();
        txFolioAud = new javax.swing.JTextField();

        pnMenu.setBackground(new java.awt.Color(220, 215, 226));
        pnMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/add16.png"))); // NOI18N
        btNuevo.setText("Nuevo");
        btNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoActionPerformed(evt);
            }
        });

        btGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/save16.png"))); // NOI18N
        btGuardar.setText("Guardar");
        btGuardar.setBorder(null);
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Cancel16.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/open16.png"))); // NOI18N
        btAbrir.setText("Abrir");
        btAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirActionPerformed(evt);
            }
        });

        jXLabel1.setForeground(new java.awt.Color(0, 51, 0));
        jXLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/OCCliente24.png"))); // NOI18N
        jXLabel1.setText("AJUSTE DE STOCK AUTORIZACION");
        jXLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout pnMenuLayout = new javax.swing.GroupLayout(pnMenu);
        pnMenu.setLayout(pnMenuLayout);
        pnMenuLayout.setHorizontalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAbrir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnMenuLayout.setVerticalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jXLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAbrir))
                    .addComponent(btGuardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        jPanel1.setBackground(new java.awt.Color(220, 215, 226));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btIr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/Go.png"))); // NOI18N
        btIr.setBorderPainted(false);
        btIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIrActionPerformed(evt);
            }
        });

        jLabel1.setText("Código");

        txSku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txSkuKeyPressed(evt);
            }
        });

        jLabel2.setText("Nombre");

        txNombre.setEditable(false);

        jLabel3.setText("Unidad");

        txUnidad.setEditable(false);

        jLabel5.setText("Stock Actual");

        txStockActual.setEditable(false);
        txStockActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txStockActualActionPerformed(evt);
            }
        });

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sumar", "Restar", "Dejar en" }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });
        cbTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbTipoKeyPressed(evt);
            }
        });

        txCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txCantidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txCantidadKeyTyped(evt);
            }
        });

        jLabel6.setText("Cantidad");

        btAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Agregar.png"))); // NOI18N
        btAgregar.setText("Agregar");
        btAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txSku, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btIr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txStockActual, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAgregar)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txStockActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btIr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAgregar)
                    .addComponent(txSku)
                    .addComponent(txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBackground(new java.awt.Color(220, 215, 226));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbMotivo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMotivoActionPerformed(evt);
            }
        });

        jLabel4.setText("Motivo");

        jLabel7.setText("Comentarios");

        txComentarios.setColumns(20);
        txComentarios.setRows(5);
        txComentarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txComentariosKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txComentarios);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("FOLIO");

        lbFolio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbFolio.setForeground(new java.awt.Color(255, 0, 0));
        lbFolio.setText("0");

        jLabel9.setText("Usuario");

        txUsuario.setEditable(false);

        jLabel10.setText("Fecha");

        txFecha.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbFolio))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txUsuario)
                    .addComponent(txFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(txUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(lbFolio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Unidad", "Acción", "Cantidad", "tipo", "NomUbica", "CodUbica", "Folio Auditoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(0).setMinWidth(90);
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(90);
            Grilla.getColumnModel().getColumn(0).setMaxWidth(100);
            Grilla.getColumnModel().getColumn(1).setMinWidth(400);
            Grilla.getColumnModel().getColumn(1).setPreferredWidth(400);
            Grilla.getColumnModel().getColumn(1).setMaxWidth(500);
            Grilla.getColumnModel().getColumn(2).setMinWidth(70);
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(70);
            Grilla.getColumnModel().getColumn(2).setMaxWidth(90);
            Grilla.getColumnModel().getColumn(3).setMinWidth(90);
            Grilla.getColumnModel().getColumn(3).setPreferredWidth(90);
            Grilla.getColumnModel().getColumn(3).setMaxWidth(90);
            Grilla.getColumnModel().getColumn(4).setMinWidth(70);
            Grilla.getColumnModel().getColumn(4).setPreferredWidth(70);
            Grilla.getColumnModel().getColumn(4).setMaxWidth(70);
            Grilla.getColumnModel().getColumn(6).setMinWidth(300);
            Grilla.getColumnModel().getColumn(6).setPreferredWidth(250);
            Grilla.getColumnModel().getColumn(6).setMaxWidth(300);
            Grilla.getColumnModel().getColumn(7).setMinWidth(0);
            Grilla.getColumnModel().getColumn(7).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        btEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Eliminar.png"))); // NOI18N
        btEliminar.setText("Eliminar");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });

        PanUbicacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanUbicacion.setToolTipText("Sacar de Ubicación");

        jLabel11.setText("Codigo Ubicación");

        txtUbicacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUbicacionKeyPressed(evt);
            }
        });

        jLabel12.setText("Descripción Ubicación");

        txNombreUbica.setEditable(false);
        txNombreUbica.setEnabled(false);

        jLabel13.setText("Cant");

        txCantUb.setEditable(false);
        txCantUb.setEnabled(false);

        javax.swing.GroupLayout PanUbicacionLayout = new javax.swing.GroupLayout(PanUbicacion);
        PanUbicacion.setLayout(PanUbicacionLayout);
        PanUbicacionLayout.setHorizontalGroup(
            PanUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanUbicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(10, 10, 10)
                .addGroup(PanUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txNombreUbica, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txCantUb, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        PanUbicacionLayout.setVerticalGroup(
            PanUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanUbicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanUbicacionLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txCantUb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanUbicacionLayout.createSequentialGroup()
                        .addGroup(PanUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txNombreUbica, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );

        PanelAuditoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Grilla_Aud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Sku", "Folio", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla_Aud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Grilla_AudMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Grilla_Aud);
        if (Grilla_Aud.getColumnModel().getColumnCount() > 0) {
            Grilla_Aud.getColumnModel().getColumn(1).setPreferredWidth(40);
            Grilla_Aud.getColumnModel().getColumn(2).setPreferredWidth(40);
        }

        javax.swing.GroupLayout PanelAuditoriaLayout = new javax.swing.GroupLayout(PanelAuditoria);
        PanelAuditoria.setLayout(PanelAuditoriaLayout);
        PanelAuditoriaLayout.setHorizontalGroup(
            PanelAuditoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAuditoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        PanelAuditoriaLayout.setVerticalGroup(
            PanelAuditoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAuditoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        txFolioAud.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txFolioAud.setText("0");
        txFolioAud.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PanelAuditoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(txFolioAud, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btEliminar)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelAuditoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txFolioAud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
 private void SetTipo(int ElTipo){
     /*Nada*/
     if(ElTipo== -1){
         LimpiaProducto();
         LimpiaGrilla();
         HabilitaEnc(false);
         HabilitaDet(false);
         btGuardar.setEnabled(false);
         btCancelar.setEnabled(false);
         btNuevo.setEnabled(true);
         btAbrir.setEnabled(true);
         Tipo=-1;
     }
     //Nuevo
     else if(ElTipo==1){ 
         LimpiaProducto();
         LimpiaGrilla();
         HabilitaEnc(true);
         HabilitaDet(true);
         txSku.requestFocus();
         btGuardar.setEnabled(true);
         btCancelar.setEnabled(true);
         btNuevo.setEnabled(false);
         btAbrir.setEnabled(false);
         txComentarios.setEditable(true);
         Tipo=1;
     }
     //Abrir
     else if(ElTipo==2){  
         HabilitaEnc(true);
         HabilitaDet(false);
         cbMotivo.setEnabled(true);
         txComentarios.setEnabled(true);
         txComentarios.setEditable(false);
         btGuardar.setEnabled(false);
         btCancelar.setEnabled(false);
         btNuevo.setEnabled(true);
         btAbrir.setEnabled(true);
         Tipo=2;
     }
     
 }
 private void LimpiaProducto(){
    txSku.setText("");
    txNombre.setText("");
    txUnidad.setText("");
    txStockActual.setText("");
    txCantidad.setText("");
    cbTipo.setSelectedIndex(-1);
    PanUbicacion.setVisible(false);
 }
 private void LimpiaGrilla(){
     DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
     while(TableModel.getRowCount()>0)
        TableModel.removeRow(0);
     txUsuario.setText("");
     txFecha.setText("");
     txComentarios.setText("");
     cbMotivo.setSelectedIndex(-1);
 }
 private void HabilitaEnc(boolean Estado){
     cbMotivo.setEnabled(Estado);
     txComentarios.setEnabled(Estado);
     txUsuario.setEnabled(Estado);
     txFecha.setEnabled(Estado);
     
 }
 private void HabilitaDet(boolean Estado){
     txSku.setEnabled(Estado);
     txNombre.setEnabled(Estado);
     txUnidad.setEnabled(Estado);
     txCantidad.setEnabled(Estado);
     btIr.setEnabled(Estado);
     btAgregar.setEnabled(Estado);
     btEliminar.setEnabled(Estado);
     txStockActual.setEnabled(Estado);
     cbTipo.setEnabled(Estado);
 }
 private void CargaMotivos(){
        ResultSet Rs;
        ExeSql Sql = new ExeSql();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbMotivo.getModel();
        model.removeAllElements();
        
        try {
            Rs = Sql.Select("select codigo,motivo\n" +
                            "from par_ajustemotivo\n" +
                            "where estado=1");
            while(Rs.next()){
                model.addElement(new ComboCodigos(Rs.getString("motivo"),Rs.getInt("codigo")));
            }
            cbMotivo.setModel(model);
            cbMotivo.setSelectedIndex(-1);
        } catch (Exception e) {
        } finally{
            Sql.Close();
        }
    }
    private void btIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIrActionPerformed
        
        if(!txSku.getText().isEmpty() && Tipo == 1){
            
            int pend = AjustePendiente(txSku.getText().trim()); 
            
            if (pend == 1){
              
                fmMain.Mensaje("Producto tiene ajustes pendientes..! ");
                txSku.requestFocus();
                txSku.setText("");
                return;
            
            }
            
            CargaProducto(txSku.getText());
            
        }else if(!txSku.getText().isEmpty() && Tipo != 1){
            txNombre.requestFocus();

        }else{
            jdBuscarProductos BP = new jdBuscarProductos(null, true);
            BP.setLocationRelativeTo(null);
            BP.setTitle("Buscar Producto");
            BP.setVisible(true);
            if(!"".equals(BP.GetCodigo()))
            CargaProducto(BP.GetCodigo());
        }
    }//GEN-LAST:event_btIrActionPerformed

    private void txSkuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSkuKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            btIr.doClick();
        }
    }//GEN-LAST:event_txSkuKeyPressed

    private void btNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoActionPerformed
//        if(fmMain.GetUsuarioAjuste()){
//            
//            SetTipo(1);
//            Nuevo = 1;
//        
//        }else{
//        
//            fmMain.Mensaje("Usuario no autorizado para ajustar");
//        }
        
          SetTipo(1);
          Nuevo = 1;    
        
        
    }//GEN-LAST:event_btNuevoActionPerformed

    private void btAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarActionPerformed
        
        if (txCantidad.getText().isEmpty() || txCantidad.getText().contains(" ")){
        
            fmMain.Mensaje("Debe ingresar una cantidad !!");
            return;
        
        
        }
        
        
        
        
        DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
        double Actual,Cantidad,Final, Ubicada;
        String stCodUbica="",Nomubica="";
        
        ExeSql Sql = new  ExeSql();
        ResultSet Rs;
        String Query="";
        String Sku="", Scant="", Stransito="";
        
        //******************************** Se verfica si hay articulos duplicados *********************//     
                    
        for (int f=0; f< Grilla.getRowCount();f++){
                         
            String elemento = Grilla.getValueAt(f, 0).toString().trim();
                        
            if (elemento.equals(txSku.getText().trim())) {
                            
                fmMain.Mensaje("Producto ya está agregado!");
                LimpiaProducto();
                return;
            }
                    
        }
        //***************************************************************************************************//    
        
        
        
        
        if (cbTipo.getSelectedItem() == "Restar" &&  Auditoria == 0){
              
              stCodUbica = txtUbicacion.getText().trim();
              Nomubica = txNombreUbica.getText().trim();
              
              Query = "select sku,cant from mt_productos where  ubicacion = '" + stCodUbica + "'" +
                      " and sku  = '" + txSku.getText().trim() + "'";
              
              try{
                   Cantidad = Double.valueOf(txCantidad.getText());
                    Rs=Sql.Select(Query);
                    if(Rs.next()){
                        Ubicada=Rs.getDouble("cant") ;
                        if (Ubicada<Cantidad ){
                            fmMain.Mensaje("No se puede ajustar, la cantidad solicitada: " + Cantidad + " es mayor que la cantidad ubicada en: " + Ubicada);
                            return;
                        }
                    }
                    else{
                            fmMain.Mensaje("Produto " +  txNombre .getText().trim() + " no pertenece a la ubicación: "+ Nomubica );
                            return;
                    }
                    
              }catch (Exception e) {
                
                  System.out.println(e);
            
              }finally{
            
                  Sql.Close();
            }
              
              
          }else if (Auditoria == 1){
          
               stCodUbica = "Auditoria";
               Nomubica= "Auditoria";
          }
        
        
        /*Revisa Datos*/
        if(txNombre.getText().isEmpty() || txCantidad.getText().isEmpty() || cbTipo.getSelectedIndex()==-1){
            
            fmMain.Mensaje("Faltan Datos");
            return;
        }
        /*Revisa que no exista*/
        
        try {
            
        
            Actual = Double.valueOf(fmMain.SetGuardar(txStockActual.getText()));
                
            Cantidad = Double.valueOf(txCantidad.getText());
        
            if(cbTipo.getSelectedIndex()==0){
                Final = Actual + Cantidad;
            }
            else if(cbTipo.getSelectedIndex()==1){
                Final = Actual - Cantidad;
            }
            else{
                Final = Cantidad;
            }
            
            TableModel.addRow(new Object[]{
                            txSku.getText().trim(), 
                            txNombre.getText().trim(), 
                            txUnidad.getText().trim(),
                            cbTipo.getSelectedItem().toString().trim(),
                            Cantidad,
                            cbTipo.getSelectedIndex(),Nomubica,stCodUbica,
                            txFolioAud.getText().trim()
                        });
        
            LimpiaProducto();
            PanelAuditoria.setVisible(false);
        
            txSku.requestFocus();
        } catch (Exception e) {
            fmMain.Mensaje(e.getMessage());
        }
    }//GEN-LAST:event_btAgregarActionPerformed

    private void cbTipoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbTipoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            txCantidad.requestFocus();
    }//GEN-LAST:event_cbTipoKeyPressed

    private void txCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCantidadKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btAgregar.doClick();
    }//GEN-LAST:event_txCantidadKeyPressed

    private void txCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCantidadKeyTyped
        if(!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar()==',')
            evt.consume();
    }//GEN-LAST:event_txCantidadKeyTyped

    private void cbMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMotivoActionPerformed
        
        if(Tipo==2){
            
            cbMotivo.setSelectedIndex(SelMotivo);
        }
        
        if (cbMotivo.getSelectedIndex() == 1 && Nuevo == 1){
        
            SetTipo(-1);
            btGuardar.setEnabled(true);
            btCancelar.setEnabled(true);
            btNuevo.setEnabled(false);
            btAbrir.setEnabled(false);
            
            txFolioAud.setText("0");
           
            cbMotivo.setSelectedIndex(1);
            
        
        }
        
        
        
        if (Nuevo == 1){
        
            if (cbMotivo.getSelectedItem().toString().trim().contains("Auditoria")){
        
                System.out.println("ES AUDITORIA !!!!!!!!!!!!!!!!");
                Auditoria = 1;
            
            }else if (!cbMotivo.getSelectedItem().toString().trim().contains("Auditoria")){
        
                System.out.println("NO ES AUDITORIA !!!!!!!!!!!!!!!!");
                Auditoria = 0;
                PanelAuditoria.setVisible(false);
        
            }
        }
        
        
    }//GEN-LAST:event_cbMotivoActionPerformed

    private void txComentariosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txComentariosKeyTyped
        if (Character.isLowerCase(evt.getKeyChar()))
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_txComentariosKeyTyped

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        SetTipo(-1);
    }//GEN-LAST:event_btCancelarActionPerformed
    private int cbId_Accion(JComboBox Combo ){
        int Codigo=-1;
        if (Combo.getSelectedIndex()>=0){
            ComboCodigos id = (ComboCodigos) Combo.getSelectedItem();
            Codigo = id.getId();
            String nombre = Combo.getSelectedItem().toString();
            Combo.hidePopup();
        } 
    return Codigo;
}
    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        
        String Query="";

        btGuardar.setEnabled(false);
        
        
        //VALIDACIONES
        if(cbMotivo.getSelectedIndex()==-1 ||
                
            txComentarios.getText().isEmpty()||
            Grilla.getRowCount()==0){
           
            fmMain.Mensaje("Faltan Motivo o Comentario no puede ser vacio.");
            btGuardar.setEnabled(true);
            return;
        }
        
        
        
        if(fmMain.OkCancel("¿Desea realizar el ajuste?") != JOptionPane.OK_OPTION){
            btGuardar.setEnabled(true);
            return;
        }
        
        ExeSql Sql = new  ExeSql();
        ExeSql Sql2 = new  ExeSql();
        ResultSet Rs;
       
        int Pendiente = 0;
        
        try {
            
            
            for(int f=0;f< Grilla.getRowCount();f++){
            
                String Sku = Grilla.getValueAt(f, 0).toString().trim();
                
                int pend = AjustePendiente(Sku.trim()); 
            
                if (pend == 1){
              
                    Pendiente = 1;
             
                }
            
            }
            
            if (Pendiente == 1){
            
                fmMain.Mensaje("Hay productos con ajustes pendientes..! ");
                txSku.requestFocus();
                txSku.setText("");
                return;
            
            }
            
            
            Rs = Sql.Select("select sp_getcorrelativo \n" +
                            "from sp_getcorrelativo('AJU')");   
            Rs.next();
            
            String Folio = Rs.getString("sp_getcorrelativo");
            
            //Cabezera
            Sql.ExeSql( "INSERT INTO ajusteenc_autoriza\n" +
                        "(folio,motivo,comentario\n" +
                        ") \n" +
                        "VALUES (\n" +
                        Folio + ",\n" +
                        String.valueOf(cbId_Accion(cbMotivo)) + ",\n'" +
                        txComentarios.getText() +"'\n" +
                        ")");
            
           
            
            //Productos
            for(int i=0;i< Grilla.getRowCount();i++){
                
                
                Query = "INSERT INTO ajustedet_autoriza\n" +
                            "(folio,sku,cantidad,tipo,ubicacion,folioaud) \n" +
                            "VALUES (\n" +
                            Folio + ",\n'" +
                            Grilla.getValueAt(i, 0).toString().trim() + "',\n" +
                            fmMain.SetGuardar(Grilla.getValueAt(i, 4).toString().trim()) + ",\n" +
                            Grilla.getValueAt(i, 5).toString() + ",\n" +
                            "'" + Grilla.getValueAt(i, 7).toString().trim()+"',"+Grilla.getValueAt(i, 8).toString().trim() + ")\n";
                Sql2.ExeSql(Query); 
               
                                   
            } // Fin For de Detalle
             
            Sql.Commit();
            Sql2.Commit();
            
            fmMain.Mensaje("Guardado Ajuste N° "+Folio+" , quedará Pendiente de Autorización.  \n "+
                          "Los Movimientos se realizaràn cuando esté Autorizado el Ajuste. \n ");
            
            //AbrirFolio(Folio);
            
            Nuevo = 0;
            SetTipo(-1);
           
            
        } catch (Exception e) {
        
            System.out.println(e);
            Sql.Rollback();
            Sql2.Rollback();
            Logger.getLogger(pfAjusteStock.class.getName()).log(Level.SEVERE, null, e);
        
        } finally{
            Sql.Close();
            Sql2.Close();
        }
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirActionPerformed
        
        Nuevo = 0;
        String Folio = JOptionPane.showInputDialog("Ingrese folio de ajuste");
        AbrirFolio(Folio);
    }//GEN-LAST:event_btAbrirActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
        
        ExeSql Sql = new ExeSql();
        
        DefaultTableModel modelo = (DefaultTableModel) Grilla.getModel();
        
        
        String Sku = Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString().trim();
        
        try {
            
            
            if(fmMain.OkCancel("¿Está seguro que desea Eliminar el Producto?")== JOptionPane.OK_OPTION){
                
                Sql.ExeSql("delete from ajustedet_autoriza where sku IN ('" + Sku.trim() + "') and folio = "+lbFolio.getText().trim());
                               
                modelo.removeRow(Grilla.getSelectedRow());
            
            
            }
           
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccione la fila que desea quitar.");
        }       
    }//GEN-LAST:event_btEliminarActionPerformed

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
                
        double Actual,Cantidad,Final, Ubicada;
        String stCodUbica="",Nomubica="";
        
        ExeSql Sql = new  ExeSql();
        ResultSet Rs;
        String Query="";
        
        if (cbTipo.getSelectedItem() == "Restar"  &&  Auditoria == 0 ){
            
            jdBuscaUbicacion Ubicacion= new jdBuscaUbicacion(null, true);
            Ubicacion.CargaBodegaOR(1);
            Ubicacion.setVisible(true);
            PanUbicacion.setVisible(true);
            txtUbicacion.setText(Ubicacion.GetUbicacion());
            txNombreUbica.setText(Ubicacion.GetNombreUbicacion());
            txCantidad.requestFocus();
           
            stCodUbica = txtUbicacion.getText().trim();
            Nomubica = txNombreUbica.getText().trim();

            Query = "SELECT sku,cant FROM mt_productos WHERE ubicacion = '" + stCodUbica + "' \n" +
                    "AND sku  = '" + txSku.getText().trim() + "'";

            try{
                    
                Rs=Sql.Select(Query);
                
                if(Rs.next()){
                
                    Ubicada=Rs.getDouble("cant") ;
                    
                }else{
                
                    fmMain.Mensaje("Produto " +  txNombre .getText().trim() + " no pertenece a la ubicación: "+ Nomubica );
                    return;
                }

            }catch (Exception e) {
            
                System.out.println(e.getMessage());
            } finally{
            
                Sql.Close();
            }
                 
           
        }
        
        
    }//GEN-LAST:event_cbTipoActionPerformed

    private void txtUbicacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUbicacionKeyPressed
        // TODO add your handling code here:
        // TODO add your handling code here:
        ExeSql Sql = new ExeSql();
        ResultSet Rs, Rs1;
        String Query2 ;
        String strUbicacion = "";

        try{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                strUbicacion = txtUbicacion.getText().trim();
                String ubicaArray[] = strUbicacion.split("\\.");

                Query2 = "SELECT (b.bodega ||' - '|| r.rack ||' - '|| m.metro) as ubc\n" +
                " from mt_bodega b, mt_rack r, mt_metro m\n" +
                " where b.codigo='" + ubicaArray[0] + "' and r.codigo= " + ubicaArray[1] +  " and m.codigo= " + ubicaArray[2] + "  and m.rack=" + ubicaArray[1];
                Rs1 = Sql.Select(Query2);
                if (Rs1.next()){
                    strUbicacion =Rs1.getString("ubc").trim();
                    txNombreUbica.setText(strUbicacion);
                    txtUbicacion.requestFocus();

                }
                else
                {
                    fmMain.Mensaje("Ubicacion no encontrada, favor revise la ubicación");
                    //limpia_all();
                    txNombreUbica.setText("");
                    txtUbicacion.setText("");
                }
            }
        }
        catch (Exception e) {
            System.out.println(e.getMessage());
        } finally{
            Sql.Close();
        }
    }//GEN-LAST:event_txtUbicacionKeyPressed

    private void txStockActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txStockActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txStockActualActionPerformed

    private void Grilla_AudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Grilla_AudMouseClicked
        
         if(evt.getClickCount()==2){
            
             txCantidad.setText(Grilla_Aud.getValueAt(Grilla_Aud.getSelectedRow(),2).toString().trim());
             txFolioAud.setText(Grilla_Aud.getValueAt(Grilla_Aud.getSelectedRow(),1).toString().trim());
         }
        
    }//GEN-LAST:event_Grilla_AudMouseClicked
    private void AbrirFolio(String Numero){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
        
        while(TableModel.getRowCount()>0)
           TableModel.removeRow(0);
        
        try {
            //Carga Encabezado
            Rs = Sql.Select("select usuario,cast(fecha as date) as fecha,motivo,comentario from ajusteenc_autoriza where folio=" + Numero);
            if(Sql.GetRowCount()==0){
                fmMain.Mensaje("Folio no encontrado");
                return;
            }
            Rs.next();
            txUsuario.setText(Rs.getString("usuario").trim());
            txFecha.setText(Rs.getString("fecha").trim());
            txComentarios.setText(Rs.getString("comentario"));
            for(int i=0 ; i < cbMotivo.getItemCount();i++){
                cbMotivo.setSelectedIndex(i);
                if(cbId_Accion(cbMotivo)==Rs.getInt("motivo") ){
                    SelMotivo=i;
                    break; 
                }
                    
            }
            lbFolio.setText(Numero);
            
            //Carga Productos
            Rs = Sql.Select("select d.sku,p.nombre,u.unidad,\n" +
                            "case d.tipo when 0 then 'Sumar' when 1 then 'Restar' else 'Dejar en' end as ElTipo, \n"+
                            "d.cantidad,d.tipo, \n"+
                            "case when cm.nombre is null then '' else cm.nombre end as desc_ubica, d.ubicacion cod_ubica \n" +
                            "from ajustedet_autoriza d\n" +
                            "left join producto p on d.sku=p.sku \n" +
                            "left join par_unidad u on p.unidad=u.codigo \n" +
                            "left join mt_codmetro cm on d.ubicacion=cm.codmetro \n" +
                            "where d.folio=" + Numero);
            
            while(Rs.next()){
                
                TableModel.addRow(new Object[]{
                        Rs.getString("Sku").trim(), 
                        Rs.getString("Nombre").trim(), 
                        Rs.getString("unidad").trim(),
                        Rs.getString("ElTipo").trim(),
                        Rs.getDouble("cantidad"),
                        Rs.getInt("tipo"),
                        Rs.getString("desc_ubica").trim(),
                        Rs.getString("cod_ubica").trim()
                });
            }
            
            SetTipo(2);
        } catch (Exception e) {
            System.out.println(e);
            
            Logger.getLogger(pfAjusteStock.class.getName()).log(Level.SEVERE, null, e);
        }finally{
            Sql.Close();
        }
    }
    
    
    public void AbrirFolio_Ext(String Numero){
        
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
        
        while(TableModel.getRowCount()>0)
           TableModel.removeRow(0);
        
        try {
            //Carga Encabezado
            Rs = Sql.Select("select usuario,cast(fecha as date) as fecha,motivo,comentario from ajusteenc_autoriza where folio=" + Numero);
            if(Sql.GetRowCount()==0){
                fmMain.Mensaje("Folio no encontrado");
                return;
            }
            Rs.next();
            txUsuario.setText(Rs.getString("usuario").trim());
            txFecha.setText(Rs.getString("fecha").trim());
            txComentarios.setText(Rs.getString("comentario"));
            for(int i=0 ; i < cbMotivo.getItemCount();i++){
                cbMotivo.setSelectedIndex(i);
                if(cbId_Accion(cbMotivo)==Rs.getInt("motivo") ){
                    SelMotivo=i;
                    break; 
                }
                    
            }
            lbFolio.setText(Numero);
            
            //Carga Productos
            Rs = Sql.Select("select d.sku,p.nombre,u.unidad,\n" +
                            "case d.tipo when 0 then 'Sumar' when 1 then 'Restar' else 'Dejar en' end as ElTipo, \n"+
                            "d.cantidad,d.tipo, \n"+
                            "case when cm.nombre is null then '' else cm.nombre end as desc_ubica, d.ubicacion cod_ubica \n" +
                            "from ajustedet_autoriza d\n" +
                            "left join producto p on d.sku=p.sku \n" +
                            "left join par_unidad u on p.unidad=u.codigo \n" +
                            "left join mt_codmetro cm on d.ubicacion=cm.codmetro \n" +
                            "where d.folio=" + Numero);
            
            while(Rs.next()){
                
                TableModel.addRow(new Object[]{
                        Rs.getString("Sku").trim(), 
                        Rs.getString("Nombre").trim(), 
                        Rs.getString("unidad").trim(),
                        Rs.getString("ElTipo").trim(),
                        Rs.getDouble("cantidad"),
                        Rs.getInt("tipo"),
                        Rs.getString("desc_ubica").trim(),
                        Rs.getString("cod_ubica").trim()
                });
            }
            
            SetTipo(2);
            
            if (fmMain.GetUsuarioAjuste()){
        
            
                btEliminar.setEnabled(true);
            
        
            }else {
        
        
                btEliminar.setEnabled(false);
        
            }
            
            
        } catch (Exception e) {
            System.out.println(e);
            
            Logger.getLogger(pfAjusteStock.class.getName()).log(Level.SEVERE, null, e);
        }finally{
            Sql.Close();
        }
    }
    
    
    
    
    private void CargaProducto(String Codigo){
        
        ResultSet Rs, Rs1;
        ExeSql Sql = new ExeSql();
        String Query ="";
        try {

            Rs = Sql.Select("select p.sku,p.nombre,u.unidad,i.stock \n" +
                            "from producto p\n" +
                            "left join inventario i on p.sku=i.sku\n" +
                            "left join par_unidad u on p.unidad=u.codigo \n" +
                            "where p.sku='"+ Codigo.trim() +"'");
            
            
            if (Rs.next()){
                
                txSku.setText(Rs.getString("Sku"));
                txNombre.setText(Rs.getString("Nombre").trim());
                txUnidad.setText(Rs.getString("Unidad").trim());
                txStockActual.setText(fmMain.FormatoNumero(Rs.getDouble("stock")));
                cbTipo.requestFocus();
                
                
                
                  if (Auditoria == 1){
                
                    BuscarAud(txSku.getText().trim());
                    
                  }
            
            }else{
            
                Query = "select p.codbar, p.sku,pr.nombre, i.stock, u.unidad \n" +
                                "from codbar p \n"+
                                "left join producto pr on p.sku = pr.sku \n" +
                                "left join inventario i on p.sku = i.sku \n" +
                                "left join par_unidad u on pr.unidad=u.codigo \n" +
                                "where (p.sku='" + Codigo.trim() + "' or p.codbar ='" + Codigo.trim() + "') and p.sku = pr.sku ";
                      
                      Rs1 = Sql.Select(Query );
                      
                      if ( Rs1.next()){
                            txSku.setText(Rs1.getString("Sku"));
                            txNombre.setText(Rs1.getString("Nombre").trim());
                            txUnidad.setText(Rs1.getString("Unidad").trim());
                            txStockActual.setText(fmMain.FormatoNumero(Rs1.getDouble("stock")));
                            cbTipo.requestFocus();
                            
                            if (Auditoria == 1){
                                
                               BuscarAud(txSku.getText().trim());
                                
                            }
                            
                      
                      }else{
                                JOptionPane.showMessageDialog(null,"Producto no encontrado");
                                return;
                      }
            }
            

        } catch (Exception e) {
            
        } finally{
            Sql.Close();
        }
            
        
        
    }
    
    
    private static int AjustePendiente(String Sku){
    
        ResultSet Rs;
        ExeSql Sql = new ExeSql();
        int pendiente = 0;
        
        try {
            
            Rs = Sql.Select("select a.folio, a.sku, a.folioaud, aj.autorizado, aj.rechazado from ajustedet_autoriza a\n" +
                            "left join ajusteenc_autoriza aj on a.folio = aj.folio\n" +
                            "where a.sku IN ('"+Sku.trim()+"')\n" +
                            "and aj.autorizado = false and aj.rechazado = 0");
            
            if (Sql.GetRowCount() > 0){
            
               
                pendiente = 1;
                
                int fila = 1;
                while (Rs.next()){
                
                    Lista.add(new ArrayList<String>());
        
                    Lista.get(fila).add(0,Rs.getString("folio"));
                    fila++;                
                
                }  
                
                
            
            }else {
            
                pendiente = 0;
                  
            
            }
            
         
            
            
        } catch (SQLException ex) {
            Logger.getLogger(pfAjusteStock_Autoriza.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
      return pendiente;
    
    
    }
    
    
    
    private void BuscarAud(String Sku){
    
        DefaultTableModel TableModelo = (DefaultTableModel) Grilla_Aud.getModel(); 
        
        while (TableModelo.getRowCount() > 0) {
            TableModelo.removeRow(0);
        }
        
        
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        String Query ="";
        int cont = 0;
       
            
            try{
         
                Query = "SELECT * FROM mt_auditoria_ubicaciones \n"+
                        "WHERE sku = '"+Sku.trim()+"' AND diferencia <> 0 \n"+
                        "ORDER BY folio desc";
            
                Rs = Sql.Select(Query);
            
                if (Sql.GetRowCount() > 0){
            
                    PanelAuditoria.setVisible(true);
                    
                    while (Rs.next()){
                        
                       String Folio = Rs.getString("folio").trim();
                       int Cant = Rs.getInt("diferencia")*-1;
                        
                        
                      TableModelo.addRow(new Object[]{Sku,Folio,Cant}); // ...se agrega
                    
                    }            
                }else{
                    
                    fmMain.Mensaje("No hay Stock de Auditoria para ajustar de este producto!!");
                    PanelAuditoria.setVisible(false);
                    return;
                
                
                }    
            }catch (SQLException e) {
            
                System.out.println(e.getMessage());
                Logger.getLogger(pfAjusteStock.class.getName()).log(Level.SEVERE, null, e);
            
            
            }    
    
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla;
    private javax.swing.JTable Grilla_Aud;
    private javax.swing.JPanel PanUbicacion;
    private javax.swing.JPanel PanelAuditoria;
    private javax.swing.JButton btAbrir;
    private javax.swing.JButton btAgregar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btIr;
    private javax.swing.JButton btNuevo;
    private javax.swing.JComboBox cbMotivo;
    private javax.swing.JComboBox cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private javax.swing.JLabel lbFolio;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JTextField txCantUb;
    private javax.swing.JTextField txCantidad;
    private javax.swing.JTextArea txComentarios;
    private javax.swing.JTextField txFecha;
    private javax.swing.JTextField txFolioAud;
    private javax.swing.JTextField txNombre;
    private javax.swing.JTextField txNombreUbica;
    private javax.swing.JTextField txSku;
    private javax.swing.JTextField txStockActual;
    private javax.swing.JTextField txUnidad;
    private javax.swing.JTextField txUsuario;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
