/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.Econa.ExeSql_Econa;
import Conexion.ExeSql;
import Dialogos.jdAjustarCant;
import Dialogos.jdBuscarProductos2;
import Formularios.fmMain;
import static Formularios.fmMain.pnPestanas;
import static PanelForm.pfIndicadoresInventario.DARK_GREEN;
import Utilidades.PanelTab;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author David Alcaman
 */
public class pfAjusteMinimos extends javax.swing.JPanel {
    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
   
    boolean autoriza = false;
    int cant = 0;
    double dcant = 0;
    int contselec = 0;
    
    
       /**
     * Creates new form OC_Clientes
     */
    public pfAjusteMinimos() {
        initComponents(); 
       
        //System.out.println("EL USUARIO  ES : "+ fmMain.GetUsuario().toLowerCase());        
        
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);  
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
             
        Grilla.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        Grilla.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        Grilla.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
                
        Grilla.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            //Se ejecuta automáticamente cada vez que se hace una nueva selección. 
            @Override
            public void valueChanged(ListSelectionEvent e) {
                
                if(Grilla.getSelectedRowCount()>0){   
                
                    
                     if (!autoriza){
                        //CargaProductos((Integer) GrillaOCP.getValueAt(GrillaOCP.getSelectedRow(),0));  
                         
                         
                     }
                }
                    
            }

        });
        
        
        
        txTexto.addKeyListener(new KeyAdapter() {

            public void keyTyped(KeyEvent e) {
                
                char keyChar = e.getKeyChar();
                if (Character.isLowerCase(keyChar)) {
                    e.setKeyChar(Character.toUpperCase(keyChar));
                }
            }

        });
        
        
        txFiltro.addKeyListener(new KeyAdapter() {

            public void keyTyped(KeyEvent e) {
                
                char keyChar = e.getKeyChar();
                if (Character.isLowerCase(keyChar)) {
                    e.setKeyChar(Character.toUpperCase(keyChar));
                }
            }

        });
        
        
       
        
       
        int pruebaUusario = 85;
        int intNivelUsuario = 0;
        intNivelUsuario = fmMain.trae_nivel(fmMain.GetUsuario());
        
        if( intNivelUsuario >= pruebaUusario){
            btActualizar.setEnabled(true);
           
        }else{
            
            btActualizar.setEnabled(false);
        }
                
        lbcargando.setVisible(false);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btCargar = new javax.swing.JButton();
        btActualizar = new javax.swing.JButton();
        lbFiltro = new javax.swing.JLabel();
        txFiltro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txCodigo = new javax.swing.JTextField();
        btIr = new javax.swing.JButton();
        lbFiltro1 = new javax.swing.JLabel();
        txTexto = new javax.swing.JTextField();
        rbEcona = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        lbCont = new javax.swing.JLabel();
        rbSala = new javax.swing.JRadioButton();
        rbTodos = new javax.swing.JRadioButton();
        lbcargando = new javax.swing.JLabel();

        jMenuItem1.setText("Ver Producto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Ver Productos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem2);

        setToolTipText("");

        Grilla.setAutoCreateRowSorter(true);
        Grilla.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sku", "Nombre", "Stock Luv", "    Sala", "  Econa", "Actualizar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(0).setMinWidth(80);
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(0).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(2).setMinWidth(60);
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(60);
            Grilla.getColumnModel().getColumn(2).setMaxWidth(60);
            Grilla.getColumnModel().getColumn(3).setMinWidth(60);
            Grilla.getColumnModel().getColumn(3).setPreferredWidth(60);
            Grilla.getColumnModel().getColumn(3).setMaxWidth(60);
            Grilla.getColumnModel().getColumn(4).setMinWidth(60);
            Grilla.getColumnModel().getColumn(4).setPreferredWidth(60);
            Grilla.getColumnModel().getColumn(4).setMaxWidth(60);
            Grilla.getColumnModel().getColumn(5).setMinWidth(70);
            Grilla.getColumnModel().getColumn(5).setPreferredWidth(70);
            Grilla.getColumnModel().getColumn(5).setMaxWidth(70);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("AJUSTE DE MINIMOS");

        btCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/refresh16.png"))); // NOI18N
        btCargar.setText("Cargar");
        btCargar.setToolTipText("");
        btCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCargarActionPerformed(evt);
            }
        });

        btActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/ok_16.png"))); // NOI18N
        btActualizar.setText("Fijar Minimo");
        btActualizar.setToolTipText("");
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        lbFiltro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbFiltro.setText("Filtrar");

        txFiltro.setEnabled(false);
        txFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFiltroActionPerformed(evt);
            }
        });
        txFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txFiltroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txFiltroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txFiltroKeyTyped(evt);
            }
        });

        jLabel2.setText("Código");

        txCodigo.setEnabled(false);
        txCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txCodigoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txCodigoKeyReleased(evt);
            }
        });

        btIr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/Go.png"))); // NOI18N
        btIr.setEnabled(false);
        btIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIrActionPerformed(evt);
            }
        });

        lbFiltro1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbFiltro1.setText("Texto");

        txTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTextoActionPerformed(evt);
            }
        });
        txTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txTextoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txTextoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txTextoKeyTyped(evt);
            }
        });

        buttonGroup1.add(rbEcona);
        rbEcona.setText("Productos que no están en Econa");
        rbEcona.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("N° de Registros");

        lbCont.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCont.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCont.setText("0");
        lbCont.setToolTipText("");
        lbCont.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(rbSala);
        rbSala.setText("Productos que no están en la Sala");
        rbSala.setToolTipText("");
        rbSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSalaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbTodos);
        rbTodos.setSelected(true);
        rbTodos.setText("Todos");
        rbTodos.setToolTipText("");
        rbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTodosActionPerformed(evt);
            }
        });

        lbcargando.setText("Cargando");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btIr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbSala)
                            .addComponent(rbEcona)
                            .addComponent(rbTodos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btActualizar))
                            .addComponent(jLabel1))
                        .addGap(209, 209, 209)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbcargando)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbCont, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbcargando, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbEcona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbSala)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbTodos))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btIr)
                            .addComponent(txCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbFiltro1))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbFiltro))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCont, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCargarActionPerformed
        
        txFiltro.setEnabled(false);
        txCodigo.setEnabled(false);
        btIr.setEnabled(false);
        
        lbcargando.setText("Cargando.....");
        URL urlInfo =  this.getClass().getResource("/Iconos16/wait.gif");
        ImageIcon IconoInfo =  new ImageIcon(urlInfo); 
        lbcargando.setIcon(IconoInfo);
        lbcargando.setForeground(Color.red);
        
        
        Runnable miRunnable = new Runnable() {
          
            public void run() {
                
                try{
                
                    if (rbEcona.isSelected()){
                        
                        lbcargando.setVisible(true);
                        
                        CargaProductosEcona();
                        
                        lbcargando.setVisible(false);
               
                    }else if (rbSala.isSelected()) {
                        
                        lbcargando.setVisible(true);
                        
                        CargaProductosSala();
                        
                        lbcargando.setVisible(false);
               
                    }else {
                         
                        lbcargando.setVisible(true);
                        
                        CargaProductos();
                        
                        lbcargando.setVisible(false);
               
                    }
        
 
                }catch (Exception e) {
                    e.printStackTrace();
                } 
          
            }
        }; 
        
        Thread hilo = new Thread(miRunnable);
        hilo.start();
        
        
        
        
        
    }//GEN-LAST:event_btCargarActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        
        if(fmMain.OkCancel("Actualizar Minimos ?")== JOptionPane.OK_OPTION){
            
            ExeSql Sql = new ExeSql();
            ExeSql_Econa SqlEcona = new ExeSql_Econa();
            
                        
            try {
                
                boolean ajusta = false;
                
                for(int i=0; i< Grilla.getRowCount(); i++){
                
                    
                    ajusta = (boolean) Grilla.getValueAt(i, 5);
                    
                    
                    if (ajusta){
                    
                        Sql.ExeSql("UPDATE producto_valores \n" +
                                   "SET minimo = "+ Grilla.getValueAt(i,3).toString().trim()+" \n" +
                                   "WHERE sku = '" + Grilla.getValueAt(i,0).toString()+"'");
                
                        Sql.Commit();
                    
                    
                        SqlEcona.ExeSql("UPDATE producto_valores \n" +
                                        "SET minimo = "+ Grilla.getValueAt(i,4).toString().trim()+" \n" +
                                        "WHERE sku = '" + Grilla.getValueAt(i,0).toString()+"'");
                
                        SqlEcona.Commit();
                
                    }
                }
                
            } catch (SQLException e) {

                JOptionPane.showMessageDialog(null,"Error: "+e);
                Logger.getLogger(pfAjusteMinimos.class.getName()).log(Level.SEVERE, null, e);
            } finally{
                Sql.Close();
                
            }
            
        }
            
    }//GEN-LAST:event_btActualizarActionPerformed

     private void eliminar(int fila){
    
        DefaultTableModel Tmodel = (DefaultTableModel) Grilla.getModel();
      
        Tmodel.removeRow(fila);
      
        autoriza = false;
    }
    
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        pfProductos Pro = new pfProductos();
        Pro.setOpaque(false);
        pnPestanas.addTab("Producto", Pro);
        PanelTab btc = new PanelTab(pnPestanas, 0);
        pnPestanas.setTabComponentAt(pnPestanas.indexOfComponent(Pro), btc);
        pnPestanas.setSelectedIndex(pnPestanas.getTabCount() - 1);
        Pro.txSku.requestFocus();
        Pro.CargaProducto(Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString().trim());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        pfProductos Pro = new pfProductos();
        Pro.setOpaque(false);
        pnPestanas.addTab("Producto", Pro);
        PanelTab btc = new PanelTab(pnPestanas, 0);
        pnPestanas.setTabComponentAt(pnPestanas.indexOfComponent(Pro), btc);
        pnPestanas.setSelectedIndex(pnPestanas.getTabCount() - 1);
        Pro.txSku.requestFocus();
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void GrillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaMouseClicked
        
        if(evt.getClickCount()==2) {
            
            
            int fila = Grilla.getSelectedRow(); // primero, obtengo la fila seleccionada
            int columna = Grilla.getSelectedColumn(); // luego, obtengo la columna seleccionada
            
            
            
            if (columna == 3 || columna == 4 ){
            
                System.out.println("La Fila ES : "+fila);
                System.out.println("La Columna ES : "+columna);
             
             
                jdAjustarCant Ajustar =  new jdAjustarCant(null,true);
                Ajustar.setLocationRelativeTo(null);
                      
                dcant = Double.parseDouble(Grilla.getValueAt(Grilla.getSelectedRow(),columna).toString().trim());
            
                cant = (int) dcant;
            
                Ajustar.SetValor(cant);
            
                Ajustar.setVisible(true);
            
                if (Ajustar.GetRetorno()){
            
                    Grilla.setValueAt(Ajustar.GetCant(),Grilla.getSelectedRow(),columna);
                
                }
            
            }
        }
        
        
    }//GEN-LAST:event_GrillaMouseClicked

    private void txFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFiltroActionPerformed

    private void txFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txFiltroKeyPressed

    }//GEN-LAST:event_txFiltroKeyPressed

    private void txFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txFiltroKeyReleased

        TableRowSorter<TableModel>sorter = new TableRowSorter<>(Grilla.getModel());
        Grilla.setRowSorter(sorter);
        String filtro = txFiltro.getText().trim();

        if (filtro.length()==0)
        {
            sorter.setRowFilter(null);
        }else{

            sorter.setRowFilter(RowFilter.regexFilter(filtro));
        }

    }//GEN-LAST:event_txFiltroKeyReleased

    private void txFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txFiltroKeyTyped
        // TODO add your handling code here:
        if (Character.isLowerCase(evt.getKeyChar()))
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_txFiltroKeyTyped

    private void txCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCodigoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btIr.doClick();
        }
    }//GEN-LAST:event_txCodigoKeyPressed

    private void btIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIrActionPerformed

        if(!txCodigo.getText().isEmpty())
        
            BuscaSku(txCodigo.getText());
        
        else{
            jdBuscarProductos2 BP = new jdBuscarProductos2(null, true);
            BP.setLocationRelativeTo(null);
            BP.setTitle("Buscar Producto");
            

            BP.setVisible(true);
            
            if(!BP.GetCodigo().isEmpty()){
                
                BuscaSku(BP.GetCodigo());
            }
        }
    }//GEN-LAST:event_btIrActionPerformed

    
    
    private void BuscaSku(String Sku){
    
           String nombrePalabra =Sku.trim();
           

           
 //            if (nombrePalabra.substring(0,3).trim().equals("LVL") || nombrePalabra.substring(0,4).trim().equals("TRAN") ||
//                 nombrePalabra.substring(0,3).trim().equals("BOD") || nombrePalabra.substring(0,5).trim().equals("TPSAL") ||
//                 nombrePalabra.substring(0,5).trim().equals("THSAL") || nombrePalabra.substring(0,5).trim().equals("TPPAT") || 
//                 nombrePalabra.substring(0,5).trim().equals("THPAT")
//              ){
           
           
           
           
           if (nombrePalabra.substring(0,3).trim().equals("LVL") || nombrePalabra.substring(0,4).trim().equals("TRAN") || 
                nombrePalabra.substring(0,3).trim().equals("INV") || nombrePalabra.substring(0,3).trim().equals("SAL")){
              
                fmMain.Mensaje("Debe ingresar un Sku válido !");
                return;   
           
           }else{
              
               
                
               BuscaCodBar(Sku.trim());
               
               
               
                int nFilasSelec = Grilla.getRowCount();
                
                System.out.println("Las Filas Son : "+nFilasSelec);
                 
                
                if (nFilasSelec > 0){
               
                    ubica_metro();
               
                    for (int i = 0; i < Grilla.getRowCount(); i++) {
                    
                        if (Grilla.getValueAt(i, 0).equals(Sku.trim())) {
                        
                            boolean selecciona = (boolean) Grilla.getValueAt(i,4);
                        
                            if (selecciona){
                            
                                Grilla.setValueAt(false, i, 4);
                                Grilla.changeSelection(i, 0, false, false);  
                            
                                contselec--;
                            
                            }else if (!selecciona) {
                            
                                Grilla.setValueAt(true, i, 4);
                                Grilla.changeSelection(i, 0, false, false);
                            
                                contselec++;
                            
                            }
                        
                        }
                    }
               
                    if (contselec > 0){
             
                        System.out.println("HAY ELEMENTOS SELECCIONADOS!!"+contselec);
                   
                    }else if (contselec == 0){
                   
                        System.out.println("NO EXISTEN ELEMENTOS SELECCIONADOS!!"+contselec);
                   
                    }
               
                }
           }
           
        }
    
    
    private void ubica_metro(){
          
        String cant="",codigo="";
        int pos =-1;
        
        
        for (int i=0; i<=Grilla.getRowCount()-1; i++ ){
            
                codigo= Grilla.getValueAt(i, 0).toString().trim();
            
                if (codigo.equals(txCodigo.getText().trim())){
                    pos = i;
                    break;
                }
        }
        
        if (pos ==-1){
          
            fmMain.Mensaje("No se encuentra el producto en La Grilla" );
            txCodigo.setText("");
            return ;
      
        }
            
        
    }
    
    
    private void txTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTextoActionPerformed

    private void txTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txTextoKeyPressed
       
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        
            btCargar.doClick();
       }
    }//GEN-LAST:event_txTextoKeyPressed

    private void txTextoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txTextoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txTextoKeyReleased

    private void txTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txTextoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txTextoKeyTyped

    private void txCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCodigoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txCodigoKeyReleased

    private void rbSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSalaActionPerformed

    private void rbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTodosActionPerformed
    
    
    private String TextoBusqueda(){
        
        String Texto="upper(p.nombre) like '%";
        String Palabras[] = txTexto.getText().split(" ");
        
        if(Palabras.length>0){
            Texto = Texto + Palabras[0] + "%' ";
            for(int i=1; i< Palabras.length; i++){
                Texto = Texto + "or upper(p.nombre) like '%" + Palabras[i] + "%' ";
            }
        }
        else{
            Texto = Texto + txTexto.getText() + "%' ";         
        }
        return Texto;
    }
    
    
    private void CargaProductos(){
        
        ExeSql  Sql = new ExeSql();
        ExeSql  Sql2 = new ExeSql();
        ExeSql_Econa  Sql_Econa = new ExeSql_Econa();
        
        ResultSet Rs;
        ResultSet Rs2;
        ResultSet Rs_Econa;
        
        DefaultTableModel TableModel  = (DefaultTableModel) Grilla.getModel();
        
        while(TableModel.getRowCount()>0)
        TableModel.removeRow(0);
        
        String Sku = "";
        String Nombre = "";
        String StockLuv = "0";
        String Minimo = "0";
        String Minimo_Econa = "0";
        
        String Query = "";
        String QueryLuv = "";
        
        int cont = 0;
        
        try{
            
            Query = "SELECT p.sku, p.nombre, \n"+
                    "CASE WHEN pv.minimo is Null THEN '0' \n"+
                    "ELSE pv.minimo \n"+
                    "END AS minimo, i.stock FROM producto p\n"+
                    "LEFT JOIN producto_valores pv ON p.sku = pv.sku \n"+
                    "LEFT JOIN inventario i ON p.sku = i.sku \n"+
                    "WHERE i.stock > 0 ";
            
            
          
            
            if (!txTexto.getText().isEmpty()){
                
                //Query = Query + "WHERE p.nombre LIKE '%"+txTexto.getText().trim()+"%'";    
                 Query = Query + "AND (" + TextoBusqueda() + ") ";
                
            }
            
            
            Rs = Sql.Select(Query);
            
            if (Sql.GetRowCount() > 0){
            
                while (Rs.next()){ 
                
                    Sku = Rs.getString("sku");
                    Nombre = Rs.getString("nombre");
                    Minimo = Rs.getString("minimo");
                    StockLuv = Rs.getString("stock");;
                    
                    Rs_Econa = Sql_Econa.Select("SELECT sku, CASE WHEN minimo is Null THEN '0'  ELSE minimo END AS minimo FROM producto_valores \n"+
                                                "WHERE sku = '" + Sku.trim() + "'");
                    
                    if (Sql_Econa.GetRowCount() > 0){
                    
                        Rs_Econa.next();
                        
                        Minimo_Econa = Rs_Econa.getString("minimo");
                        
                        
                    }else{
                    
                    
                             Minimo_Econa = "0";
                    
                    }    
                           
                    TableModel.addRow(new Object[]{Sku.trim(),  
                                                   Nombre.trim(),
                                                   StockLuv.trim(),
                                                   Minimo.trim(), 
                                                   Minimo_Econa.trim(),
                                                   false
                                                  
                    });
                        
                    cont++;
                    
                    
                }
                
                int nFilasSelec = Grilla.getRowCount();
                
                 System.out.println("Las Filas Son : "+nFilasSelec);
                
                
                if (nFilasSelec > 0){
                
                    txFiltro.setEnabled(true);
                    txCodigo.setEnabled(true);
                    btIr.setEnabled(true);
                
                }
                
                System.out.println("Proceso Terminado !!!");
                lbCont.setText(""+cont);
            
            }
            
        } catch (SQLException e) {
          Sql.Rollback();
            JOptionPane.showMessageDialog(null, e);
            Logger.getLogger(pfAjusteMinimos.class.getName()).log(Level.SEVERE, null, e);
        }finally{
        
         Sql.Close();
        
        }
        
    }
    
    
    private void CargaProductosEcona(){
        
        ExeSql  Sql = new ExeSql();
        ExeSql  Sql2 = new ExeSql();
        ExeSql_Econa  Sql_Econa = new ExeSql_Econa();
        ExeSql  Sql_Sala = new ExeSql();
        
        ResultSet Rs;
        ResultSet Rs2;
        ResultSet Rs_Econa;
        ResultSet Rs_Sala;
        
        DefaultTableModel TableModel  = (DefaultTableModel) Grilla.getModel();
        
        while(TableModel.getRowCount()>0)
        TableModel.removeRow(0);
        
        String Sku = "";
        String Nombre = "";
        String StockLuv = "0";
        String Minimo = "0";
        String Minimo_Econa = "0";
        
        String Query = "";
        String QuerySala = "";
        String QueryLuv = "";
        
        int cont = 0;
        
        try{
            
            
            //Query = "SELECT sku, nombre FROM producto \n";
            
            Query = "SELECT p.sku, p.nombre, \n"+
                    "CASE WHEN pv.minimo is Null THEN '0' \n"+
                    "ELSE pv.minimo \n"+
                    "END AS minimo, i.stock FROM producto p\n"+
                    "LEFT JOIN producto_valores pv ON p.sku = pv.sku \n"+
                    "LEFT JOIN inventario i ON p.sku = i.sku \n"+
                    "WHERE i.stock > 0 ";
            
            
                    
            
            if (!txTexto.getText().isEmpty()){
                
                Query = Query + "AND nombre LIKE '%"+txTexto.getText().trim()+"%' \n";    
                
            }
            
            Query = Query + "ORDER BY sku ";    
            
            
            
            Rs = Sql.Select(Query);
            
            if (Sql.GetRowCount() > 0){
            
                while (Rs.next()){ 
                
                    Sku = Rs.getString("sku");
                    Nombre = Rs.getString("nombre");
                    StockLuv = Rs.getString("stock");
                    Minimo = Rs.getString("minimo");
                                      
                    Rs_Econa = Sql_Econa.Select("SELECT sku, CASE WHEN minimo is Null THEN '0'  ELSE minimo END AS minimo FROM producto_valores \n"+
                                                "WHERE sku  = '" + Sku.trim() + "'");
                    
                    if (Sql_Econa.GetRowCount() == 0){
                        
                        Minimo_Econa = "0";
                        
                        TableModel.addRow(new Object[]{Sku.trim(),  
                                                  Nombre.trim(),
                                                  StockLuv.trim(),
                                                  Minimo.trim(), 
                                                  Minimo_Econa.trim(),
                                                  false
                                                  
                        });
                        
                        cont++;
                        
                    }
                    
                }
                
                int nFilasSelec = Grilla.getRowCount();
                
                 System.out.println("Las Filas Son : "+nFilasSelec);
                
                
                if (nFilasSelec > 0){
                
                    txFiltro.setEnabled(true);
                    txCodigo.setEnabled(true);
                    btIr.setEnabled(true);
                
                }
                
                System.out.println("Proceso Terminado !!!");
                lbCont.setText(""+cont);
            
            }
            
        } catch (SQLException e) {
          
          JOptionPane.showMessageDialog(null, e);
          Logger.getLogger(pfAjusteMinimos.class.getName()).log(Level.SEVERE, null, e);
        }finally{
        
         Sql.Close();
        
        }
        
    }
    
    
    private void CargaProductosSala(){
        
        ExeSql  Sql = new ExeSql();
        ExeSql  Sql_Sala = new ExeSql();
        ExeSql_Econa  Sql_Econa = new ExeSql_Econa();
                
        ResultSet Rs;
        ResultSet Rs_Sala;
        ResultSet Rs_Econa;
       
        
        DefaultTableModel TableModel  = (DefaultTableModel) Grilla.getModel();
        
        while(TableModel.getRowCount()>0)
        TableModel.removeRow(0);
        
        String Sku = "";
        String Nombre = "";
        String StockLuv = "0";
        String Minimo = "0";
        String Minimo_Econa = "0";
        
        String Query = "";
        
        int cont = 0;
        
        try{
            
             Query = "SELECT p.sku, p.nombre, \n"+
                     "CASE WHEN pv.minimo is Null THEN '0' \n"+
                     "ELSE pv.minimo \n"+
                     "END AS minimo, i.stock FROM producto p\n"+
                     "LEFT JOIN producto_valores pv ON p.sku = pv.sku \n"+
                     "LEFT JOIN inventario i ON p.sku = i.sku \n"+
                     "WHERE i.stock > 0 ";
            
            
            if (!txTexto.getText().isEmpty()){
                
                Query = Query + "AND nombre LIKE '%"+txTexto.getText().trim()+"%' \n";    
                
            }
            
            Query = Query + "ORDER BY p.sku ";    
            
            Rs = Sql.Select(Query);
            
            
            if (Sql.GetRowCount() > 0){
            
                while (Rs.next()){ 
                
                    Sku = Rs.getString("sku");
                    Nombre = Rs.getString("nombre");
                    StockLuv = Rs.getString("stock");
                    Minimo = Rs.getString("minimo");;
                    
                    Rs_Sala = Sql_Sala.Select("select p.sku from producto p\n" +
                                              "where NOT EXISTS (select sku from mt_productos where sku=p.sku and ubicacion like '%SAL%' ) \n" +
                                              "and p.sku = '" + Sku.trim() + "' \n"+
                                              "ORDER BY p.sku");

                    if (Sql_Sala.GetRowCount() > 0){    
                        
                            Rs_Econa = Sql_Econa.Select("SELECT sku, CASE WHEN minimo is Null THEN '0'  ELSE minimo END AS minimo FROM producto_valores \n"+
                                                        "WHERE sku  = '" + Sku.trim() + "'");
                        
                            if (Sql_Econa.GetRowCount() > 0){
                        
                                Rs_Econa.next();
                                Minimo_Econa = Rs_Econa.getString("minimo");
                                                  
                            }else {
                        
                                Minimo_Econa = "0";
                        
                            }
                        
                        
                            TableModel.addRow(new Object[]{Sku.trim(),  
                                                           Nombre.trim(),
                                                           StockLuv.trim(),
                                                           Minimo.trim(), 
                                                           Minimo_Econa.trim(),
                                                           false
                                                  
                        });
                        
                        cont++;
                        
                    }
                    
                }
                
                int nFilasSelec = Grilla.getRowCount();
                
                 System.out.println("Las Filas Son : "+nFilasSelec);
                 System.out.println("El cont ES : "+cont);
                
                
                if (nFilasSelec > 0){
                
                    txFiltro.setEnabled(true);
                    txCodigo.setEnabled(true);
                    btIr.setEnabled(true);
                
                }
                
                System.out.println("Proceso Terminado !!!");
                lbCont.setText(""+cont);
            
            }
            
        } catch (SQLException e) {
          Sql.Rollback();
            JOptionPane.showMessageDialog(null, e);
            Logger.getLogger(pfAjusteMinimos.class.getName()).log(Level.SEVERE, null, e);
        }finally{
        
         Sql.Close();
        
        }
        
    }
    
    
    
    //-----------------------------------------------------------------------------
//  CARGA PRODUCTOS
//-----------------------------------------------------------------------------    
    
    public void BuscaCodBar(String Codigo) {
        ExeSql Sql = new ExeSql();
        
        ResultSet Rs = null;
       
        int revisa_codbar =0;
        int revisa_codchile =0;
        ExeSql luv = new ExeSql();
        ResultSet producto = null;
   
        try {
            String Query;
            //Limpia la Lista
            
            Rs = luv.Select("select codbar, sku from codbar where sku='" + Codigo + "' or codbar='"+ Codigo + "'" );        
                    if (Rs.next())
                        {
                        Codigo = Rs.getString("sku").trim();
                        revisa_codbar++;
                        }
            Rs = luv.Select("select idch, sku from codchile where sku='" + Codigo +"' or idch='"+ Codigo + "'" );
                    if (Rs.next())
                        {
                        Codigo = Rs.getString("sku").trim();
                        revisa_codchile++;
                        }
            Rs = luv.Select("select codbar, sku from codbar where sku='" + Codigo + "' or codbar='"+ Codigo + "'" );        
                    if (Rs.next())
                        {
                        Codigo = Rs.getString("sku").trim();
                        revisa_codbar++;
                        }
             
                    
                    
            Query ="select p.sku,p.nombre " 
                    + " from producto p \n"
                    + " where p.sku='" + Codigo + "' or p.sku in (select sku from codbar where codbar='" + Codigo + "')";
              Rs = luv.Select(Query);

              if(luv.GetRowCount()==0){   
                 fmMain.Mensaje("SKU: " + Codigo.trim() + " no esta en Nuestra Bases de Datos. Comuniquese con Informática");
                 txCodigo.setText("");
                 txCodigo.requestFocus();
                 return;
            }      
            Rs.next();
            Codigo = Rs.getString("sku").trim();
            
            
            txCodigo.setText(Codigo);
            
           
        } catch (SQLException ex) {
            System.out.println(ex);
        } finally {
            Sql.Close();
            luv.Close();
        }
    }
    
    
    
    
    
    
    
//    class Elrender extends DefaultTableCellRenderer {
//         
//        @Override
//        public Component getTableCellRendererComponent(JTable tabla, Object valor, boolean isSelected, boolean hasFocus, int fila, int columna) {
//        
//            Component componente = super.getTableCellRendererComponent(tabla,valor,isSelected, hasFocus, fila, columna);
//         
//        
//          
//            double stock_dif = (Double.parseDouble(tabla.getValueAt(fila,3).toString()) + Double.parseDouble(GrillaDatos.getValueAt(fila, 0).toString()))
//                                + Double.parseDouble(GrillaDatos.getValueAt(fila, 2).toString());
//                       
//            double porcentaje = (stock_dif / Double.parseDouble(GrillaDatos.getValueAt(fila, 2).toString()))*100;
//           
//            if (porcentaje == 0 || porcentaje > 0 ){
//            
//                porcentaje = porcentaje * 1;
//            
//            }else if (porcentaje < 0){
//             
//                porcentaje = porcentaje * -1;
//            }
//            
//            if(porcentaje >= 40){
//                 
//                sobre_stock = true;
//                componente.setForeground(Color.white);
//                componente.setBackground(Color.red);  
//            
//            }else{
//            
//                if (!sobre_stock){
//                
//                    sobre_stock = false;
//                }
//                
//                componente.setForeground(Color.black);
//                componente.setBackground(Color.white); 
//            }     
//             
//            return componente;
//        }
//        
//    } 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla;
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btCargar;
    private javax.swing.JButton btIr;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCont;
    private javax.swing.JLabel lbFiltro;
    private javax.swing.JLabel lbFiltro1;
    private javax.swing.JLabel lbcargando;
    private javax.swing.JRadioButton rbEcona;
    private javax.swing.JRadioButton rbSala;
    private javax.swing.JRadioButton rbTodos;
    private javax.swing.JTextField txCodigo;
    private javax.swing.JTextField txFiltro;
    private javax.swing.JTextField txTexto;
    // End of variables declaration//GEN-END:variables
}
