/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Dialogos.jdEditaNuevoSku;
import Formularios.fmMain;
import facturas.ArrayOfString;
import facturas.DTE;
import facturas.DTESoap;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.net.CookieHandler;
import java.net.CookieManager;
import java.net.CookiePolicy;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.PrintService;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.printing.PDFPageable;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.Namespace;
import org.jdom2.output.Format;
import org.jdom2.output.XMLOutputter;

/**
 *
 * @author infornatica
 */
public class pfAutorizaSKU extends javax.swing.JPanel {

    /**
     * Creates new form pfAutorizaNCC
     */
    
    int Filas = 0;
    
    public pfAutorizaSKU() {
        initComponents();
        CargaDatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btAutorizar = new javax.swing.JButton();
        btRechazar = new javax.swing.JButton();
        bnAutorizadas = new javax.swing.JRadioButton();
        bnPorAutorizar = new javax.swing.JRadioButton();
        bnRechazadas = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        txSku1 = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Grilla.setAutoCreateRowSorter(true);
        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SKU", "Nombre", "Fecha", "Usuario Solicita", "Convenio", "linea", "sublinea", "Unidad", "estado", "Embalaje"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(0).setMinWidth(80);
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(0).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(1).setPreferredWidth(550);
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(120);
            Grilla.getColumnModel().getColumn(3).setPreferredWidth(120);
            Grilla.getColumnModel().getColumn(4).setMinWidth(0);
            Grilla.getColumnModel().getColumn(4).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(4).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(5).setMinWidth(0);
            Grilla.getColumnModel().getColumn(5).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(5).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(6).setMinWidth(0);
            Grilla.getColumnModel().getColumn(6).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(6).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(7).setMinWidth(0);
            Grilla.getColumnModel().getColumn(7).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(7).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(8).setMinWidth(0);
            Grilla.getColumnModel().getColumn(8).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(8).setMaxWidth(0);
        }

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Actualiza.png"))); // NOI18N
        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btAutorizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/ok_16.png"))); // NOI18N
        btAutorizar.setText("Autorizar");
        btAutorizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAutorizarActionPerformed(evt);
            }
        });

        btRechazar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Cancel16.png"))); // NOI18N
        btRechazar.setText("Rechazar");
        btRechazar.setToolTipText("");
        btRechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRechazarActionPerformed(evt);
            }
        });

        buttonGroup1.add(bnAutorizadas);
        bnAutorizadas.setText("Autorizadas");
        bnAutorizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnAutorizadasActionPerformed(evt);
            }
        });

        buttonGroup1.add(bnPorAutorizar);
        bnPorAutorizar.setSelected(true);
        bnPorAutorizar.setText("Por Autorizar");

        buttonGroup1.add(bnRechazadas);
        bnRechazadas.setText("Rechazadas");
        bnRechazadas.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bnPorAutorizar)
                .addGap(18, 18, 18)
                .addComponent(bnAutorizadas)
                .addGap(18, 18, 18)
                .addComponent(bnRechazadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(btAutorizar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bnAutorizadas)
                        .addComponent(bnPorAutorizar)
                        .addComponent(bnRechazadas))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btAutorizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/search16.png"))); // NOI18N
        jLabel12.setText("FILTRO:");

        txSku1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txSku1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txSku1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txSku1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txSku1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txSku1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
     
    
    
    
    private void txSku1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSku1KeyTyped
        if (Character.isLowerCase(evt.getKeyChar()))
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_txSku1KeyTyped

    private void txSku1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSku1KeyReleased
        TableRowSorter<TableModel>sorter = new TableRowSorter<TableModel>(Grilla.getModel());
        Grilla.setRowSorter(sorter);
        String sku = txSku1.getText().trim();
        
        if (sku.length()==0){
            
            sorter.setRowFilter(null);
        
        }else{
        
            int cant=0;
            int ev=0;
            String precio = "";
            sorter.setRowFilter(RowFilter.regexFilter(sku));
        }
    }//GEN-LAST:event_txSku1KeyReleased

    private void txSku1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSku1KeyPressed

    }//GEN-LAST:event_txSku1KeyPressed

    private void btAutorizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAutorizarActionPerformed
        
        int estado = Integer.parseInt(Grilla.getValueAt(Grilla.getSelectedRow(), 8).toString().trim());
        
        Filas =  Grilla.getRowCount();    
            
        System.out.println("Filas ES : "+Filas);
        
        
        if (Filas==0){    
           
            fmMain.Mensaje("No se puede autorizar no hay registros");
            return;
        }

        
       if(estado==1){
                
           JOptionPane.showMessageDialog(null, "SKU ya está Autorizado !!");
           return;
                
        
        }else {
        
        
            if (JOptionPane.showConfirmDialog(null, "¿Desea autorizar creación SKU?")==0){
            
                CreaSku();
          
            }
        
        
        }
        
//        else if(estado==2){
//                
//           JOptionPane.showMessageDialog(null, "SKU ya está Rechazado !!");
//           return;    
//        }
        

        CargaDatos();
    }//GEN-LAST:event_btAutorizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        CargaDatos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GrillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaMouseClicked
        
        String Sku = Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString().trim();
        
        
        if(evt.getClickCount()==2){
        
            jdEditaNuevoSku nsk = new jdEditaNuevoSku(null, true);
            nsk.setLocationRelativeTo(null);
            nsk.setTitle("Edita Nuevo Sku");
           
            nsk.SetSku(Sku);
            nsk.CargaSku();
            nsk.setVisible(true);
            
            
            if (nsk.GeAcepta() == 1){
            
                Grilla.setValueAt(nsk.GetNombreCompleto(), Grilla.getSelectedRow(), 1);
                Grilla.setValueAt(nsk.GetEmbalaje(), Grilla.getSelectedRow(), 9);
            
            }
        }
        

    }//GEN-LAST:event_GrillaMouseClicked

    private void btRechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRechazarActionPerformed
       
        Filas =  Grilla.getRowCount();    
            
        System.out.println("Filas ES : "+Filas);
        
        if (Filas==0){    
            
            fmMain.Mensaje("No se puede rechazar, no hay registros");
            return;
        }
        
        int estado = Integer.parseInt(Grilla.getValueAt(Grilla.getSelectedRow(), 8).toString().trim());
        
        
        if(estado==0 ){
            
            if (JOptionPane.showConfirmDialog(null, "¿Desea rechazar creación de SKU?")==0){
                        
                RechazaSku();
            }    
        
        }else if(estado ==1 ) {
        
            JOptionPane.showMessageDialog(null, "Creación de SKU ya fue autorizada");
        
        }else if(estado ==1 ) {
        
            JOptionPane.showMessageDialog(null, "Creación de SKU ya fue rechazada");
        }

        CargaDatos();
        
        
        
    }//GEN-LAST:event_btRechazarActionPerformed

    private void bnAutorizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnAutorizadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnAutorizadasActionPerformed
    
    
    
    private void CreaSku(){
        
        ExeSql Sql = new ExeSql(); 
        ExeSql Sql2 = new ExeSql(); 
         
        try {
             
            String Sku = Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString().trim();
            int Unidad = Integer.parseInt(Grilla.getValueAt(Grilla.getSelectedRow(), 7).toString().trim());
            String Nombre = Grilla.getValueAt(Grilla.getSelectedRow(), 1).toString().trim();
           
            int Familia = Integer.parseInt(Grilla.getValueAt(Grilla.getSelectedRow(), 5).toString().trim());
            int SubFamilia = Integer.parseInt(Grilla.getValueAt(Grilla.getSelectedRow(), 6).toString().trim());
           
            String Display = Grilla.getValueAt(Grilla.getSelectedRow(), 9).toString().trim();
            
            String Convenio = Grilla.getValueAt(Grilla.getSelectedRow(), 4).toString().trim();
            
            
            String NroPublicacion = "0";
             
            
                
            String Query = "INSERT INTO producto\n"
                            + "(sku, unidad, nombre, pventa, imptoiva, linea, sublinea, peso, largo, ancho,alto, marca, display, publicado, discontinuado, \n"
                            + "sinstock, desxprecio, notransado, convenio, sin_publicar, pventa_web2,precio_publicar, comision,envio,nropublicacion)\n" 
                            + "VALUES \n"                                                                                                     
                            + "('" + Sku.trim() + "', "
                            + Unidad + ","
                            + "'" + Nombre.trim() + "',"
                            + 0 + ","
                            + 0 + "," 
                            + Familia + ","
                            + SubFamilia + ","
                            + 0 + ","
                            + 0 + ","
                            + 0 + ","
                            + 0 + ","
                            + 1 + ","
                            + Display.trim() + ","
                            + false + ","
                            + false + ","
                            + false + ","
                            + false + ","
                            + false + ","
                            + Convenio + ","
                            + false+","
                            + 0+","
                            + 0+","
                            + 0+","
                            + 0+",'"
                            + NroPublicacion.trim()+"')";
                    
                    System.out.println(Query);
                    Sql.ExeSql(Query);
                    
                    Sql.Commit();

                    
                    
                    
                    Sql2.ExeSql("update producto_autoriza set \n"+
                                "estado = 1 "+
                                "where sku = '"+Sku.trim()+"' \n"+
                                "and convenio = "+Convenio );
                    Sql2.Commit();
            
                    JOptionPane.showMessageDialog(null,"Creación de Sku ("+Sku+") Aprobada");
                    
                    JOptionPane.showMessageDialog(null, "Producto Guardado");  

                    
        } catch (SQLException e) {
        
            Sql.Rollback();
            Sql2.Rollback();
            JOptionPane.showMessageDialog(null, "Error al guardar " + e.getMessage());
            Logger.getLogger(pfAutorizaSKU.class.getName()).log(Level.SEVERE, null, e);
                    
                   
        }finally {
            
            Sql.Close();
            Sql2.Close();

        }
        
    }
    
     
     
    private void RechazaSku(){
         
        ExeSql Sql = new ExeSql();
        
        try {

            String sku = Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString().trim();
            int convenio = Integer.parseInt(Grilla.getValueAt(Grilla.getSelectedRow(), 4).toString().trim());
            
            
            Sql.ExeSql("update producto_autoriza set \n"+
                       "estado = 2 "+
                       "where sku = '"+sku.trim()+"' \n"+
                       "and estado = 0 \n"+
                       "and convenio = "+convenio );
            
            
//            Sql.ExeSql("delete from producto_autoriza \n" +
//                       "where sku = '"+sku.trim()+"' \n"+
//                       "and convenio = "+convenio+" \n"+
//                       "and estado = 0");
            
            
            Sql.Commit();
            
            JOptionPane.showMessageDialog(null,"Creación de Sku ("+sku+") Rechazada");
            
            
            
        } catch (SQLException ex) {
           
            Sql.Rollback();
            fmMain.Mensaje(ex.getMessage());
            Logger.getLogger(pfAutorizaSKU.class.getName()).log(Level.SEVERE, null, ex);
        
        } finally{
            Sql.Close();
            

        }      
    } 
     
     
     
    private void GeneraDTE_NCC(String ParRut,String ParTipo, String ParNumero){
    
        File factura = null;
        
       // boolean Resultado=true;
        String Rut = ParRut;
        String Tipo = ParTipo;
        String Numero = ParNumero;
        String TipoNro = "";
        
        String ElRut = "";
        String ElNombre = "";
        String ElGiro = "";
        String LaDireccion = "";
        String LaComuna = "";
        String LaCiudad = "";
        
        String Fecha = "";
        
        String ElAfecto = "";
        String ElIva = "";
        String ElTotal = "";
        
        String FolioRef = "";
        String TipoFolioRef = "";
        String FechaGDC = "";
        
        String CodRef = "";
                        
        ExeSql Sql = new ExeSql();
        ExeSql Sql2 = new ExeSql();
        ExeSql Sql3 = new ExeSql();
        ExeSql Sql4 = new ExeSql();
        ExeSql Sql5 = new ExeSql();
       
        
        ResultSet Rs, Rs2, Rs3,Rs4, Rs5 = null;
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
         Document doc= new Document();    
        
        try {
        
            Rs = Sql.Select("select * from ctactecli where tipdocto='" + Tipo +"' and nrodocto=" + Numero);
            Rs.next();
        
            switch (Tipo){
                case "GDC": TipoNro="52"; break;
                case "FAC": TipoNro="33"; break;
                case "NCC": TipoNro="61"; break;
                case "NDC": TipoNro="56"; break;
                case "FEC": TipoNro="34"; break;
                case "BOC": TipoNro="39"; break;
            }
            
            Fecha = sdf.format(Rs.getDate("femision"));
            
            Namespace ns= Namespace.getNamespace("http://www.sii.cl/SiiDte");
            
           // Document doc= new Document();    
            
                Element root=new Element("DTE").setAttribute("version", "1.0");
                root.setNamespace(ns);
                
                    Element documento=new Element("Documento").setAttribute("ID","F"+Numero+"T"+TipoNro);
                    documento.setNamespace(ns);
        
                        Element encabezado=new Element("Encabezado"); 
                        encabezado.setNamespace(ns);
        
                            Element Iddoc=new Element("IdDoc").setNamespace(ns); 
                                            
                                Iddoc.addContent(new Element("TipoDTE").addContent(TipoNro).setNamespace(ns));
                                Iddoc.addContent(new Element("Folio").addContent(Numero).setNamespace(ns));
                                Iddoc.addContent(new Element("FchEmis").addContent(Fecha).setNamespace(ns));
                                
                                
                            
                            Element Emisor=new Element("Emisor").setNamespace(ns); 
                                
                                Emisor.addContent(new Element("RUTEmisor").addContent("76231391-K").setNamespace(ns));
                                Emisor.addContent(new Element("RznSoc").addContent("EMPRESA COMERCIALIZADORA LUIS VALDES LYON S.P.A.").setNamespace(ns));
                                Emisor.addContent(new Element("GiroEmis").addContent("COMERCIALIZADORA DE ARTICULOS DE FERRETERIA").setNamespace(ns));
                                Emisor.addContent(new Element("Telefono").addContent("+56(45)2658390").setNamespace(ns));
                                Emisor.addContent(new Element("CorreoEmisor").addContent("contacto@luvaly.cl").setNamespace(ns));
                                Emisor.addContent(new Element("Acteco").addContent("464909").setNamespace(ns));
                                Emisor.addContent(new Element("Acteco").addContent("466302").setNamespace(ns));
                                Emisor.addContent(new Element("DirOrigen").addContent("AVENIDA HUERFANOS 01871").setNamespace(ns));
                                Emisor.addContent(new Element("CmnaOrigen").addContent("TEMUCO").setNamespace(ns));
                                Emisor.addContent(new Element("CiudadOrigen").addContent("TEMUCO").setNamespace(ns));
                                
                                
                                
                        //**************************************************************** DATOS CLIENTE ******************************************************************//        
                                
                                String Query = "select d.rut || '-' || co.dv as rut, co.nombre,c.giro,c.direccion,c.ciudad,c.comuna \n"+
                                               "from ctactecli d \n"+
                                               "left join cliente co on co.rut=d.rut \n"+
                                               "left join clicontacto c on d.rut=c.rut and d.codigo_oc = c.codigo_oc \n"+
                                               "where d.rut=" + Rut + "\n"+
                                               "and d.tipdocto='" + Tipo + "'\n"+
                                               "and d.nrodocto=" + Numero;
                                //System.out.println(Query);
                                Rs2 = Sql2.Select(Query);
                                Rs2.next();

                                ElRut = Rs2.getString("rut").trim();
                                
                                //ElNombre = Rs2.getString("Nombre").trim().replaceAll("\\&", "&amp;");
                                ElNombre = Rs2.getString("Nombre").trim();
                                
                                
                                
                                if(Rs2.getString("giro").trim().length()>40){
                                    
                                     ElGiro = Rs2.getString("giro").substring(0, 40).trim();
                                    
                                }else{
                                    
                                    ElGiro = Rs2.getString("giro").trim();
                                
                                }    
                                
                                LaDireccion = Rs2.getString("direccion").trim();
                                LaComuna= Rs2.getString("comuna").trim();
                                LaCiudad = Rs2.getString("ciudad").trim();
                                
                                
                        //********************************************************************************************************************************************************//    
                            Element Receptor=new Element("Receptor").setNamespace(ns); 
                                            
                                Receptor.addContent(new Element("RUTRecep").addContent(ElRut).setNamespace(ns));
                                Receptor.addContent(new Element("RznSocRecep").addContent(ElNombre).setNamespace(ns));
                                Receptor.addContent(new Element("GiroRecep").addContent(ElGiro).setNamespace(ns));    
                                Receptor.addContent(new Element("DirRecep").addContent(LaDireccion).setNamespace(ns));    
                                Receptor.addContent(new Element("CmnaRecep").addContent(LaComuna).setNamespace(ns));    
                                Receptor.addContent(new Element("CiudadRecep").addContent(LaCiudad).setNamespace(ns));    
                                
                        //**************************************************************** TOTALES DOCUMENTO ******************************************************************//   
                                
                          ElAfecto = Rs.getString("totalafecto");
                          ElIva = Rs.getString("totaliva");
                          ElTotal = Rs.getString("totaldocto");
                                
                                
                                
                            Element Totales=new Element("Totales").setNamespace(ns); 
                                            
                                Totales.addContent(new Element("MntNeto").addContent(ElAfecto).setNamespace(ns));
                                Totales.addContent(new Element("TasaIVA").addContent("19").setNamespace(ns));
                                Totales.addContent(new Element("IVA").addContent(ElIva).setNamespace(ns));
                                Totales.addContent(new Element("MntTotal").addContent(ElTotal).setNamespace(ns));
                        
                       
                                    
                        encabezado.addContent(Iddoc);
                        encabezado.addContent(Emisor);
                        encabezado.addContent(Receptor);
                        encabezado.addContent(Totales);
                
                    documento.addContent(encabezado);    
             
                    //********************************************************************************************************************************************************//             
                    
                    //**************************************************************** DETALLE PRODUCTOS ******************************************************************//   
                    
                    int linea = 1;
                    
                    Rs3 = Sql3.Select("select d.sku,p.nombre,u.um,d.cantidad,d.valorunitario,d.totallinea\n" +
                                       "from ctacteclidet d\n" +
                                       "left join producto p on d.sku=p.sku \n" +
                                        "left join par_unidad u on u.codigo=p.unidad\n" +
                                        "where d.tipdocto='"+ Tipo +"'\n" +
                                        "and d.rut="+ Rut +"\n" +
                                        "and d.nrodocto=" + Numero);
                     
                   
                    if (Sql3.GetRowCount() > 0){
                    
                        while(Rs3.next()){ //Una iteración por producto
                   
                            String ElProd = Rs3.getString("nombre").trim();
                            String LaCantidad = fmMain.FormatoNumero3(Rs3.getDouble("cantidad"));
                            String LaUnidad = Rs3.getString("um");
                            String ElUnitario = fmMain.FormatoNumero4(Rs3.getDouble("valorunitario"));
                            String LaLinea = String.valueOf(Math.round(Rs3.getDouble("totallinea")));
                            
                            String ElSku = Rs3.getString("sku").trim();
                        
                            Element Detalle=new Element("Detalle").setNamespace(ns);
                        
                                String nLinea = String.valueOf(linea);    
                            
                                Detalle.addContent(new Element("NroLinDet").addContent(nLinea).setNamespace(ns));
                                
                                    Element CdgItem=new Element("CdgItem").setNamespace(ns);  //Tipo Codificacion para los items
                                
                                            CdgItem.addContent(new Element("TpoCodigo").addContent("INT1").setNamespace(ns));
                                            CdgItem.addContent(new Element("VlrCodigo").addContent(ElSku).setNamespace(ns));
                            
                                Detalle.addContent(CdgItem);       
                                
                                Detalle.addContent(new Element("NmbItem").addContent(ElProd).setNamespace(ns));
                                Detalle.addContent(new Element("QtyItem").addContent(LaCantidad).setNamespace(ns));
                                Detalle.addContent(new Element("UnmdItem").addContent(LaUnidad).setNamespace(ns));
                                Detalle.addContent(new Element("PrcItem").addContent(ElUnitario).setNamespace(ns));
                                Detalle.addContent(new Element("MontoItem").addContent(LaLinea).setNamespace(ns));
                            
                                linea++;
                            
                           documento.addContent(Detalle);
                        }
                    
                    }
                    
                    //********************************************* SI ES CORRIGE TEXTO **********************************************//
                    
                        String ElTexto="";
                        Rs5 = Sql5.Select("select motivo from corrige_texto where nrodocto="+ Numero);
                
                        if(Sql5.GetRowCount()>0){
                            
                            Rs5.next();
                            
                            ElTexto = Rs5.getString("motivo").trim();
                            
                            Element DetalleCorrige=new Element("Detalle").setNamespace(ns);
                    
                                String nLineaCorrige = String.valueOf(linea);
                                
                                DetalleCorrige.addContent(new Element("NroLinDet").addContent(nLineaCorrige).setNamespace(ns));
                                DetalleCorrige.addContent(new Element("NmbItem").addContent("CORRIGE TEXTO:").setNamespace(ns));
                                DetalleCorrige.addContent(new Element("DscItem").addContent(ElTexto).setNamespace(ns));
                                DetalleCorrige.addContent(new Element("MontoItem").addContent("0").setNamespace(ns));
                    
                            documento.addContent(DetalleCorrige); 
                            
                        }
                    
                    
                    
                    
                    //*****************************************************************************************************************//
                    
                    String TipoDocRef = Rs.getString("tipdocorigen");
                    
                    
        
                    Rs4 = Sql4.Select("select * from ctactecli where tipdocto IN ('"+TipoDocRef+"') and nrodocto =" + Rs.getInt("nrodocorigen"));
 
        
                    Rs4.next();
                    
                    
                    FolioRef = Rs4.getString("nrodocto"); 
                    
                    String TipoRef = "";
                    
                    if (Rs4.getString("tipdocto").equals("BOC")){
                    
                        TipoRef = "39";
                    
                    }else if (Rs4.getString("tipdocto").equals("FAC")){
                    
                         TipoRef = "33";
                    
                    }
                    
                    
                    
                    FechaGDC = sdf.format(Rs4.getDate("femision"));
                    CodRef = Rs.getString("tipo");
                    
                    if (CodRef.trim().equals("4") || CodRef.trim().equals("5")){
                                        
                        CodRef = "3";
                    }
                    
                    
                    Element Referencia=new Element("Referencia").setNamespace(ns);
                    
                          Referencia.addContent(new Element("NroLinRef").addContent("1").setNamespace(ns));
                          Referencia.addContent(new Element("TpoDocRef").addContent(TipoRef).setNamespace(ns));
                          Referencia.addContent(new Element("FolioRef").addContent(FolioRef).setNamespace(ns));
                          Referencia.addContent(new Element("FchRef").addContent(FechaGDC).setNamespace(ns));
                          Referencia.addContent(new Element("CodRef").addContent(CodRef).setNamespace(ns));
                    documento.addContent(Referencia);
                    
           root.addContent(documento);
        doc.setRootElement(root);

       
//Se genera el archivo XML 
//        XMLOutputter outter=new XMLOutputter();
//        outter.setFormat(Format.getPrettyFormat());
//        factura = new File("C:/temp_luvaly/minotacredito.xml");
//        outter.output(doc, new FileWriter(factura));
    
    }catch (SQLException ex) {
    
        Logger.getLogger(pfAutorizaSKU.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
        XMLOutputter outter=new XMLOutputter();
        outter.setFormat(Format.getPrettyFormat());
        
        DTE dte = new DTE();
        DTESoap soap = dte.getDTESoap();
        
        //ArrayOfString respuesta = soap.ponerDTE("ws_econa", "5df28bdd52", outter.outputString(doc), false);               
        ArrayOfString respuesta = soap.ponerDTE("ws_econa", "5df28bdd52", outter.outputString(doc), true);               
        
        if (respuesta.getString().isEmpty()){   //Si la respuesta es una cadena vacía el envío fue exitoso
        
            System.out.println("Documento ha sido emitido");
            Imprimir("76231391-K",ElRut,TipoNro,Numero,Fecha,ElTotal,0,0);
                        
        }else{        //De lo contrario el archivo XML presenta errores
        
            System.out.println("Error en envío : "+respuesta.getString());   //Se muestra los errores señalados
            
        }
        
    } 
     
     
     
    
   public void Imprimir(String emisor, String receptor, String tipodte, String folio, String fecha, String total, int cimp,int imprime)  {
      
        System.out.println(emisor);
        System.out.println(receptor) ;
        System.out.println(tipodte);
        System.out.println(folio);
        System.out.println(fecha); 
        System.out.println(total);
        
        int Imprimir = imprime;
       
        try {
            PrintService[] services = PrinterJob.lookupPrintServices();
          
         //   int value = 4;
            
            int value = cimp; // El valor obtenido especifica la posicion de la impresora
            
            PrintService print = services[value];
           // System.out.println("EL VALOR DE LA IMPRESORA ES :"+services[value]);
            
            
            URL url=null;
            try {
           
                CookieHandler.setDefault(new CookieManager(null, CookiePolicy.ACCEPT_ALL));
    
                //URL de pruebas
//                
//                url = new URL("https://www.efacturadelsur.cl/certificacion/pdf?rutEmisor="+emisor+"&rutReceptor="+receptor+"&tipoDte="+tipodte+
//                              "&folio="+folio+"&fechaEmision="+fecha+"&montoTotal="+total);
                
                
                //URL de producción

              url = new URL("https://www.efacturadelsur.cl/app/pdf?rutEmisor="+emisor+"&rutReceptor="+receptor+"&tipoDte="+tipodte+
                            "&folio="+folio+"&fechaEmision="+fecha+"&montoTotal="+total);
                
                InputStream in = url.openStream();
                Files.copy(in, Paths.get("C:/doc_luvaly/NCC"+folio+".pdf"), StandardCopyOption.REPLACE_EXISTING);
          

          

            } catch (MalformedURLException e) {
                Logger.getLogger(pfGDCliente.class.getName()).log(Level.SEVERE, null, e);
            }
            
            
            File fin = new File("C:/doc_luvaly/NCC"+folio+".pdf");

            
            if (Imprimir == 1){
            
                PDDocument document = Loader.loadPDF(fin);

                PrinterJob job = PrinterJob.getPrinterJob();
                job.setPageable(new PDFPageable(document));
                job.setPrintService(print);
                job.print();
            
            }
            
        
        }catch (FileNotFoundException ex) {
            
            Logger.getLogger(pfGDCliente.class.getName()).log(Level.SEVERE, null, ex);
        
        }catch (IOException | PrinterException ex) {
            
            Logger.getLogger(pfGDCliente.class.getName()).log(Level.SEVERE, null, ex);
        } 
    
    } 
    
    
     
     
     
    public void CargaDatos() {
        ExeSql sql = new ExeSql();
        ResultSet rs = null;
        
        
        String query = "";
        
        if(bnAutorizadas.isSelected()){
            //query = "select * from producto_autoriza where estado = 1";
            
            query ="select pa.*, p.usuario, p.alias from producto_autoriza pa\n" +
                   "left join personal p on upper(pa.usuariocreacion) = p.usuario \n" +
                   "where pa.estado = 1";
                    
        }
        if(bnPorAutorizar.isSelected()) {
            //query = "select * from producto_autoriza where estado = 0";
            
            query ="select pa.*, p.usuario, p.alias from producto_autoriza pa\n" +
                   "left join personal p on upper(pa.usuariocreacion) = p.usuario \n" +
                   "where pa.estado = 0";
            
            
        }
        if(bnRechazadas.isSelected()) {
            //query = "select * from producto_autoriza where estado = 0";
            
            query ="select pa.*, p.usuario, p.alias from producto_autoriza pa\n" +
                   "left join personal p on upper(pa.usuariocreacion) = p.usuario \n" +
                   "where pa.estado = 2";
            
            
        }
        
        
        
        
        
        try {
            rs =sql.Select(query);
            DefaultTableModel model = (DefaultTableModel) Grilla.getModel();
            
            while(model.getRowCount()>0){
            
                model.removeRow(0);
            }
            
            for(int i = 0; rs.next(); i++){  
                
                model.addRow(new Object[]{
                            rs.getString("sku"),
                            rs.getString("nombre"),
                            rs.getString("fcreacion"),
                            //rs.getString("usuariocreacion").toUpperCase(),
                            rs.getString("alias").toUpperCase(),
                            rs.getInt("convenio"),
                            rs.getInt("linea"),
                            rs.getInt("sublinea"),
                            rs.getString("unidad"),
                            rs.getInt("estado"),
                            rs.getString("display")
                           
                            
                });
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(pfAutorizaSKU.class.getName()).log(Level.SEVERE, null, ex); 
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla;
    private javax.swing.JRadioButton bnAutorizadas;
    private javax.swing.JRadioButton bnPorAutorizar;
    private javax.swing.JRadioButton bnRechazadas;
    private javax.swing.JButton btAutorizar;
    private javax.swing.JButton btRechazar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txSku1;
    // End of variables declaration//GEN-END:variables
}
