package PanelForm;

import Conexion.ExeSql;
import Dialogos.jdCompara;
import Formularios.fmMain;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Roberto López
 */

public class pfBalanceGeneral extends javax.swing.JPanel {
    
    Calendar cal = Calendar.getInstance(); 
    
    double mFEC = 0;
    int cFEC = 0;
    double mFAC = 0;
    int cFAC = 0;
    double mNCC = 0;
    int cNCC = 0;
    double mFAG = 0;
    int cFAG = 0;
    double mFAG2 = 0;
    int cFAG2 = 0;
    double mFAP = 0;
    int cFAP = 0;
    double mNCP = 0;
    int cNCP = 0;
    double mIMPU = 0;
    double mIMPRenta = 0;
    double mPPM = 0;
    double mBImponible = 0;
    double mTDebitos = 0;
    double mTCreditos = 0;
    double mTIVAd = 0;
    double mSTimp = 0;
    
  //**** Pasivos **************//  
    
    double tCxp = 0;
    double tRxp = 0;
    double tHxp = 0;
    double tCBanc = 0;
    double tCPrev = 0;
    double tDIVA = 0;
    
 //**** Activos **************//      
    double tCxc = 0;
    
    
    
    DecimalFormat formateador = new DecimalFormat("###,###");
    
    public pfBalanceGeneral() {
        
        initComponents();
        
        
        cbAgno.setSelectedItem(Integer.toString(cal.get(Calendar.YEAR))); 
        cbMes.setSelectedIndex((cal.get(Calendar.MONTH))+1); 
        
        btComparar.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cbAgno = new javax.swing.JComboBox<String>();
        jLabel1 = new javax.swing.JLabel();
        cbMes = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        btAbrir = new javax.swing.JButton();
        btComparar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txCxp = new javax.swing.JTextField();
        txRxp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txHxp = new javax.swing.JTextField();
        txTDebitos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txCBancos = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txCPrev = new javax.swing.JTextField();
        txDIVA = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txCxc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txMercaderia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txPrestamos = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txAFamilar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txTCreditos = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txDCredito1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txPPrev = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txDCredito3 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txDCredito4 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txDCredito5 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txDCredito6 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txDCredito7 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txDCredito8 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txDCredito9 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txCIVA = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txIVAdet = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txSTImpuesto = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txTotal = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txTdeterm = new javax.swing.JTextField();

        pnMenu.setBackground(new java.awt.Color(220, 215, 226));

        jPanel1.setBackground(new java.awt.Color(220, 215, 226));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setName(""); // NOI18N

        cbAgno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Año", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        cbAgno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAgnoActionPerformed(evt);
            }
        });

        jLabel1.setText("AÑO :");

        cbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Mes", "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));

        jLabel4.setText("MES  :");

        btAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/Open.png"))); // NOI18N
        btAbrir.setText("ABRIR");
        btAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirActionPerformed(evt);
            }
        });

        btComparar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/derecha16.png"))); // NOI18N
        btComparar.setText("Comparar");
        btComparar.setEnabled(false);
        btComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCompararActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbMes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbAgno, 0, 101, Short.MAX_VALUE))
                .addGap(114, 114, 114)
                .addComponent(btAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(572, 572, 572))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbAgno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btComparar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAbrir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Cuentas por Pagar (Proveedores y Gastos)");

        txCxp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txCxp.setText(" ");
        txCxp.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txCxp.setEnabled(false);

        txRxp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txRxp.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txRxp.setEnabled(false);

        jLabel3.setText("Remuneraciones por Pagar");

        jLabel6.setText("Honorarios por Pagar");

        txHxp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txHxp.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txHxp.setEnabled(false);

        txTDebitos.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txTDebitos.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Total Pasivos");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PASIVOS");

        jLabel34.setText("Crédito Bancos");

        txCBancos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txCBancos.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txCBancos.setEnabled(false);

        jLabel37.setText("Cotizaciones Previsionales");

        jLabel38.setText("Débito IVA (IVA de las Ventas)");

        txCPrev.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txCPrev.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txCPrev.setEnabled(false);

        txDIVA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txDIVA.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txDIVA.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(340, 340, 340))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txTDebitos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(65, 65, 65)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txCxp)
                                        .addComponent(txRxp, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txHxp, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txCBancos, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txCPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txDIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(180, 180, 180))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel6)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel34))
                            .addComponent(jLabel2))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel38))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txCxp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(txRxp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(txHxp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(txCBancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txCPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(txDIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(208, 208, 208)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txTDebitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Cuentas por Cobrar (Clientes)");

        txCxc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txCxc.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txCxc.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ACTIVOS");

        jLabel12.setText("Mercadería (Facturas de Proveedores)");

        txMercaderia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txMercaderia.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txMercaderia.setEnabled(false);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Préstamos o Anticipos (cuota)");

        txPrestamos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txPrestamos.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txPrestamos.setEnabled(false);
        txPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPrestamosActionPerformed(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Asignación Familiar");

        txAFamilar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txAFamilar.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txAFamilar.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Total Activos ");

        txTCreditos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txTCreditos.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txTCreditos.setEnabled(false);

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Boletas de Garantía ");

        txDCredito1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txDCredito1.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txDCredito1.setEnabled(false);

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Pagos Previsionales");

        txPPrev.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txPPrev.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txPPrev.setEnabled(false);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("Compra de Vehículos");

        txDCredito3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txDCredito3.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txDCredito3.setEnabled(false);

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("Compra de Maquinarias");

        txDCredito4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txDCredito4.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txDCredito4.setEnabled(false);

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("Compra de Terrenos");

        txDCredito5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txDCredito5.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txDCredito5.setEnabled(false);

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setText("Compra de Equipamiento Informático");

        txDCredito6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txDCredito6.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txDCredito6.setEnabled(false);

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel39.setText("Compra de Mobiliario y Útiles ");

        txDCredito7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txDCredito7.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txDCredito7.setEnabled(false);

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel40.setText("Compra de Otros Activos");

        txDCredito8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txDCredito8.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txDCredito8.setEnabled(false);

        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel41.setText("Capital en Cuentas Bancarias");

        txDCredito9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txDCredito9.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txDCredito9.setEnabled(false);

        jLabel42.setText("Crédito IVA (IVA de las Compras)");

        txCIVA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txCIVA.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txCIVA.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txTCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txAFamilar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txMercaderia, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txCxc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txDCredito1)
                            .addComponent(txPPrev)
                            .addComponent(txDCredito3)
                            .addComponent(txDCredito4)
                            .addComponent(txDCredito5)
                            .addComponent(txDCredito6)
                            .addComponent(txDCredito7)
                            .addComponent(txDCredito8)
                            .addComponent(txDCredito9)
                            .addComponent(txCIVA))
                        .addGap(183, 183, 183)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txCxc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txMercaderia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txAFamilar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txDCredito1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txPPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txDCredito3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txDCredito4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txDCredito5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txDCredito6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(txDCredito7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(txDCredito8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(txDCredito9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txCIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txTCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("TOTALES");

        jLabel23.setText("IVA determinado (89)");

        txIVAdet.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txIVAdet.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txIVAdet.setEnabled(false);

        jLabel24.setText("SubTotal Impuesto Determinado Anverso (595)");

        txSTImpuesto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txSTImpuesto.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txSTImpuesto.setEnabled(false);

        jLabel25.setText("TOTAL A PAGAR  (91)");

        txTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txTotal.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txTotal.setEnabled(false);

        jLabel32.setText("Totral Determinado (547)");

        txTdeterm.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txTdeterm.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txTdeterm.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(412, 412, 412))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txIVAdet, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txSTImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txTdeterm, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(136, 136, 136))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txIVAdet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txSTImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txTdeterm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout pnMenuLayout = new javax.swing.GroupLayout(pnMenu);
        pnMenu.setLayout(pnMenuLayout);
        pnMenuLayout.setHorizontalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnMenuLayout.createSequentialGroup()
                        .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnMenuLayout.setVerticalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMenuLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(pnMenuLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1.getAccessibleContext().setAccessibleName(" ");
        jPanel1.getAccessibleContext().setAccessibleDescription("");
        jPanel2.getAccessibleContext().setAccessibleName("");
        jPanel2.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void cbAgnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAgnoActionPerformed
     
        
    }//GEN-LAST:event_cbAgnoActionPerformed

    private void btAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirActionPerformed
        
        if (cbAgno.getSelectedIndex() == 0){
        
           fmMain.Mensaje("Debe Ingresar un Año");
           return;
        
        }
        
        if (cbMes.getSelectedIndex() == 0){
        
           fmMain.Mensaje("Debe Ingresar un Mes");
           return;
        
        }
        
        CuentasxPagar();
        RemxPagar();
        HonorariosxPagar();
        CreditoBancos();
        CotizacionesPrev();
        DebitoIVA();
     
     //**********************************************************//
        
        CuentasxCobrar();
        
        

        mTDebitos =  tCxp + tRxp + tHxp + tCBanc + tCPrev + tDIVA;
        
        txTDebitos.setText("$ "+formateador.format(Math.round(mTDebitos)));
    }//GEN-LAST:event_btAbrirActionPerformed

    
    
    
    private void CuentasxPagar(){
        
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        
        tCxp = 0;
        
        try{
            

           Rs = Sql.Select("SELECT rut, monto, pagado, (monto - pagado) as saldo, fpago FROM prv_cuentasxpagar \n" +
                           "WHERE monto > pagado and tipdocto IN ('BGA','BOG','CLI','COM','FAG','FAP')  \n"+
                           "AND ( EXTRACT(YEAR FROM fpago) = "+cbAgno.getSelectedItem()+" AND EXTRACT(MONTH FROM fpago) = "+cbMes.getSelectedIndex()+")");
            
            if (Sql.GetRowCount() > 0){
            
                while (Rs.next()){
                   
                    tCxp = tCxp + Rs.getDouble("saldo");
                   
                }
            
            }
            
           
            txCxp.setText("$ "+formateador.format(Math.round(tCxp)));
          
            
        }catch (SQLException ex) {
        
            Logger.getLogger(pfBalanceGeneral.class.getName()).log(Level.SEVERE, null, ex);
        
        }
        
        
        
        
        
    }
        
    
    private void RemxPagar(){
        
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        
        tRxp = 0;
        
        try{
            

           Rs = Sql.Select("SELECT rut, monto, pagado, (monto - pagado) as saldo, fpago FROM prv_cuentasxpagar \n" +
                           "WHERE monto > pagado and tipdocto IN ('REM')  \n"+
                           "AND ( EXTRACT(YEAR FROM fpago) = "+cbAgno.getSelectedItem()+" AND (EXTRACT(MONTH FROM fpago)-1) = "+cbMes.getSelectedIndex()+")");
            
            if (Sql.GetRowCount() > 0){
            
                while (Rs.next()){
                   
                    tRxp = tRxp + Rs.getDouble("saldo");
                   
                }
            
            }
            
           
            txRxp.setText("$ "+formateador.format(Math.round(tRxp)));
          
            
        }catch (SQLException ex) {
        
            Logger.getLogger(pfBalanceGeneral.class.getName()).log(Level.SEVERE, null, ex);
        
        }
        
        
    }
    
    private void HonorariosxPagar(){
        
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        
        tHxp = 0;
        
        try{
            

           Rs = Sql.Select("SELECT rut, monto, pagado, (monto - pagado) as saldo, fpago FROM prv_cuentasxpagar \n" +
                           "WHERE monto > pagado and tipdocto IN ('BOH')  \n"+
                           "AND ( EXTRACT(YEAR FROM fpago) = "+cbAgno.getSelectedItem()+" AND EXTRACT(MONTH FROM fpago) = "+cbMes.getSelectedIndex()+")");
            
            if (Sql.GetRowCount() > 0){
            
                while (Rs.next()){
                   
                    tHxp = tHxp + Rs.getDouble("saldo");
                   
                }
            
            }
            
           
            txHxp.setText("$ "+formateador.format(Math.round(tHxp)));
          
            
        }catch (SQLException ex) {
        
            Logger.getLogger(pfBalanceGeneral.class.getName()).log(Level.SEVERE, null, ex);
        
        }
        
        
    }
    
    
    private void CreditoBancos(){
        
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        
        tCBanc = 0;
        
        try{
            

           Rs = Sql.Select("SELECT rut, monto, pagado, (monto - pagado) as saldo, fpago FROM prv_cuentasxpagar \n" +
                           "WHERE monto > pagado and tipdocto LIKE '%HP%'  \n"+
                           "AND ( EXTRACT(YEAR FROM fpago) = "+cbAgno.getSelectedItem()+" AND EXTRACT(MONTH FROM fpago) = "+cbMes.getSelectedIndex()+")");
            
            if (Sql.GetRowCount() > 0){
            
                while (Rs.next()){
                   
                    tCBanc = tCBanc + Rs.getDouble("saldo");
                   
                }
            
            }
            
           
            txCBancos.setText("$ "+formateador.format(Math.round(tCBanc)));
          
            
        }catch (SQLException ex) {
        
            Logger.getLogger(pfBalanceGeneral.class.getName()).log(Level.SEVERE, null, ex);
        
        }
        
        
    }
    
    private void CotizacionesPrev(){
        
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        
        tCPrev = 0;
        
        try{
            

           Rs = Sql.Select("SELECT rut, monto, pagado, (monto - pagado) as saldo, fpago FROM prv_cuentasxpagar \n" +
                           "WHERE monto > pagado and tipdocto IN ('PRV')  \n"+
                           "AND ( EXTRACT(YEAR FROM fpago) = "+cbAgno.getSelectedItem()+" AND (EXTRACT(MONTH FROM fpago)-1) = "+cbMes.getSelectedIndex()+")");
            
            if (Sql.GetRowCount() > 0){
            
                while (Rs.next()){
                   
                    tCPrev = tCPrev + Rs.getDouble("saldo");
                   
                }
            
            }
            
           
            txCPrev.setText("$ "+formateador.format(Math.round(tCPrev)));
          
            
        }catch (SQLException ex) {
        
            Logger.getLogger(pfBalanceGeneral.class.getName()).log(Level.SEVERE, null, ex);
        
        }
        
        
    } 
    
    
    private void DebitoIVA(){
        
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        
        tDIVA = 0;
        
        try{
            

//           Rs = Sql.Select("SELECT rut, monto, pagado, (monto - pagado) as saldo, fpago FROM prv_cuentasxpagar \n" +
//                           "WHERE monto > pagado and tipdocto IN ('PRV')  \n"+
//                           "AND ( EXTRACT(YEAR FROM fpago) = "+cbAgno.getSelectedItem()+" AND (EXTRACT(MONTH FROM fpago)-1) = "+cbMes.getSelectedIndex()+")");
           
           Rs = Sql.Select("SELECT monto, pagado, (monto - pagado) as saldo, (ROUND((pagado / 1.19)*0.19)) as iva, femision FROM cli_cuentasxcobrar \n" +
                           "WHERE pagado > 0 and tipdocto IN ('BOC','FAC') \n"+
                           "AND (EXTRACT(YEAR FROM femision) = "+cbAgno.getSelectedItem()+" AND EXTRACT(MONTH FROM femision) = "+cbMes.getSelectedIndex()+")");
           
           
            if (Sql.GetRowCount() > 0){
            
                while (Rs.next()){
                   
                    tDIVA = tDIVA + Rs.getDouble("iva");
                   
                }
            
            }
            
           
            txDIVA.setText("$ "+formateador.format(Math.round(tDIVA)));
          
            
        }catch (SQLException ex) {
        
            Logger.getLogger(pfBalanceGeneral.class.getName()).log(Level.SEVERE, null, ex);
        
        }
        
        
    } 
    
    
//***************************************************************************************************************************//
    
    
    private void CuentasxCobrar(){
        
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        
        tCxc = 0;
        
        try{
            

           Rs = Sql.Select("SELECT rut, monto, pagado, (monto - pagado) as saldo, femision FROM cli_cuentasxcobrar \n" +
                           "WHERE monto > pagado and tipdocto IN ('BOC','FAC')  \n"+
                           "AND ( EXTRACT(YEAR FROM femision) = "+cbAgno.getSelectedItem()+" AND EXTRACT(MONTH FROM femision) = "+cbMes.getSelectedIndex()+")");
            
            if (Sql.GetRowCount() > 0){
            
                while (Rs.next()){
                   
                    tCxc = tCxc + Rs.getDouble("saldo");
                   
                }
            
            }
            
           
            txCxc.setText("$ "+formateador.format(Math.round(tCxc)));
          
            
        }catch (SQLException ex) {
        
            Logger.getLogger(pfBalanceGeneral.class.getName()).log(Level.SEVERE, null, ex);
        
        }
        
        
        
        
        
    }
    
    
    
    
    private void txPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPrestamosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPrestamosActionPerformed

    private void btCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCompararActionPerformed
//        
//        jdCompara Comparar = new jdCompara(null, true);
//        Comparar.setLocationRelativeTo(null);
//        Comparar.setTitle("Comparar Formulario 29");
//        Comparar.setVisible(true);
        
    }//GEN-LAST:event_btCompararActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbrir;
    private javax.swing.JButton btComparar;
    private javax.swing.JComboBox<String> cbAgno;
    private javax.swing.JComboBox cbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JTextField txAFamilar;
    private javax.swing.JTextField txCBancos;
    private javax.swing.JTextField txCIVA;
    private javax.swing.JTextField txCPrev;
    private javax.swing.JTextField txCxc;
    private javax.swing.JTextField txCxp;
    private javax.swing.JTextField txDCredito1;
    private javax.swing.JTextField txDCredito3;
    private javax.swing.JTextField txDCredito4;
    private javax.swing.JTextField txDCredito5;
    private javax.swing.JTextField txDCredito6;
    private javax.swing.JTextField txDCredito7;
    private javax.swing.JTextField txDCredito8;
    private javax.swing.JTextField txDCredito9;
    private javax.swing.JTextField txDIVA;
    private javax.swing.JTextField txHxp;
    private javax.swing.JTextField txIVAdet;
    private javax.swing.JTextField txMercaderia;
    private javax.swing.JTextField txPPrev;
    private javax.swing.JTextField txPrestamos;
    private javax.swing.JTextField txRxp;
    private javax.swing.JTextField txSTImpuesto;
    private javax.swing.JTextField txTCreditos;
    private javax.swing.JTextField txTDebitos;
    private javax.swing.JTextField txTdeterm;
    private javax.swing.JTextField txTotal;
    // End of variables declaration//GEN-END:variables
}
