/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Formularios.fmMain;
import java.awt.Font;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David Alcaman
 */
public class pfBlogCobranza1 extends javax.swing.JPanel {

    /**
     * Creates new form pfCXC_Resultados
     */
    public pfBlogCobranza1() {
        initComponents();
         Date date = new Date();
        dtInicio.setDate(date);
        dtFin.setDate(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        Gcobranza = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dtInicio = new org.jdesktop.swingx.JXDatePicker();
        dtFin = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        btCargar = new javax.swing.JButton();

        Gcobranza.setAutoCreateRowSorter(true);
        Gcobranza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USUARIO", "RUT", "FECHA", "DESCRIPCION", "ORDEN", "FECHA COMP", "NRO DOC."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Gcobranza.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane2.setViewportView(Gcobranza);
        if (Gcobranza.getColumnModel().getColumnCount() > 0) {
            Gcobranza.getColumnModel().getColumn(0).setMinWidth(100);
            Gcobranza.getColumnModel().getColumn(0).setPreferredWidth(100);
            Gcobranza.getColumnModel().getColumn(0).setMaxWidth(100);
            Gcobranza.getColumnModel().getColumn(1).setMinWidth(80);
            Gcobranza.getColumnModel().getColumn(1).setPreferredWidth(80);
            Gcobranza.getColumnModel().getColumn(1).setMaxWidth(80);
            Gcobranza.getColumnModel().getColumn(2).setMinWidth(100);
            Gcobranza.getColumnModel().getColumn(2).setPreferredWidth(100);
            Gcobranza.getColumnModel().getColumn(2).setMaxWidth(100);
            Gcobranza.getColumnModel().getColumn(3).setMinWidth(500);
            Gcobranza.getColumnModel().getColumn(3).setPreferredWidth(800);
            Gcobranza.getColumnModel().getColumn(3).setMaxWidth(1000);
            Gcobranza.getColumnModel().getColumn(4).setMinWidth(50);
            Gcobranza.getColumnModel().getColumn(4).setPreferredWidth(50);
            Gcobranza.getColumnModel().getColumn(4).setMaxWidth(50);
            Gcobranza.getColumnModel().getColumn(5).setMinWidth(80);
            Gcobranza.getColumnModel().getColumn(5).setPreferredWidth(80);
            Gcobranza.getColumnModel().getColumn(5).setMaxWidth(80);
            Gcobranza.getColumnModel().getColumn(6).setMinWidth(50);
            Gcobranza.getColumnModel().getColumn(6).setPreferredWidth(50);
            Gcobranza.getColumnModel().getColumn(6).setMaxWidth(50);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "PERIODO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 10))); // NOI18N

        jLabel1.setText("Desde");

        dtInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtInicioActionPerformed(evt);
            }
        });

        jLabel2.setText("Hasta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dtInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dtFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/refresh16.png"))); // NOI18N
        btCargar.setText("Cargar");
        btCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1318, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCargarActionPerformed
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        String Query = "";
        DefaultTableModel ModelBlog   = (DefaultTableModel) Gcobranza.getModel();
        fmMain.LimpiaGrilla(ModelBlog);

        try {

            Query = "SELECT \n" +
            "  usuario,\n" +
            "  rut,\n" +
            "  fecha,\n" +
            "  texto,\n" +
            "  codigo_oc,\n" +
            "  fcompromiso,\n" +
            "  nrodocto\n" +
            "FROM \n" +
            " public.cli_cobranzablog \n" +
            "  where " +
            "  CAST(fcompromiso AS VARCHAR(10)) between  '" + getDesde() + "' and '" + getHasta() + "'\n";
                if (!fmMain.GetUsuarioAdministrador()){
                Query = Query + " and usuario = '" + fmMain.GetUsuario().toLowerCase() + "'";       
                }    
            Rs = Sql.Select(Query);
            
            
            if (!Rs.next()){
                fmMain.Mensaje("No existen Registros");
                return;
            }
            
            while(Rs.next()){

                ModelBlog.addRow(new Object[]{
                    Rs.getString("usuario"),
                    Rs.getInt("rut"),
                    Rs.getString("fecha").trim(),
                    Rs.getString("texto"),
                    Rs.getInt("codigo_oc"),
                    Rs.getString("fcompromiso"),
                    Rs.getInt("nrodocto")});

        }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally{
            Sql.Close();
        }
    }//GEN-LAST:event_btCargarActionPerformed

    private void dtInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtInicioActionPerformed
    

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Gcobranza;
    private javax.swing.JButton btCargar;
    private javax.swing.ButtonGroup buttonGroup1;
    private org.jdesktop.swingx.JXDatePicker dtFin;
    private org.jdesktop.swingx.JXDatePicker dtInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables



public String getDesde() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return( sdf.format( (dtInicio.getDate()).getTime() ) );
    }
    public String getHasta() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return( sdf.format( (dtFin.getDate()).getTime() ) );
    }
   




}
