/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Dialogos.jdBuscaCheques;
import Dialogos.jdBuscarProductos;
import Dialogos.jdIngresoCheque;
import Dialogos.jdIngresoTalonarioCheque;
import Formularios.fmMain;
import Utilidades.TableCellRendererBuscaProducto;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David Alcaman
 */
public class pfCheques extends javax.swing.JPanel {
    int Iniciando;
    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
    
    Calendar fecha = new GregorianCalendar();
    int año = fecha.get(Calendar.YEAR);
    int mes = fecha.get(Calendar.MONTH);
     
    
    
    /**
     * Creates new form pfCheques
     */
    public pfCheques() {
        Iniciando=1;
        initComponents();
        
        String anox ="x";
        int mesx = 0;
        
        anox = String.valueOf(año);
        mesx = mes;

        
        cboAgno.setSelectedItem(anox); 
        cboMes.setSelectedItem(mesx); 
        int i=0;
        boolean esta = false;

        if(cboAgno.getItemCount()-1>0){
        
            for (i=0; i<=cboAgno.getItemCount()-1;i++){
            
                cboAgno.setSelectedIndex(i);
                
                if(anox.equals(String.valueOf( cboAgno.getSelectedItem()))){
                    esta = true;
                    break;
                }

            }
        }
        
        
        if(cboMes.getItemCount()-1>0){
        
            for (i=0; i<=cboMes.getItemCount()-1;i++){
            
                cboMes.setSelectedIndex(i);
                
                if(mesx == cboMes.getSelectedIndex()){
                    esta = true;
                    break;
                }

            }
        }
        
        
        CargaBancos();
        CargaTalonarios();
        cbBancoId.setVisible(false);
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        GrillaCheques.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
        GrillaCheques.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
        GrillaCheques.getColumnModel().getColumn(6).setCellRenderer(rightRenderer);
        GrillaFacturas.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
        
        
        GrillaTalonarios.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            //Se ejecuta automáticamente cada vez que se hace una nueva selección. 
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(GrillaTalonarios.getSelectedRowCount()>0)
                    CargaCheques();
            }

        });
        GrillaCheques.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            //Se ejecuta automáticamente cada vez que se hace una nueva selección. 
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(GrillaCheques.getSelectedRowCount()>0)
                    CargaDoctos(cbBancoId.getSelectedItem().toString(), GrillaCheques.getValueAt(GrillaCheques.getSelectedRow(),0).toString());
            }

        });
        
        CargaDias();
        
        
        Iniciando=0;
        
       
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        cbBanco = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cbBancoId = new javax.swing.JComboBox();
        txBuscar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btIr = new javax.swing.JButton();
        txBuscarP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btIr2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        GrillaCheques = new javax.swing.JTable();
        btAsociarCheque = new javax.swing.JButton();
        btAnulaCheque = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GrillaTalonarios = new javax.swing.JTable();
        btNuevoTalonario = new javax.swing.JButton();
        btEditarTalonario = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        GrillaFacturas = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        GrillaxCobrar = new javax.swing.JTable();
        JLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        JLabel2 = new javax.swing.JLabel();
        cboAgno = new javax.swing.JComboBox<String>();
        cboMes = new javax.swing.JComboBox<String>();

        jMenuItem1.setText("Ver Facturas Pagadas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbBanco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBancoActionPerformed(evt);
            }
        });

        jLabel1.setText("Banco");

        cbBancoId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txBuscar.setToolTipText("");
        txBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txBuscarActionPerformed(evt);
            }
        });
        txBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txBuscarKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("BUSCAR CHEQUE :");

        btIr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/search16.png"))); // NOI18N
        btIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIrActionPerformed(evt);
            }
        });

        txBuscarP.setToolTipText("");
        txBuscarP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txBuscarPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txBuscarPKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("BUSCAR PROVEEDOR :");

        btIr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/search16.png"))); // NOI18N
        btIr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIr2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbBancoId, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btIr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btIr2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btIr2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btIr, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(cbBancoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Cheques"));

        GrillaCheques.setAutoCreateRowSorter(true);
        GrillaCheques.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Emisión", "Destinatario", "Vencimiento", "Monto", "Utilizado", "Disponible", "Conciliado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GrillaCheques.setComponentPopupMenu(jPopupMenu1);
        jScrollPane2.setViewportView(GrillaCheques);
        if (GrillaCheques.getColumnModel().getColumnCount() > 0) {
            GrillaCheques.getColumnModel().getColumn(2).setPreferredWidth(400);
            GrillaCheques.getColumnModel().getColumn(7).setMinWidth(60);
            GrillaCheques.getColumnModel().getColumn(7).setPreferredWidth(60);
            GrillaCheques.getColumnModel().getColumn(7).setMaxWidth(60);
        }

        btAsociarCheque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Pencil16.png"))); // NOI18N
        btAsociarCheque.setToolTipText("Asignar Destinatario");
        btAsociarCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAsociarChequeActionPerformed(evt);
            }
        });

        btAnulaCheque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Cancel16.png"))); // NOI18N
        btAnulaCheque.setToolTipText("Anular Cheque");
        btAnulaCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnulaChequeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAsociarCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAnulaCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(741, 741, 741))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAnulaCheque)
                    .addComponent(btAsociarCheque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Talonarios"));

        GrillaTalonarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Desde", "Hasta", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(GrillaTalonarios);
        if (GrillaTalonarios.getColumnModel().getColumnCount() > 0) {
            GrillaTalonarios.getColumnModel().getColumn(0).setMinWidth(80);
            GrillaTalonarios.getColumnModel().getColumn(0).setPreferredWidth(80);
            GrillaTalonarios.getColumnModel().getColumn(0).setMaxWidth(80);
            GrillaTalonarios.getColumnModel().getColumn(3).setMinWidth(0);
            GrillaTalonarios.getColumnModel().getColumn(3).setPreferredWidth(0);
            GrillaTalonarios.getColumnModel().getColumn(3).setMaxWidth(0);
        }

        btNuevoTalonario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Agregar.png"))); // NOI18N
        btNuevoTalonario.setToolTipText("Nuevo Talonario");
        btNuevoTalonario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoTalonarioActionPerformed(evt);
            }
        });

        btEditarTalonario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Pencil16.png"))); // NOI18N
        btEditarTalonario.setToolTipText("Editar Talonario");
        btEditarTalonario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarTalonarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btNuevoTalonario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEditarTalonario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btNuevoTalonario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEditarTalonario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Facturas Asociadas"));

        GrillaFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Doc", "Número", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(GrillaFacturas);
        if (GrillaFacturas.getColumnModel().getColumnCount() > 0) {
            GrillaFacturas.getColumnModel().getColumn(0).setMinWidth(45);
            GrillaFacturas.getColumnModel().getColumn(0).setPreferredWidth(45);
            GrillaFacturas.getColumnModel().getColumn(0).setMaxWidth(45);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(392, 392, 392))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cheques x Cobrar"));

        GrillaxCobrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Dia", "Monto", "N° Cheques"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GrillaxCobrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaxCobrarMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(GrillaxCobrar);
        if (GrillaxCobrar.getColumnModel().getColumnCount() > 0) {
            GrillaxCobrar.getColumnModel().getColumn(0).setMinWidth(50);
            GrillaxCobrar.getColumnModel().getColumn(0).setPreferredWidth(50);
            GrillaxCobrar.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        JLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JLabel1.setText("MES");
        JLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Total Mes");

        lbTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTotal.setText("0");

        JLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JLabel2.setText("AÑO");
        JLabel2.setToolTipText("");

        cboAgno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035" }));
        cboAgno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboAgnoMouseClicked(evt);
            }
        });
        cboAgno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAgnoActionPerformed(evt);
            }
        });
        cboAgno.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cboAgnoPropertyChange(evt);
            }
        });

        cboMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        cboMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(JLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(JLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(cboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(cboAgno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboAgno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void CargaBancos(){
        ExeSql  Sql = new ExeSql();
        ResultSet Rs;

        cbBanco.removeAllItems();
        cbBancoId.removeAllItems();

        try {
            Rs = Sql.Select("select codigo, banco\n" +
                    "from par_banco\n" +
                    "where codigo > 0 order by codigo asc ");
            while(Rs.next()){
                cbBanco.addItem(Rs.getString("banco").trim());
                cbBancoId.addItem(Rs.getString("codigo"));
                
            }
        } catch (Exception e) {
            fmMain.Mensaje(e.getMessage());
        }finally{
            Sql.Close();
        }
    }
    private void CargaTalonarios(){
        ExeSql Sql = new ExeSql();
        ExeSql Sql2 = new ExeSql();
        ResultSet Rs;
        ResultSet Rs2;
        DefaultTableModel TableModel = (DefaultTableModel) GrillaTalonarios.getModel();
        DefaultTableModel TableModel2 = (DefaultTableModel) GrillaCheques.getModel();
        
        while(TableModel.getRowCount()>0)
                        TableModel.removeRow(0);  
        
        
        //Limpia Grilla de Cheques
        while(TableModel2.getRowCount()>0)
                        TableModel2.removeRow(0);  
        
        
        try {
            
            
            Rs = Sql.Select("select che.talonario from cheques_emitidos che\n" +
                            "left join cheques_talonarios ct on che.talonario = ct.id\n" +
//                            "where (extract(year from che.fvencimiento)>= "+año+" or extract(year from ct.fecha)>= "+año+") \n"+
//                            "and che.cobrado is false\n" +
                            "group by che.talonario, ct.nroini\n" +
                            "order by ct.nroini DESC");
            
            
            
            
            while(Rs.next()){
                
                int id = Rs.getInt("talonario");
                
                Rs2 = Sql2.Select("select *\n" +
                                 "from cheques_talonarios\n" +
                                 "where banco="+ cbBancoId.getSelectedItem().toString().trim() +" and id = "+id+"  \n" +
                                 "order by nroini");
                
                if (Sql2.GetRowCount() > 0){
                
                    Rs2.next();
                    
                    TableModel.addRow(new Object[]{Rs2.getString("fecha").trim(), 
                                                   Rs2.getString("nroini").trim(), 
                                                   Rs2.getString("nrofin").trim(), 
                                                   Rs2.getString("id").trim()
                                                });
                }
            }
            
        } catch (Exception e) {
        
        }finally{
            Sql.Close();
        }
        
    }
    
    private void CargaCheques(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel TableModel = (DefaultTableModel) GrillaCheques.getModel();
        String FEmision,FVencimiento;
        
        while(TableModel.getRowCount()>0)
                        TableModel.removeRow(0);  
        
        try {
            
            
//            Rs = Sql.Select("select c.numero,c.femision, \n" +
//                            "case p.nombre when p.nombre then p.nombre else 'Sin Asociar' end as nombre,c.fvencimiento,c.monto, \n" +
//                            "c.pagado,c.monto+c.pagado as saldo,c.cobrado,c.estado\n" +
//                            "from cheques_emitidos c\n" +
//                            "left join proveedor p on p.rut=c.rut\n" +
//                            "where c.banco=1\n" +
//                            "and c.talonario=" + GrillaTalonarios.getValueAt(GrillaTalonarios.getSelectedRow(),3).toString().trim() + " \n"+ 
//                            "and c.estado = 1 \n" +
//                            "and cobrado = false\n" +
//                            "order by cast(c.numero as integer)");
            
            
            
             Rs = Sql.Select("select c.numero,c.femision, \n" +
                             "case p.nombre when p.nombre then p.nombre else 'Sin Asociar' end as nombre,c.fvencimiento,c.monto, \n" +
                             "c.pagado,c.monto+c.pagado as saldo,c.cobrado,c.estado,c.talonario\n" +
                             "from cheques_emitidos c\n" +
                             "left join proveedor p on p.rut=c.rut\n" +
                             "where c.banco=1 \n"+
                             "and c.talonario=" + GrillaTalonarios.getValueAt(GrillaTalonarios.getSelectedRow(),3).toString().trim() + " \n"+ 
                             "and ((c.monto+c.pagado) > 0 or (c.monto = 0 and c.estado =1))\n" +
                             "order by cast(c.numero as integer)");
            
            
            
            
            while(Rs.next()){
                
                try {
                    FEmision = Rs.getString("femision").trim();
                    FVencimiento = Rs.getString("fvencimiento").trim();
                } catch (Exception e) {
                    FEmision="";
                    FVencimiento="";
                }
                
                //Cheque Asociado
                if(Rs.getInt("Estado")>0 && Rs.getDouble("monto")>=0){
                    
                    TableModel.addRow(new Object[]{Rs.getString("numero").trim(), 
                                                   FEmision, 
                                                   Rs.getString("nombre").trim(), 
                                                   FVencimiento, 
                                                   fmMain.FormatoTotal(Rs.getDouble("monto")),
                                                   fmMain.FormatoTotal(Rs.getDouble("pagado")),
                                                   fmMain.FormatoTotal(Rs.getDouble("saldo")),
                                                   Rs.getBoolean("cobrado")
                                                    });
                //Cheque en blanco
                }else if(Rs.getInt("Estado")>0 && Rs.getDouble("monto")<0){
                    
                    TableModel.addRow(new Object[]{Rs.getString("numero").trim(), 
                                                   FEmision, 
                                                   Rs.getString("nombre").trim(), 
                                                   FVencimiento, 
                                                   "BLANCO",
                                                   "BLANCO",
                                                   "BLANCO",
                                                   Rs.getBoolean("cobrado")
                                                    });
                }else{
                    
                    TableModel.addRow(new Object[]{Rs.getString("numero").trim(), 
                                                   "", 
                                                   "DOCUMENTO NULO", 
                                                   "", 
                                                   "",
                                                   "",
                                                   "",
                                                   true
                                                    });
                    
                }    
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }finally{
            Sql.Close();
        }
    }
    
    
    private void BuscarCheques(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel TableModel = (DefaultTableModel) GrillaCheques.getModel();
        String FEmision,FVencimiento;
        
        while(TableModel.getRowCount()>0)
                        TableModel.removeRow(0);  
        
        try {
            
            
            Rs = Sql.Select("select DISTINCT c.numero,c.femision, \n" +
                            "case p.nombre when p.nombre then p.nombre else 'Sin Asociar' end as nombre,c.fvencimiento,c.monto, \n" +
                            "c.pagado,c.monto+c.pagado as saldo,c.cobrado,c.estado, bc.nrodocumento \n" +
                            "from cheques_emitidos c\n" +
                            "left join proveedor p on p.rut=c.rut\n" +
                            "left join bco_cartola bc on c.numero = bc.nrodocumento \n" +
                           "where c.banco=" + cbBancoId.getSelectedItem().toString() + "\n" +
                            "and c.numero='"+txBuscar.getText().toString().trim()+"' ");
            
            
            while(Rs.next()){
                
                try {
                    FEmision = Rs.getString("femision").trim();
                    FVencimiento = Rs.getString("fvencimiento").trim();
                } catch (Exception e) {
                    FEmision="";
                    FVencimiento="";
                }
                
                //Cheque Asociado
                if(Rs.getInt("Estado")>0 && Rs.getDouble("monto")>=0){
                    
                    TableModel.addRow(new Object[]{Rs.getString("numero").trim(), 
                                                   FEmision, 
                                                   Rs.getString("nombre").trim(), 
                                                   FVencimiento, 
                                                   fmMain.FormatoTotal(Rs.getDouble("monto")),
                                                   fmMain.FormatoTotal(Rs.getDouble("pagado")),
                                                   fmMain.FormatoTotal(Rs.getDouble("saldo")),
                                                   Rs.getBoolean("cobrado")
                                                    });
                //Cheque en blanco
                }else if(Rs.getInt("Estado")>0 && Rs.getDouble("monto")<0){
                    
                    TableModel.addRow(new Object[]{Rs.getString("numero").trim(), 
                                                   FEmision, 
                                                   Rs.getString("nombre").trim(), 
                                                   FVencimiento, 
                                                   "BLANCO",
                                                   "BLANCO",
                                                   "BLANCO",
                                                   Rs.getBoolean("cobrado")
                                                    });
                }else{
                    
                    TableModel.addRow(new Object[]{Rs.getString("numero").trim(), 
                                                   "", 
                                                   "DOCUMENTO NULO", 
                                                   "", 
                                                   "",
                                                   "",
                                                   "",
                                                   true
                                                    });
                    
                }    
            }
            
            
            CargaDoctos(cbBancoId.getSelectedItem().toString(), txBuscar.getText().toString().trim());
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }finally{
            Sql.Close();
        }
    }
    
    
    
    
    
    
    
    private void btNuevoTalonarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoTalonarioActionPerformed
        jdIngresoTalonarioCheque Chq = new jdIngresoTalonarioCheque(null,true);
        Chq.setLocationRelativeTo(null);
        Chq.setTitle("Ingreso de Talonario");
        Chq.CargaDatos(cbBanco.getSelectedItem().toString(), cbBancoId.getSelectedItem().toString());
        Chq.setVisible(true);
        CargaTalonarios();
    }//GEN-LAST:event_btNuevoTalonarioActionPerformed

    private void btEditarTalonarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarTalonarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEditarTalonarioActionPerformed

    private void cbBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBancoActionPerformed
        if(Iniciando==0){
            cbBancoId.setSelectedIndex(cbBanco.getSelectedIndex());
            CargaTalonarios();
        }
            
    }//GEN-LAST:event_cbBancoActionPerformed

    private void btAsociarChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAsociarChequeActionPerformed
        if(GrillaCheques.getSelectedRow()>=0 && GrillaCheques.getValueAt(GrillaCheques.getSelectedRow(), 1).toString().isEmpty()){
            jdIngresoCheque Chq = new jdIngresoCheque(null,true);
            Chq.setLocationRelativeTo(null);
            Chq.setTitle("Emitir Cheque");
            Chq.CargaDatos(cbBanco.getSelectedItem().toString().trim(), cbBancoId.getSelectedItem().toString().trim(), GrillaCheques.getValueAt(GrillaCheques.getSelectedRow(),0).toString().trim());
            Chq.setVisible(true);    
            CargaCheques();
            CargaDias();
        }
        if(GrillaCheques.getSelectedRow()>=0 && GrillaCheques.getValueAt(GrillaCheques.getSelectedRow(), 4).toString().trim().equals("BLANCO")){
            jdIngresoCheque Chq = new jdIngresoCheque(null,true);
            Chq.setLocationRelativeTo(null);
            Chq.setTitle("Emitir Cheque");
            Chq.CargaDatosBlanco(cbBanco.getSelectedItem().toString().trim(), cbBancoId.getSelectedItem().toString().trim(), GrillaCheques.getValueAt(GrillaCheques.getSelectedRow(),0).toString().trim());
            Chq.setVisible(true);    
            CargaCheques();
            CargaDias();
        }
        if(GrillaCheques.getSelectedRow()>=0 && GrillaCheques.getValueAt(GrillaCheques.getSelectedRow(), 5).toString().trim().equals("0")){
            jdIngresoCheque Chq = new jdIngresoCheque(null,true);
            Chq.setLocationRelativeTo(null);
            Chq.setTitle("Emitir Cheque");
            Chq.CargaDatos(cbBanco.getSelectedItem().toString().trim(), cbBancoId.getSelectedItem().toString().trim(), GrillaCheques.getValueAt(GrillaCheques.getSelectedRow(),0).toString().trim());
            Chq.setVisible(true);    
            CargaCheques();
            CargaDias();
        }
        
    }//GEN-LAST:event_btAsociarChequeActionPerformed

    private void btAnulaChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnulaChequeActionPerformed
        if(GrillaCheques.getSelectedRow()>=0){
            if(fmMain.OkCancel("¿Desea Anular el cheque?")== JOptionPane.OK_OPTION){
                ExeSql Sql = new ExeSql();
                ResultSet Rs;
            
                try {
                    
                    Rs = Sql.Select("select fn_anula_cheque("+ cbBancoId.getSelectedItem().toString().trim() +",'"+ GrillaCheques.getValueAt(GrillaCheques.getSelectedRow(),0).toString().trim() +"')");
                    Rs.next();
                    Sql.Commit();
                    if(Rs.getInt("fn_anula_cheque")==2)
                        fmMain.Mensaje("Cheque Anulado. Pagos Reversados");
                    else
                        fmMain.Mensaje("Cheque Anulado");
                    CargaCheques();
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }finally{
                    Sql.Close();
                }
            }
        }
    }//GEN-LAST:event_btAnulaChequeActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         ExeSql SqlAnt = new ExeSql();
        ResultSet RsAnt;
        String qry = "select nrodocto from cheques_emitidos_facturas where numero='"+GrillaCheques.getValueAt(GrillaCheques.getSelectedRow(), 0).toString().trim()+"'";
        
        
            try {
                String muestra="<br>";
                RsAnt = SqlAnt.Select(qry);
                while (RsAnt.next()) {
                    muestra =  muestra+RsAnt.getString("nrodocto").trim()+"<br>"; 
                }
                JOptionPane.showMessageDialog(null, String.format("<html><body>"+muestra+"</body></html>", 150, 150));
              
            } catch (Exception e) {
                fmMain.Mensaje("Error al cargar facturas " + e);
            } finally {
                SqlAnt.Close();
            }
  
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void cboAgnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboAgnoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cboAgnoMouseClicked

    private void cboAgnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAgnoActionPerformed
        año = Integer.parseInt(cboAgno.getSelectedItem().toString().trim());
        CargaDias();
    }//GEN-LAST:event_cboAgnoActionPerformed

    private void cboAgnoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cboAgnoPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_cboAgnoPropertyChange

    private void cboMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMesActionPerformed
        
        if(Iniciando==0){
        
        
            System.out.println("ENTRA A MES!!!!!!!!!!!!!!!!!");
        
            mes = cboMes.getSelectedIndex();
        
            CargaDias();
        
        }

    }//GEN-LAST:event_cboMesActionPerformed

    private void btIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIrActionPerformed

        
        if (txBuscar.getText().isEmpty() || txBuscar.getText().equals("")){
        
            fmMain.Mensaje("Debe ingresar un número...!!");
            return;
            
        
        }
        
        BuscarCheques();
        
        
    }//GEN-LAST:event_btIrActionPerformed

    private void txBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBuscarKeyPressed
       
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
         
             btIr.doClick();
         
         }
        
        
    }//GEN-LAST:event_txBuscarKeyPressed

    private void GrillaxCobrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaxCobrarMouseClicked
        
        if(evt.getClickCount()==2){
        
            jdBuscaCheques Chq = new jdBuscaCheques(null,true);
            Chq.setLocationRelativeTo(null);
            Chq.setTitle("Cheques");
            Chq.CargaDatos( GrillaxCobrar.getValueAt(GrillaxCobrar.getSelectedRow(),0).toString().trim(),
                            cboMes.getSelectedIndex(),
                            cboAgno.getSelectedItem().toString().trim()) ;
            Chq.setVisible(true);    
        }
        
    }//GEN-LAST:event_GrillaxCobrarMouseClicked

    private void txBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txBuscarActionPerformed

    private void btIr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIr2ActionPerformed
        
         if (txBuscarP.getText().isEmpty() || txBuscarP.getText().equals("")){
        
            fmMain.Mensaje("Debe ingresar texto...!!");
            return;
            
        
        }
        
        buscar_prod();
        
        
    }//GEN-LAST:event_btIr2ActionPerformed

    private void txBuscarPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBuscarPKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
         
             btIr2.doClick();
         
         }
        
    }//GEN-LAST:event_txBuscarPKeyPressed

    private void txBuscarPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBuscarPKeyTyped
        
        char keyChar = evt.getKeyChar();
          if (Character.isLowerCase(keyChar)) {
            evt.setKeyChar(Character.toUpperCase(keyChar));
          }
        
    }//GEN-LAST:event_txBuscarPKeyTyped
    
    
    
    
    private String TextoBusqueda(){
        
        String Texto="upper(p.nombre) like '%";
        String Palabras[] = txBuscarP.getText().split(" ");
        
        if(Palabras.length>0){
            
            Texto = Texto + Palabras[0] + "%' ";
            
            for(int i=1; i< Palabras.length; i++){
                Texto = Texto + "or upper(p.nombre) like '%" + Palabras[i] + "%' ";
            }
        }
        else{
            Texto = Texto + txBuscarP.getText() + "%' ";         
        }
        return Texto;
    }
    
   
    
    public void buscar_prod(){
        
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel TableModel = (DefaultTableModel) GrillaCheques.getModel();
        String FEmision,FVencimiento;
        
        while(TableModel.getRowCount()>0)
                        TableModel.removeRow(0);  
        
        

        try {
            
             Rs = Sql.Select("select DISTINCT c.numero,c.femision, \n" +
                             "case p.nombre when p.nombre then p.nombre else 'Sin Asociar' end as nombre,c.fvencimiento,c.monto, \n" +
                             "c.pagado,c.monto+c.pagado as saldo,c.cobrado,c.estado, bc.nrodocumento \n" +
                             "from cheques_emitidos c\n" +
                             "left join proveedor p on p.rut=c.rut\n" +
                             "left join bco_cartola bc on c.numero = bc.nrodocumento \n" +
                             "where  (" + TextoBusqueda() + ") order by c.numero");
            
            while(Rs.next()){
                
                try {
                    FEmision = Rs.getString("femision").trim();
                    FVencimiento = Rs.getString("fvencimiento").trim();
                } catch (Exception e) {
                    FEmision="";
                    FVencimiento="";
                }
                
                //Cheque Asociado
                if(Rs.getInt("Estado")>0 && Rs.getDouble("monto")>=0){
                    
                    TableModel.addRow(new Object[]{Rs.getString("numero").trim(), 
                                                   FEmision, 
                                                   Rs.getString("nombre").trim(), 
                                                   FVencimiento, 
                                                   fmMain.FormatoTotal(Rs.getDouble("monto")),
                                                   fmMain.FormatoTotal(Rs.getDouble("pagado")),
                                                   fmMain.FormatoTotal(Rs.getDouble("saldo")),
                                                   Rs.getBoolean("cobrado")
                                                    });
                //Cheque en blanco
                }else if(Rs.getInt("Estado")>0 && Rs.getDouble("monto")<0){
                    
                    TableModel.addRow(new Object[]{Rs.getString("numero").trim(), 
                                                   FEmision, 
                                                   Rs.getString("nombre").trim(), 
                                                   FVencimiento, 
                                                   "BLANCO",
                                                   "BLANCO",
                                                   "BLANCO",
                                                   Rs.getBoolean("cobrado")
                                                    });
                }else{
                    
                    TableModel.addRow(new Object[]{Rs.getString("numero").trim(), 
                                                   "", 
                                                   "DOCUMENTO NULO", 
                                                   "", 
                                                   "",
                                                   "",
                                                   "",
                                                   true
                                                    });
                    
                }    
            }

          

        } catch (Exception e) {
        }
        finally {
            Sql.Close();
        }
    }
    
    
    
    
    
    
    
    private void CargaDoctos(String Banco,String Documento){
        
        ExeSql Sql = new ExeSql();
        ExeSql Sql2 = new ExeSql();
        ExeSql Sql3 = new ExeSql();
        ResultSet Rs;
        ResultSet Rs2;
        ResultSet Rs3;
        
        DefaultTableModel TableModel = (DefaultTableModel) GrillaFacturas.getModel();
        
        while(TableModel.getRowCount()>0)
              TableModel.removeRow(0);  
        
        try {
            
          

           Rs = Sql.Select("select DISTINCT bc.id, bc.nrodocumento, cpp.tipdocto, cpp.nrodocto, cpp.monto from bco_cartola bc\n" +
                           "left join prv_pagos pv on bc.id = pv.id_cartola\n" +
                           "left join prv_cuentasxpagar cpp on pv.cuenta = cpp.id\n" +
                            "where bc.nrodocumento in ('"+Documento+"') and cpp.tipdocto in ('FAP','REM','FIN') ");
           
            
           if (Sql.GetRowCount() > 0){
            
                while(Rs.next()){
                    TableModel.addRow(new Object[]{ Rs.getString("tipdocto").trim(), 
                                                Rs.getString("nrodocto").trim(), 
                                                fmMain.FormatoTotal(Rs.getInt("monto"))
                                                });
                }
            
           }
            
            Rs2 = Sql2.Select("select DISTINCT c.numero, case when cp.tipdocto is null then '' else cp.tipdocto end as tipo,\n" +
                              "case when cp.nrodocto is null then 0 else cp.nrodocto end as nro ,\n" +
                              "case when cp.totaldocto is null then 0 else cp.totaldocto end as monto \n" +
                              "from cheques_emitidos_facturas c\n" +
                              "left join ctacteprv cp on c.nrodocto = cp.nrodocto and c.tipodoc = cp.tipdocto and c.rut = cp.rut\n" +
                              "where cp.tipdocto in ('OCP') and c.numero in ('"+Documento+"')");
            
            
            
            if (Sql2.GetRowCount() > 0){
            
                while(Rs2.next()){
                    TableModel.addRow(new Object[]{ Rs2.getString("tipo").trim(), 
                                                Rs2.getString("nro").trim(), 
                                                fmMain.FormatoTotal(Rs2.getInt("monto"))
                                                });
                }
            }else {
            
                
                Rs3 = Sql3.Select("select * from cheques_emitidos_facturas \n" +
                                   "where numero in ('"+Documento+"')");
                
                
                if (Sql3.GetRowCount() > 0){
                
                    
                    while(Rs3.next()){
                    
                        TableModel.addRow(new Object[]{ Rs3.getString("tipodoc").trim(), 
                                                Rs3.getString("nrodocto").trim(), 
                                                " "
                                                });
                    }
                    
                    
                    
                
                
                }
            
            
            
            }
            
            
        } catch (SQLException e) {
            fmMain.Mensaje(e.getMessage());
            Logger.getLogger(pfCheques.class.getName()).log(Level.SEVERE, null, e);
        }finally{
            Sql.Close();
        }
    }

    
    private void CargaDias(){
        
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel TableModel = (DefaultTableModel) GrillaxCobrar.getModel();
        
        String Query = "";
        Double Total = 0.0;
     
        
        while(TableModel.getRowCount()>0) 
              TableModel.removeRow(0);     
        
        try {
            
//            Query = "select che.fvencimiento, extract(day from che.fvencimiento) as dia, sum(che.monto) as total, count(che.fvencimiento) as cheques from cheques_emitidos che\n" +
//                    "left join bco_cartola bc on che.numero = bc.nrodocumento\n" +
//                    "where extract(year from che.fvencimiento)= "+año+" \n" +
//                    "and extract(month from che.fvencimiento)= "+(mes+1)+" \n" +
//                    "and bc.nrodocumento is null\n" +
//                    "group by che.fvencimiento, extract(day from che.fvencimiento)\n" +
//                    "order by che.fvencimiento";
            
            
             Query = "select che.fvencimiento, extract(day from che.fvencimiento) as dia, sum(che.monto) as total, count(che.fvencimiento) as cheques from cheques_emitidos che\n" +
                     "where extract(year from che.fvencimiento)= "+año+" \n" +
                    "and extract(month from che.fvencimiento)= "+(mes+1)+" \n" +
                    "and che.cobrado is false\n" +
                    "group by che.fvencimiento, extract(day from che.fvencimiento)\n" +
                    "order by che.fvencimiento";
            
            
            
            Rs = Sql.Select(Query);
            
            
            while (Rs.next()){
                
                TableModel.addRow(new Object[]{Rs.getString("dia").trim(),"$ "+fmMain.FormatoTotal(Rs.getDouble("total")),Rs.getInt("cheques") });
                
                Total  = Total  + Math.round(Rs.getDouble("total")) ;
                
            }
            
            lbTotal.setText("$ "+fmMain.FormatoTotal(Total));
             
        } catch (SQLException e) {
            
            JOptionPane.showMessageDialog(null, e);  
            Logger.getLogger(pf_Compras_Cliente.class.getName()).log(Level.SEVERE, null, e);
        
        } finally{
            Sql.Close();
        }
    
    
    
    
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GrillaCheques;
    private javax.swing.JTable GrillaFacturas;
    private javax.swing.JTable GrillaTalonarios;
    private javax.swing.JTable GrillaxCobrar;
    private javax.swing.JLabel JLabel1;
    private javax.swing.JLabel JLabel2;
    private javax.swing.JButton btAnulaCheque;
    private javax.swing.JButton btAsociarCheque;
    private javax.swing.JButton btEditarTalonario;
    private javax.swing.JButton btIr;
    private javax.swing.JButton btIr2;
    private javax.swing.JButton btNuevoTalonario;
    private javax.swing.JComboBox cbBanco;
    private javax.swing.JComboBox cbBancoId;
    private javax.swing.JComboBox<String> cboAgno;
    private javax.swing.JComboBox<String> cboMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTextField txBuscar;
    private javax.swing.JTextField txBuscarP;
    // End of variables declaration//GEN-END:variables
}
