/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Dialogos.jdBuscarCliPrv;
import Dialogos.jdPagadoPrvCli;
import Dialogos.jdPagarPrv;
import Formularios.fmMain;
import static Formularios.fmMain.pnPestanas;
import Utilidades.Exporter;
import Utilidades.PanelTab;
import java.awt.event.KeyEvent;
import java.io.File;
import java.math.BigInteger;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.JComboBox;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/**
 *
 * @author David Alcaman
 */
public class pfConvenios extends javax.swing.JPanel {
    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
    private int w;
    String  clave_convenio="";    
    String clave_linea=""; 
    /**
     * Creates new form pfReportePagosPrv
     */
    public pfConvenios() {
    
    String Query ="";    
        initComponents();
        CargaConvenio();
        CboConvenio.setEnabled(true);
        txConvenio.setEnabled(false);
        CboLinea.setEnabled(false);
        txLinea.setEnabled(false);
        CboSubLine.setEnabled(false);
        txSubLinea.setEnabled(false);
                
        
        
        CboConvenio.setSelectedIndex(0);
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
//        Grilla.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
            
         // Enlaza Grilla con Grilla
//          Grilla.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
//        @Override
//       public void valueChanged(ListSelectionEvent e){
//           if (Grilla.getSelectedRowCount()>0)
//               Carga_Detalle_separacion(Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString().trim(),Grilla.getValueAt(Grilla.getSelectedRow(), 1).toString().trim(),Grilla.getValueAt(Grilla.getSelectedRow(), 2).toString().trim());
//       } 
//    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        CboConvenio = new javax.swing.JComboBox<String>();
        lblUsuario = new javax.swing.JLabel();
        CboLinea = new javax.swing.JComboBox<String>();
        lblUsuario1 = new javax.swing.JLabel();
        lblUsuario2 = new javax.swing.JLabel();
        txConvenio = new javax.swing.JTextField();
        txLinea = new javax.swing.JTextField();
        txSubLinea = new javax.swing.JTextField();
        CboSubLine = new javax.swing.JComboBox<String>();
        btConv = new javax.swing.JButton();
        btLinea = new javax.swing.JButton();
        btSublinea = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PROVEEDOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        CboConvenio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Nuevo>" }));
        CboConvenio.setName("CboConvenio"); // NOI18N
        CboConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboConvenioActionPerformed(evt);
            }
        });

        lblUsuario.setText("Convenio");

        CboLinea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Nuevo>" }));
        CboLinea.setName("CboConvenio"); // NOI18N
        CboLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboLineaActionPerformed(evt);
            }
        });

        lblUsuario1.setText("Linea");

        lblUsuario2.setText("Sub Linea");

        txConvenio.setEnabled(false);
        txConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txConvenioActionPerformed(evt);
            }
        });
        txConvenio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txConvenioKeyReleased(evt);
            }
        });

        txLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txLineaActionPerformed(evt);
            }
        });
        txLinea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txLineaKeyReleased(evt);
            }
        });

        txSubLinea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txSubLineaKeyReleased(evt);
            }
        });

        CboSubLine.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Nuevo>" }));
        CboSubLine.setName("CboConvenio"); // NOI18N
        CboSubLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboSubLineActionPerformed(evt);
            }
        });

        btConv.setText("Graba Convenio");
        btConv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConvActionPerformed(evt);
            }
        });

        btLinea.setText("Graba Linea");
        btLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLineaActionPerformed(evt);
            }
        });

        btSublinea.setText("Graba SubLinea");
        btSublinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSublineaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblUsuario)
                        .addGap(42, 42, 42)
                        .addComponent(CboConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblUsuario1)
                        .addGap(63, 63, 63)
                        .addComponent(CboLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblUsuario2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CboSubLine, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txConvenio, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addComponent(txLinea)
                    .addComponent(txSubLinea))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btConv)
                    .addComponent(btLinea)
                    .addComponent(btSublinea))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(CboConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConv))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario1)
                    .addComponent(CboLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLinea))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario2)
                    .addComponent(txSubLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CboSubLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSublinea))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1662, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );

        jPanel3.getAccessibleContext().setAccessibleName("CONVENIIOS");
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void CargaConvenio(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        String f ="";
        CboConvenio.removeAllItems();
        CboLinea.removeAllItems();
        CboSubLine.removeAllItems();
        CboConvenio.addItem("<Nuevo>");  // Agrego la condicion inicial de Todos
        try {
            Rs = Sql.Select("select * from par_convenio order by cod");
            if(Sql.GetRowCount()==0) return;
     
           while(Rs.next()){
          f= Rs.getString("codigo").trim() + "-" + Rs.getString("convenio").trim();
            CboConvenio.addItem( f);
  } 
           
           CboConvenio.setSelectedIndex(0);

           
           
        } catch (Exception e) {
            System.out.println(e);
        }
        finally{
            Sql.Close();
        }
    }
    
    
    
    private void CargaCombo(JComboBox Cbo, String Query ){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        String f ="";
        Cbo.removeAllItems();
        Cbo.addItem("<Nuevo>");  // Agrego la condicion inicial de Todos
        try {
            Rs = Sql.Select(Query);
            if(Sql.GetRowCount()==0) return;
     
           while(Rs.next()){
                f= Rs.getString(1).trim() + "-" + Rs.getString(2).trim();
            Cbo.addItem( f);
  } 
           
           Cbo.setSelectedIndex(0);

           
           
        } catch (Exception e) {
            System.out.println(e);
        }
        finally{
            Sql.Close();
        }
    }
    
    
    
    
   
    
    private void CboConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboConvenioActionPerformed
      
      
      ExeSql Sql = new ExeSql();
      ResultSet Rs;
      String Query="";
          
try {
     String nombrePalabra1="";
      if(CboConvenio.getSelectedIndex() >0){
                 CboLinea.setEnabled(true);
                 txConvenio.setEnabled(false);
                nombrePalabra1 =CboConvenio.getSelectedItem().toString();
                int j;
                j=0;
                 for(int i=0; i <nombrePalabra1.length(); i++ ){
                   if( nombrePalabra1.charAt(i)== '-'){
                       System.out.println("Clave = " + nombrePalabra1.substring(0,j));
                       System.out.println("Convenio = " + nombrePalabra1.substring(j+1,nombrePalabra1.length()));
                       j=i;
                       clave_convenio =nombrePalabra1.substring(0,j).trim();
                      break;
                   }
                 }
               Query = "select l.codigo, l.linea from par_linea l\n" +
               "where l.convenio = " +  clave_convenio + " order by l.codigo;";
                CargaCombo(CboLinea, Query);
                
              
                
                
                
        }
        else
      {
          txConvenio.setEnabled(true);
                  
      }
   }
catch (Exception e) {
            fmMain.Mensaje("Existe una inconsistencia en la información.");
        }finally{
            Sql.Close();
        }        
    }//GEN-LAST:event_CboConvenioActionPerformed

    private void CboLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboLineaActionPerformed
      ExeSql Sql = new ExeSql();
      ResultSet Rs;
      String Query="";
         
try {
     String nombrePalabra1="";
      if(CboLinea.getSelectedIndex() >0){
                CboSubLine.setEnabled(true);
                txLinea.setEnabled(false);
                nombrePalabra1 =CboLinea.getSelectedItem().toString();
                int j;
                j=0;
                 for(int i=0; i <nombrePalabra1.length(); i++ ){
                   if( nombrePalabra1.charAt(i)== '-'){
                       System.out.println("Codigo = " + nombrePalabra1.substring(0,j).trim());
                       System.out.println("La palabra clave es " + nombrePalabra1.substring(j+1,nombrePalabra1.length()).trim() );
                       j=i;
                       clave_linea =nombrePalabra1.substring(0,j).trim();
                      break;
                   }
                 }
               Query = "select l.linea, l.sublinea from par_sublinea l\n" +
               "where l.linea = " +  clave_linea + " order by l.cod;";
                CargaCombo(CboSubLine, Query);
        }
        else
      {
           txLinea.setEnabled(true);
      }
   }
catch (Exception e) {
            fmMain.Mensaje("Existe una inconsistencia en la información.");
        }finally{
            Sql.Close();
        }                // TODO add your handling code here:
    }//GEN-LAST:event_CboLineaActionPerformed

    private void CboSubLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboSubLineActionPerformed
      ExeSql Sql = new ExeSql();
      ResultSet Rs;
      String Query="";
      String clave="";    
try {
     String nombrePalabra1="";
      if(CboSubLine.getSelectedIndex() >0){
                txSubLinea.setEnabled(false);
        }
        else
      {
           txSubLinea.setEnabled(true);
      }
   }
catch (Exception e) {
            fmMain.Mensaje("Existe una inconsistencia en la información.");
        }finally{
            Sql.Close();
        }         
    }//GEN-LAST:event_CboSubLineActionPerformed

    private void txConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txConvenioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txConvenioActionPerformed

    private void txConvenioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txConvenioKeyReleased
         txConvenio.setText(txConvenio.getText().toUpperCase());// TODO add your handling code here:
    }//GEN-LAST:event_txConvenioKeyReleased

    private void txLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txLineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txLineaActionPerformed

    private void txLineaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txLineaKeyReleased
        txLinea.setText(txLinea.getText().toUpperCase());
    }//GEN-LAST:event_txLineaKeyReleased

    private void txSubLineaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSubLineaKeyReleased
      txSubLinea.setText(txSubLinea.getText().toUpperCase());
    }//GEN-LAST:event_txSubLineaKeyReleased

    private void btConvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConvActionPerformed
    ExeSql Sql = new ExeSql();
      ResultSet Rs;
      String Query="";
      String clave="";    
      int cod =0;
      String CodS= "";
try {
            Query = "select max(cod) from par_convenio \n";
            Rs = Sql.Select(Query);
            if(Sql.GetRowCount()==0) return;
     
            if (Rs.next()){
                cod= Integer.parseInt(Rs.getString(1).trim());
                cod = cod+1;
                CodS= String.valueOf(cod);}
                
            Query = "insert into par_convenio(convenio,cod)\n" +
                        "values('"+ txConvenio.getText().trim() +"','"+ CodS + "');";
            
            Sql.ExeSql(Query);
            Sql.Commit();
            CargaConvenio();
            fmMain.Mensaje("Convenio Creado Exitosamente");
            
   }
catch (Exception e) {
            fmMain.Mensaje("Existe una inconsistencia en la información.");
        }finally{
            Sql.Close();
        }         
    }//GEN-LAST:event_btConvActionPerformed

    private void btLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLineaActionPerformed
      ExeSql Sql = new ExeSql();
      ResultSet Rs;
      String Query="";
 
      int cod =0;
      String CodS= "";
try {
            Query = "select max(cod) from par_linea where convenio = " + clave_convenio + "\n";
            Rs = Sql.Select(Query);
            
            if(Sql.GetRowCount()==0){
                CodS = "01";
            }
     
            if (Rs.next()){
               CodS = Rs.getString(1);
               if (CodS == null) {
                cod =0;}
               else{
                cod= Integer.parseInt(Rs.getString(1).trim());
               }
                cod = cod+1;
                CodS= String.valueOf(cod);
            
               if (cod <=9 ){
                   CodS = "0" + cod;
               }
            }
            
            
            
            
            Query = "insert into par_linea(linea,cod,convenio)\n" +
             "values('"+ txLinea.getText().trim() +"','"+ CodS + "'," + clave_convenio +");";

            Sql.ExeSql(Query);
            Sql.Commit();
            // Recarga el combo con el nuevo dato
             Query = "select l.codigo, l.linea from par_linea l\n" +
            "where l.convenio = " +  clave_convenio + " order by l.codigo;";
             CargaCombo(CboLinea, Query);
            
            fmMain.Mensaje("Linea Creado Exitosamente");
            
   }
catch (Exception e) {
            fmMain.Mensaje("Existe una inconsistencia en la información.");
        }finally{
            Sql.Close();
        }         
    
    }//GEN-LAST:event_btLineaActionPerformed

    private void btSublineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSublineaActionPerformed
  ExeSql Sql = new ExeSql();
      ResultSet Rs;
      String Query="";
 
      int cod =0;
      String CodS= "";
try {
            Query = "select max(cod) from par_sublinea where linea =" + clave_linea + "\n";
            Rs = Sql.Select(Query);
            if(Sql.GetRowCount()==0){
                CodS = "01";
            };
     
            if (Rs.next()){
               CodS = Rs.getString(1);
               if (CodS == null) {
                cod =0;}
               else{
                cod= Integer.parseInt(Rs.getString(1).trim());
               }
                cod = cod+1;
                CodS= String.valueOf(cod);
            
               if (cod <=9 ){
                   CodS = "0" + cod;
               }
            }
               
            
            Query = "insert into par_sublinea(linea,sublinea,cod,contador)\n" +
             "values(" + clave_linea + ",'"+ txSubLinea.getText().trim() +"','"+ CodS + "'," + "0" +");";

            Sql.ExeSql(Query);
            Sql.Commit();
            // Recarga la Sublinea con el nuevo dato 
            Query = "select l.linea, l.sublinea from par_sublinea l\n" +
            "where l.linea = " +  clave_linea + " order by l.cod;";
            CargaCombo(CboSubLine, Query);
            fmMain.Mensaje("Sublinea Creado Exitosamente");
            
   }
catch (Exception e) {
            fmMain.Mensaje("Existe una inconsistencia en la información.");
        }finally{
            Sql.Close();
        }         
    
    }//GEN-LAST:event_btSublineaActionPerformed
//6700

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboConvenio;
    private javax.swing.JComboBox<String> CboLinea;
    private javax.swing.JComboBox<String> CboSubLine;
    private javax.swing.JButton btConv;
    private javax.swing.JButton btLinea;
    private javax.swing.JButton btSublinea;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel lblUsuario2;
    private javax.swing.JTextField txConvenio;
    private javax.swing.JTextField txLinea;
    private javax.swing.JTextField txSubLinea;
    // End of variables declaration//GEN-END:variables

   

   
}