/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Dialogos.jdOC_PendientesFac;
import Formularios.fmMain;
import static Formularios.fmMain.Mensaje;
import static Formularios.fmMain.pnPestanas;
import static PanelForm.pfReporteMercadoPublico.BLACK_GRAY;
import static PanelForm.pfReporteMercadoPublico.DARK_GREEN;
import Utilidades.CargaGrilla;
import Utilidades.ComboCodigos;
import Utilidades.Exporter;
import Utilidades.LogError;
import Utilidades.PanelTab;
import Utilidades.Utl_Excel;
import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import static javax.swing.SwingConstants.CENTER;
import static javax.swing.SwingConstants.LEADING;
import static javax.swing.SwingConstants.RIGHT;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author David Alcaman
 */
public class pfControlInventario_resp extends javax.swing.JPanel {
    int BigCont=0;
    int contselec = 0;
    int contselec2 = 0;
    String Rut_Asoc = "";
    
    ArrayList<ArrayList<String>> Lista  = new ArrayList<ArrayList<String>>();
    ArrayList<ArrayList<String>> Lista2  = new ArrayList<ArrayList<String>>();
    /**
     * Creates new form pfControlInventario
     */
    public pfControlInventario_resp() {
        initComponents();
        CargaConvenios();
        CargaProveedor();
        
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        //jLabel6.setVisible(false);
        //txCadena.setVisible(false);
        
        txBuscarCodigo.setVisible(false);
        txBuscarNombre.setVisible(false);
        jButton1.setVisible(false);
        
        cbIdConvenio.setVisible(false);
        cbIdProveedor.setVisible(false);
        cbProveedor.setVisible(false);
        chk_ult_proveedor.setVisible(false);
       
        jPanel3.setVisible(false);
        
        btAsociar.setVisible(false);
        btAsociar_otro.setVisible(false);
        
        Grilla.getTableHeader().setFont(new Font("Arial", Font.BOLD, 9));
        GrillaPrv.getTableHeader().setFont(new Font("Arial", Font.BOLD, 9));
        
        Grilla.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            //Se ejecuta automáticamente cada vez que se hace una nueva selección. 
            @Override
            public void valueChanged(ListSelectionEvent e) {
                
                if(Grilla.getSelectedRowCount()>0)
                   CargaProveedores();
                  // CodigosChileMat();
                    
            }

        });
        
        
        System.out.println("LOS ELEMENTOS SON : "+Grilla.getRowCount());
        
        
        
//        GrillaPrv.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
//            //Se ejecuta automáticamente cada vez que se hace una nueva selección. 
//            @Override
//            public void valueChanged(ListSelectionEvent e) {
//                if(GrillaPrv.getSelectedRowCount()>0)
//                  
//                  CodigosChileMat_2();
//                    
//            }
//
//        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMenu = new javax.swing.JPanel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbSaldos = new javax.swing.JComboBox();
        btCargar = new javax.swing.JButton();
        lbContProductos = new javax.swing.JLabel();
        cbConvenio = new javax.swing.JComboBox<String>();
        txBuscarCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txBuscarNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txBuscarProveedor = new javax.swing.JTextField();
        btLimpiar = new javax.swing.JButton();
        chk_ult_proveedor = new javax.swing.JCheckBox();
        btCrearOCP = new javax.swing.JButton();
        btIr = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        GrillaPrv = new javax.swing.JTable();
        btAsociar = new javax.swing.JButton();
        btAsociar_otro = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        GrillaChilemat = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbProveedor = new javax.swing.JComboBox<String>();
        cbIdProveedor = new javax.swing.JComboBox<String>();
        cbIdConvenio = new javax.swing.JComboBox<String>();
        txCadena = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnMenu.setBackground(new java.awt.Color(220, 215, 226));

        jXLabel1.setForeground(new java.awt.Color(0, 51, 0));
        jXLabel1.setText("CONTROL DE INVENTARIO");
        jXLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout pnMenuLayout = new javax.swing.GroupLayout(pnMenu);
        pnMenu.setLayout(pnMenuLayout);
        pnMenuLayout.setHorizontalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(750, Short.MAX_VALUE))
        );
        pnMenuLayout.setVerticalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        add(pnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Saldos");

        cbSaldos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Negativos", "Positivos", "Todos" }));
        cbSaldos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSaldosActionPerformed(evt);
            }
        });

        btCargar.setText("Cargar");
        btCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCargarActionPerformed(evt);
            }
        });

        lbContProductos.setText("0 Productos");

        cbConvenio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Convenio" }));
        cbConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbConvenioActionPerformed(evt);
            }
        });

        txBuscarCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txBuscarCodigoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txBuscarCodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txBuscarCodigoKeyTyped(evt);
            }
        });

        jLabel3.setText("Código Producto");

        jLabel4.setText("Nombre Producto");

        txBuscarNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txBuscarNombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txBuscarNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txBuscarNombreKeyTyped(evt);
            }
        });

        jLabel5.setText(" Proveedor");

        txBuscarProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txBuscarProveedorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txBuscarProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txBuscarProveedorKeyTyped(evt);
            }
        });

        btLimpiar.setText("LIMPIAR");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        chk_ult_proveedor.setSelected(true);
        chk_ult_proveedor.setText("Rut Ult Proveedor");
        chk_ult_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_ult_proveedorActionPerformed(evt);
            }
        });

        btCrearOCP.setText("Crear OCP");
        btCrearOCP.setToolTipText("");
        btCrearOCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearOCPActionPerformed(evt);
            }
        });

        btIr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/search.png"))); // NOI18N
        btIr.setBorderPainted(false);
        btIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbSaldos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chk_ult_proveedor)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(txBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btIr, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addComponent(cbConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbContProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66)
                .addComponent(btCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCrearOCP, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(443, 443, 443))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbSaldos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbContProductos))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btIr, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(txBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btCrearOCP, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chk_ult_proveedor)
                            .addComponent(jLabel4)
                            .addComponent(txBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 1353, 110));

        Grilla.setAutoCreateRowSorter(true);
        Grilla.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "PROVEEDOR", "UM", "INV.", "OCP", "OCC", "GUIAS", "TOTAL", "-Fecha", "-DIAS", "PROVEEDOR ASOCIADO", "DIAS CLIENTES", "Min.", "null", "null", "null", "tipo_vend", "borrar", "ocp", "rut"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, true, true, true, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        Grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaMouseClicked(evt);
            }
        });
        Grilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GrillaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(0).setMinWidth(70);
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(70);
            Grilla.getColumnModel().getColumn(0).setMaxWidth(70);
            Grilla.getColumnModel().getColumn(1).setMinWidth(180);
            Grilla.getColumnModel().getColumn(1).setPreferredWidth(180);
            Grilla.getColumnModel().getColumn(1).setMaxWidth(250);
            Grilla.getColumnModel().getColumn(2).setMinWidth(50);
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(50);
            Grilla.getColumnModel().getColumn(2).setMaxWidth(300);
            Grilla.getColumnModel().getColumn(3).setMinWidth(0);
            Grilla.getColumnModel().getColumn(3).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(3).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(4).setMinWidth(40);
            Grilla.getColumnModel().getColumn(4).setPreferredWidth(40);
            Grilla.getColumnModel().getColumn(4).setMaxWidth(40);
            Grilla.getColumnModel().getColumn(5).setMinWidth(50);
            Grilla.getColumnModel().getColumn(5).setPreferredWidth(50);
            Grilla.getColumnModel().getColumn(5).setMaxWidth(50);
            Grilla.getColumnModel().getColumn(6).setMinWidth(50);
            Grilla.getColumnModel().getColumn(6).setPreferredWidth(50);
            Grilla.getColumnModel().getColumn(6).setMaxWidth(50);
            Grilla.getColumnModel().getColumn(7).setMinWidth(50);
            Grilla.getColumnModel().getColumn(7).setPreferredWidth(50);
            Grilla.getColumnModel().getColumn(7).setMaxWidth(50);
            Grilla.getColumnModel().getColumn(8).setMinWidth(50);
            Grilla.getColumnModel().getColumn(8).setPreferredWidth(50);
            Grilla.getColumnModel().getColumn(8).setMaxWidth(50);
            Grilla.getColumnModel().getColumn(9).setMinWidth(0);
            Grilla.getColumnModel().getColumn(9).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(9).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(10).setMinWidth(0);
            Grilla.getColumnModel().getColumn(10).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(10).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(11).setMinWidth(65);
            Grilla.getColumnModel().getColumn(11).setPreferredWidth(65);
            Grilla.getColumnModel().getColumn(11).setMaxWidth(300);
            Grilla.getColumnModel().getColumn(12).setMinWidth(0);
            Grilla.getColumnModel().getColumn(12).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(12).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(13).setMinWidth(40);
            Grilla.getColumnModel().getColumn(13).setPreferredWidth(40);
            Grilla.getColumnModel().getColumn(13).setMaxWidth(40);
            Grilla.getColumnModel().getColumn(14).setMinWidth(0);
            Grilla.getColumnModel().getColumn(14).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(14).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(15).setMinWidth(0);
            Grilla.getColumnModel().getColumn(15).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(15).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(16).setMinWidth(0);
            Grilla.getColumnModel().getColumn(16).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(16).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(17).setMinWidth(0);
            Grilla.getColumnModel().getColumn(17).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(17).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(18).setMinWidth(0);
            Grilla.getColumnModel().getColumn(18).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(18).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(19).setMinWidth(35);
            Grilla.getColumnModel().getColumn(19).setPreferredWidth(35);
            Grilla.getColumnModel().getColumn(19).setMaxWidth(35);
            Grilla.getColumnModel().getColumn(20).setMinWidth(0);
            Grilla.getColumnModel().getColumn(20).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(20).setMaxWidth(0);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 191, 880, 490));

        GrillaPrv.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        GrillaPrv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "FECHA", "PROVEEDOR", "PROVEEDOR ASOCIADO", "VALOR", "RUT", " "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GrillaPrv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaPrvMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(GrillaPrv);
        if (GrillaPrv.getColumnModel().getColumnCount() > 0) {
            GrillaPrv.getColumnModel().getColumn(0).setMinWidth(80);
            GrillaPrv.getColumnModel().getColumn(0).setPreferredWidth(80);
            GrillaPrv.getColumnModel().getColumn(0).setMaxWidth(80);
            GrillaPrv.getColumnModel().getColumn(1).setMinWidth(0);
            GrillaPrv.getColumnModel().getColumn(1).setPreferredWidth(0);
            GrillaPrv.getColumnModel().getColumn(1).setMaxWidth(0);
            GrillaPrv.getColumnModel().getColumn(2).setPreferredWidth(250);
            GrillaPrv.getColumnModel().getColumn(3).setResizable(false);
            GrillaPrv.getColumnModel().getColumn(3).setPreferredWidth(85);
            GrillaPrv.getColumnModel().getColumn(5).setMinWidth(35);
            GrillaPrv.getColumnModel().getColumn(5).setPreferredWidth(35);
            GrillaPrv.getColumnModel().getColumn(5).setMaxWidth(35);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 190, 462, 260));

        btAsociar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/copy.png"))); // NOI18N
        btAsociar.setText("Asociar Código Proveedor");
        btAsociar.setToolTipText("");
        btAsociar.setEnabled(false);
        btAsociar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAsociarActionPerformed(evt);
            }
        });
        add(btAsociar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 630, 180, 40));

        btAsociar_otro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/copy.png"))); // NOI18N
        btAsociar_otro.setText("Asociar Codigo otro Proveedor");
        btAsociar_otro.setToolTipText("");
        btAsociar_otro.setEnabled(false);
        btAsociar_otro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAsociar_otroActionPerformed(evt);
            }
        });
        add(btAsociar_otro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 630, 200, 40));

        GrillaChilemat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sku", "Cod. Prv.", "Nombre", "Cant", "rutprv_asoc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GrillaChilemat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GrillaChilematKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(GrillaChilemat);
        if (GrillaChilemat.getColumnModel().getColumnCount() > 0) {
            GrillaChilemat.getColumnModel().getColumn(0).setMinWidth(60);
            GrillaChilemat.getColumnModel().getColumn(0).setPreferredWidth(60);
            GrillaChilemat.getColumnModel().getColumn(0).setMaxWidth(60);
            GrillaChilemat.getColumnModel().getColumn(1).setMinWidth(90);
            GrillaChilemat.getColumnModel().getColumn(1).setPreferredWidth(90);
            GrillaChilemat.getColumnModel().getColumn(1).setMaxWidth(90);
            GrillaChilemat.getColumnModel().getColumn(3).setMinWidth(45);
            GrillaChilemat.getColumnModel().getColumn(3).setPreferredWidth(45);
            GrillaChilemat.getColumnModel().getColumn(3).setMaxWidth(45);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Codigos para Chilemat");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 480, 470, 140));

        cbProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Proveedor" }));
        cbProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProveedorActionPerformed(evt);
            }
        });
        add(cbProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 690, -1, -1));

        cbIdProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "rut proveedor" }));
        cbIdProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIdProveedorActionPerformed(evt);
            }
        });
        add(cbIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 690, -1, -1));

        cbIdConvenio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "id convenio" }));
        add(cbIdConvenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 690, -1, -1));

        txCadena.setEnabled(false);
        txCadena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txCadenaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txCadenaKeyReleased(evt);
            }
        });
        add(txCadena, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 390, -1));

        jLabel6.setText("BUSCAR");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 60, 20));

        jButton1.setText("Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 690, 125, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCargarActionPerformed
        TableRowSorter<TableModel>sorter = new TableRowSorter<TableModel>(Grilla.getModel());   //Se crea un Modelo para filtrar la Tabla
        Grilla.setRowSorter(sorter);     //Se filtra la Tabla de acuerdo al Modelo
        sorter.setRowFilter(null);      
        
    //************************************************************************************************************************************************************//    
        
        Runnable miRunnable = new Runnable() {
          
            public void run() {
                
                try{
                
                   buscarDatos();
                   txBuscarNombre.setText("");
                   txBuscarProveedor.setText("");
                   
                   if (Grilla.getRowCount() > 0){
                   
                   
                       txCadena.setEnabled(true);
                       
                   }else{
                   
                       txCadena.setEnabled(false);
                   
                   }
                   
                 
                }catch (Exception e) {
                    e.printStackTrace();
                } 
          
            }
        }; 
        
        Thread hilo = new Thread(miRunnable);
        hilo.start();
        
        
    //*************************************************************************************************************************************************************//    
        
    }//GEN-LAST:event_btCargarActionPerformed
   
    public void buscarDatos(){
        ExeSql Sql = new ExeSql();
        ExeSql Sql2 = new ExeSql();
        ResultSet Rs = null;
        ResultSet Rs2 = null;
        String Query = "";
        String Query2 = "";
        DefaultTableModel tbModel = (DefaultTableModel) Grilla.getModel();
        DefaultTableModel tbModel2 = (DefaultTableModel) GrillaChilemat.getModel();
        DefaultTableModel tbModel3 = (DefaultTableModel) GrillaPrv.getModel();
        String conv = "";
        String prov = "";
        String prov2 = "";
    
        while(tbModel.getRowCount()>0)
              tbModel.removeRow(0);
        
        while(tbModel2.getRowCount()>0)
              tbModel2.removeRow(0);
         
         while(tbModel3.getRowCount()>0)
              tbModel3.removeRow(0);
     
        
        
        if (!txBuscarProveedor.getText().isEmpty() || !txBuscarProveedor.getText().equals("") ){
        
            
            prov="and p.proveedor_asociado LIKE '%"+txBuscarProveedor.getText().trim()+"%'";
         
            prov2="where p.proveedor_asociado LIKE '%"+txBuscarProveedor.getText().trim()+"%'";
            
        
        }else {
        
            
          prov="";
         
          prov2="";
        
        
        
        }
            
        if (cbConvenio.getSelectedIndex()>0){
        
            conv = " and p.convenio='"+cbIdConvenio.getSelectedItem()+"' ";
    
        }else{
        
            conv="";
        }
    
    

    
        try {
            
            if (cbSaldos.getSelectedItem().toString().equals("Negativos")) {
                
                System.out.println("\n\n"+fmMain.GetUsuario()+"\n");
                              
                        Query="select DISTINCT trim(i.sku) as codigo,p.nombre,\n" +
                               "case \n" +
                               "when (select trim(nombre) from proveedor where rut=p.rutultprv) is null then 'SIN PROVEEDOR ASOCIADO' \n" +
                               "else (select trim(nombre) from proveedor where rut=p.rutultprv) \n" +
                               "end as proveedor,\n" +
                               "u.um,i.stock,i.ocp,i.occ,i.gdc,i.stock+i.ocp+i.occ+i.gdc-case when p.minimo is null then 0 else p.minimo end as total,\n" +
                               "p.proveedor_asociado as proveedor_asc, p.rut_proveedor_asociado, \n"+
                               "case when p.minimo is null then 0 else p.minimo end, \n" +
                               "case when p.display is null then 0 else p.display end as embalaje, p.rutultprv \n" +
                               "from inventario i\n" +
                               "left join producto p on i.sku=p.sku\n" +
                               "left join par_unidad u on p.unidad=u.codigo\n" +
                               "left join occhdet d on i.sku=d.sku and d.cantidad > d.separado + despachado\n" +
                               "left join occh oc on d.rut=oc.rut and d.codigo_oc=oc.codigo_oc and d.orden=oc.orden\n" +
                               "left join personal ps on oc.vendedor = ps.vendedor\n" +
                               "left join ctacteprvdet cpt on i.sku = cpt.sku\n" +
                               "left join proveedor po on cpt.rut = po.rut  \n" +
                               "left join ctacteprv e on e.tipdocto=cpt.tipdocto and cpt.nrodocto=e.nrodocto and cpt.rut=e.rut \n" +
                               "WHERE i.stock+i.ocp+i.occ+i.gdc < case when p.minimo is null then 0 else p.minimo end \n"+ conv + prov + " \n";
             
                        Query = Query + " group by i.sku,p.nombre,u.um,i.stock,i.ocp,i.occ,i.gdc, i.stock+i.ocp+i.occ+i.gdc,p.rutultprv,p.proveedor_asociado, p.rut_proveedor_asociado,\n" +
                                        " case when p.minimo is null then 0 else p.minimo end,p.rutultprv, po.nombre,case when p.display is null then 0 else p.display end \n" +
                                        " order by trim(i.sku)";
                
                        
                
                
            } else if (cbSaldos.getSelectedItem().toString().equals("Positivos")) {
                
                          
                Query="select trim(i.sku) as codigo,p.nombre,\n" +
                           "case \n" +
                           "when (select trim(nombre) from proveedor where rut=p.rutultprv) is null then 'SIN PROVEEDOR ASOCIADO' \n" +
                           "else (select trim(nombre) from proveedor where rut=p.rutultprv) \n" +
                           "end as proveedor,\n" +
                           "u.um,i.stock,i.ocp,i.occ,i.gdc,i.stock+i.ocp+i.occ+i.gdc-case when p.minimo is null then 0 else p.minimo end as total,\n" +
                           "p.proveedor_asociado as proveedor_asc, p.rut_proveedor_asociado, \n"+
                           "case when p.minimo is null then 0 else p.minimo end, \n" +
                           "case when p.display is null then 0 else p.display end as embalaje, p.rutultprv \n" +
                           "from inventario i\n" +
                           "left join producto p on i.sku=p.sku\n" +
                           "left join par_unidad u on p.unidad=u.codigo\n" +
                           "left join occhdet d on i.sku=d.sku and d.cantidad > d.separado + despachado\n" +
                           "left join occh oc on d.rut=oc.rut and d.codigo_oc=oc.codigo_oc and d.orden=oc.orden\n" +
                           "left join personal ps on oc.vendedor = ps.vendedor\n" +
                           "left join ctacteprvdet cpt on i.sku = cpt.sku\n" +
                           "left join proveedor po on cpt.rut = po.rut \n" +
                           "left join ctacteprv e on e.tipdocto=cpt.tipdocto and cpt.nrodocto=e.nrodocto and cpt.rut=e.rut \n"+
                           "WHERE i.stock+i.ocp+i.occ+i.gdc > case when p.minimo is null then 0 else p.minimo end \n"+ conv + prov + " \n"; 
                        
                                            
                        Query = Query + " group by i.sku,p.nombre,u.um,i.stock,i.ocp,i.occ,i.gdc, i.stock+i.ocp+i.occ+i.gdc,p.rutultprv,p.proveedor_asociado,p.rut_proveedor_asociado, \n" +
                                        " case when p.minimo is null then 0 else p.minimo end,p.rutultprv,po.nombre,case when p.display is null then 0 else p.display end  \n" +
                                        " order by i.sku";
                       
                        
                
            }else {
                     
                    Query="select trim(i.sku) as codigo,p.nombre,\n" +
                           "case \n" +
                           "when (select trim(nombre) from proveedor where rut=p.rutultprv) is null then 'SIN PROVEEDOR ASOCIADO' \n" +
                           "else (select trim(nombre) from proveedor where rut=p.rutultprv) \n" +
                           "end as proveedor,\n" +
                           "u.um,i.stock,i.ocp,i.occ,i.gdc,i.stock+i.ocp+i.occ+i.gdc-case when p.minimo is null then 0 else p.minimo end as total,\n" +
                           "p.proveedor_asociado as proveedor_asc, p.rut_proveedor_asociado, \n"+
                           "case when p.minimo is null then 0 else p.minimo end, \n" +
                           "case when p.display is null then 0 else p.display end as embalaje, p.rutultprv \n" +
                           "from inventario i\n" +
                           "left join producto p on i.sku=p.sku\n" +
                           "left join par_unidad u on p.unidad=u.codigo\n" +
                           "left join occhdet d on i.sku=d.sku and d.cantidad > d.separado + despachado\n" +
                           "left join occh oc on d.rut=oc.rut and d.codigo_oc=oc.codigo_oc and d.orden=oc.orden\n" +
                           "left join personal ps on oc.vendedor = ps.vendedor\n" +
                           "left join ctacteprvdet cpt on i.sku = cpt.sku\n" +
                           "left join proveedor po on cpt.rut = po.rut \n" +
                           "left join ctacteprv e on e.tipdocto=cpt.tipdocto and cpt.nrodocto=e.nrodocto and cpt.rut=e.rut \n"+ prov2 + " \n"; 
                        
             
                        Query = Query + " group by i.sku,p.nombre,u.um,i.stock,i.ocp,i.occ,i.gdc, i.stock+i.ocp+i.occ+i.gdc,p.rutultprv, p.proveedor_asociado, p.rut_proveedor_asociado, \n" +
                                        " case when p.minimo is null then 0 else p.minimo end,p.rutultprv, po.nombre,case when p.display is null then 0 else p.display end \n" +
                                        " order by i.sku";
                
               
            }
            
            
            Rs = Sql.Select(Query);
            
            String Sku = "";
            String Sku2 = "";
            double total = 0;
            int cont = 0;
            String proveedor_asc = "";
            String rut_proveedor_asc = "";
            
            
            if (Sql.GetRowCount() > 0){
            
                while (Rs.next()){

                    Sku2 = Rs.getString("codigo").trim();
                    
                    if (!Sku2.equals(Sku)){
                        
                        
                         if (Rs.getString("proveedor_asc") == null){
                            
                                
                                proveedor_asc = "SIN PROVEEDOR ASOCIADO";
                                rut_proveedor_asc = "0";
                                
                            
                            }else {
                            
                                 proveedor_asc = Rs.getString("proveedor_asc").trim();
                                 rut_proveedor_asc = Rs.getString("rut_proveedor_asociado").trim();
                            
                            
                            }
                             
                        
                        
                    
                        //********************************************************************************
                        
                        if (!txBuscarProveedor.getText().isEmpty() || !txBuscarProveedor.getText().equals("") ){
                        
                            System.out.println("EL proveedor_asc ES : "+Rs.getString("proveedor_asc"));
                            
                           
                            
                            if (proveedor_asc.contains(txBuscarProveedor.getText().trim())) {
                                
                                if (cbSaldos.getSelectedItem().toString().equals("Negativos")) {
                         
                                    total = Rs.getDouble("total");
                                    
                                    
                                }else {
                         
                         
                                    total = Rs.getDouble("total");
                         
                                }
                                
                                
                                tbModel.addRow(new Object[]{
                                                Rs.getString("codigo").trim(),
                                                Rs.getString("nombre").trim(),
                                                Rs.getString("proveedor"),
                                                Rs.getString("um"),    
                                                Rs.getDouble("stock"),
                                                Rs.getDouble("ocp"),
                                                Rs.getDouble("occ"),
                                                Rs.getDouble("gdc"),
                                                total,
                                                "", //Rs.getString("fnegativo"),
                                                0, //Rs.getInt("dias"),
                                                proveedor_asc,
                                                0, //Rs.getInt("dias2"),
                                                Rs.getInt("minimo"),"","","","","",
                                                false,
                                                rut_proveedor_asc //Rs.getString("rutultprv")
                            
                                });
                                
                                cont++;
                                
                                System.out.println("EL cont ES : "+cont);
                         
                            }    
                        
                        }else {
                            
                            
                            if (cbSaldos.getSelectedItem().toString().equals("Negativos")) {
                                
                                    total = Rs.getDouble("total");
                                
                         
                                }else {
                         
                         
                                    total = Rs.getDouble("total");
                         
                                }
                            
                            
                        
                                                
                            tbModel.addRow(new Object[]{
                                                Rs.getString("codigo").trim(),
                                                Rs.getString("nombre").trim(),
                                                Rs.getString("proveedor"),
                                                Rs.getString("um"),    
                                                Rs.getDouble("stock"),
                                                Rs.getDouble("ocp"),
                                                Rs.getDouble("occ"),
                                                Rs.getDouble("gdc"),
                                                total,
                                                "", //Rs.getString("fnegativo"),
                                                0, //Rs.getInt("dias"),
                                                proveedor_asc,
                                                0, //Rs.getInt("dias2"),
                                                Rs.getInt("minimo"),"","","","","",
                                                false,
                                                rut_proveedor_asc //Rs.getString("rutultprv")
                            
                            });
                            
                            cont++;
                            
                            
                            
                        }    
                            
                        Sku = Sku2;    
                    
                    }
            
                }
             
            
            }
            
            
            lbContProductos.setText(cont + " Productos");
//            lbContProductos1.setText(String.valueOf(Grilla2.getRowCount()) + " Productos2");
            
            btAsociar.setEnabled(true);
            //btAgregar_otro.setEnabled(true);
        
        } catch (SQLException ex) {
            //LogError.Guardar(this.getClass().getSimpleName(),ex.getMessage());
            fmMain.Mensaje("Opppss existe un error");
            Logger.getLogger(pfControlInventario_resp.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            Sql.Close();
        }
    }
    
    
    private void CargaConvenios(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        try{
            Rs = Sql.Select("Select codigo, convenio from par_convenio");
            while (Rs.next())
                {
                cbConvenio.addItem(Rs.getString("convenio"));
                cbIdConvenio.addItem(Rs.getString("codigo"));
                }
        }
        catch (Exception e)
        {
            fmMain.Mensaje("Error al cargar convenios: "+e);
        }
       finally
        {
            Sql.Close();
        }
   }
   
   private void CargaProveedor(){
       ExeSql Sql = new ExeSql();
        ResultSet Rs;
        try{
            Rs = Sql.Select("Select rut, nombre from proveedor order by nombre");
            while (Rs.next())
                {
                cbProveedor.addItem(Rs.getString("nombre"));
                cbIdProveedor.addItem(Rs.getString("rut"));
                }
        }
        catch (Exception e)
        {
            fmMain.Mensaje("Error al cargar lista de proveedores: "+e);
        }
       finally
        {
            Sql.Close();
        }
       
       
   }
    
    
   private void CodigosChileMat(){
   
    //********************************************************************************************************************************************
      
        Lista2.clear();
        Lista2.add(new ArrayList<String>());

        String sku2 = Grilla.getValueAt(Grilla.getSelectedRow(),0).toString();
        String Nombre = Grilla.getValueAt(Grilla.getSelectedRow(),1).toString();
        String Cantidad = Grilla.getValueAt(Grilla.getSelectedRow(),8).toString().replaceAll("\\-", "");
        String Proveedor = Grilla.getValueAt(Grilla.getSelectedRow(),20).toString().trim();

        Lista2.get(0).add(0,sku2);
        Lista2.get(0).add(1,Nombre);
        Lista2.get(0).add(2,Cantidad);
        Lista2.get(0).add(3,Proveedor);
  
    //*************************************************************************************************************************************//
       
        ExeSql Sql2= new ExeSql();
        ResultSet Rs2 = null;  
        
        String CodPrv = "";
        
    
        
        System.out.println("EL TAMAÑO ES : "+Lista2.size());
    
        
        DefaultTableModel tbModel = (DefaultTableModel) GrillaChilemat.getModel();
                
        while(tbModel.getRowCount()>0)
              tbModel.removeRow(0);
    
            
            try {
                
                System.out.println("SKU ES : "+Lista2.get(0).get(0));
                System.out.println("NOMBRES ES : "+Lista2.get(0).get(1));
                System.out.println("CANTIDAD ES : "+Lista2.get(0).get(2));
                System.out.println("PROVEEDOR ASOCIADO ES : "+Lista2.get(0).get(3));
                        
                Rs2 = Sql2.Select("Select codbar, rutprv from codbar \n" +
                                  "where rutprv="+Lista2.get(0).get(3)+" and sku='"+Lista2.get(0).get(0)+"'" );
                
                if (Rs2.next()){
                    
                    CodPrv = Rs2.getString("codbar");
                }else {
                    
                    CodPrv = "";
                }
                                           
                tbModel.addRow(new Object[]{ Lista2.get(0).get(0),
                                             CodPrv,
                                             Lista2.get(0).get(1),       //Nombre Producto
                                             Lista2.get(0).get(2),       //Cantidad
                                             Lista2.get(0).get(3)       //Rut Proveedor Asociado
                                                   
                });
                    
          
            //****************************************************************************************************************************************//
            } catch (SQLException ex) {
                    
                Logger.getLogger(pfOCProveedor.class.getName()).log(Level.SEVERE, null, ex);
            }
       
        
   
   }
   
   
   private void CodigosChileMat_2(){
   
    //********************************************************************************************************************************************
         
        Lista2.clear();

        Lista2.add(new ArrayList<String>());

        String sku2 = Grilla.getValueAt(Grilla.getSelectedRow(),0).toString();
        String Nombre = Grilla.getValueAt(Grilla.getSelectedRow(),1).toString();
        String Cantidad = Grilla.getValueAt(Grilla.getSelectedRow(),8).toString().replaceAll("\\-", "");
        String Proveedor = GrillaPrv.getValueAt(GrillaPrv.getSelectedRow(),4).toString().trim();

        Lista2.get(0).add(0,sku2);
        Lista2.get(0).add(1,Nombre);
        Lista2.get(0).add(2,Cantidad);
        Lista2.get(0).add(3,Proveedor);
    //*************************************************************************************************************************************//
      
        ExeSql Sql2= new ExeSql();
       
        ResultSet Rs2 = null;  
        
        String CodPrv = "";
        
        System.out.println("EL TAMAÑO ES : "+Lista2.size());
    
        
        DefaultTableModel tbModel = (DefaultTableModel) GrillaChilemat.getModel();
                
        while(tbModel.getRowCount()>0)
              tbModel.removeRow(0);
    
            
        try {
                
            System.out.println("SKU ES : "+Lista2.get(0).get(0));
            System.out.println("NOMBRES ES : "+Lista2.get(0).get(1));
            System.out.println("CANTIDAD ES : "+Lista2.get(0).get(2));
            System.out.println("PROVEEDOR ASOCIADO ES : "+Lista2.get(0).get(3));
                        
                        
            Rs2 = Sql2.Select("Select codbar, rutprv from codbar \n" +
                               "where rutprv="+Lista2.get(0).get(3)+" and sku='"+Lista2.get(0).get(0)+"'" );
                        
                        
                
            if (Rs2.next()){
                    
                CodPrv = Rs2.getString("codbar");
            }else {
                    
                CodPrv = "";
            }
                                           
            tbModel.addRow(new Object[]{ Lista2.get(0).get(0),
                                         CodPrv,
                                         Lista2.get(0).get(1),       //Nombre Producto
                                         Lista2.get(0).get(2),       //Cantidad
                                         Lista2.get(0).get(3)       //Rut Proveedor Asociado
                                                   
            });
                
                        
            GrillaPrv.setValueAt(false,GrillaPrv.getSelectedRow(),5);        
                        
            btAsociar_otro.setEnabled(false);
            btAsociar.setEnabled(true);
            
         //****************************************************************************************************************************************//
            } catch (SQLException ex) {
                    
                Logger.getLogger(pfOCProveedor.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    
   
   }
   
   
   
   
    
    private void CargaProveedores(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel Model = (DefaultTableModel)GrillaPrv.getModel();
        
        fmMain.LimpiaGrilla(Model);
            

        
        try {
            Rs = Sql.Select("select cast(e.femision as date) as femision,p.nombre, \n" +
                            "(select * from fn_get_proveedor_asociado(e.rut,e.nrodocto)) as proveedor_as,\n"+
                            "(select * from fn_get_rut_asociado(e.rut,e.nrodocto)) as rut_proveedor_as, \n"+
                            "d.valorunitario\n" +
                            "from ctacteprvdet d\n" +
                            "left join ctacteprv e on e.tipdocto=d.tipdocto and d.nrodocto=e.nrodocto and d.rut=e.rut \n" +
                            "left join proveedor p on e.rut=p.rut\n" +
                            "where d.sku='"+ Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString().trim() +"'\n" +
                            "and d.tipdocto='FAP' order by femision desc");
            while(Rs.next()){
                Model.addRow(new Object[]{
                            Rs.getString("femision").trim(),
                            Rs.getString("nombre").trim(),
                            Rs.getString("proveedor_as"),
                            fmMain.FormatoNumero(Rs.getDouble("valorunitario")),
                            Rs.getString("rut_proveedor_as"),
                            false
                            
                        });
            }
            
            //GrillaPrv.setDefaultRenderer(Object.class, new Elrender()); 
            
        } catch (Exception e) {
        }finally{
            Sql.Close();
        }
    }
    private void GrillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaMouseClicked
        
        if (evt.getClickCount() == 2) {
            pfProductos Pro = new pfProductos();
            Pro.setOpaque(false);
            pnPestanas.addTab("Producto", Pro);
            PanelTab btc = new PanelTab(pnPestanas, 0);
            pnPestanas.setTabComponentAt(pnPestanas.indexOfComponent(Pro), btc);
            pnPestanas.setSelectedIndex(pnPestanas.getTabCount() - 1);
            Pro.txSku.requestFocus();
            Pro.CargaProducto(Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString());
        
        }else if(evt.getClickCount()==1){
         
             boolean selecciona = (boolean) Grilla.getValueAt(Grilla.getSelectedRow(),19);
             
             if (selecciona){
                 
               // Grilla.setValueAt(false,Grilla.getSelectedRow(),19) ;
                contselec++;
                
                
                
                Rut_Asoc = Grilla.getValueAt(Grilla.getSelectedRow(),20).toString();
             
             }else if (!selecciona) {
                
                // Grilla.setValueAt(true,Grilla.getSelectedRow(),19) ;
                 contselec--;
             
             }
             
             
             if (contselec > 0){
             
                System.out.println("HAY ELEMENTOS SELECCIONADOS!!"+contselec);
               
             
             }else if (contselec == 0){
             
                System.out.println("NO EXISTEN ELEMENTOS SELECCIONADOS!!"+contselec);
               
                 
             }
             
         }
        
    }//GEN-LAST:event_GrillaMouseClicked

    private void btAsociarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAsociarActionPerformed
        
      
            //********************************************************************************************************************************************
            boolean agrega = false;
            int fila = 0;
         
            Lista2.clear();

            for(int i=0; i< Grilla.getRowCount(); i++){

                //agrega = (boolean) Grilla.getValueAt(i,19);

              //  if (agrega){

                    Lista2.add(new ArrayList<String>());

                    String sku2 = Grilla.getValueAt(i,0).toString();
                    String Nombre = Grilla.getValueAt(i,1).toString();
                    String Cantidad = Grilla.getValueAt(i,8).toString().replaceAll("\\-", "");
                    String Proveedor = Grilla.getValueAt(i,20).toString().trim();

                    Lista2.get(fila).add(0,sku2);
                    Lista2.get(fila).add(1,Nombre);
                    Lista2.get(fila).add(2,Cantidad);
                    Lista2.get(fila).add(3,Proveedor);
                    //
                    //                    System.out.println("EL SKU ES :"+Lista.get(fila).get(0));
                    //                    System.out.println("EL NOMBRE ES :"+Lista.get(fila).get(1));
                    //                    System.out.println("LA UNIDAD DE MEDIDAD ES :"+Lista.get(fila).get(2));
                    //                    System.out.println("LA CANTIDAD ES :"+Lista.get(fila).get(3));
                    //
                
                    fila++;

             //   }

            }
            //*************************************************************************************************************************************//
            
            
        ExeSql SqlEc2= new ExeSql();
        ExeSql Sql2= new ExeSql();
        
        ResultSet RsEc1 = null;   
        ResultSet Rs2 = null;  
        
        String CodPrv = "";
        
    
        
        System.out.println("EL TAMAÑO ES : "+Lista2.size());
    
        
        DefaultTableModel tbModel = (DefaultTableModel) GrillaChilemat.getModel();
                
        while(tbModel.getRowCount()>0)
              tbModel.removeRow(0);
    
    
    
        for(int i=0 ; i < Lista2.size();i++){
            
            try {
                
                System.out.println("SKU ES : "+Lista2.get(i).get(0));
                System.out.println("NOMBRES ES : "+Lista2.get(i).get(1));
                System.out.println("CANTIDAD ES : "+Lista2.get(i).get(2));
                System.out.println("PROVEEDOR ASOCIADO ES : "+Lista2.get(i).get(3));
                        
//                        Rs2 = Sql2.Select("Select codbar from codbar where rutprv="+rut+ " and sku='"+Lista.get(i).get(0)+"'" );
                        
                        
                        Rs2 = Sql2.Select("Select codbar, rutprv from codbar \n" +
                                          "where rutprv="+Lista2.get(i).get(3)+" and sku='"+Lista2.get(i).get(0)+"'" );
                        
                        
                
                        if (Rs2.next()){
                    
                                CodPrv = Rs2.getString("codbar");
                        }else {
                    
                                CodPrv = "";
                        }
                                           
                        tbModel.addRow(new Object[]{ Lista2.get(i).get(0),
                                                     CodPrv,
                                                     Lista2.get(i).get(1),       //Nombre Producto
                                                     Lista2.get(i).get(2),       //Cantidad
                                                     Lista2.get(i).get(3)       //Rut Proveedor Asociado
                                                   
                        });
                    
                       
                    
                    
                  
             
            
            //****************************************************************************************************************************************//
            } catch (SQLException ex) {
                    
                Logger.getLogger(pfOCProveedor.class.getName()).log(Level.SEVERE, null, ex);
            }
       
        }
    
            
            
            
        
        
    }//GEN-LAST:event_btAsociarActionPerformed

    private void cbConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbConvenioActionPerformed
        cbIdConvenio.setSelectedIndex(cbConvenio.getSelectedIndex());
        chk_ult_proveedor.setSelected(true);
        btCargar.doClick();
       
    }//GEN-LAST:event_cbConvenioActionPerformed

    private void cbProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProveedorActionPerformed
        cbIdProveedor.setSelectedIndex(cbProveedor.getSelectedIndex());
       // chk_ult_proveedor.setSelected(true);
        btCargar.doClick();
         
    }//GEN-LAST:event_cbProveedorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String nombre = "Control de Stock";    
    
    String ruta_local="";
    String carpeta = "temp";
    String sistema = System.getProperty("os.name").toLowerCase();

    
        if(Grilla.getRowCount()==0){
            fmMain.Mensaje("Nada que exportar");
            return;
        }

            List<JTable> tb=new ArrayList<>();
            List<String> nom=new ArrayList<>();
            tb.add(Grilla);
            String str_convenio="conv";
            String str_proveedor="prov";
          
            nom.add(nombre);
            
            //------------------  Rescata Ruta  -------------------------------
            // Objetivo: rescatar ruta de Windows y de Linux segun sea el caso para poder
            // Generar el archivo Esxcel en forma automatica
            File f = new File("");
                    if (sistema.contains("win"))
                    {
                         ruta_local = "c:/" + carpeta + "/";
                         f = new File(ruta_local.substring(0,ruta_local.length()-1));
                    }
                    else{
                          ruta_local = "/" + carpeta + "/";
                          //folder = new File(ruta_local);
                          f = new File(ruta_local);
                    }
//                    if (!folder.exists())
//                    {
//                        folder.mkdir();
//                    }
                    if(!f.isDirectory()) {
                    String newFolder = ruta_local; //cualquierCarpeta es el nombre de la Carpeta que vamos a crear
                    
                    File myNewFolder = new File(newFolder);
                    myNewFolder.mkdirs(); //creamos la carpeta
                   }
                    else
                   {
                          System.out.println("La carpeta ya estaba creada");
                   }
                    
            //------------------  Rescata Ruta  -------------------------------
            
//            File folder = new File("c:/temp");
//            if (!folder.exists())
//            {
//                folder.mkdir();
//            }
            
            
            
             String file = ruta_local + nombre + ".xls";       
            
            
            try {
                Exporter e = new Exporter(new File(file), tb, nom);
                
                if(e.export())

                //abrir(file);
                //Abrir_Doc(file);
                Utl_Excel.Abrir_Doc(file);
                
            } catch (Exception e) {
                fmMain.Mensaje(e.getMessage());
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txBuscarCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBuscarCodigoKeyTyped

    }//GEN-LAST:event_txBuscarCodigoKeyTyped

    private void txBuscarNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBuscarNombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txBuscarNombreKeyTyped

    private void txBuscarProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBuscarProveedorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txBuscarProveedorKeyTyped

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
       // Limpiar();
        
      
        DefaultTableModel tbModel = (DefaultTableModel) Grilla.getModel();
        DefaultTableModel tbModel2 = (DefaultTableModel) GrillaChilemat.getModel();
        DefaultTableModel tbModel3 = (DefaultTableModel) GrillaPrv.getModel();
      
        while(tbModel.getRowCount()>0)
              tbModel.removeRow(0);
        
        while(tbModel2.getRowCount()>0)
              tbModel2.removeRow(0);
         
         while(tbModel3.getRowCount()>0)
              tbModel3.removeRow(0);
         
        lbContProductos.setText("0 Productos");
        
        txCadena.setEnabled(false);
        
        
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void txBuscarCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBuscarCodigoKeyPressed
        // TODO add your handling code here:
          if(evt.getKeyCode()== KeyEvent.VK_ENTER)
            btCargar.doClick();
    }//GEN-LAST:event_txBuscarCodigoKeyPressed

    private void txBuscarNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBuscarNombreKeyPressed
        // TODO add your handling code here:
               if(evt.getKeyCode()== KeyEvent.VK_ENTER)
                btCargar.doClick();
    }//GEN-LAST:event_txBuscarNombreKeyPressed

    private void txBuscarProveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBuscarProveedorKeyPressed
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
        
            
            if (!txBuscarProveedor.getText().isEmpty()){
            
                System.out.println("ENTRA A NO VACÍO !!!");
                
                btCargar.doClick();
            
            }else {
            
                System.out.println("ENTRA A VACÍO !!!");
                btIr.doClick();
            
            }
                        
        }                
    }//GEN-LAST:event_txBuscarProveedorKeyPressed

    private void txBuscarCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBuscarCodigoKeyReleased
        // TODO add your handling code here:
        txBuscarCodigo.setText(txBuscarCodigo.getText().toUpperCase());
    }//GEN-LAST:event_txBuscarCodigoKeyReleased

    private void txBuscarNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBuscarNombreKeyReleased
        // TODO add your handling code here:
        txBuscarNombre.setText(txBuscarNombre.getText().toUpperCase());
    }//GEN-LAST:event_txBuscarNombreKeyReleased

    private void txBuscarProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBuscarProveedorKeyReleased
        // TODO add your handling code here:
        txBuscarProveedor.setText(txBuscarProveedor.getText().toUpperCase());
    }//GEN-LAST:event_txBuscarProveedorKeyReleased

    private void chk_ult_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_ult_proveedorActionPerformed
        // TODO add your handling code here:
        btCargar.doClick();
         
    }//GEN-LAST:event_chk_ult_proveedorActionPerformed

    private void cbSaldosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSaldosActionPerformed
        TableRowSorter<TableModel>sorter = new TableRowSorter<TableModel>(Grilla.getModel());   //Se crea un Modelo para filtrar la Tabla
        Grilla.setRowSorter(sorter);     //Se filtra la Tabla de acuerdo al Modelo
        sorter.setRowFilter(null);         //Se elimina el Filtro y se muestran todos los datos
    }//GEN-LAST:event_cbSaldosActionPerformed

    private void cbIdProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIdProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIdProveedorActionPerformed

    private void btCrearOCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearOCPActionPerformed

        if (contselec == 0){

            fmMain.Mensaje("No hay Productos Seleccionados!!");
            return;

        }
   
            ExeSql  SqlLuv = new ExeSql();
            ExeSql  SqlLuv3 = new ExeSql();
            ResultSet Rs, Rs2, Rs3;
            String sku = "";
            double valor_uc = 0;
            double vunitario = 0;
            double cost_ref = 0;
            double cost_vent_neto1 = 0;
           
            //********************************************************************************************************************************************
            boolean agrega = false;
            int fila = 0;
           
            Lista.clear();

            for(int i=0; i< Grilla.getRowCount(); i++){

                agrega = (boolean) Grilla.getValueAt(i,19);

                if (agrega){

                    Lista.add(new ArrayList<String>());

                    String sku2 = Grilla.getValueAt(i,0).toString();
                    String Nombre = Grilla.getValueAt(i,1).toString();
                    String Cantidad = Grilla.getValueAt(i,8).toString();
                    String UM = Grilla.getValueAt(i,3).toString();
                    

                    Lista.get(fila).add(0,sku2);
                    Lista.get(fila).add(1,Nombre);
                    Lista.get(fila).add(2,UM);
                    Lista.get(fila).add(3,Cantidad);
                    //
                    //                    System.out.println("EL SKU ES :"+Lista.get(fila).get(0));
                    //                    System.out.println("EL NOMBRE ES :"+Lista.get(fila).get(1));
                    //                    System.out.println("LA UNIDAD DE MEDIDAD ES :"+Lista.get(fila).get(2));
                    //                    System.out.println("LA CANTIDAD ES :"+Lista.get(fila).get(3));
                    //
                   
                
                    fila++;

                }

            }
            //*************************************************************************************************************************************//

            try {

                //    System.out.println("EL TAMAÑO DE LA LISTA ES :"+Lista.size());

                for(int i=0 ; i < Lista.size();i++){

                    Rs = SqlLuv.Select("select p.sku,p.valultcompra \n" +
                        "from producto p\n" +
                        "where p.sku='" + Lista.get(i).get(0).toString().trim() + "'");

                    if (SqlLuv.GetRowCount() > 0){

                        Rs.next();

                        valor_uc = Rs.getDouble("valultcompra");
                        sku = Rs.getString("sku");

                        Rs3 = SqlLuv3.Select("SELECT ccd.sku, ccd.valorunitario, ccd.tipdocto, ccd.nrodocto FROM ctacteprvdet ccd\n" +
                                             "WHERE ccd.sku = '"+sku+"'\n" +
                                             "AND ccd.tipdocto IN ('OCP')\n" +
                                             "ORDER BY ccd.nrodocto DESC\n" +
                                             "LIMIT 1");
                        Rs3.next();
                
                        if (SqlLuv3.GetRowCount() > 0){
            
                            vunitario = Rs3.getDouble("valorunitario");
            
                        }else{
            
                            vunitario = 0;
            
                        }
                  
            
                        if (valor_uc >= vunitario ){
            
                            cost_ref = valor_uc;
                
            
                        }else if (vunitario >= valor_uc) {
            
                            cost_ref = vunitario;      
            
                        }
             
                        cost_vent_neto1 = Math.round(cost_ref);
                        Lista.get(i).add(4,String.valueOf(cost_vent_neto1));        //Costo Referencial de Luvaly + 6 %
                //        System.out.println("EL VALOR UNITARIO ES :"+Lista.get(i).get(4));    
      
                    
                    }

                }

                pfOCProveedor OCP = new pfOCProveedor();
            
                OCP.NuevaOcp(Rut_Asoc, Lista);
                pnPestanas.addTab("OC Proveedor         ", OCP);
                PanelTab btc=new PanelTab(pnPestanas,0);
                pnPestanas.setTabComponentAt(pnPestanas.indexOfComponent(OCP), btc);
                pnPestanas.setSelectedIndex(pnPestanas.getTabCount()-1);

            
    
                
                

            } catch (SQLException ex) {

                Logger.getLogger(pfControlInventario_resp.class.getName()).log(Level.SEVERE, null, ex);
            }

      //  }

      //  }

      //  }

      //  }

      //  }

      //  }

      //  }

      //  }

    }//GEN-LAST:event_btCrearOCPActionPerformed

    private void btIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIrActionPerformed
        
        Dialogos.jdBuscarCliPrv BPC = new Dialogos.jdBuscarCliPrv(null, true);
            BPC.setLocationRelativeTo(null);
            BPC.setTitle("Buscar Proveedor");
            BPC.SetTipo(1);
            BPC.setVisible(true);
            
            txBuscarProveedor.setText(BPC.GetNom());
            btCargar.doClick();
            
        
    }//GEN-LAST:event_btIrActionPerformed

    private void GrillaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GrillaKeyPressed
        
        ExeSql Sql = new ExeSql();
        ExeSql Sql2 = new ExeSql();
        ExeSql Sql3 = new ExeSql();
        ExeSql Sql4 = new ExeSql();
        ResultSet Rs,Rs3;
        String Sku = "";
        int Minimo = 0;
        int indice = 0;
        
          
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try {
                Sku = Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString().trim();
//                String StrMin = Grilla.getValueAt(Grilla.getSelectedRow(), 13).toString().trim();
//                indice = StrMin.indexOf(".");
//                Minimo = Integer.parseInt(StrMin.substring(0, indice));
                Minimo = Integer.parseInt(Grilla.getValueAt(Grilla.getSelectedRow(), 13).toString().trim());
                
                System.out.println("EL SKU ES : "+Sku);
                
                Rs = Sql.Select("SELECT * FROM producto WHERE sku = '"+Sku+"'");
                
                if (Sql.GetRowCount() == 0){
                
                        fmMain.Mensaje("El Producto no está Registrado!...!");
                        return;
                    
                   
                }else if (Sql.GetRowCount() > 0) {
                
                    Sql3.ExeSql("UPDATE producto SET \n"+
                                "minimo = "+Minimo+" \n"+
                                "WHERE sku = '"+Sku+"'");
                    
                    Sql3.Commit();
                    
                    fmMain.Mensaje("Mínimo actualizado!");
                
                }
                
                
               
                
                                
                
            } catch (SQLException ex) {
               Sql2.Rollback();
               Sql3.Rollback();
               Logger.getLogger(pfReporteMercadoPublico.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
            
               Sql2.Close();
               Sql3.Close();
            }
            
            
        }
        
        
    }//GEN-LAST:event_GrillaKeyPressed

    private void GrillaChilematKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GrillaChilematKeyPressed
        
        ExeSql Sql = new ExeSql();
        ExeSql Sql3 = new ExeSql();
        ResultSet Rs;
        String Sku = "";
        String Rut = "";
        String CodPrv = "";
              
          
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try {
                Sku = GrillaChilemat.getValueAt(GrillaChilemat.getSelectedRow(),0).toString().trim();
                CodPrv = GrillaChilemat.getValueAt(GrillaChilemat.getSelectedRow(),1).toString().trim();
                Rut = GrillaChilemat.getValueAt(GrillaChilemat.getSelectedRow(), 4).toString().trim();
                
                System.out.println("EL SKU ES : "+Sku);
                
                
                Rs = Sql.Select("Select codbar, rutprv from codbar \n" +
                                "where rutprv="+Rut+ "\n"+
                                "and sku='"+Sku+"'" );
                
                if (Sql.GetRowCount() == 0){
                
                    Sql3.ExeSql("INSERT into codbar (sku,codbar,rutprv) VALUES ( \n" +
                                "'" + Sku + "','"+CodPrv + "'," + Rut + ")");
                    
                    Sql3.Commit();
                    
                     fmMain.Mensaje("Codido Proveedor agregado!");
                   
                }else if (Sql.GetRowCount() > 0) {
                
                    Sql3.ExeSql("UPDATE codbar SET \n"+
                                "codbar = '" + CodPrv +"' \n"+
                                "WHERE sku = '"+Sku+"'");
                    
                    Sql3.Commit();
                    
                    fmMain.Mensaje("Codido Proveedor actualizado!");
                
                }
                              
                
            } catch (SQLException ex) {
               Sql3.Rollback();
               Logger.getLogger(pfReporteMercadoPublico.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
            
               Sql.Close();
               Sql3.Close();
            }
            
            
        }
        
        
        
    }//GEN-LAST:event_GrillaChilematKeyPressed

    private void btAsociar_otroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAsociar_otroActionPerformed
        
        //********************************************************************************************************************************************
            boolean agrega = false;
            boolean selecciona = false;
            
            selecciona = (boolean) Grilla.getValueAt(Grilla.getSelectedRow(),19);
            
            
            if (!selecciona){
            
                fmMain.Mensaje(("Debe seleccionar producto !!"));
                return;
            
            }
            
            
            
            
            
            int fila = 0;
         
            Lista2.clear();

            for(int i=0; i< GrillaPrv.getRowCount(); i++){

                agrega = (boolean) GrillaPrv.getValueAt(i,5);

                if (agrega){

                    Lista2.add(new ArrayList<String>());

                    String sku2 = Grilla.getValueAt(Grilla.getSelectedRow(),0).toString();
                    String Nombre = Grilla.getValueAt(Grilla.getSelectedRow(),1).toString();
                    String Cantidad = Grilla.getValueAt(Grilla.getSelectedRow(),8).toString().replaceAll("\\-", "");
                    String Proveedor = GrillaPrv.getValueAt(i,4).toString().trim();

                    Lista2.get(fila).add(0,sku2);
                    Lista2.get(fila).add(1,Nombre);
                    Lista2.get(fila).add(2,Cantidad);
                    Lista2.get(fila).add(3,Proveedor);
                    //
                    //                    System.out.println("EL SKU ES :"+Lista.get(fila).get(0));
                    //                    System.out.println("EL NOMBRE ES :"+Lista.get(fila).get(1));
                    //                    System.out.println("LA UNIDAD DE MEDIDAD ES :"+Lista.get(fila).get(2));
                    //                    System.out.println("LA CANTIDAD ES :"+Lista.get(fila).get(3));
                    //
                
                    fila++;

                }

            }
            //*************************************************************************************************************************************//
            
            
        ExeSql SqlEc2= new ExeSql();
        ExeSql Sql2= new ExeSql();
        
        ResultSet RsEc1 = null;   
        ResultSet Rs2 = null;  
        
        String CodPrv = "";
        
    
        
        System.out.println("EL TAMAÑO ES : "+Lista2.size());
    
        
        DefaultTableModel tbModel = (DefaultTableModel) GrillaChilemat.getModel();
                
        while(tbModel.getRowCount()>0)
              tbModel.removeRow(0);
    
    
    
        for(int i=0 ; i < Lista2.size();i++){
            
            try {
                
                System.out.println("SKU ES : "+Lista2.get(i).get(0));
                System.out.println("NOMBRES ES : "+Lista2.get(i).get(1));
                System.out.println("CANTIDAD ES : "+Lista2.get(i).get(2));
                System.out.println("PROVEEDOR ASOCIADO ES : "+Lista2.get(i).get(3));
                        
                        
                        Rs2 = Sql2.Select("Select codbar, rutprv from codbar \n" +
                                          "where rutprv="+Lista2.get(i).get(3)+" and sku='"+Lista2.get(i).get(0)+"'" );
                        
                        
                
                        if (Rs2.next()){
                    
                                CodPrv = Rs2.getString("codbar");
                        }else {
                    
                                CodPrv = "";
                        }
                                           
                        tbModel.addRow(new Object[]{ Lista2.get(i).get(0),
                                                     CodPrv,
                                                     Lista2.get(i).get(1),       //Nombre Producto
                                                     Lista2.get(i).get(2),       //Cantidad
                                                     Lista2.get(i).get(3)       //Rut Proveedor Asociado
                                                   
                        });
                
                        
                GrillaPrv.setValueAt(false,GrillaPrv.getSelectedRow(),5);        
                        
                btAsociar_otro.setEnabled(false);
                btAsociar.setEnabled(true);
            
            //****************************************************************************************************************************************//
            } catch (SQLException ex) {
                    
                Logger.getLogger(pfOCProveedor.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        
    }//GEN-LAST:event_btAsociar_otroActionPerformed

    private void GrillaPrvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaPrvMouseClicked
       
        if(evt.getClickCount()==1){
         
             boolean selecciona = (boolean) GrillaPrv.getValueAt(GrillaPrv.getSelectedRow(),5);
             
             if (selecciona){
                 
                 contselec2++;
               //  GrillaPrv.setValueAt(false,GrillaPrv.getSelectedRow(),5) ;
                 
                  Rut_Asoc = GrillaPrv.getValueAt(GrillaPrv.getSelectedRow(),4).toString().trim();
                 
                 btAsociar_otro.setEnabled(true);
                 btAsociar.setEnabled(false);
             
             }else if (!selecciona) {
             
                contselec2--;
               // GrillaPrv.setValueAt(true,GrillaPrv.getSelectedRow(),5) ; 
                
               Rut_Asoc = Grilla.getValueAt(Grilla.getSelectedRow(),20).toString();
                 
                btAsociar_otro.setEnabled(false);
                btAsociar.setEnabled(true);
             
             }
             
             
             if (contselec2 > 0){
             
                System.out.println("HAY ELEMENTOS SELECCIONADOS!!"+contselec2);
             
             }else if (contselec2 == 0){
             
                System.out.println("NO EXISTEN ELEMENTOS SELECCIONADOS!!"+contselec2);
                 
             }
             
         }
        
        
        
    }//GEN-LAST:event_GrillaPrvMouseClicked

    private void txCadenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCadenaKeyPressed
        
           if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           
           
                DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
                TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(TableModel); 
                String filtrar =txCadena.getText().trim();
         
                sorter.setRowFilter(RowFilter.regexFilter(filtrar,1));
                                                        
                Grilla.setRowSorter(sorter);
           
           }
        
        
    }//GEN-LAST:event_txCadenaKeyPressed

    private void txCadenaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCadenaKeyReleased
        
        txCadena.setText(txCadena.getText().toUpperCase());
        
    }//GEN-LAST:event_txCadenaKeyReleased
    
      public void abrir(String file ){
        
       try {
           String url = file;
           ProcessBuilder p = new ProcessBuilder();
           p.command("cmd.exe", "/c",url);
           p.start();
       } catch (IOException ex) {
           Logger.getLogger(jdOC_PendientesFac.class.getName()).log(Level.SEVERE, null, ex);
       }
        
    }
    
      public void Abrir_Doc(String file) throws IOException{
          File pathCompleto = new File(file);
          Desktop.getDesktop().open(pathCompleto); 
      }
      
      
    
    private void CargaProveedoresegativos(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel Model = (DefaultTableModel)GrillaChilemat.getModel();
        fmMain.LimpiaGrilla(Model);
        try {
            Rs = Sql.Select("select max(p.rut)as rut,p.nombre,count(DISTINCT(i.Sku)) as conta\n" +
                            "from inventario i\n" +
                            "left join ctacteprvdet d on i.sku=d.sku\n" +
                            "left join proveedor p on d.rut=p.rut\n" +
                            "WHERE i.stock+i.ocp+i.occ+i.gdc<0 \n" +
                            "and p.nombre is not null\n" +
                            "group by p.nombre\n" +
                            "order by conta desc");
            while(Rs.next()){
                Model.addRow(new Object[]{Rs.getString("rut").trim(),Rs.getString("nombre").trim(),Rs.getInt("conta")});
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }finally{
            Sql.Close();
        }
    }
    private void CargaSkuAsociados(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        Grilla.clearSelection();
        try {
            System.out.println("select DISTINCT(i.sku) as sku\n" +
                            "from inventario i\n" +
                            "left join ctacteprvdet d on i.sku=d.sku\n" +
                            "left join proveedor p on d.rut=p.rut\n" +
                            "WHERE (select sp_get_inventarrio_sin_metros from sp_get_inventarrio_sin_metros(i.sku))+i.ocp+i.occ+i.gdc<0 \n" +
                            "and p.nombre is not null\n" +
                            "and p.rut=" + GrillaChilemat.getValueAt(GrillaChilemat.getSelectedRow(), 0).toString().trim());
            Rs = Sql.Select("select DISTINCT(i.sku) as sku\n" +
                            "from inventario i\n" +
                            "left join ctacteprvdet d on i.sku=d.sku\n" +
                            "left join proveedor p on d.rut=p.rut\n" +
                            "WHERE (select sp_get_inventarrio_sin_metros from sp_get_inventarrio_sin_metros(i.sku))+i.ocp+i.occ+i.gdc<0 \n" +
                            "and p.nombre is not null\n" +
                            "and p.rut=" + GrillaChilemat.getValueAt(GrillaChilemat.getSelectedRow(), 0).toString().trim());
            while(Rs.next()){
                    for(int i=0; i<Grilla.getRowCount();i++){
                    if(Rs.getString("sku").trim().equals(Grilla.getValueAt(i, 0).toString().trim())){
                       // Grilla.getSelectionModel().setSelectionInterval(i, i);
                       Grilla.changeSelection(i, i, true,false);
                       System.out.println(Rs.getString("Sku"));
                       break;
                    }
                }
//System.out.println(Rs.getString("Sku"));
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    
    

    public void Limpiar(){
        txBuscarCodigo.setText("");
        txBuscarNombre.setText("");
        txBuscarProveedor.setText("");
        cbConvenio.setSelectedIndex(0);
        cbIdConvenio.setSelectedIndex(0);
        cbIdProveedor.setSelectedIndex(0);
        cbProveedor.setSelectedIndex(0);
        cbSaldos.setSelectedIndex(0);
        btCargar.doClick();
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla;
    private javax.swing.JTable GrillaChilemat;
    private javax.swing.JTable GrillaPrv;
    private javax.swing.JButton btAsociar;
    private javax.swing.JButton btAsociar_otro;
    private javax.swing.JButton btCargar;
    private javax.swing.JButton btCrearOCP;
    private javax.swing.JButton btIr;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JComboBox<String> cbConvenio;
    private javax.swing.JComboBox<String> cbIdConvenio;
    private javax.swing.JComboBox<String> cbIdProveedor;
    private javax.swing.JComboBox<String> cbProveedor;
    private javax.swing.JComboBox cbSaldos;
    private javax.swing.JCheckBox chk_ult_proveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private javax.swing.JLabel lbContProductos;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JTextField txBuscarCodigo;
    private javax.swing.JTextField txBuscarNombre;
    private javax.swing.JTextField txBuscarProveedor;
    private javax.swing.JTextField txCadena;
    // End of variables declaration//GEN-END:variables
}
