/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Dialogos.jdOC_PendientesFac;
import Formularios.fmMain;
import static Formularios.fmMain.pnPestanas;
import Utilidades.Exporter;
import Utilidades.PanelTab;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.SelectionMode;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David Alcaman
 */
public class pfCXC_Resultados extends javax.swing.JPanel {

    /**
     * Creates new form pfCXC_Resultados
     */
    public pfCXC_Resultados() {
        initComponents();
        GrillaTramos.getTableHeader().setFont(new Font("Arial", Font.BOLD, 10));
        GrillaDeuda.getTableHeader().setFont(new Font("Arial", Font.BOLD, 10));
        GrillaPagos.getTableHeader().setFont(new Font("Arial", Font.BOLD, 10));
        GrillaEjecutivos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        GrillaTramos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(GrillaTramos.getSelectedRowCount()>0)
                    Cambioselect(1);
            }
        });
        GrillaDeuda.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(GrillaDeuda.getSelectedRowCount()>0)
                    Cambioselect(2);
            }
        });
        GrillaPagos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(GrillaPagos.getSelectedRowCount()>0)
                    Cambioselect(3);
            }
        });
        CargaEjecutivos();
    }

     private void CargaEjecutivos(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel Model = (DefaultTableModel) GrillaEjecutivos.getModel();
        fmMain.LimpiaGrilla(Model);
        try {
            Rs = Sql.Select("select p.rut,p.apellidopaterno, p.nombre as nombre\n" +
                        "from personal_ccostos cc\n" +
                        "left join personal p on cc.rut=p.rut\n" +
                        "where cc.ccosto=3\n" +
                        "and p.rut>10000");
            while(Rs.next()){
                Model.addRow(new Object[]{
                                Rs.getString("rut").trim(),
                                Rs.getString("nombre").trim(),
                                Rs.getString("apellidopaterno")
                                });
            }
            
        } catch (Exception e) {
        }finally{
            Sql.Close();
        }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        Abrir = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dtInicio = new org.jdesktop.swingx.JXDatePicker();
        dtFin = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GrillaTramos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        GrillaDetalle = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        GrillaDeuda = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        GrillaPagos = new javax.swing.JTable();
        btCargar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rbDeudas = new javax.swing.JRadioButton();
        rbPagos = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        cantidad_label = new javax.swing.JLabel();
        btExcel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        GrillaEjecutivos = new javax.swing.JTable();

        Abrir.setText("Abrir");
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Abrir);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "PERIODO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 10))); // NOI18N

        jLabel1.setText("Desde");

        jLabel2.setText("Hasta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dtInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dtFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GrillaTramos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TRAMO DIAS", "MINIMO", "MAXIMO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(GrillaTramos);
        if (GrillaTramos.getColumnModel().getColumnCount() > 0) {
            GrillaTramos.getColumnModel().getColumn(0).setMinWidth(200);
            GrillaTramos.getColumnModel().getColumn(0).setPreferredWidth(200);
            GrillaTramos.getColumnModel().getColumn(0).setMaxWidth(200);
            GrillaTramos.getColumnModel().getColumn(1).setMinWidth(0);
            GrillaTramos.getColumnModel().getColumn(1).setPreferredWidth(0);
            GrillaTramos.getColumnModel().getColumn(1).setMaxWidth(0);
            GrillaTramos.getColumnModel().getColumn(2).setMinWidth(0);
            GrillaTramos.getColumnModel().getColumn(2).setPreferredWidth(0);
            GrillaTramos.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        GrillaDetalle.setAutoCreateRowSorter(true);
        GrillaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RUT", "NOMBRE", "ORDEN", "FACTURA", "FECHA", "DIAS", "MONTO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GrillaDetalle.setComponentPopupMenu(jPopupMenu1);
        jScrollPane2.setViewportView(GrillaDetalle);
        if (GrillaDetalle.getColumnModel().getColumnCount() > 0) {
            GrillaDetalle.getColumnModel().getColumn(0).setMinWidth(85);
            GrillaDetalle.getColumnModel().getColumn(0).setPreferredWidth(85);
            GrillaDetalle.getColumnModel().getColumn(0).setMaxWidth(85);
            GrillaDetalle.getColumnModel().getColumn(1).setMinWidth(300);
            GrillaDetalle.getColumnModel().getColumn(1).setPreferredWidth(350);
            GrillaDetalle.getColumnModel().getColumn(1).setMaxWidth(400);
            GrillaDetalle.getColumnModel().getColumn(2).setMinWidth(100);
            GrillaDetalle.getColumnModel().getColumn(2).setPreferredWidth(120);
            GrillaDetalle.getColumnModel().getColumn(2).setMaxWidth(150);
            GrillaDetalle.getColumnModel().getColumn(3).setMinWidth(80);
            GrillaDetalle.getColumnModel().getColumn(3).setPreferredWidth(80);
            GrillaDetalle.getColumnModel().getColumn(3).setMaxWidth(80);
            GrillaDetalle.getColumnModel().getColumn(4).setMinWidth(90);
            GrillaDetalle.getColumnModel().getColumn(4).setPreferredWidth(90);
            GrillaDetalle.getColumnModel().getColumn(4).setMaxWidth(90);
            GrillaDetalle.getColumnModel().getColumn(5).setMinWidth(45);
            GrillaDetalle.getColumnModel().getColumn(5).setPreferredWidth(45);
            GrillaDetalle.getColumnModel().getColumn(5).setMaxWidth(45);
            GrillaDetalle.getColumnModel().getColumn(6).setMinWidth(150);
            GrillaDetalle.getColumnModel().getColumn(6).setPreferredWidth(150);
            GrillaDetalle.getColumnModel().getColumn(6).setMaxWidth(150);
        }

        GrillaDeuda.setBackground(new java.awt.Color(251, 220, 220));
        GrillaDeuda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MONTO DEUDA", "% DEUDA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(GrillaDeuda);
        if (GrillaDeuda.getColumnModel().getColumnCount() > 0) {
            GrillaDeuda.getColumnModel().getColumn(0).setMinWidth(200);
            GrillaDeuda.getColumnModel().getColumn(0).setPreferredWidth(200);
            GrillaDeuda.getColumnModel().getColumn(0).setMaxWidth(200);
            GrillaDeuda.getColumnModel().getColumn(1).setMinWidth(100);
            GrillaDeuda.getColumnModel().getColumn(1).setPreferredWidth(100);
            GrillaDeuda.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        GrillaPagos.setBackground(new java.awt.Color(209, 255, 215));
        GrillaPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MONTO PAGADO", "% PAGADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(GrillaPagos);
        if (GrillaPagos.getColumnModel().getColumnCount() > 0) {
            GrillaPagos.getColumnModel().getColumn(0).setMinWidth(200);
            GrillaPagos.getColumnModel().getColumn(0).setPreferredWidth(200);
            GrillaPagos.getColumnModel().getColumn(0).setMaxWidth(200);
            GrillaPagos.getColumnModel().getColumn(1).setMinWidth(100);
            GrillaPagos.getColumnModel().getColumn(1).setPreferredWidth(100);
            GrillaPagos.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        btCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/refresh16.png"))); // NOI18N
        btCargar.setText("Cargar");
        btCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCargarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ver Detalle"));

        buttonGroup1.add(rbDeudas);
        rbDeudas.setSelected(true);
        rbDeudas.setText("Deudas");
        rbDeudas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDeudasActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbPagos);
        rbPagos.setText("Pagos");
        rbPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPagosActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad:");

        cantidad_label.setText("0");

        btExcel.setText("Excel");
        btExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbPagos)
                    .addComponent(rbDeudas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidad_label, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDeudas)
                    .addComponent(btExcel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPagos)
                    .addComponent(jLabel3)
                    .addComponent(cantidad_label))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        GrillaEjecutivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "iD", "Ejecutivo", "Apellido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(GrillaEjecutivos);
        if (GrillaEjecutivos.getColumnModel().getColumnCount() > 0) {
            GrillaEjecutivos.getColumnModel().getColumn(0).setMinWidth(0);
            GrillaEjecutivos.getColumnModel().getColumn(0).setPreferredWidth(0);
            GrillaEjecutivos.getColumnModel().getColumn(0).setMaxWidth(0);
            GrillaEjecutivos.getColumnModel().getColumn(1).setMinWidth(200);
            GrillaEjecutivos.getColumnModel().getColumn(1).setPreferredWidth(200);
            GrillaEjecutivos.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void Cambioselect(int Numero){
        if(Numero==1){
            GrillaDeuda.getSelectionModel().setSelectionInterval(GrillaTramos.getSelectedRow(),GrillaTramos.getSelectedRow());
            GrillaDeuda.repaint();
            GrillaPagos.getSelectionModel().setSelectionInterval(GrillaTramos.getSelectedRow(),GrillaTramos.getSelectedRow());
            GrillaPagos.repaint();
            CargaDet();
        }
        else if(Numero==2){
            GrillaTramos.getSelectionModel().setSelectionInterval(GrillaDeuda.getSelectedRow(),GrillaDeuda.getSelectedRow());
            GrillaTramos.repaint();
            GrillaPagos.getSelectionModel().setSelectionInterval(GrillaDeuda.getSelectedRow(),GrillaDeuda.getSelectedRow());
            GrillaPagos.repaint();
            CargaDet();
        }
        else{
            GrillaTramos.getSelectionModel().setSelectionInterval(GrillaPagos.getSelectedRow(),GrillaPagos.getSelectedRow());
            GrillaTramos.repaint();
            GrillaDeuda.getSelectionModel().setSelectionInterval(GrillaPagos.getSelectedRow(),GrillaPagos.getSelectedRow());
            GrillaDeuda.repaint();
            CargaDet();
        }
    }
    
    private void CargaDet(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        String Query="";
        DefaultTableModel Model = (DefaultTableModel) GrillaDetalle.getModel();
        String Orden="";
        
        fmMain.LimpiaGrilla(Model);
            
        double Sumador=0;
        
        try {
            
            if(rbDeudas.isSelected()){

                Query = "select cxc.rut,cli.nombre,f.codigo_oc || '-' || f.occh as orden, cxc.nrodocto,cxc.femision, '"+ dtFin.getDate() +"' - cxc.femision as dias,cxc.monto-cxc.pagado as monto\n" +
                        "from cli_cuentasxcobrar cxc\n" +
                        "left join cliente cli on cli.rut=cxc.rut\n" +
                        "left join ctactecli f on f.tipdocto=cxc.tipdocto and f.nrodocto=cxc.nrodocto\n" +
                        "left join cli_cartera car on car.cliente = cxc.rut\n" +
                        "left join personal per on per.rut = car.ejecutivo\n"+
                        "where cxc.femision <= '"+ dtFin.getDate() +"'\n" +
                        " and '"+ dtFin.getDate() +"' - cxc.femision >  "+ GrillaTramos.getValueAt(GrillaTramos.getSelectedRow(),1).toString().trim() +"\n" +
                        " and '"+ dtFin.getDate() +"' - cxc.femision <= "+ GrillaTramos.getValueAt(GrillaTramos.getSelectedRow(),2).toString().trim() +"\n" +
                        " and cxc.monto-cxc.pagado>1\n" ;
                
                if(GrillaEjecutivos.getSelectedRow()==-1){

                }
                else {
                    Query = Query + " and per.apellidopaterno = '"+GrillaEjecutivos.getValueAt(GrillaEjecutivos.getSelectedRow(), 2).toString()+"' \n"
                                    + "and per.nombre = '"+GrillaEjecutivos.getValueAt(GrillaEjecutivos.getSelectedRow(), 1).toString()+"' \n"
                                    + "and car.ejecutivo = "+GrillaEjecutivos.getValueAt(GrillaEjecutivos.getSelectedRow(), 0).toString()+"\n";
                }
                Query = Query + " order by dias\n";
            }
            else{
            
                Query = " select cxc.rut,cli.nombre,f.codigo_oc || '-' || f.occh as orden, max(cxc.nrodocto) as nrodocto,cxc.femision, cp.fechapago  - cxc.femision as dias,cxc.pagado as monto\n" +
                        " from cli_pagos cp\n" +
                        " left join cli_cuentasxcobrar cxc on cxc.id=cp.cuenta\n" +
                        " left join cliente cli on cli.rut=cxc.rut\n" +
                        " left join ctactecli f on f.tipdocto=cxc.tipdocto and f.nrodocto=cxc.nrodocto\n" +
                        "left join cli_cartera car on car.cliente = cxc.rut\n" +
                        "left join personal per on per.rut = car.ejecutivo\n"+
                        " where cp.fechapago between '"+ dtInicio.getDate() +"' and '"+ dtFin.getDate() +"'\n" +
                        " and cp.fechapago - cxc.femision >  "+ GrillaTramos.getValueAt(GrillaTramos.getSelectedRow(),1).toString().trim() +"\n" +
                        " and cp.fechapago - cxc.femision <= "+ GrillaTramos.getValueAt(GrillaTramos.getSelectedRow(),2).toString().trim() +"\n" ;
                
                if(GrillaEjecutivos.getSelectedRow()==-1){
                            
                }
                else {
                    Query = Query + " and per.apellidopaterno = '"+GrillaEjecutivos.getValueAt(GrillaEjecutivos.getSelectedRow(), 2).toString()+"' \n"
                                    + "and per.nombre = '"+GrillaEjecutivos.getValueAt(GrillaEjecutivos.getSelectedRow(), 1).toString()+"' \n"
                                    + "and car.ejecutivo = "+GrillaEjecutivos.getValueAt(GrillaEjecutivos.getSelectedRow(), 0).toString()+"\n";
                }

                Query = Query + " group by cxc.rut,cli.nombre,f.codigo_oc,f.occh,cxc.femision, cxc.pagado ,cp.fechapago\n" +
                " order by dias";
            }
            
            Rs = Sql.Select(Query);
            int cantidad = 0;
            while(Rs.next()){
                try {
                    Orden = Rs.getString("orden").trim();
                } catch (Exception e) {
                    Orden="";
                }
                
                Model.addRow(new Object[]{  Rs.getString("rut").trim(),
                                            Rs.getString("nombre").trim(),
                                            Orden,
                                            Rs.getString("nrodocto").trim(),
                                            Rs.getDate("femision"),
                                            Rs.getInt("dias"),
                                            Rs.getDouble("monto")
                        
                });
                Sumador = Sumador + Rs.getDouble("monto");
                cantidad = cantidad + 1;
            }
            cantidad_label.setText(String.valueOf(cantidad));
            System.out.println(Sumador);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally{
            Sql.Close();
        }
    }
    private void btCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCargarActionPerformed
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel ModelTramo = (DefaultTableModel) GrillaTramos.getModel();
        DefaultTableModel ModelDeuda = (DefaultTableModel) GrillaDeuda.getModel();
        DefaultTableModel ModelPagos = (DefaultTableModel) GrillaPagos.getModel();
        DefaultTableModel ModelDet   = (DefaultTableModel) GrillaDetalle.getModel();
        
        fmMain.LimpiaGrilla(ModelTramo);
        fmMain.LimpiaGrilla(ModelDeuda);
        fmMain.LimpiaGrilla(ModelPagos);
        fmMain.LimpiaGrilla(ModelDet);
        
        
        
        try {
            Rs = Sql.Select("select * from fn_cxc_tramos('"+ dtInicio.getDate() +"','"+ dtFin.getDate() +"')");
            while(Rs.next()){
                ModelTramo.addRow(new Object[]{Rs.getString("tramo").trim(), Rs.getInt("min_tramo"),Rs.getInt("max_tramo") });
                
                ModelDeuda.addRow(new Object[]{Rs.getDouble("deuda"),Rs.getDouble("deuda_porcentaje")});
                
                ModelPagos.addRow(new Object[]{Rs.getDouble("pago"),Rs.getDouble("pago_porcentaje")});
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally{
            Sql.Close();
        }
    }//GEN-LAST:event_btCargarActionPerformed

    private void rbDeudasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDeudasActionPerformed
        CargaDet();
    }//GEN-LAST:event_rbDeudasActionPerformed

    private void rbPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPagosActionPerformed
        CargaDet();
    }//GEN-LAST:event_rbPagosActionPerformed

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        // TODO add your handling code here:
        System.out.println( GrillaDetalle.getValueAt(GrillaDetalle.getSelectedRow(), 1).toString().trim());
        pfCLI_EstadoCXC Pro = new pfCLI_EstadoCXC();

        pnPestanas.addTab("Cuentas por Cobrar", Pro);
        PanelTab btc = new PanelTab(pnPestanas, 0);
        pnPestanas.setTabComponentAt(pnPestanas.indexOfComponent(Pro), btc);
        pnPestanas.setSelectedIndex(pnPestanas.getTabCount() - 1);
        String rut = GrillaDetalle.getValueAt(GrillaDetalle.getSelectedRow(), 0).toString();
        String oc = GrillaDetalle.getValueAt(GrillaDetalle.getSelectedRow(), 2).toString();
        Pro.SetRut(rut, oc);
        
        
    }//GEN-LAST:event_AbrirActionPerformed

    private void btExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcelActionPerformed

        if(GrillaDetalle.getRowCount()==0){
            fmMain.Mensaje("Nada que exportar");
            return;
        }

        //        JFileChooser chooser = new JFileChooser();
        //        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo Excel",".xls");
        //        chooser.setFileFilter(filter);
        //        chooser.setDialogTitle("Guardar Informe en Excel");
        //        chooser.setMultiSelectionEnabled(false);
        //        chooser.setAcceptAllFileFilterUsed(false);

        List<JTable> tb=new ArrayList<>();
        List<String> nom=new ArrayList<>();
        tb.add(GrillaDetalle);
        String str_convenio="conv";
        String str_proveedor="prov";





        nom.add(str_convenio + '_' + str_proveedor);
        String os = System.getProperty("os.name").toString().toLowerCase();
        System.out.println(os);
        File folder  = new File("c:/temp");
        String file = "";
        if(os.contains("win")){

            if (!folder.exists()){
                folder.mkdir();
            }
            file = "C:/temp/convenio_" + str_convenio + '_' + str_proveedor + ".xls";
        }
        else  {
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de excel", "xls");
            chooser.setSelectedFile(new File("/user",".xls"));
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar archivo");
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                file = chooser.getSelectedFile().toString().concat(".xls");
                try {
                    Exporter e = new Exporter(new File(file), tb, nom);
                    if (e.export()) {
                        JOptionPane.showMessageDialog(null, "Los datos fueron exportados en el directorio seleccionado", "Mensaje de Informacion", JOptionPane.INFORMATION_MESSAGE);
                        abrir(file);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Hubo un error " + e.getMessage(), " Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        }

        try {
            Exporter e = new Exporter(new File(file), tb, nom);

            if(e.export())
            //fmMain.Mensaje("Datos Exportados");
            abrir(file);

        } catch (Exception e) {
            fmMain.Mensaje(e.getMessage());
        }
    }//GEN-LAST:event_btExcelActionPerformed
    public void abrir(String file ){

        try {
            String url = file;
            ProcessBuilder p = new ProcessBuilder();
            p.command("cmd.exe", "/c",url);
            p.start();
        } catch (IOException ex) {
            Logger.getLogger(jdOC_PendientesFac.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abrir;
    private javax.swing.JTable GrillaDetalle;
    private javax.swing.JTable GrillaDeuda;
    private javax.swing.JTable GrillaEjecutivos;
    private javax.swing.JTable GrillaPagos;
    private javax.swing.JTable GrillaTramos;
    private javax.swing.JButton btCargar;
    private javax.swing.JButton btExcel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cantidad_label;
    private org.jdesktop.swingx.JXDatePicker dtFin;
    private org.jdesktop.swingx.JXDatePicker dtInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JRadioButton rbDeudas;
    private javax.swing.JRadioButton rbPagos;
    // End of variables declaration//GEN-END:variables
}
