/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Dialogos.jdBuscarClienteDeuda;
import Formularios.fmMain;
import static Formularios.fmMain.GetUsuarioAdministrador;
import static Formularios.fmMain.pnPestanas;
import Utilidades.PanelTab;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import jxl.biff.drawing.ComboBox;
import java.util.logging.Level;
import java.util.logging.Logger;
import jxl.Workbook;
import jxl.WorkbookSettings;
import jxl.format.Alignment;
import jxl.format.Border;
import jxl.format.Colour;
import jxl.format.UnderlineStyle;
import jxl.write.BorderLineStyle;
import jxl.write.NumberFormat;
import jxl.write.WritableCell;
import jxl.write.WritableCellFormat;
import jxl.write.WritableFont;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;


/**
 *
 * @author David Alcaman
 */
public class pfCXC_Cartera extends javax.swing.JPanel {

    /**
     * Creates new form pfCXC_Cartera
     */
    
    SimpleDateFormat formatofecha = new SimpleDateFormat("dd-MM-yyyy");
    Date hoy = new Date();
    
    
    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
    java.util.Date Fecha = new Date();
    boolean Cargando;
    public pfCXC_Cartera() {
        Cargando=true;
        initComponents();
        if (GetUsuarioAdministrador())
            {
            txPagos.setVisible(true);
            lbPagos.setVisible(true);
            }
        else{
            txPagos.setVisible(false);
            lbPagos.setVisible(false);
            }
                   
        CargaCombAño();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        GrillaClientes.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
        GrillaClientes.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        GrillaTramos.getColumnModel().getColumn(1).setCellRenderer(rightRenderer);
        GrillaTramos.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
        CargaEjecutivos();
        cbMes.setSelectedIndex(Fecha.getMonth());
        GrillaEjecutivos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            //Se ejecuta automáticamente cada vez que se hace una nueva selección. 
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(GrillaEjecutivos.getSelectedRowCount()>0){
                    CargaClientes(GrillaEjecutivos.getValueAt(GrillaEjecutivos.getSelectedRow(),0).toString().trim());
                    CargaTramos(GrillaEjecutivos.getValueAt(GrillaEjecutivos.getSelectedRow(),0).toString().trim());
                    CargaPagos(GrillaEjecutivos.getValueAt(GrillaEjecutivos.getSelectedRow(),0).toString().trim());
                }
                    
            }

        });
        
        if(!fmMain.GetUsuarioAdministrador()){
            btAgregar.setEnabled(false);
            btEliminar.setEnabled(false);
        }
        Cargando=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        GrillaEjecutivos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        GrillaClientes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txNroClientes = new javax.swing.JTextField();
        btAgregar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        GrillaTramos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txDeuda = new javax.swing.JTextField();
        txVencida = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbPagos = new javax.swing.JLabel();
        txPagos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbMes = new javax.swing.JComboBox<String>();
        cbAgno = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txPagosNeto = new javax.swing.JTextField();
        btExportar = new javax.swing.JButton();

        GrillaEjecutivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Ejecutiva"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GrillaEjecutivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaEjecutivosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(GrillaEjecutivos);
        if (GrillaEjecutivos.getColumnModel().getColumnCount() > 0) {
            GrillaEjecutivos.getColumnModel().getColumn(0).setMinWidth(0);
            GrillaEjecutivos.getColumnModel().getColumn(0).setPreferredWidth(0);
            GrillaEjecutivos.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        GrillaClientes.setAutoCreateRowSorter(true);
        GrillaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Rut", "Nombre", "Total", "Vencida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GrillaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaClientesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(GrillaClientes);
        if (GrillaClientes.getColumnModel().getColumnCount() > 0) {
            GrillaClientes.getColumnModel().getColumn(0).setMinWidth(80);
            GrillaClientes.getColumnModel().getColumn(0).setPreferredWidth(80);
            GrillaClientes.getColumnModel().getColumn(0).setMaxWidth(80);
            GrillaClientes.getColumnModel().getColumn(2).setMinWidth(95);
            GrillaClientes.getColumnModel().getColumn(2).setPreferredWidth(95);
            GrillaClientes.getColumnModel().getColumn(2).setMaxWidth(95);
            GrillaClientes.getColumnModel().getColumn(3).setMinWidth(95);
            GrillaClientes.getColumnModel().getColumn(3).setPreferredWidth(95);
            GrillaClientes.getColumnModel().getColumn(3).setMaxWidth(95);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nro. Clientes");

        txNroClientes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(txNroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txNroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Agregar.png"))); // NOI18N
        btAgregar.setText("Agregar");
        btAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarActionPerformed(evt);
            }
        });

        btEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Cancel16.png"))); // NOI18N
        btEliminar.setText("Eliminar");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Deuda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        GrillaTramos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Periodo", "Deuda", "%"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(GrillaTramos);
        if (GrillaTramos.getColumnModel().getColumnCount() > 0) {
            GrillaTramos.getColumnModel().getColumn(2).setMinWidth(45);
            GrillaTramos.getColumnModel().getColumn(2).setPreferredWidth(45);
            GrillaTramos.getColumnModel().getColumn(2).setMaxWidth(45);
        }

        jLabel2.setText("Deuda Total");

        jLabel3.setText("Deuda Vencida");

        txDeuda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txDeuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDeudaActionPerformed(evt);
            }
        });

        txVencida.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txVencida, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txVencida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pagos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        lbPagos.setText("Pagos");

        txPagos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel6.setText("Mes");

        cbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesActionPerformed(evt);
            }
        });

        cbAgno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbAgno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAgnoActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Año");

        jLabel7.setText("Neto");

        txPagosNeto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbPagos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbAgno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txPagos)
                    .addComponent(cbMes, 0, 120, Short.MAX_VALUE)
                    .addComponent(txPagosNeto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAgno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPagos)
                    .addComponent(txPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txPagosNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/OCProveedor24.png"))); // NOI18N
        btExportar.setText("Exportar");
        btExportar.setToolTipText("");
        btExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(6, 6, 6)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarActionPerformed
        jdBuscarClienteDeuda Morosos = new jdBuscarClienteDeuda(null, true);
        Morosos.setLocationRelativeTo(null);
        Morosos.setTitle("Clientes con Deuda");
        Morosos.setVisible(true);
        if(!Morosos.GetRut().isEmpty()){
            ExeSql Sql = new ExeSql();
            try {
                Sql.ExeSql("insert into cli_cartera (ejecutivo,cliente) values (" + 
                        GrillaEjecutivos.getValueAt(GrillaEjecutivos.getSelectedRow(), 0).toString().trim() + "," +
                        Morosos.GetRut() + ")");
                Sql.Commit();
                CargaClientes(GrillaEjecutivos.getValueAt(GrillaEjecutivos.getSelectedRow(), 0).toString().trim());
                CargaTramos(GrillaEjecutivos.getValueAt(GrillaEjecutivos.getSelectedRow(), 0).toString().trim());
            } catch (Exception e) {
                Sql.Rollback();
                fmMain.Mensaje(e.getMessage());
            } finally{
                Sql.Close();
            }
        }
    }//GEN-LAST:event_btAgregarActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
        ExeSql Sql = new ExeSql();
        try {
            Sql.ExeSql("delete from cli_cartera \n" +
                       "where ejecutivo=" + GrillaEjecutivos.getValueAt(GrillaEjecutivos.getSelectedRow(),0).toString() + "\n" +
                       "and cliente=" + GrillaClientes.getValueAt(GrillaClientes.getSelectedRow(), 0).toString()
                    );
            Sql.Commit();
            CargaClientes(GrillaEjecutivos.getValueAt(GrillaEjecutivos.getSelectedRow(), 0).toString().trim());
            CargaTramos(GrillaEjecutivos.getValueAt(GrillaEjecutivos.getSelectedRow(), 0).toString().trim());
        } catch (Exception e) {
            Sql.Rollback();
            fmMain.Mensaje(e.getMessage());
        } finally{
            Sql.Close();
        }
    }//GEN-LAST:event_btEliminarActionPerformed
    private void CargaPagos(String Ejecutivo){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        String Query ="";
        try {
            Query = "select sum(p.monto) as Pago\n" +
                            " from cli_pagos p\n" +
                            " left join cli_cuentasxcobrar cxc on p.cuenta=cxc.id\n" +
                            " where extract(month from p.fechapago)="+ String.valueOf(cbMes.getSelectedIndex() + 1) +"\n" +
                            " and extract(year from p.fechapago)=" + cbAgno.getSelectedItem().toString()  + " \n" +
                            " and cxc.rut in (select cliente from cli_cartera where ejecutivo="+ Ejecutivo +")\n" +
                            " and p.tipopago<>4";
// Fecha : 25-01-2017
//Modificacion: Se agrega el Año en la pantalla para la carga de Pagos.             //011714029
//
// Comentario de Query Anterior            
//            "select sum(p.monto) as Pago\n" +
//                            "from cli_pagos p\n" +
//                            "left join cli_cuentasxcobrar cxc on p.cuenta=cxc.id\n" +
//                            "where extract(month from p.fechapago)="+ String.valueOf(cbMes.getSelectedIndex() + 1) +"\n" +
//                            "and extract(year from p.fechapago)=2016\n" +
//                            "and cxc.rut in (select cliente from cli_cartera where ejecutivo="+ Ejecutivo +")\n" +
//                            "and p.tipopago<>4"

//---------------------------------------------------------------------------------------------------------
            Rs = Sql.Select(Query);
            if(Sql.GetRowCount()>0){
                Rs.next();
                txPagos.setText(fmMain.FormatoTotal(Rs.getDouble("Pago")));
                txPagosNeto.setText(fmMain.FormatoTotal(Rs.getDouble("Pago")/1.19));
            }
        } catch (Exception e) {
            
        }finally{
            Sql.Close();
        }
    }
    private void GrillaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaClientesMouseClicked
        if(evt.getClickCount()==2){
            pfCLI_EstadoCXC CxC = new pfCLI_EstadoCXC();
            CxC.CargaClienteCartera(GrillaClientes.getValueAt(GrillaClientes.getSelectedRow(), 0).toString().trim());
            pnPestanas.addTab("Cuentas por Cobrar", CxC);
            PanelTab btc = new PanelTab(pnPestanas, 0);
            pnPestanas.setTabComponentAt(pnPestanas.indexOfComponent(CxC), btc);
            pnPestanas.setSelectedIndex(pnPestanas.getTabCount() - 1);
        }
    }//GEN-LAST:event_GrillaClientesMouseClicked

    private void cbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesActionPerformed
        if(!Cargando)
            CargaPagos(GrillaEjecutivos.getValueAt(GrillaEjecutivos.getSelectedRow(),0).toString().trim());
    }//GEN-LAST:event_cbMesActionPerformed

    private void cbAgnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAgnoActionPerformed
        if(!Cargando)
            CargaPagos(GrillaEjecutivos.getValueAt(GrillaEjecutivos.getSelectedRow(),0).toString().trim());        // TODO add your handling code here:
    }//GEN-LAST:event_cbAgnoActionPerformed

    private void GrillaEjecutivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaEjecutivosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GrillaEjecutivosMouseClicked

    private void btExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExportarActionPerformed
       
             
        File ruta = null;                                           
        File carpeta = null;
       // String sSistemaOperativo = System.getProperty("os.name");
        carpeta = new File("C:\\informe_cartera\\");
        if (!carpeta.exists()){  //Si la carpeta no existe, se crea
            
            carpeta.mkdir();
            
        }
        
        String Cartera = GrillaEjecutivos.getValueAt(GrillaEjecutivos.getSelectedRow(),1).toString().trim();
        
        ruta = new File("C:\\informe_cartera\\Informe_Cartera_"+Cartera+"_"+formatofecha.format(hoy)+".xls");
        WorkbookSettings conf = new WorkbookSettings();
        conf.setEncoding("ISO-8859-1");
        try {
            
            WritableWorkbook libro = Workbook.createWorkbook(ruta,conf);     //Se crea libro de excel
            WritableFont Fuente = new WritableFont(WritableFont.ARIAL, 10, WritableFont.BOLD,false, UnderlineStyle.NO_UNDERLINE, Colour.WHITE);
            
            
            WritableCellFormat format = new WritableCellFormat();               //Alineación para los encabezados
            format.setAlignment(Alignment.CENTRE);
            format.setBackground(Colour.GREY_40_PERCENT);
            format.setFont(Fuente);
            format.setBorder(Border.ALL, BorderLineStyle.THIN,Colour.BLACK); //table border style
            format.setWrap(true);
            
            
           NumberFormat decimalNo = new NumberFormat("#,##0"); 
            
            WritableCellFormat format2 = new WritableCellFormat(decimalNo);              //Alineación para los datos numericos a la derecha
            format2.setAlignment(Alignment.RIGHT);
            format2.setBorder(Border.ALL, BorderLineStyle.THIN,Colour.BLACK); //table border style
      
 
            
            WritableCellFormat format3 = new WritableCellFormat();              //Alineación para los datos texto a la izquierda
            format3.setAlignment(Alignment.LEFT);
            format3.setBorder(Border.ALL, BorderLineStyle.THIN,Colour.BLACK); //table border style
            
            WritableCellFormat format4 = new WritableCellFormat();              //Alineación para los datos texto al centro
            format4.setAlignment(Alignment.CENTRE);
            format4.setBorder(Border.ALL, BorderLineStyle.THIN,Colour.BLACK); //table border style
            
            
            WritableCellFormat format5 = new WritableCellFormat(decimalNo);              //Alineación para los Totales a la derecha
            format2.setAlignment(Alignment.RIGHT);
            //format2.setBorder(Border.ALL, BorderLineStyle.THIN,Colour.BLACK); //table border style
            
            
            
            WritableSheet hoja = libro.createSheet("Informe de Deudas", 0);     //Se le asigna nombre a la primera hoja(0) del libro excel
            hoja.setColumnView(0, 15);     //Rut                                  //Ancho de la columna (en número de caracteres)
            hoja.setColumnView(1, 80);     //Nombre
            hoja.setColumnView(2, 15);     //Deuda
            hoja.setColumnView(3, 15);     //Dias de Vencimiento
            
            
            
            hoja.setRowView(0,26*20);    //la altura de la fila del encabezado
            
            //********************************  Se agregan contenido a las celdas de la hoja  *******************************************
            hoja.addCell(new jxl.write.Label(0,0,"Rut",format));
            hoja.addCell(new jxl.write.Label(1,0,"Nombre",format));
            hoja.addCell(new jxl.write.Label(2,0,"Total",format));
            hoja.addCell(new jxl.write.Label(3,0,"Vencida",format));
           
            double totaldeuda = 0;
            double totalvencida = 0;
            
            int fila = GrillaClientes.getRowCount();
            
            for (int i = 0; i < GrillaClientes.getRowCount(); i++) {
                
                double deuda = Double.parseDouble(GrillaClientes.getValueAt(i,2).toString().trim().replaceAll("\\,",""));
                double vencida = Double.parseDouble(GrillaClientes.getValueAt(i,3).toString().trim().replaceAll("\\,",""));
                
                totaldeuda = totaldeuda + deuda;
                totalvencida = totalvencida + vencida;
                
                hoja.addCell(new jxl.write.Label(0,i+1,GrillaClientes.getValueAt(i,0).toString().trim(),format4));
                hoja.addCell(new jxl.write.Label(1,i+1,GrillaClientes.getValueAt(i,1).toString().trim(),format3));
                hoja.addCell(new jxl.write.Number(2,i+1,deuda,format2));
                hoja.addCell(new jxl.write.Number(3,i+1,vencida,format2));
                
                
                
            }
            
            hoja.addCell(new jxl.write.Label(0,fila+1,"",format5));
            hoja.addCell(new jxl.write.Label(1,fila+1,"",format5));
            hoja.addCell(new jxl.write.Number(2,fila+1,totaldeuda,format5));
            hoja.addCell(new jxl.write.Number(3,fila+1,totalvencida,format5));
            
            
            
            //***************************************************************************************************************************
            libro.write();          //Se escriben el contenido en el libro
            libro.close();          //se cierra el libro
            
            fmMain.Mensaje("Archivo : Informe_Cartera_"+Cartera+"_"+formatofecha.format(hoy)+".xls \n creado con éxito");
            
        } catch (WriteException | IOException ex) {
            Logger.getLogger(pfCXC_Cartera.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
        
        
    }//GEN-LAST:event_btExportarActionPerformed

    private void txDeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDeudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDeudaActionPerformed
    private void CargaEjecutivos(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel Model = (DefaultTableModel) GrillaEjecutivos.getModel();
        fmMain.LimpiaGrilla(Model);
        
        String Nombre = "";
        try {
//            Rs = Sql.Select("select p.rut,p.apellidopaterno || ', ' || p.nombre as nombre\n" +
//                            "from personal_ccostos cc\n" +
//                            "left join personal p on cc.rut=p.rut\n" +
//                            "where cc.ccosto=3\n" +
//                            "and p.rut>10000");
            
            
             Rs = Sql.Select("select p.rut, p.nombre || ' ' || p.apellidopaterno as nombre\n" +
                            "from personal_ccostos cc\n" +
                            "left join personal p on cc.rut=p.rut\n" +
                            "where cc.ccosto=3\n" +
                            "and p.rut>10000");
            
            while(Rs.next()){
                
                Nombre =  Rs.getString("nombre").trim();
                
                if (Rs.getString("rut").equals("19196156")){
                
                        Nombre = "CARTERA MUNICIPAL";
                    
                }
                
                if (Rs.getString("rut").equals("18193732")){
                
                        Nombre = "CARTERA SALUD";
                    
                }
                
                if (Rs.getString("rut").equals("76440015")){
                
                        Nombre = "CARTERA ECONA";
                    
                }
                
                if (Rs.getString("rut").equals("77244658")){
                
                        Nombre = "CARTERA DISOSUR";
                    
                }
                
                
                Model.addRow(new Object[]{
                                Rs.getString("rut").trim(),
//                                Rs.getString("nombre").trim()
                                Nombre
                });
            }
            
            
            
            
        } catch (Exception e) {
        }finally{
            Sql.Close();
        }
       
    }
    
    private void CargaCombAño(){
        cbAgno.removeAllItems();
        Calendar fecha = new GregorianCalendar();
        //Obtenemos el valor del año, mes, día,
        //hora, minuto y segundo del sistema
        //usando el método get y el parámetro correspondiente
        int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
       /* int dia = fecha.get(Calendar.DAY_OF_MONTH);
        int hora = fecha.get(Calendar.HOUR_OF_DAY);
        int minuto = fecha.get(Calendar.MINUTE);
        int segundo = fecha.get(Calendar.SECOND);*/
        
        String anox ="x";
        String mesx ="x";
        
        anox = String.valueOf(año);
        mesx = String.valueOf(mes+1);

        
        for (int ano=año-5; ano <= año+5; ano++){
            cbAgno.addItem( String.valueOf(ano));
        }
        
        
        
        cbAgno.setSelectedItem(anox); 
        cbMes.setSelectedItem(mesx); 
        
    }
    private void CargaClientes(String Ejecutivo){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel Model = (DefaultTableModel) GrillaClientes.getModel();
        double Deuda=0,Vencida=0;
        
        fmMain.LimpiaGrilla(Model);
        
        try {
//            Rs = Sql.Select("select cc.cliente,c.nombre,\n" +
//                            "(select sum(monto-pagado) from cli_cuentasxcobrar where rut=cc.cliente)as Deuda,\n" +
//                            "(select sum(monto-pagado) from cli_cuentasxcobrar where rut=cc.cliente and current_date - femision > 30)as Vencido\n" +
//                            "from cli_cartera cc \n" +
//                            "left join cliente c on cc.cliente=c.rut\n" +
//                            "where cc.ejecutivo="+ Ejecutivo +" and (select sum(monto-pagado) from cli_cuentasxcobrar where rut=cc.cliente) > 0 \n" +
//                            "group by cc.cliente,c.nombre\n" +
//                            "order by Vencido desc");
            
            
            
            
            
             Rs = Sql.Select("select cc.cliente,c.nombre,\n" +
                             "case \n" +
                             "	when (select sum(monto-pagado) from cli_cuentasxcobrar where rut=cc.cliente) is null\n" +
                             "       then 0\n" +
                             "       else (select sum(monto-pagado) from cli_cuentasxcobrar where rut=cc.cliente)\n" +
                             "end as Deuda,\n" +
                             "case \n" +
                             "	when (select sum(monto-pagado) from cli_cuentasxcobrar where rut=cc.cliente and current_date - femision > 30) is null \n" +
                             "    	then 0\n" +
                             "		else (select sum(monto-pagado) from cli_cuentasxcobrar where rut=cc.cliente and current_date - femision > 30)\n" +
                             "end as Vencido\n" +
                             "from cli_cartera cc \n" +
                             "left join cliente c on cc.cliente=c.rut\n" +
                             "where cc.ejecutivo="+ Ejecutivo +" and (select sum(monto-pagado) from cli_cuentasxcobrar where rut=cc.cliente) > 0 \n" +
                             "group by cc.cliente,c.nombre\n" +
                             "order by Vencido desc");
            
            txNroClientes.setText(String.valueOf(Sql.GetRowCount()));
            
            if(Sql.GetRowCount()==0){
                txDeuda.setText("0");
                txVencida.setText("0");
            }
            
            while(Rs.next()){
                
                Double deudanull = new Double(Rs.getDouble("deuda"));
                Double vencnull = new Double(Rs.getDouble("vencido"));
                
                double GetDeuda = 0;
                double GetVencido = 0;
                
                if(deudanull != null){
                    
                    GetDeuda = Rs.getDouble("deuda");
                
                }else {
                
                    GetDeuda = 0;
                    
                }
                
                if(vencnull != null){
                    
                    GetVencido = Rs.getDouble("vencido");
                
                }else {
                
                    GetVencido = 0;
                    
                }
                
                Model.addRow(new Object[]{
                    Rs.getString("cliente"),
                    Rs.getString("nombre").trim(),
                    //fmMain.FormatoTotal(Rs.getDouble("deuda")),
                    fmMain.FormatoTotal(GetDeuda),
                   // fmMain.FormatoTotal(Rs.getDouble("vencido"))
                    fmMain.FormatoTotal(GetVencido)
                });
                
                    
                Deuda = Deuda + Rs.getDouble("deuda");
                
                Vencida = Vencida + Rs.getDouble("vencido");
                
                
                txDeuda.setText(fmMain.FormatoTotal(Deuda));
                txVencida.setText(fmMain.FormatoTotal(Vencida));
            }
            
            
        } catch (Exception e) {
            Sql.Rollback();
            fmMain.Mensaje("Error: " + e.getMessage());
        }finally{
            Sql.Close();
        }
        
    }
    
    
       
    private void CargaTramos(String Ejecutivo){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        ResultSet Rs2;
        ResultSet Rs3;
        ResultSet Rs4;
        ResultSet Rs5;
        ResultSet Rs6;
        ResultSet Rs7;
        DefaultTableModel Model = (DefaultTableModel) GrillaTramos.getModel();
        int Total=0;
        
        fmMain.LimpiaGrilla(Model);
        
        try {
//            Rs = Sql.Select("select \n" +
//                            "sum((select sum(monto - pagado) from cli_cuentasxcobrar where current_date - femision<=30 and rut=c.cliente)) as uno,\n" +
//                            "sum((select sum(monto - pagado) from cli_cuentasxcobrar where current_date - femision between 31  and 60 and rut=c.cliente)) as dos,\n" +
//                            "sum((select sum(monto - pagado) from cli_cuentasxcobrar where current_date - femision between 61  and 90 and rut=c.cliente)) as tres,\n" +
//                            "sum((select sum(monto - pagado) from cli_cuentasxcobrar where current_date - femision between 91  and 120 and rut=c.cliente))as cuatro,\n" +
//                            "sum((select sum(monto - pagado) from cli_cuentasxcobrar where current_date - femision between 121 and 150 and rut=c.cliente))as cinco,\n" +
//                            "sum((select sum(monto - pagado) from cli_cuentasxcobrar where current_date - femision between 151 and 180 and rut=c.cliente)) as seis,\n" +
//                            "sum((select sum(monto - pagado) from cli_cuentasxcobrar where current_date - femision >180 and rut=c.cliente)) as siete\n" +
//                            "\n" +
//                            "from cli_cartera c\n" +
//                            "where c.ejecutivo=" + Ejecutivo);
            
                Rs = Sql.Select("select sum(cli.monto - cli.pagado ) as uno from cli_cartera c\n" +
                                "left join cli_cuentasxcobrar cli on c.cliente = cli.rut\n" +
                                "where c.ejecutivo="+Ejecutivo+"  and current_date - femision <=30 and (cli.monto - cli.pagado ) > 0");
            
                Rs.next();
                
                Total=Rs.getInt("uno");
            
            
                Rs2 = Sql.Select("select sum(cli.monto - cli.pagado ) as dos from cli_cartera c\n" +
                                "left join cli_cuentasxcobrar cli on c.cliente = cli.rut\n" +
                                "where c.ejecutivo="+Ejecutivo+"  and current_date - femision between 31 and 60 and (cli.monto - cli.pagado ) > 0");
            
                Rs2.next();
                
                Total= Total + Rs2.getInt("dos");
                
                
                Rs3 = Sql.Select("select sum(cli.monto - cli.pagado ) as tres from cli_cartera c\n" +
                                "left join cli_cuentasxcobrar cli on c.cliente = cli.rut\n" +
                                "where c.ejecutivo="+Ejecutivo+"  and current_date - femision between 61 and 90 and (cli.monto - cli.pagado ) > 0");
            
                Rs3.next();
                
                Total= Total + Rs3.getInt("tres");
                
                
                
                Rs4 = Sql.Select("select sum(cli.monto - cli.pagado ) as cuatro from cli_cartera c\n" +
                                "left join cli_cuentasxcobrar cli on c.cliente = cli.rut\n" +
                                "where c.ejecutivo="+Ejecutivo+"  and current_date - femision between 91 and 120 and (cli.monto - cli.pagado ) > 0");
            
                Rs4.next();
                
                Total= Total + Rs4.getInt("cuatro");
                
                
                Rs5 = Sql.Select("select sum(cli.monto - cli.pagado ) as cinco from cli_cartera c\n" +
                                "left join cli_cuentasxcobrar cli on c.cliente = cli.rut\n" +
                                "where c.ejecutivo="+Ejecutivo+"  and current_date - femision between 121 and 150 and (cli.monto - cli.pagado ) > 0");
            
                Rs5.next();
                
                Total= Total + Rs5.getInt("cinco");
                
                
                Rs6 = Sql.Select("select sum(cli.monto - cli.pagado ) as seis from cli_cartera c\n" +
                                "left join cli_cuentasxcobrar cli on c.cliente = cli.rut\n" +
                                "where c.ejecutivo="+Ejecutivo+"  and current_date - femision between 151 and 180 and (cli.monto - cli.pagado ) > 0");
            
                Rs6.next();
                
                Total= Total + Rs6.getInt("seis");
                
                
            
                Rs7 = Sql.Select("select sum(cli.monto - cli.pagado ) as siete from cli_cartera c\n" +
                             "left join cli_cuentasxcobrar cli on c.cliente = cli.rut\n" +
                             "where c.ejecutivo="+Ejecutivo+"  and current_date - femision > 180 and (cli.monto - cli.pagado ) > 0");
            
                Rs7.next();
               // Total=Rs.getInt("uno") + Rs.getInt("dos") + Rs.getInt("tres") + Rs.getInt("cuatro") + Rs.getInt("cinco") + Rs.getInt("seis") + Rs.getInt("siete");
                Total=Total + Rs7.getInt("siete");
                
                
                
                
                
            
                if(Total>0){
                   Model.addRow(new Object[]{"Vigente",fmMain.FormatoTotal(Rs.getDouble("uno")), String.valueOf(Math.round((Rs.getDouble("uno")*100/Total))) + "%"});
                   Model.addRow(new Object[]{"30-60",fmMain.FormatoTotal(Rs2.getDouble("dos")), String.valueOf(Math.round((Rs2.getDouble("dos")*100/Total))) + "%"});
                    Model.addRow(new Object[]{"60-90",fmMain.FormatoTotal(Rs3.getDouble("tres")), String.valueOf(Math.round((Rs3.getDouble("tres")*100/Total))) + "%"});
                    Model.addRow(new Object[]{"90-120",fmMain.FormatoTotal(Rs4.getDouble("cuatro")), String.valueOf(Math.round((Rs4.getDouble("cuatro")*100/Total))) + "%"});
                    Model.addRow(new Object[]{"120-150",fmMain.FormatoTotal(Rs5.getDouble("cinco")), String.valueOf(Math.round((Rs5.getDouble("cinco")*100/Total))) + "%"});
                    Model.addRow(new Object[]{"150-180",fmMain.FormatoTotal(Rs6.getDouble("seis")), String.valueOf(Math.round((Rs6.getDouble("seis")*100/Total))) + "%"});
                    Model.addRow(new Object[]{"Mayor a 180",fmMain.FormatoTotal(Rs7.getDouble("siete")), String.valueOf(Math.round((Rs7.getDouble("siete")*100/Total))) + "%"});
                }
            
        } catch (SQLException e) {
            Sql.Rollback();
            fmMain.Mensaje(e.getMessage());
            Logger.getLogger(pfCXC_Cartera.class.getName()).log(Level.SEVERE, null, e);
        } finally{
            Sql.Close();
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GrillaClientes;
    private javax.swing.JTable GrillaEjecutivos;
    private javax.swing.JTable GrillaTramos;
    private javax.swing.JButton btAgregar;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btExportar;
    private javax.swing.JComboBox<String> cbAgno;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbPagos;
    private javax.swing.JTextField txDeuda;
    private javax.swing.JTextField txNroClientes;
    private javax.swing.JTextField txPagos;
    private javax.swing.JTextField txPagosNeto;
    private javax.swing.JTextField txVencida;
    // End of variables declaration//GEN-END:variables
}
