/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Dialogos.jdAbrirDocumento;
import Dialogos.jdBuscarCliPrv;
import Dialogos.jdIngresaNumero;
import Formularios.fmMain;
import Utilidades.GeneraDTE;
import facturas.ArrayOfString;
import facturas.DTE;
import facturas.DTESoap;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.CookieHandler;
import java.net.CookieManager;
import java.net.CookiePolicy;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.PrintService;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.printing.PDFPageable;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.Namespace;
import org.jdom2.output.Format;
import org.jdom2.output.XMLOutputter;

/**
 *
 * @author David Alcaman
 */
public class pfNDBCliente extends javax.swing.JPanel {

    String RutMaster;
    int Tipo; // 0::Nuevo    1:Abrir
    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
    private enum Columnas{Sku,Nombre,UM,Cantidad,Unitario,Total};
    private String Codigo_OC;
    private String NroOrden;
    private int ElTipo,PosTipoDoc;
    private String ElMotivo;
    
    public pfNDBCliente() {
        initComponents();
        SetTipo(-1);
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        Grilla.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        Grilla.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
        Grilla.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMenu = new javax.swing.JPanel();
        btNuevo = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btEmitir = new javax.swing.JButton();
        btAbrir = new javax.swing.JButton();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txRut = new javax.swing.JTextField();
        txDv = new javax.swing.JTextField();
        btIr = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txDireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txComuna = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txCiudad = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lbFolio = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txEstado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dtEmision = new org.jdesktop.swingx.JXDatePicker();
        btPDF = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txNroDocumento = new javax.swing.JTextField();
        btCargaDocumento = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txExento = new javax.swing.JTextField();
        txNeto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txIva = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txTotal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txImpEspecifico = new javax.swing.JTextField();

        pnMenu.setBackground(new java.awt.Color(220, 215, 226));

        btNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/add16.png"))); // NOI18N
        btNuevo.setText("Nuevo");
        btNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoActionPerformed(evt);
            }
        });

        btGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/save16.png"))); // NOI18N
        btGuardar.setText("Guardar");
        btGuardar.setBorder(null);
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Cancel16.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btEmitir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/derecha16.png"))); // NOI18N
        btEmitir.setText("Emitir");
        btEmitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmitirActionPerformed(evt);
            }
        });

        btAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/open16.png"))); // NOI18N
        btAbrir.setText("Abrir");
        btAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirActionPerformed(evt);
            }
        });

        jXLabel1.setText("NOTA DE DÉBITO CLIENTE");
        jXLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout pnMenuLayout = new javax.swing.GroupLayout(pnMenu);
        pnMenu.setLayout(pnMenuLayout);
        pnMenuLayout.setHorizontalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177)
                .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAbrir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btEmitir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnMenuLayout.setVerticalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btNuevo)
                            .addComponent(btAbrir)
                            .addComponent(btEmitir))
                        .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btCancelar)
                            .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel1.setText("Rut");

        txRut.setEnabled(false);
        txRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txRutKeyPressed(evt);
            }
        });

        txDv.setEditable(false);

        btIr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/Go.png"))); // NOI18N
        btIr.setBorderPainted(false);
        btIr.setEnabled(false);
        btIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIrActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        txNombre.setEnabled(false);

        jLabel9.setText("Dirección");

        txDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDireccionActionPerformed(evt);
            }
        });

        jLabel7.setText("Comuna");

        jLabel8.setText("Ciudad");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txRut, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txDv, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btIr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                    .addComponent(txDireccion)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(txComuna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(txRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btIr)
                        .addComponent(txDv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("NOTA DE DÉBITO");

        lbFolio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbFolio.setForeground(new java.awt.Color(255, 51, 51));

        jLabel5.setText("F. Emisión");

        txEstado.setEditable(false);

        jLabel6.setText("Estado");

        btPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/pdf.png"))); // NOI18N
        btPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbFolio)
                .addGap(155, 155, 155))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txEstado)
                    .addComponent(dtEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(lbFolio))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(dtEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Referencia"));

        jLabel3.setText("Tipo");

        jLabel4.setText("Numero");

        txNroDocumento.setEnabled(false);
        txNroDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txNroDocumentoKeyPressed(evt);
            }
        });

        btCargaDocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/Go.png"))); // NOI18N
        btCargaDocumento.setBorderPainted(false);
        btCargaDocumento.setEnabled(false);
        btCargaDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCargaDocumentoActionPerformed(evt);
            }
        });

        jLabel16.setText("Tipo");

        jTextField1.setEditable(false);
        jTextField1.setText("Nota de Crédito");

        jTextField2.setEditable(false);
        jTextField2.setText("Anula Documento");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txNroDocumento)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCargaDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txNroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btCargaDocumento))
                .addGap(8, 8, 8))
        );

        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "UM", "Cantidad", "V. Unitario", "Total Linea"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(0).setMinWidth(60);
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(0).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(1).setMinWidth(400);
            Grilla.getColumnModel().getColumn(1).setPreferredWidth(400);
            Grilla.getColumnModel().getColumn(2).setMinWidth(35);
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(35);
            Grilla.getColumnModel().getColumn(2).setMaxWidth(45);
            Grilla.getColumnModel().getColumn(3).setMinWidth(75);
            Grilla.getColumnModel().getColumn(3).setPreferredWidth(75);
            Grilla.getColumnModel().getColumn(3).setMaxWidth(85);
            Grilla.getColumnModel().getColumn(4).setMinWidth(75);
            Grilla.getColumnModel().getColumn(4).setPreferredWidth(75);
            Grilla.getColumnModel().getColumn(4).setMaxWidth(85);
            Grilla.getColumnModel().getColumn(5).setMinWidth(80);
            Grilla.getColumnModel().getColumn(5).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(5).setMaxWidth(90);
        }

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel11.setText("Exento");

        txExento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txExento.setText("0");

        txNeto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txNeto.setText("0");

        jLabel10.setText("Neto");

        txIva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txIva.setText("0");
        txIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIvaActionPerformed(evt);
            }
        });

        jLabel12.setText("I.V.A.");

        txTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txTotal.setText("0");

        jLabel13.setText("TOTAL");

        jLabel17.setText("Imp. específico");

        txImpEspecifico.setEditable(false);
        txImpEspecifico.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txImpEspecifico.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txExento, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(txNeto)
                    .addComponent(txIva)
                    .addComponent(txTotal)
                    .addComponent(txImpEspecifico))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txExento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txImpEspecifico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    static public int GetCol(String Col){
        return Columnas.valueOf(Col).ordinal();
    }
     private void SetTipo(int ElTipo){
        // NADA
        if(ElTipo==-1){
          fmMain.SetEstado(fmMain.pnPestanas.getSelectedIndex(),0);
          Habilita(false);
          Edicion(false);
          Limpia();
          btIr.setEnabled(true);
          txRut.requestFocus();
          btCancelar.setEnabled(false);
          btGuardar.setEnabled(false);
          btNuevo.setEnabled(true);
          Tipo=-1;
          
        }
        // NUEVA ORDEN   
        else if(ElTipo==1){
          fmMain.SetEstado(fmMain.pnPestanas.getSelectedIndex(),1);
          btGuardar.setEnabled(true);
          btCancelar.setEnabled(true);
          btNuevo.setEnabled(false);
          txEstado.setText("Sin Emitir");

          Habilita(true);
          Edicion(true);
          Limpia();
          txRut.requestFocus();
          Tipo=1;
        }
        else if(ElTipo==2){
          fmMain.SetEstado(fmMain.pnPestanas.getSelectedIndex(),0);
          btNuevo.setEnabled(true);
          btGuardar.setEnabled(false);
          btCancelar.setEnabled(false);
          Habilita(true);
          Edicion(false);
          txRut.setEditable(true);
          Tipo=2;
        }
        else if(ElTipo==3){
           // btEmitir.setEnabled(false);
            btGuardar.setEnabled(true);
            btCancelar.setEnabled(true);
            btNuevo.setEnabled(false);
            Habilita(true);
            Edicion(true);
            Tipo=3;
        }
    }
//--------------------------------------------------------------------------------
// EDICION
//--------------------------------------------------------------------------------
private void Edicion(boolean Estado){
    
//    txNroOc.setEditable(Estado);
    txDireccion.setEditable(Estado);
    txCiudad.setEditable(Estado);
    txComuna.setEditable(Estado);
    txRut.setEditable(Estado);
    txNombre.setEditable(Estado);
    txDv.setEditable(Estado);
    txNroDocumento.setEditable(Estado);
    txNeto.setEditable(Estado);
    txExento.setEditable(Estado);
    txIva.setEditable(Estado);
    txTotal.setEditable(Estado);
    btCargaDocumento.setEnabled(Estado);
    txNroDocumento.setEditable(Estado);
    

}
//--------------------------------------------------------------------------------
// LIMPIA
//--------------------------------------------------------------------------------
private void Limpia(){
    DefaultComboBoxModel dfCm = new DefaultComboBoxModel();
    DefaultTableModel   dfTm = (DefaultTableModel) Grilla.getModel();
    txRut.setText("");
    txNombre.setText("");
    txDv.setText("");
    txNeto.setText("");
    txExento.setText("");
    txIva.setText("");
    txTotal.setText("");
    txDireccion.setText("");
    txComuna.setText("");
    txCiudad.setText("");
    txNroDocumento.setText("");
           
//    cbTipoDocumento.setModel(dfCm);
//    cbContacto.setModel(dfCm);
    
        
    while(dfTm.getRowCount()>0)
        dfTm.removeRow(0);
    //chbPrioridad.
    
}    
//--------------------------------------------------------------------------------
// HABILITA
//--------------------------------------------------------------------------------
private void Habilita(boolean Estado){
    
    txDireccion.setEnabled(Estado);
    txCiudad.setEnabled(Estado);
    txComuna.setEnabled(Estado);
    txRut.setEnabled(Estado);
    txNombre.setEnabled(Estado);
    txDv.setEnabled(Estado);
  
    dtEmision.setEnabled(Estado);
    txNeto.setEnabled(Estado);
    txExento.setEnabled(Estado);
    txIva.setEnabled(Estado);
    txTotal.setEnabled(Estado);
    btIr.setEnabled(Estado);
    txEstado.setEnabled(Estado);
    btCargaDocumento.setEnabled(Estado);
    txNroDocumento.setEnabled(Estado);
    txImpEspecifico.setEnabled(Estado);
    
}
    
    private void btNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoActionPerformed
        Tipo=1;
        Limpia();
        Habilita(false);
        Edicion(false);
        txRut.setEnabled(true);
        txRut.setEditable(true);
        btIr.setEnabled(true);
        btAbrir.setEnabled(false);
        btGuardar.setEnabled(true);
        btCancelar.setEnabled(true);
        txRut.requestFocus();
    }//GEN-LAST:event_btNuevoActionPerformed
    public String getFechaAsString() {
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    return( sdf.format( (dtEmision.getDate()).getTime() ) );
    }
    
    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed

        if(fmMain.OkCancel("¿Guardar Documento?")== JOptionPane.OK_OPTION){
            ExeSql  Sql = new ExeSql();
            String Query="";

            //Graba Nueva Guia
            if(Tipo==1){
                
                try{
                    //Obtiene Correlativo
                    
                    String NewCorrelativo = "";
                    
                    Sql.ExeSql("update par_correlativo set numero=numero + 1 where tipo='NDC'");
                    NewCorrelativo = Sql.SelectUnico("select numero from par_correlativo where tipo='NDC'");
                    
                    
                                              
                     //**************************************************** // 
                    
//                      NewCorrelativo = "15";    //Folio Provisorio
                    
                  //*****************************************************//      
                    
                    

                    Query = " INSERT INTO ctactecli(\n" +
                            " rut, tipdocto, nrodocto, tipdocorigen, nrodocorigen, femision, \n" +
                            " totalexento, totalafecto, totaliva, totalimpespecifico,totaldocto,codigo_oc,occh,tipo)\n" +
                            " VALUES (" +
                            txRut.getText() + "," +
                            "'NDC'," +
                            NewCorrelativo +  "," +
                            "'NCC'," +
                            txNroDocumento.getText().trim() + ",'" +
                            getFechaAsString() + "'," +
                            fmMain.SetGuardar(txExento.getText().trim()) + "," +
                            fmMain.SetGuardar(txNeto.getText().trim()) + "," +
                            fmMain.SetGuardar(txIva.getText().trim()) + "," +
                            fmMain.SetGuardar(txImpEspecifico.getText().trim()) + "," +
                            fmMain.SetGuardar(txTotal.getText().trim()) + "," +
                            Codigo_OC + ",'" +
                            NroOrden + "'," +
                            "1" + ")";
                    
                    System.out.println(Query);
                    Sql.ExeSql(Query);

                    for(int i=0; i< Grilla.getRowCount(); i++){
                        
                        Query = " INSERT INTO ctacteclidet(\n" +
                        " rut, tipdocto, nrodocto, sku, cantidad, valorunitario, totallinea)\n" +
                        " VALUES (" +
                        txRut.getText() +"," +
                        "'NDC'," +
                        NewCorrelativo + ",'" +
                        Grilla.getModel().getValueAt(i,GetCol("Sku")).toString().trim() + "'," +
                        fmMain.SetGuardar(Grilla.getModel().getValueAt(i,GetCol("Cantidad")).toString()) + "," +
                        fmMain.SetGuardar(Grilla.getModel().getValueAt(i,GetCol("Unitario")).toString()) + "," +
                        fmMain.SetGuardar(Grilla.getModel().getValueAt(i,GetCol("Total")).toString()) + ")";
                        Sql.ExeSql(Query);

                    }

                    Sql.Commit();
                    JOptionPane.showMessageDialog(null,"Guardado");
                    lbFolio.setText(NewCorrelativo);
                    btEmitir.setEnabled(true);
                    SetTipo(2);

                } catch (Exception e) {
                    Sql.Rollback();
                    fmMain.Mensaje(e.getMessage());
                    Logger.getLogger(pfNDBCliente.class.getName()).log(Level.SEVERE, null, e);
                }finally{
                    Sql.Close();
                }

            }
        }

    }//GEN-LAST:event_btGuardarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        
        if(fmMain.GetEstado(fmMain.pnPestanas.getSelectedIndex())==0){
            
            Limpia();
            Habilita(false);
            btGuardar.setEnabled(false);
            btCancelar.setEnabled(false);
            btNuevo.setEnabled(true);
            btAbrir.setEnabled(true);   
        
        }else if(fmMain.OkCancel("¿Seguro de cancelar?")==JOptionPane.OK_OPTION){
            
            Limpia();
            Habilita(false);
            btGuardar.setEnabled(false);
            btCancelar.setEnabled(false);
            btNuevo.setEnabled(true);
            btAbrir.setEnabled(true);

        }
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btEmitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmitirActionPerformed
        
        ExeSql Sql = new ExeSql();   

        try {
        
          //  GeneraDTE.Generar(txRut.getText().trim(),"NDC" ,lbFolio.getText().trim());
             GeneraDTE_NDC(txRut.getText().trim(),"NDC" ,lbFolio.getText().trim());
            
            
            Sql.ExeSql("update ctactecli set estado=1 where tipdocto='NDC' and nrodocto=" + lbFolio.getText().trim());  //Estado a Emitida
            Sql.Commit();
            JOptionPane.showMessageDialog(null,"Documento Emitido");
           // btEmitir.setEnabled(false);
            txEstado.setText("Emitido"); 
        
        
        } catch (SQLException ex) {
        
            fmMain.Mensaje(ex.getMessage()); 
            System.out.println(ex);
        
        } finally{
            Sql.Close();
        }

    }//GEN-LAST:event_btEmitirActionPerformed

    
    
    private void GeneraDTE_NDC(String ParRut,String ParTipo, String ParNumero){
    
        File factura = null;
        
       // boolean Resultado=true;
        String Rut = ParRut;
        String Tipo = ParTipo;
        String Numero = ParNumero;
        String TipoNro = "";
        
        String ElRut = "";
        String ElNombre = "";
        String ElGiro = "";
        String LaDireccion = "";
        String LaComuna = "";
        String LaCiudad = "";
        
        String Fecha = "";
        
        String ElAfecto = "";
        String ElIva = "";
        String ElTotal = "";
        
        String FolioRef = "";
        String TipoFolioRef = "";
        String FechaGDC = "";
        
        String CodRef = "";
                        
        ExeSql Sql = new ExeSql();
        ExeSql Sql2 = new ExeSql();
        ExeSql Sql3 = new ExeSql();
        ExeSql Sql4 = new ExeSql();
        ExeSql Sql5 = new ExeSql();
       
        
        ResultSet Rs, Rs2, Rs3,Rs4, Rs5 = null;
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Document doc= new Document();    
        
        try {
        
            Rs = Sql.Select("select * from ctactecli where tipdocto='" + Tipo +"' and nrodocto=" + Numero);
            Rs.next();
        
            switch (Tipo){
                case "GDC": TipoNro="52"; break;
                case "FAC": TipoNro="33"; break;
                case "NCC": TipoNro="61"; break;
                case "NDC": TipoNro="56"; break;
                case "FEC": TipoNro="34"; break;
                case "BOC": TipoNro="39"; break;
            }
            
            Fecha = sdf.format(Rs.getDate("femision"));
            
            Namespace ns= Namespace.getNamespace("http://www.sii.cl/SiiDte");
            
            //Document doc= new Document();    
            
                Element root=new Element("DTE").setAttribute("version", "1.0");
                root.setNamespace(ns);
                
                    Element documento=new Element("Documento").setAttribute("ID","F"+Numero+"T"+TipoNro);
                    documento.setNamespace(ns);
        
                        Element encabezado=new Element("Encabezado"); 
                        encabezado.setNamespace(ns);
        
                            Element Iddoc=new Element("IdDoc").setNamespace(ns); 
                                            
                                Iddoc.addContent(new Element("TipoDTE").addContent(TipoNro).setNamespace(ns));
                                Iddoc.addContent(new Element("Folio").addContent(Numero).setNamespace(ns));
                                Iddoc.addContent(new Element("FchEmis").addContent(Fecha).setNamespace(ns));
                                
                                
                            
                            Element Emisor=new Element("Emisor").setNamespace(ns); 
                                
                                Emisor.addContent(new Element("RUTEmisor").addContent("76231391-K").setNamespace(ns));
                                Emisor.addContent(new Element("RznSoc").addContent("EMPRESA COMERCIALIZADORA LUIS VALDES LYON S.P.A.").setNamespace(ns));
                                Emisor.addContent(new Element("GiroEmis").addContent("COMERCIALIZADORA DE ARTICULOS DE FERRETERIA").setNamespace(ns));
                                Emisor.addContent(new Element("Telefono").addContent("+56(45)2658390").setNamespace(ns));
                                Emisor.addContent(new Element("CorreoEmisor").addContent("contacto@luvaly.cl").setNamespace(ns));
                                Emisor.addContent(new Element("Acteco").addContent("464909").setNamespace(ns));
                                Emisor.addContent(new Element("Acteco").addContent("466302").setNamespace(ns));
                                Emisor.addContent(new Element("DirOrigen").addContent("AVENIDA HUERFANOS 01871").setNamespace(ns));
                                Emisor.addContent(new Element("CmnaOrigen").addContent("TEMUCO").setNamespace(ns));
                                Emisor.addContent(new Element("CiudadOrigen").addContent("TEMUCO").setNamespace(ns));
                                
                                
                                
                        //**************************************************************** DATOS CLIENTE ******************************************************************//        
                                
                                String Query = "select d.rut || '-' || co.dv as rut, co.nombre,c.giro,c.direccion,c.ciudad,c.comuna \n"+
                                               "from ctactecli d \n"+
                                               "left join cliente co on co.rut=d.rut \n"+
                                               "left join clicontacto c on d.rut=c.rut and d.codigo_oc = c.codigo_oc  \n"+
                                               "where d.rut=" + Rut + "\n"+
                                               "and d.tipdocto='" + Tipo + "'\n"+
                                               "and d.nrodocto=" + Numero;
                                //System.out.println(Query);
                                Rs2 = Sql2.Select(Query);
                                Rs2.next();

                                ElRut = Rs2.getString("rut").trim();
                                ElNombre = Rs2.getString("Nombre").trim();
                                
                                
                                if(Rs2.getString("giro").trim().length()>40){
                                    
                                     ElGiro = Rs2.getString("giro").substring(0, 40).trim();
                                    
                                }else{
                                    
                                    ElGiro = Rs2.getString("giro").trim();
                                
                                }    
                                
                                LaDireccion = Rs2.getString("direccion").trim();
                                LaComuna= Rs2.getString("comuna").trim();
                                LaCiudad = Rs2.getString("ciudad").trim();
                                
                                
                        //********************************************************************************************************************************************************//    
                            Element Receptor=new Element("Receptor").setNamespace(ns); 
                                            
                                Receptor.addContent(new Element("RUTRecep").addContent(ElRut).setNamespace(ns));
                                Receptor.addContent(new Element("RznSocRecep").addContent(ElNombre).setNamespace(ns));
                                Receptor.addContent(new Element("GiroRecep").addContent(ElGiro).setNamespace(ns));    
                                Receptor.addContent(new Element("DirRecep").addContent(LaDireccion).setNamespace(ns));    
                                Receptor.addContent(new Element("CmnaRecep").addContent(LaComuna).setNamespace(ns));    
                                Receptor.addContent(new Element("CiudadRecep").addContent(LaCiudad).setNamespace(ns));    
                                
                        //**************************************************************** TOTALES DOCUMENTO ******************************************************************//   
                                
                          ElAfecto = Rs.getString("totalafecto");
                          ElIva = Rs.getString("totaliva");
                          ElTotal = Rs.getString("totaldocto");
                                
                                
                                
                            Element Totales=new Element("Totales").setNamespace(ns); 
                                            
                                Totales.addContent(new Element("MntNeto").addContent(ElAfecto).setNamespace(ns));
                                Totales.addContent(new Element("TasaIVA").addContent("19").setNamespace(ns));
                                Totales.addContent(new Element("IVA").addContent(ElIva).setNamespace(ns));
                                Totales.addContent(new Element("MntTotal").addContent(ElTotal).setNamespace(ns));
                        
                       
                                    
                        encabezado.addContent(Iddoc);
                        encabezado.addContent(Emisor);
                        encabezado.addContent(Receptor);
                        encabezado.addContent(Totales);
                
                    documento.addContent(encabezado);    
             
                    //********************************************************************************************************************************************************//             
                    
                    //**************************************************************** DETALLE PRODUCTOS ******************************************************************//   
                    
                    int linea = 1;
                    
                    Rs3 = Sql3.Select("select d.sku,p.nombre,u.um,d.cantidad,d.valorunitario,d.totallinea\n" +
                                       "from ctacteclidet d\n" +
                                       "left join producto p on d.sku=p.sku \n" +
                                        "left join par_unidad u on u.codigo=p.unidad\n" +
                                        "where d.tipdocto='"+ Tipo +"'\n" +
                                        "and d.rut="+ Rut +"\n" +
                                        "and d.nrodocto=" + Numero);
                     
                   
                    if (Sql3.GetRowCount() > 0){
                    
                        while(Rs3.next()){ //Una iteración por producto
                   
                            String ElProd = Rs3.getString("nombre").trim();
                            String LaCantidad = fmMain.FormatoNumero3(Rs3.getDouble("cantidad"));
                            String LaUnidad = Rs3.getString("um");
                            String ElUnitario = fmMain.FormatoNumero4(Rs3.getDouble("valorunitario"));
                            String LaLinea = String.valueOf(Math.round(Rs3.getDouble("totallinea")));
                            String ElSku = Rs3.getString("sku").trim();
                        
                            Element Detalle=new Element("Detalle").setNamespace(ns);
                        
                                String nLinea = String.valueOf(linea);    
                            
                                Detalle.addContent(new Element("NroLinDet").addContent(nLinea).setNamespace(ns));
                                
                                    Element CdgItem=new Element("CdgItem").setNamespace(ns);  //Tipo Codificacion para los items
                                
                                            CdgItem.addContent(new Element("TpoCodigo").addContent("INT1").setNamespace(ns));
                                            CdgItem.addContent(new Element("VlrCodigo").addContent(ElSku).setNamespace(ns));
                            
                                Detalle.addContent(CdgItem);       
                                
                                Detalle.addContent(new Element("NmbItem").addContent(ElProd).setNamespace(ns));
                                Detalle.addContent(new Element("QtyItem").addContent(LaCantidad).setNamespace(ns));
                                Detalle.addContent(new Element("UnmdItem").addContent(LaUnidad).setNamespace(ns));
                                Detalle.addContent(new Element("PrcItem").addContent(ElUnitario).setNamespace(ns));
                                Detalle.addContent(new Element("MontoItem").addContent(LaLinea).setNamespace(ns));
                            
                                linea++;
                            
                           documento.addContent(Detalle);
                        }
                    
                    }
                    
                    //*****************************************************************************************************************//
                    
                    String TipoDocRef = Rs.getString("tipdocorigen");
                    
                    
        
                    Rs4 = Sql4.Select("select * from ctactecli where tipdocto IN ('"+TipoDocRef+"') and nrodocto =" + Rs.getInt("nrodocorigen"));
 
        
                    Rs4.next();
                    
                    
                    FolioRef = Rs4.getString("nrodocto"); 
                    
                    String TipoRef = "";
                    
                    if (Rs4.getString("tipdocto").equals("BOC")){
                    
                        TipoRef = "39";
                    
                    }else if (Rs4.getString("tipdocto").equals("FAC")){
                    
                         TipoRef = "33";
                    
                    }else if (Rs4.getString("tipdocto").equals("NCC")){
                    
                         TipoRef = "61";
                    
                    }
                    
                    
                    
                    FechaGDC = sdf.format(Rs4.getDate("femision"));
                    CodRef = Rs.getString("tipo");
                    
                    if (CodRef.trim().equals("4")){
                                        
                        CodRef = "3";
                    }
                    
                    
                    
                    Element Referencia=new Element("Referencia").setNamespace(ns);
                    
                          Referencia.addContent(new Element("NroLinRef").addContent("1").setNamespace(ns));
                          Referencia.addContent(new Element("TpoDocRef").addContent(TipoRef).setNamespace(ns));
                          Referencia.addContent(new Element("FolioRef").addContent(FolioRef).setNamespace(ns));
                          Referencia.addContent(new Element("FchRef").addContent(FechaGDC).setNamespace(ns));
                          Referencia.addContent(new Element("CodRef").addContent(CodRef).setNamespace(ns));
                    documento.addContent(Referencia);
                    
           root.addContent(documento);
        doc.setRootElement(root);

       
//Se genera el archivo XML 
//        XMLOutputter outter=new XMLOutputter();
//        outter.setFormat(Format.getPrettyFormat());
//        factura = new File("C:/temp_luvaly/minotadebito.xml");
//        outter.output(doc, new FileWriter(factura));
    
    }catch (SQLException ex) {
    
        Logger.getLogger(pfNDBCliente.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
        XMLOutputter outter=new XMLOutputter();
        outter.setFormat(Format.getPrettyFormat());
        
        DTE dte = new DTE();
        DTESoap soap = dte.getDTESoap();
        
        //ArrayOfString respuesta = soap.ponerDTE("ws_econa", "5df28bdd52", outter.outputString(doc), false);
        ArrayOfString respuesta = soap.ponerDTE("ws_econa", "5df28bdd52", outter.outputString(doc), true);
        
        if (respuesta.getString().isEmpty()){   //Si la respuesta es una cadena vacía el envío fue exitoso
        
            System.out.println("Documento ha sido emitido");
            Imprimir("76231391-K",ElRut,TipoNro,Numero,Fecha,ElTotal,0,0);
                        
        }else{        //De lo contrario el archivo XML presenta errores
        
            System.out.println("Error en envío : "+respuesta.getString());   //Se muestra los errores señalados
            
        }
        
    }  
    
    
    
    public void Imprimir(String emisor, String receptor, String tipodte, String folio, String fecha, String total, int cimp,int imprime)  {
      
        System.out.println(emisor);
        System.out.println(receptor) ;
        System.out.println(tipodte);
        System.out.println(folio);
        System.out.println(fecha); 
        System.out.println(total);
        
        int Imprimir = imprime;
       
        try {
            PrintService[] services = PrinterJob.lookupPrintServices();
          
         //   int value = 4;
            
            int value = cimp; // El valor obtenido especifica la posicion de la impresora
            
            PrintService print = services[value];
           // System.out.println("EL VALOR DE LA IMPRESORA ES :"+services[value]);
            
            
            URL url=null;
            try {
           
                CookieHandler.setDefault(new CookieManager(null, CookiePolicy.ACCEPT_ALL));
    
                //URL de pruebas
                
//                url = new URL("https://www.efacturadelsur.cl/certificacion/pdf?rutEmisor="+emisor+"&rutReceptor="+receptor+"&tipoDte="+tipodte+
//                              "&folio="+folio+"&fechaEmision="+fecha+"&montoTotal="+total);
//                
                
                //URL de producción

              url = new URL("https://www.efacturadelsur.cl/app/pdf?rutEmisor="+emisor+"&rutReceptor="+receptor+"&tipoDte="+tipodte+
                            "&folio="+folio+"&fechaEmision="+fecha+"&montoTotal="+total);
            try{    
            
                InputStream in = url.openStream();
                Files.copy(in, Paths.get("C:/doc_luvaly/NDC"+folio+".pdf"), StandardCopyOption.REPLACE_EXISTING);
            
            }catch(Exception e){

                System.out.println("Archivo no encontrado !!");   //Se muestra los errores señalados
                    
            }    

          

            } catch (MalformedURLException e) {
                Logger.getLogger(pfGDCliente.class.getName()).log(Level.SEVERE, null, e);
            }
            
            
            File fin = new File("C:/doc_luvaly/NDC"+folio+".pdf");

            
            if (Imprimir == 1){
            
                PDDocument document = Loader.loadPDF(fin);

                PrinterJob job = PrinterJob.getPrinterJob();
                job.setPageable(new PDFPageable(document));
                job.setPrintService(print);
                job.print();
            
            }else if (Imprimir == 2){
                
                
                Desktop.getDesktop().open(fin);
                
            }
            
        
        }catch (FileNotFoundException ex) {
            
            Logger.getLogger(pfGDCliente.class.getName()).log(Level.SEVERE, null, ex);
        
        }catch (IOException | PrinterException ex) {
            
            Logger.getLogger(pfGDCliente.class.getName()).log(Level.SEVERE, null, ex);
        } 
    
    } 
    
    
    
    
    private void btAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirActionPerformed
        SetTipo(1);
        Habilita(false);
        Edicion(false);
        Limpia();
        txRut.setEnabled(true);
        txRut.setEditable(true);
        btIr .setEnabled(true);
        btCancelar.setEnabled(true);
        txRut.requestFocus();
        Tipo=2;
    }//GEN-LAST:event_btAbrirActionPerformed

    private void txRutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txRutKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btIr.doClick();
        }
    }//GEN-LAST:event_txRutKeyPressed
    
    private boolean CargaCliente(String Rut){
    ExeSql Sql = new ExeSql();
    ResultSet Rs;
    
    try {
        Rs = Sql.Select("select rut,dv,nombre\n" +
                    "from cliente\n" +
                    "where rut=" + Rut);
        Rs.next();
        txRut.setText(Rs.getString("Rut"));
        txDv.setText(Rs.getString("dv"));
        txNombre.setText(Rs.getString("nombre").trim());
        dtEmision.setDate(new Date());
        RutMaster=Rs.getString("Rut");
        return true;
    } catch (Exception e) {
    }
        return false;
    } 
    private void FindeAgno(){
        if(fmMain.GetFacNewYear()==1){
            try {
                SimpleDateFormat df = new SimpleDateFormat("yyyy/MM/dd");
                Date Fecha=df.parse("2015/12/31");
                dtEmision.setDate(Fecha);
                dtEmision.setEditable(false);
                System.out.println("NewYear");
            } catch (Exception e) {
                System.out.println("Error New Year");
            }
            
        }
            
        
    }
    private void btIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIrActionPerformed
        boolean Carga;
        if(!txRut.getText().isEmpty()){
            Carga=CargaCliente(txRut.getText());
        }
        else{
            jdBuscarCliPrv BPC = new jdBuscarCliPrv(null, true);
            BPC.setLocationRelativeTo(null);
            BPC.setTitle("Buscar Cliente");
            BPC.SetTipo(1);
            BPC.setVisible(true);
            Carga=CargaCliente(BPC.GetRut());
        }

        // Si cargó cliente y es nuevo.
        if(Carga && Tipo==1){
            //CargaCodOc(RutMaster);
            Habilita(true);
            Edicion(true);
            txNroDocumento.requestFocus();
            //            btGuardar.setEnabled(true);
            //            btCancelar.setEnabled(true);
            //            btNuevo.setEnabled(false);
            //            btEditar.setEnabled(false);
            //            btAbrir.setEnabled(false);
            txEstado.setText("Sin Emitir");
            fmMain.SetEstado(fmMain.pnPestanas.getSelectedIndex(),1);
            FindeAgno();
        }
        // Si cargó cliente y esta abriendo
        if(Carga && Tipo==2){

            jdAbrirDocumento ADoc = new jdAbrirDocumento(null, true);
            if(ADoc.ShowModal("NDC",RutMaster)==JOptionPane.YES_OPTION){
                Tipo=-99;
                AbrirNDC(RutMaster, ADoc.GetNumero());
                SetTipo(2);
                //AbrirOCC(RutMaster, AOC.GetOrden());
                //JOptionPane.showMessageDialog(null, "Abriendo...");

            }
            else{
                txRut.setText("");
                txNombre.setText("");
                txRut.requestFocus();
            }

        }

    }//GEN-LAST:event_btIrActionPerformed
public void AbrirNDC(String Rut,String Numero){
        ResultSet Rs;
        ExeSql Sql = new ExeSql();
        DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
        
        
        try{
            while(TableModel.getRowCount()>0)
                  TableModel.removeRow(0);

            Tipo=0;
            Rs = Sql.Select("select c.rut,c.nrodocto,c.tipdocorigen,c.nrodocorigen,c.estado as estadoint, c.femision,c.codigo_oc,c.occh,c.totalexento,c.totalafecto,c.totaliva,totalimpespecifico,c.totaldocto, cc.giro,cc.direccion,cc.ciudad,cc.comuna,cc.region,c.estado,c.tipo as tipoem " +
                            "from ctactecli c left join clicontacto cc " +
                            "on c.rut=cc.rut and c.codigo_oc=cc.codigo_oc " +
                            "WHERE c.rut=" + Rut + " " +
                            "AND c.tipdocto='NDC' " +
                            "AND c.nrodocto=" + Numero);
            Rs.next();
            
            lbFolio.setText(Numero);
            dtEmision.setDate(Rs.getDate("femision"));
            txDireccion.setText(Rs.getString("direccion").trim());
            txCiudad.setText(Rs.getString("ciudad").trim());
            txComuna.setText(Rs.getString("comuna").trim());
            txNroDocumento.setText(Rs.getString("nrodocorigen").trim());
            Codigo_OC = Rs.getString("codigo_oc").trim();
            NroOrden = Rs.getString("occh").trim();
            
            ElTipo=Rs.getInt("tipoem")-1;
            
            if(Rs.getInt("estadoint")==0){ 
                btEmitir.setEnabled(true);
            }
            else{
               // btEmitir.setEnabled(false);
            }
            
            txNeto.setText(fmMain.FormatoTotal(Rs.getDouble("totalafecto")));
            txExento.setText(fmMain.FormatoTotal(Rs.getDouble("totalexento")));
            txIva.setText(fmMain.FormatoTotal(Rs.getDouble("totaliva")));
            txImpEspecifico.setText(fmMain.FormatoTotal(Rs.getDouble("totalimpespecifico")));
            txTotal.setText(fmMain.FormatoTotal(Rs.getDouble("totaldocto")));
            
            switch(Rs.getInt("estado")){
                case 0: txEstado.setText("Sin Emitir"); break;
                case 1: txEstado.setText("Emitida");break;
            }
            Tipo=2;
        } catch (Exception e) {
            System.out.println(e);
            Tipo=2;
            }

        
        try{
            //CARGA PRODUCTOS 
            CargaProductos(Rut, "NDC", Numero);
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
    }
void CargaProductos(String Rut,String TipDocto,String NroDocto){
        ExeSql  Sql = new ExeSql();
        DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
        ResultSet Rs;
        
        while(TableModel.getRowCount()>0)
            TableModel.removeRow(0);
        
        
        try {
            Rs = Sql.Select("select d.sku,p.nombre,u.um,d.cantidad,d.valorunitario,d.totallinea \n" +
                            "from ctacteclidet d\n" +
                            "left join producto p\n" +
                            "on d.sku=p.sku\n" +
                            "left join par_unidad u\n" +
                            "on p.unidad=u.codigo\n" +
                            "where d.rut=" + Rut + "\n" +
                            "and d.tipdocto='"+ TipDocto +"'\n" +
                            "and d.nrodocto=" + NroDocto);
            while(Rs.next()){
                TableModel.addRow(new Object[]{
                        Rs.getString("sku"), 
                        Rs.getString("nombre"), 
                        Rs.getString("um"),
                        fmMain.FormatoNumero(Rs.getDouble("cantidad")),
                        fmMain.FormatoNumero(Rs.getDouble("valorunitario")),
                        fmMain.FormatoNumero(Rs.getDouble("totallinea"))});
            }
            Sumador();
        } catch (Exception e) {
        } finally{
            Sql.Close();
        }
    }
private void Sumador(){    
    double Neto=0;
    double Exento=0;
    double Iva=0;
    double Total=0;
    String Valor;
    
    for(int i=0; i< Grilla.getRowCount(); i++){
        Valor = Grilla.getModel().getValueAt(i,GetCol("Total")).toString();
        Valor = Valor.replace(fmMain.GetMiles(), "");
        Neto =  Math.round(Float.parseFloat(Valor)) + Neto;
    }
        Neto = Math.round(Neto);
        Iva = Math.round((Neto * Double.parseDouble("0.19")));
        Total = Neto + Iva; 
    txNeto.setText(fmMain.FormatoTotal(Neto));
    txExento.setText(fmMain.FormatoTotal(Exento));
    txIva.setText(fmMain.FormatoTotal(Iva));
    txTotal.setText(fmMain.FormatoTotal(Total));
}
    private void txDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDireccionActionPerformed

    private void txNroDocumentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNroDocumentoKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            btCargaDocumento.doClick();
        }
    }//GEN-LAST:event_txNroDocumentoKeyPressed

    private void btCargaDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCargaDocumentoActionPerformed

        if(txRut.getText().isEmpty()) return;

        if(!txNroDocumento.getText().isEmpty()){
            CargaDocumentoOrigen("NCC", txNroDocumento.getText().trim());
        }
        else{
            jdAbrirDocumento ADoc = new jdAbrirDocumento(null, true);
            if(ADoc.ShowModal("NCC",txRut.getText().trim())==JOptionPane.YES_OPTION){
                CargaDocumentoOrigen("NCC", ADoc.GetNumero());
            }
        }

    }//GEN-LAST:event_btCargaDocumentoActionPerformed

    void CargaDocumentoOrigen(String TipDocto, String NroDocto){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        
        txNroDocumento.setText(NroDocto);
        
        try {
            //CARGA DATOS DE CLIENTE
            Rs= Sql.Select( "select cc.direccion,cc.comuna,cc.ciudad,cc.codigo_oc, c.occh\n" +
                            "from ctactecli c\n" +
                            "left join clicontacto cc on c.rut=cc.rut and c.codigo_oc=cc.codigo_oc \n" +
                            "where c.tipdocto='"+ TipDocto +"'\n" +
                            "and nrodocto=" + NroDocto);
            if(Sql.GetRowCount()==0){
                JOptionPane.showMessageDialog(null, "Documento no encontrado");
                return;
            }
            
            Rs.next();
            
            txDireccion.setText(Rs.getString("direccion").trim());
            txComuna.setText(Rs.getString("Comuna").trim());
            txCiudad.setText(Rs.getString("Ciudad").trim());
            Codigo_OC = Rs.getString("codigo_oc").trim();
            NroOrden  = Rs.getString("occh").trim();
           
            //CARGA PRODUCTOS DE DOCUMENTO DE ORIGEN
            CargaProductos(txRut.getText().trim(),TipDocto,NroDocto);
            
            
        } catch (SQLException | HeadlessException e) {
            System.out.println(e);
        }
    }
    private void GrillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaMouseClicked
        if(evt.getClickCount()==2 && !Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString().isEmpty()){
            jdIngresaNumero jdNumero = new jdIngresaNumero(null, true);
            jdNumero.setLocationRelativeTo(null);
            jdNumero.setVisible(true);
            if(jdNumero.GetNumero() != -99 ){
                try {

                    double TotLinea = jdNumero.GetNumero() * Float.parseFloat(fmMain.SetGuardar(Grilla.getValueAt(Grilla.getSelectedRow(), GetCol("Unitario")).toString()));

                    Grilla.setValueAt(jdNumero.GetNumero(), Grilla.getSelectedRow(),GetCol("Cantidad"));
                    Grilla.setValueAt(fmMain.FormatoNumero(TotLinea),Grilla.getSelectedRow(),GetCol("Total"));
                    Sumador();
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        }

    }//GEN-LAST:event_GrillaMouseClicked

    private void txIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIvaActionPerformed

    private void btPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPDFActionPerformed

       //  busca_pdf();
        busca_pdfNdc();
    }//GEN-LAST:event_btPDFActionPerformed

    
    public void busca_pdfNdc(){
    
        int encontrado = 0;
        
        try {
            
            
            String Tipo;
            String Numero;
           
            long size = 0;
            
             
            Tipo="NDC";
            System.out.println(Tipo);
            System.out.println(lbFolio.getText().trim());
            Numero= Tipo+lbFolio.getText().trim()+".";
            
           
            File directorio = new File("C:\\doc_luvaly");

            if (directorio.exists()){
                              
                File[] archivos = directorio.listFiles();
                
                for (File elemento : archivos) {
            
                    if (elemento.getName().contains(Numero)) {
                        
                          Numero = elemento.getName();
                          encontrado = 1;
                          break;
                        
                    }else{
                    
                        encontrado = 0;
                    }
                }
                
                
                
            }else if (!directorio.exists()){
                
                directorio.mkdir();
                
                
            }
            
            
            if (encontrado == 1 ){
            
                Path filePath =  Paths.get("c:/doc_luvaly/"+Numero);
            
                size = Files.size(filePath);
                System.out.println("The file size is " + size + " bytes");
            
            }
            
            
            if (encontrado == 1 && size > 0 ){
            
                System.out.println("EL Documento ES :"+Numero);
                System.out.println("ENTRA A LOCAL !!!!!!!!!!!");

                File archivo = new File ("c:/doc_luvaly/"+Numero);
                Desktop.getDesktop().open(archivo);
                
                
                
            }else if (encontrado == 1 && size == 0 ){
                
                System.out.println("EL Documento ES :"+Numero);
                System.out.println("ENTRA A REMOTO 1 !!!!!!!!!!!");
                
                
                
                String ElRut = txRut.getText().trim()+"-"+txDv.getText().trim();
                
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String Fecha = sdf.format(dtEmision.getDate());
                String ElTotal = txTotal.getText().trim().replaceAll("\\,", "");
                
                Imprimir("76231391-K",ElRut,"56",lbFolio.getText().trim(),Fecha,ElTotal,0,2);
                
                
                
            }else if (encontrado == 0){
                
                System.out.println("EL Documento ES :"+Numero);
                System.out.println("ENTRA A REMOTO 2 !!!!!!!!!!!");
                
                
                try{
                    
                    String ElRut = txRut.getText().trim()+"-"+txDv.getText().trim();
                
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    String Fecha = sdf.format(dtEmision.getDate());
                    String ElTotal = txTotal.getText().trim().replaceAll("\\,", "");
                
                    Imprimir("76231391-K",ElRut,"56",lbFolio.getText().trim(),Fecha,ElTotal,0,2);
                
                }catch (Exception e){
                
//                        System.out.println("El arhivo no fue encontrado...");
//                        return;
                          busca_pdf();
                    
                }
            
            }
            
            
        } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No se pudo abrir el archivo,"
                    + " probablemente fue borrado","ERROR",JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(pfFACCliente.class.getName()).log(Level.SEVERE, null, e);
                
        }
    
    }
    
    
    
    
    
    
    
    
    public void busca_pdf(){
    
        int encontrado = 0;
        
        try {
            
            
            String Tipo;
            String Numero;
            int cont =0; 
            long size = 0;
             
            Tipo="56F";
            System.out.println(Tipo);
            System.out.println(lbFolio.getText().trim());
            Numero= Tipo+lbFolio.getText().trim()+".";
            
            
            
           
            File directorio = new File("C:\\facturas");

            if (directorio.exists()){
    
                              
                File[] archivos = directorio.listFiles();
                
                for (File elemento : archivos) {
            
                    if (elemento.getName().contains(Numero)) {
                        
                          Numero = elemento.getName();
                          encontrado = 1;
                          break;
                        
                    }else{
                    
                        encontrado = 0;
                    }
                }
                
                
                
            }else if (!directorio.exists()){

                directorio.mkdir();
                
            }
            
            
            if (encontrado == 1 ){
            
                Path filePath =  Paths.get("c:/facturas/"+Numero);
            
                size = Files.size(filePath);
                System.out.println("The file size is " + size + " bytes");
            
            }
            
            


             if (encontrado == 1 && size > 0 ){
            
                System.out.println("EL Documento ES :"+Numero);
                System.out.println("ENTRA A LOCAL !!!!!!!!!!!");

                File objetofile = new File ("c:/facturas/"+Numero);
                 Desktop.getDesktop().open(objetofile);
                
            }else if (encontrado == 1 && size == 0 ){
            
                
                System.out.println("ENTRA A REMOTO con Archivo LOCAL en 0   !!!!!!!!!");
                
                File directorioFtp = new File("\\\\192.168.0.130\\Documentos Electronicos");
               

                if (directorioFtp.exists()){   //Se verifica que el directorio (carpeta) exista
    
                    File[] archivos = directorioFtp.listFiles();      //se capturan los nombres de todos los archivos del directorio
                
                    for (File elemento : archivos) {     //se va leyendo cada archivo
            
                        if (elemento.getName().contains(Numero)) {    //Si el nombre del archivo contiene el nombre que se busca
                        
                           Numero = elemento.getName();           //Se nota el nombre completo del archivo 
                           encontrado = 1;                        //Se indica que se ha encontrado  
                           break;                                 //Se termona el ciclo for  
                        
                        }else{
                    
                           encontrado = 0;
                        }
                    }
                    
                    
                    //***********
                    if (encontrado == 1){   //Si el archivo fue encontrado
            
                        System.out.println("LA Documento ES :"+Numero);
            

                        //File objetofile = new File ("c:/facturas/"+Factura);
                        File objetofile = new File ("//192.168.0.130/Documentos Electronicos/"+Numero);
                        
                        Desktop.getDesktop().open(objetofile);   //Se abre el archivo segun el programa asociado a él (configurado previamente en Windows)
                
                    }else if (encontrado == 0){
                    
                        System.out.println("El Archivo no existe...");
                        
                    
                    }        
                //***********
                
                }else{
        
                    System.out.println("El directorio no existe, verifique la ruta remota...");
                    return;
                }   
               
                
            }else if (encontrado == 0){
                
                 System.out.println("ENTRA A REMOTO !!!!!!!!!!!");
                
                File directorioFtp = new File("\\\\192.168.0.130\\Documentos Electronicos");
               

                if (directorioFtp.exists()){   //Se verifica que el directorio (carpeta) exista
    
                    File[] archivos = directorioFtp.listFiles();      //se capturan los nombres de todos los archivos del directorio
                
                    for (File elemento : archivos) {     //se va leyendo cada archivo
            
                        if (elemento.getName().contains(Numero)) {    //Si el nombre del archivo contiene el nombre que se busca
                        
                           Numero = elemento.getName();           //Se nota el nombre completo del archivo 
                           encontrado = 1;                        //Se indica que se ha encontrado  
                           break;                                 //Se termona el ciclo for  
                        
                        }else{
                    
                           encontrado = 0;
                        }
                    }
                    
                    
                    //***********
                    if (encontrado == 1){   //Si el archivo fue encontrado
            
                        System.out.println("LA Documento ES :"+Numero);
            

                        //File objetofile = new File ("c:/facturas/"+Factura);
                        File objetofile = new File ("//192.168.0.130/Documentos Electronicos/"+Numero);
                        
                        Desktop.getDesktop().open(objetofile);   //Se abre el archivo segun el programa asociado a él (configurado previamente en Windows)
                
                    }else if (encontrado == 0){
                    
                        System.out.println("El Archivo no existe...");
                        
                    
                    }        
                //***********
                
                }else{
        
                    System.out.println("El directorio no existe, verifique la ruta remota...");
                    return;
                }   
            
            
            }
            
            
        } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No se pudo abrir el archivo,"
                    + " probablemente fue borrado","ERROR",JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(pfNDBCliente.class.getName()).log(Level.SEVERE, null, e);
                
        }
    
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla;
    private javax.swing.JButton btAbrir;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCargaDocumento;
    private javax.swing.JButton btEmitir;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btIr;
    private javax.swing.JButton btNuevo;
    private javax.swing.JButton btPDF;
    private org.jdesktop.swingx.JXDatePicker dtEmision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private javax.swing.JLabel lbFolio;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JTextField txCiudad;
    private javax.swing.JTextField txComuna;
    private javax.swing.JTextField txDireccion;
    private javax.swing.JTextField txDv;
    private javax.swing.JTextField txEstado;
    private javax.swing.JTextField txExento;
    private javax.swing.JTextField txImpEspecifico;
    private javax.swing.JTextField txIva;
    private javax.swing.JTextField txNeto;
    private javax.swing.JTextField txNombre;
    private javax.swing.JTextField txNroDocumento;
    private javax.swing.JTextField txRut;
    private javax.swing.JTextField txTotal;
    // End of variables declaration//GEN-END:variables
}
