/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Conexion.Disosur.ExeSqlDisosur;
import Formularios.fmMain;
import static Formularios.fmMain.pnPestanas;
import static PanelForm.pfGDCliente.GetCol;
import Utilidades.PanelTab;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import jxl.Workbook;
import jxl.WorkbookSettings;
import jxl.format.Alignment;
import jxl.format.Border;
import jxl.format.Colour;
import jxl.format.UnderlineStyle;
import jxl.write.BorderLineStyle;
import jxl.write.WritableCellFormat;
import jxl.write.WritableFont;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;

/**
 *
 * @author David Alcaman
 */
public class pfReportePrecios extends javax.swing.JPanel {
    
    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    
    
    SimpleDateFormat formatofecha = new SimpleDateFormat("dd-MM-yyyy");
    Date hoy = new Date();
    
    public pfReportePrecios() {
        initComponents();
        
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
             
        Grilla.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        Grilla.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        
        
        DefaultTableModel TableModel  = (DefaultTableModel) Grilla.getModel();
        
        while(TableModel.getRowCount()>0)
        TableModel.removeRow(0);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btExportar = new javax.swing.JButton();
        btCargar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();

        btExportar.setText("Exportar");
        btExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExportarActionPerformed(evt);
            }
        });

        btCargar.setText("Cargar");
        btCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCargarActionPerformed(evt);
            }
        });

        Grilla.setAutoCreateRowSorter(true);
        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "SKU", "NOMBRE", "STOCK", "COSTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.setAutoscrolls(false);
        Grilla.setName(""); // NOI18N
        Grilla.getTableHeader().setReorderingAllowed(false);
        Grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaMouseClicked(evt);
            }
        });
        Grilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GrillaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(0).setMinWidth(75);
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(75);
            Grilla.getColumnModel().getColumn(0).setMaxWidth(75);
            Grilla.getColumnModel().getColumn(1).setMinWidth(400);
            Grilla.getColumnModel().getColumn(1).setPreferredWidth(400);
            Grilla.getColumnModel().getColumn(1).setMaxWidth(400);
            Grilla.getColumnModel().getColumn(2).setMinWidth(80);
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(2).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(3).setMinWidth(80);
            Grilla.getColumnModel().getColumn(3).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExportarActionPerformed

        
        int nFilasSelec = Grilla.getRowCount();
                
        System.out.println("Las Filas Son : "+nFilasSelec);
                
                
        if (nFilasSelec == 0){
        
            fmMain.Mensaje("No hay datos que exportar !!");
            return;
        }
        
        
        try {

            ExeSql Sql = new ExeSql();
            
            ResultSet Rs = null;
           
            int fila = 1;

            Rs = Sql.Select("SELECT p.sku, p.nombre, pss.stock, (((p.valultcompra/0.94)/0.75)*1.19) as costo FROM producto p\n" +
                            "LEFT JOIN producto_stock_suma pss ON p.sku = pss.sku \n" +
                            "WHERE pss.database IN ('DIS') AND pss.stock > 0 \n"+
                            "ORDER BY p.nombre");
                        

            if (Sql.GetRowCount() > 0){

                File ruta = null;
                File carpeta = null;

                String sSistemaOperativo = System.getProperty("os.name");               //Determina el Sistema Operativo del Equipo

                if (sSistemaOperativo.contains("Win")){        //Si es Windows

                    carpeta = new File("C:\\temp\\");

                        if (!carpeta.exists()){

                            //fmMain.Mensaje("Carpeta NO existe!!");
                            carpeta.mkdir();

                        }

                        ruta = new File("C:\\temp\\Reporte_Productos"+formatofecha.format(hoy)+".xls");

                    }else{      //Si es Linux

                        String NombreMetodo = "getUsername";
                        String claseNombre = "com.sun.security.auth.module.UnixSystem";
                        Object usuario = null;

                        if( claseNombre != null ){            //Obtiene el nombre de usuaio de Linux

                            try{
                                Class<?> NombreClase = Class.forName(claseNombre);
                                Method metodo = NombreClase.getDeclaredMethod( NombreMetodo );
                                usuario = NombreClase.newInstance();
                                //fmMain.Mensaje(""+method.invoke(usuario));
                                usuario = metodo.invoke(usuario).toString();

                            }catch (ClassNotFoundException | InstantiationException | IllegalAccessException | IllegalArgumentException |
                                InvocationTargetException | NoSuchMethodException | SecurityException ex) {

                                Logger.getLogger(pfFechaVencimiento.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }

                        carpeta = new File("/home/"+usuario+"/Escritorio/temp/");

                        if (!carpeta.exists()){

                            carpeta.mkdir();
                        }

                        ruta = new File("/home/"+usuario+"/Escritorio/temp/Reporte_Productos"+formatofecha.format(hoy)+".xls");

                    }

                    WorkbookSettings conf = new WorkbookSettings();
                    conf.setEncoding("ISO-8859-1");                                     //Se establece la norma ISO de codificación de caracteres

                    try {

                        WritableWorkbook libro = Workbook.createWorkbook(ruta,conf);     //Se crea libro de excel
                        WritableFont Fuente = new WritableFont(WritableFont.ARIAL, 10, WritableFont.BOLD,false, UnderlineStyle.NO_UNDERLINE, Colour.WHITE);

                        WritableCellFormat format = new WritableCellFormat();               //Alineación para los encabezados
                        format.setAlignment(Alignment.CENTRE);
                        format.setBackground(Colour.GREY_40_PERCENT);
                        format.setFont(Fuente);
                        format.setBorder(Border.ALL, BorderLineStyle.THIN,Colour.BLACK); //table border style
                        format.setWrap(true);

                        WritableCellFormat format2 = new WritableCellFormat();              //Alineación para los datos numericos a la derecha
                        format2.setAlignment(Alignment.RIGHT);
                        format2.setBorder(Border.ALL, BorderLineStyle.THIN,Colour.BLACK); //table border style

                        WritableCellFormat format3 = new WritableCellFormat();              //Alineación para los datos texto a la izquierda
                        format3.setAlignment(Alignment.LEFT);
                        format3.setBorder(Border.ALL, BorderLineStyle.THIN,Colour.BLACK); //table border style

                        WritableCellFormat format4 = new WritableCellFormat();              //Alineación para los datos texto al centro
                        format4.setAlignment(Alignment.CENTRE);
                        format4.setBorder(Border.ALL, BorderLineStyle.THIN,Colour.BLACK); //table border style

                        WritableSheet hoja = libro.createSheet("Reporte Productos", 0);     //Se le asigna nombre a la primera hoja(0) del libro excel
                        hoja.setColumnView(0, 15);     //Sku
                        hoja.setColumnView(1, 80);     //nombre Producto
                        hoja.setColumnView(2, 15);     //Stock
                        hoja.setColumnView(3, 20);     //Costo
                        

                        hoja.setRowView(0,26*20);    //la altura de la fila del encabezado

                        //********************************  Se agregan contenido a las celdas de la hoja  *******************************************
                        hoja.addCell(new jxl.write.Label(0,0,"Sku",format));
                        hoja.addCell(new jxl.write.Label(1,0,"Descripcion",format));
                        hoja.addCell(new jxl.write.Label(2,0,"Stock",format));
                        hoja.addCell(new jxl.write.Label(3,0,"Costo",format));
                       

                        while(Rs.next()){ //While

                            String costo = String.valueOf(Math.round(Rs.getDouble("costo")));
                            
                            hoja.addCell(new jxl.write.Label(0,fila,Rs.getString("sku"),format4));
                            hoja.addCell(new jxl.write.Label(1,fila,Rs.getString("nombre"),format3));
                            hoja.addCell(new jxl.write.Label(2,fila,Rs.getString("stock"),format4));
                            hoja.addCell(new jxl.write.Label(3,fila,costo,format2));
                            

                            fila++;

                        }

                        //***************************************************************************************************************************
                        libro.write();          //Se escriben el contenido en el libro
                        libro.close();          //se cierra el libro

                        fmMain.Mensaje("Archivo : Informe_Margen"+formatofecha.format(hoy)+".xls \n creado con éxito");

                    } catch (WriteException | IOException ex) {
                        Logger.getLogger(pfReportePrecios.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            } catch (SQLException ex) {
                Logger.getLogger(pfReportePrecios.class.getName()).log(Level.SEVERE, null, ex);
            }

    }//GEN-LAST:event_btExportarActionPerformed

    private void btCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCargarActionPerformed

        ExeSql Sql = new ExeSql();
              
        ResultSet Rs = null;
             
        DefaultTableModel Model = (DefaultTableModel)Grilla.getModel();
       
        fmMain.LimpiaGrilla(Model);
      
        try {


            Rs = Sql.Select("SELECT p.sku, p.nombre, pss.stock, (((p.valultcompra/0.94)/0.75)*1.19) as costo FROM producto p\n" +
                            "LEFT JOIN producto_stock_suma pss ON p.sku = pss.sku \n" +
                            "WHERE pss.database IN ('DIS') AND pss.stock > 0 \n"+
                            "ORDER BY p.nombre");

            while(Rs.next()){
    
                Model.addRow(new Object[]{
                    Rs.getString("sku").trim(),
                    Rs.getString("nombre").trim(),
                    Rs.getString("stock").trim(),
                    Math.round(Rs.getDouble("costo"))                   
                });
                
            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            Logger.getLogger(pfFechaVencimiento.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            Sql.Close();
        }

    }//GEN-LAST:event_btCargarActionPerformed

    private void GrillaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GrillaKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_GrillaKeyPressed

    private void GrillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_GrillaMouseClicked

       
    
    class Elrender extends DefaultTableCellRenderer {
         
        @Override
        public Component getTableCellRendererComponent(JTable tabla, Object valor, boolean isSelected, boolean hasFocus, int fila, int columna) {
        super.getTableCellRendererComponent(tabla,valor,isSelected, hasFocus, fila, columna);
         
            if( (Double)tabla.getValueAt(fila,5) == 0)
            {
                
                this.setForeground(Color.black);
               // this.setFont(new Font("Tahoma", Font.BOLD, 11));
                this.setBackground(Color.yellow);    
                
                
            }else {
                
                this.setForeground(Color.black);    
                this.setBackground(Color.white);
                
            
            } 
            return this;
        }
    } 
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla;
    private javax.swing.JButton btCargar;
    private javax.swing.JButton btExportar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
