/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Formularios.fmMain;
import static Formularios.fmMain.pnPestanas;
import Utilidades.Exporter;
import Utilidades.PanelTab;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.File;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author infornatica
 */
public class pfReportesMargenProveedor extends javax.swing.JPanel {

    /**
     * Creates new form pfReportesMargen
     */
    public pfReportesMargenProveedor() {
        initComponents();
        lbcargando.setVisible(false);
        Calendar fecha = new GregorianCalendar();
        
        int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
        
        String anox ="x";
        String mesx ="x";
        
        anox = String.valueOf(año);
        mesx = String.valueOf(mes+1);
        
        cbAno.setSelectedItem(anox); 
        cbMes.setSelectedItem(mesx); 
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cbAno = new javax.swing.JComboBox<String>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbMes = new javax.swing.JComboBox<String>();
        CargaButton = new javax.swing.JButton();
        cbEcona = new javax.swing.JCheckBox();
        cbDisosur = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        lbcargando = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DetalleDocumento = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        documentodetalleregistro = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem1.setText("Ficha Producto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem3.setText("Copiar N° Documento");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        jMenuItem2.setText("Ficha Producto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem2);

        jMenuItem4.setText("Copiar N° Documento");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem4);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Reporte Margen Proveedor"));
        jPanel1.setToolTipText("");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));

        cbAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035" }));

        jLabel1.setText("Año:");

        jLabel2.setText("Mes:");

        cbMes.setMaximumRowCount(12);
        cbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesActionPerformed(evt);
            }
        });

        CargaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Actualiza.png"))); // NOI18N
        CargaButton.setText("Cargar");
        CargaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargaButtonActionPerformed(evt);
            }
        });

        cbEcona.setText("Econa");

        cbDisosur.setText("Disosur");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbAno, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbEcona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDisosur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CargaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbEcona)
                        .addComponent(cbDisosur))
                    .addComponent(CargaButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbcargando.setText("Calculando Márgenes");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbcargando, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbcargando)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        DetalleDocumento.setAutoCreateRowSorter(true);
        DetalleDocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut", "Nombre", "$ Venta", "$ Costo", "Sku", "Producto", "Fecha Emision", "Fecha Creacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DetalleDocumento.setComponentPopupMenu(jPopupMenu1);
        DetalleDocumento.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(DetalleDocumento);
        if (DetalleDocumento.getColumnModel().getColumnCount() > 0) {
            DetalleDocumento.getColumnModel().getColumn(0).setMinWidth(80);
            DetalleDocumento.getColumnModel().getColumn(0).setPreferredWidth(80);
            DetalleDocumento.getColumnModel().getColumn(0).setMaxWidth(80);
            DetalleDocumento.getColumnModel().getColumn(2).setMinWidth(70);
            DetalleDocumento.getColumnModel().getColumn(2).setPreferredWidth(70);
            DetalleDocumento.getColumnModel().getColumn(2).setMaxWidth(70);
            DetalleDocumento.getColumnModel().getColumn(3).setMinWidth(70);
            DetalleDocumento.getColumnModel().getColumn(3).setPreferredWidth(70);
            DetalleDocumento.getColumnModel().getColumn(3).setMaxWidth(70);
            DetalleDocumento.getColumnModel().getColumn(4).setMinWidth(90);
            DetalleDocumento.getColumnModel().getColumn(4).setPreferredWidth(90);
            DetalleDocumento.getColumnModel().getColumn(4).setMaxWidth(90);
            DetalleDocumento.getColumnModel().getColumn(6).setMinWidth(90);
            DetalleDocumento.getColumnModel().getColumn(6).setPreferredWidth(90);
            DetalleDocumento.getColumnModel().getColumn(6).setMaxWidth(90);
            DetalleDocumento.getColumnModel().getColumn(7).setMinWidth(90);
            DetalleDocumento.getColumnModel().getColumn(7).setPreferredWidth(90);
            DetalleDocumento.getColumnModel().getColumn(7).setMaxWidth(90);
        }

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Registros:");

        documentodetalleregistro.setText("0");

        jButton1.setText("Exportar Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(documentodetalleregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 722, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(documentodetalleregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_cbMesActionPerformed
    
    
    private void CargaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargaButtonActionPerformed
        
        CargaDetalle();
                
    }//GEN-LAST:event_CargaButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String SKU = DetalleDocumento.getValueAt(DetalleDocumento.getSelectedRow(), 0).toString().trim();      
        pfProductos Pro = new pfProductos();
        pnPestanas.addTab("Ficha Producto", Pro);
        PanelTab btc=new PanelTab(pnPestanas,0);
        pnPestanas.setTabComponentAt(pnPestanas.indexOfComponent(Pro), btc);
        pnPestanas.setSelectedIndex(pnPestanas.getTabCount()-1);
        Pro.txSku.requestFocus();
        Pro.txSku.setText(SKU);
        Pro.btIr.doClick();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
     //   String SKU = DetalleOrdenes.getValueAt(DetalleOrdenes.getSelectedRow(), 0).toString().trim();      
        pfProductos Pro = new pfProductos();
        pnPestanas.addTab("Ficha Producto", Pro);
        PanelTab btc=new PanelTab(pnPestanas,0);
        pnPestanas.setTabComponentAt(pnPestanas.indexOfComponent(Pro), btc);
        pnPestanas.setSelectedIndex(pnPestanas.getTabCount()-1);
        Pro.txSku.requestFocus();
     //   Pro.txSku.setText(SKU);
        Pro.btIr.doClick();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        StringSelection Voucher = new StringSelection(DetalleDocumento.getValueAt(DetalleDocumento.getSelectedRow(), 6).toString().trim());
        Clipboard cb = Toolkit.getDefaultToolkit().getSystemClipboard();
        cb.setContents(Voucher, null);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
//        StringSelection Voucher = new StringSelection(DetalleOrdenes.getValueAt(DetalleOrdenes.getSelectedRow(), 6).toString().trim());
//        Clipboard cb = Toolkit.getDefaultToolkit().getSystemClipboard();
//        cb.setContents(Voucher, null);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (DetalleDocumento.getRowCount() > 0) {
                JFileChooser chooser = new JFileChooser();
                FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de excel", "xls");
                chooser.setFileFilter(filter);
                chooser.setDialogTitle("Guardar archivo");
                chooser.setAcceptAllFileFilterUsed(false);
                if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                    List tb = new ArrayList();
                    List nom = new ArrayList();
                    tb.add(DetalleDocumento);
                    nom.add("Reporte Margen");
                    String file = chooser.getSelectedFile().toString().concat(".xls");
                    try {
                       Exporter e = new Exporter(new File(file), tb, nom);
                        if (e.export()) {
                            JOptionPane.showMessageDialog(null, "Los datos fueron exportados en el directorio seleccionado", "Mensaje de Informacion", JOptionPane.INFORMATION_MESSAGE);
                        }
                    } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Hubo un error " + e.getMessage(), " Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this, "No hay datos para exportar","Mensaje de error",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    
     public void CargaDetalle() {
        
        DefaultTableModel model = (DefaultTableModel) DetalleDocumento.getModel();
         
        while(model.getRowCount()>0){
             model.removeRow(0);
        }
         
         
        int mes = cbMes.getSelectedIndex()+1;
        String ano = cbAno.getSelectedItem().toString();
        String Skunext = "";
        
        
        ExeSql sql = new ExeSql();
        ExeSql sqlVentas = new ExeSql();
        ResultSet rs = null;
        ResultSet rs2 = null;
        
       
        
        
                        
        try {

            
            
                
                String queryClientes = "select cd.rut, cd.sku, cd.tipdocto, cd.nrodocto, c.femision, round(cd.valorunitario) as venta from ctacteclidet cd\n" +
                                       "left join ctactecli c on cd.rut = c.rut and cd.nrodocto = c.nrodocto and cd.tipdocto IN ('BOC','FAC')  \n" +
                                       "where EXTRACT(YEAR FROM c.femision) = "+ cbAno.getSelectedItem().toString().trim()+ " \n" +
                                       "and EXTRACT(MONTH FROM c.femision) = "+ cbMes.getSelectedItem().toString().trim()+ " \n" +
                                       "order by cd.sku";
            
            
           
                rs = sqlVentas.Select(queryClientes);
           
            
                while (rs.next()) {

                
                    if (!rs.getString("sku").equals(Skunext) ){
                
                        
                        String query =  "SELECT pr.rut, pr.nombre, \n" +
                                        "(select cc.valorunitario from ctacteprvdet cc \n" +
                                        "  left join ctacteprv c ON  cc.rut = c.rut AND c.tipdocto IN ('FAP') AND cc.nrodocto = c.nrodocto \n" +
                                        "  where cc.rut = pr.rut and cc.sku = cd.sku \n" +
                                        "  and EXTRACT(YEAR FROM c.femision) = "+ cbAno.getSelectedItem().toString().trim()+" \n" +
                                        "  and EXTRACT(MONTH FROM c.femision) = "+ cbMes.getSelectedItem().toString().trim()+" \n" +
                                        "  order by c.fcreacion DESC LIMIT 1 \n" +
                                        " ) costo, \n" +
                                        " cd.sku, p.nombre as producto, c.femision, c.fcreacion FROM proveedor pr \n" +
                                        " left join ctacteprvdet cd ON pr.rut = cd.rut AND cd.tipdocto IN ('FAP') \n" +
                                        " left join ctacteprv c ON  cd.rut = c.rut AND c.tipdocto IN ('FAP') AND cd.nrodocto = c.nrodocto \n" +
                                        " left join producto p ON cd.sku = p.sku \n" +
                                        " WHERE EXTRACT(YEAR FROM c.femision) = "+ cbAno.getSelectedItem().toString().trim()+" \n" +
                                        " AND EXTRACT(MONTH FROM c.femision) = "+ cbMes.getSelectedItem().toString().trim()+" \n" +
                                        " AND pr.rut = "+rs.getString("sku").trim()+" \n"+
                                        " ORDER BY pr.rut, cd.sku ASC, c.fcreacion DESC";
                        
                        rs2 = sql.Select(query);
                        
                        if(sql.GetRowCount() > 0){
                        
                            
                            while (rs2.next()) { 
                            
                                model.addRow(new Object[]{
                   
                                    rs2.getString("rut").trim(),
                                    rs2.getString("nombre").trim(),
                                    rs.getString("venta").trim(),
                                    Math.round(rs2.getFloat("costo")),
                                    rs2.getString("sku").trim(),
                                    rs2.getString("producto").trim(),
                                    rs2.getString("femision"),
                                    rs2.getString("fcreacion")
                    
                
                                });
                            
                            }
                        
                            Skunext = rs.getString("sku");
                            
                        }    
                    }
                    
                    
                }

            
        } catch (SQLException ex) {
            Logger.getLogger(pfReportesMargenProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally {
            sql.Close();
            sqlVentas.Close();
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton CargaButton;
    private javax.swing.JTable DetalleDocumento;
    private javax.swing.JComboBox<String> cbAno;
    private javax.swing.JCheckBox cbDisosur;
    private javax.swing.JCheckBox cbEcona;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JLabel documentodetalleregistro;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbcargando;
    // End of variables declaration//GEN-END:variables
}
