/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Dialogos.jdPagadoPrvCli;
import Formularios.fmMain;
import java.math.BigInteger;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/**
 *
 * @author David Alcaman
 */
public class pfReporteSeparacion extends javax.swing.JPanel {
    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
    /**
     * Creates new form pfReportePagosPrv
     */
    public pfReporteSeparacion() {
        initComponents();
        //CargaUsuario();
          //Setea fecha inicial Desde y Hasta
            Date date = new Date();
            dtDesde.setDate(date);
            dtHasta.setDate(date);
            dtDesde.setEnabled(true);
            dtHasta.setEnabled(true);
//            btExcel.setVisible(false);
        carga_usuarios();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        Grilla.getColumnModel().getColumn(1).setCellRenderer(rightRenderer);

        String item= fmMain.GetUsuario();
        int i =-100;
        
        
//        if (!fmMain.GetUsuarioAdministrador())
//        {
//            CboUsuario.setEnabled(false);
//              boolean exists = false;
//                    for (int index = 0; index < CboUsuario.getItemCount() && !exists; index++) {
//                      if (item.equals(CboUsuario.getItemAt(index))) {
//                        exists = true;
//                        i=index;
//                       break;
//                      }
//                    }
//            CboUsuario.setSelectedIndex(i);
//                
//        }
//        else
//        {
//            CboUsuario.setEnabled(true);    
//        }
        
        
        
        
        
        
        
      
        
        // Enlaza Grilla con Grilla
        
        
        Grilla.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        @Override
        public void valueChanged(ListSelectionEvent e){
           if (Grilla.getSelectedRowCount()>0)
               Carga_Detalle_separacion(Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString().trim(),Grilla.getValueAt(Grilla.getSelectedRow(), 1).toString().trim(),Grilla_Usu.getValueAt(Grilla_Usu.getSelectedRow(), 0).toString().trim());
       } 
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Grilla_Usu = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        dtDesde = new org.jdesktop.swingx.JXDatePicker();
        dtHasta = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        rbDesde = new javax.swing.JRadioButton();
        rbPeriodoTodos = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        Tot_Ordenes = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbReg = new javax.swing.JLabel();
        lbTotalSeparadas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Grilla_Det = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lbReg_det = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbTotalSeparadasDet = new javax.swing.JLabel();
        BtBuscar = new javax.swing.JButton();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PROVEEDOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        Grilla_Usu.setAutoCreateRowSorter(true);
        Grilla_Usu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Usuario", "Ordenes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla_Usu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Grilla_UsuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Grilla_Usu);
        if (Grilla_Usu.getColumnModel().getColumnCount() > 0) {
            Grilla_Usu.getColumnModel().getColumn(0).setMinWidth(80);
            Grilla_Usu.getColumnModel().getColumn(0).setPreferredWidth(80);
            Grilla_Usu.getColumnModel().getColumn(0).setMaxWidth(80);
            Grilla_Usu.getColumnModel().getColumn(1).setMinWidth(200);
            Grilla_Usu.getColumnModel().getColumn(1).setPreferredWidth(200);
            Grilla_Usu.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PERIODO VENCIMIENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        dtDesde.setEnabled(false);
        dtDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtDesdeActionPerformed(evt);
            }
        });

        dtHasta.setEnabled(false);
        dtHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtHastaActionPerformed(evt);
            }
        });

        jLabel2.setText("Hasta");

        buttonGroup1.add(rbDesde);
        rbDesde.setSelected(true);
        rbDesde.setText("Desde");
        rbDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDesdeActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbPeriodoTodos);
        rbPeriodoTodos.setText("Todos");
        rbPeriodoTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPeriodoTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbDesde)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rbPeriodoTodos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(rbDesde)))
                .addGap(18, 18, 18)
                .addComponent(rbPeriodoTodos)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Total Ordenes");

        Tot_Ordenes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tot_Ordenes.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tot_Ordenes, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Tot_Ordenes)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Ordenes");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Prod. Separados");

        lbReg.setText("0.00");

        lbTotalSeparadas.setText("0.00");

        Grilla.setAutoCreateRowSorter(true);
        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha", "Orden", "Prod. Sepa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(0).setMinWidth(80);
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(0).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(1).setMinWidth(200);
            Grilla.getColumnModel().getColumn(1).setPreferredWidth(200);
            Grilla.getColumnModel().getColumn(1).setMaxWidth(200);
            Grilla.getColumnModel().getColumn(2).setMinWidth(40);
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(40);
            Grilla.getColumnModel().getColumn(2).setMaxWidth(40);
        }

        Grilla_Det.setAutoCreateRowSorter(true);
        Grilla_Det.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Orden", "Sku", "Nombre", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla_Det.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Grilla_DetMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Grilla_Det);
        if (Grilla_Det.getColumnModel().getColumnCount() > 0) {
            Grilla_Det.getColumnModel().getColumn(0).setMinWidth(80);
            Grilla_Det.getColumnModel().getColumn(0).setPreferredWidth(80);
            Grilla_Det.getColumnModel().getColumn(0).setMaxWidth(80);
            Grilla_Det.getColumnModel().getColumn(1).setMinWidth(100);
            Grilla_Det.getColumnModel().getColumn(1).setPreferredWidth(100);
            Grilla_Det.getColumnModel().getColumn(1).setMaxWidth(100);
            Grilla_Det.getColumnModel().getColumn(2).setMinWidth(100);
            Grilla_Det.getColumnModel().getColumn(2).setPreferredWidth(100);
            Grilla_Det.getColumnModel().getColumn(2).setMaxWidth(100);
            Grilla_Det.getColumnModel().getColumn(3).setMinWidth(200);
            Grilla_Det.getColumnModel().getColumn(3).setPreferredWidth(200);
            Grilla_Det.getColumnModel().getColumn(3).setMaxWidth(200);
            Grilla_Det.getColumnModel().getColumn(4).setMinWidth(100);
            Grilla_Det.getColumnModel().getColumn(4).setPreferredWidth(100);
            Grilla_Det.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Sku");

        lbReg_det.setText("0.00");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Sum Cantidad");

        lbTotalSeparadasDet.setText("0.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbReg, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalSeparadas, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbReg_det, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalSeparadasDet, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(lbReg)
                    .addComponent(lbTotalSeparadas)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(lbReg_det)
                    .addComponent(lbTotalSeparadasDet))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(253, Short.MAX_VALUE))
        );

        BtBuscar.setText("Buscar");
        BtBuscar.setName("CboUsuario"); // NOI18N
        BtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtBuscar)
                .addContainerGap(474, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(BtBuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
//    private void CargaUsuario(){
//        ExeSql Sql = new ExeSql();
//        ResultSet Rs;
//        CboUsuario.removeAllItems();
//        CboUsuario.addItem("<Todos>");  // Agrego la condicion inicial de Todos
//        try {
//            Rs = Sql.Select("select distinct s.usuario from separacion s\n" +
//                            "left  join usuario u\n" +
//                            "on TRIM(s.usuario) = TRIM(u.usuario)\n" +
//                            "where\n" +
//                            "s.recepcion = FALSE\n" +
//                                                         "order by usuario");
//            if(Sql.GetRowCount()==0) return;
//     
//           while(Rs.next()){
//          
//            CboUsuario.addItem( Rs.getString("usuario").trim());
//
//            //cbvenId.addItem(Rs.getInt("cod"));   
//            //btBuscar.doClick();
//           } 
//           
//           CboUsuario.setSelectedIndex(0);
//
//           
//           
//        } catch (Exception e) {
//            System.out.println(e);
//        }
//        finally{
//            Sql.Close();
//        }
//    }
    
    public void limpiar(){

    DefaultTableModel   enca = (DefaultTableModel) Grilla.getModel();
    DefaultTableModel   det = (DefaultTableModel) Grilla_Det.getModel();
    DefaultTableModel   usu = (DefaultTableModel) Grilla_Usu.getModel();
    while(enca.getRowCount()>0)
        enca.removeRow(0);
    
    while(det.getRowCount()>0)
        det.removeRow(0);
    
    while(usu.getRowCount()>0)
        usu.removeRow(0);
    }
    
    
    public void Carga_Detalle_separacion(String fecha, String Orden, String usuario ){
        String Query ="";
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel TableModel = (DefaultTableModel) Grilla_Det.getModel();
        double Sumador=0;
        int ContReg=0;
         while(TableModel.getRowCount()>0)
             TableModel.removeRow(0);
        try {
Query = " select CAST (fecha AS VARCHAR (10)) fecha,\n" +
"               s.codigo_oc || '-' || s.orden CodigoOrden,\n" +
"               s.sku,\n" +
"               p.nombre,\n" +
"               s.cantidad \n" +
"        from separacion s\n" +
"inner join producto p on  p.sku = s.sku" +        
"        WHERE fecha is NOT NULL and\n" +
"              CAST (fecha AS VARCHAR (10)) = '" + fecha + "'\n" +
"               and   s.usuario in ('" + usuario + "') \n" +
"               and  s.codigo_oc || '-' || s.orden  in ('" + Orden + "')";
            Rs = Sql.Select(Query);
    while (Rs.next()){
                ContReg++;
                        TableModel.addRow(new Object[]{Rs.getString("fecha").trim(),
                                               Rs.getString("CodigoOrden").trim(),  
                                               Rs.getString("sku").trim(), 
                                               Rs.getString("nombre").trim(),
                                               fmMain.FormatoNumero(Rs.getDouble("cantidad"))});
                Sumador = Sumador + Rs.getDouble("cantidad");
                
                lbTotalSeparadasDet.setText(fmMain.FormatoNumero(Sumador));
                lbReg_det.setText(fmMain.FormatoTotal(ContReg));
                Grilla_Det.changeSelection(0, 0 , false, false);
               }
         
            
        } catch (Exception e) {
          
        } finally{
            Sql.Close();
        }
}
 
    
    private void BtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarActionPerformed
        
        int Pos_Sel=0;        
        String Usu="";    
        carga_usuarios();
        if (Grilla_Usu.getSelectedRow()<0 && Grilla_Usu.getRowCount()>=0){
            Usu= Grilla_Usu.getValueAt(0,0).toString();
            Grilla_Usu.changeSelection(0, 0 , false, false);
        }   
        else{
            Usu= Grilla_Usu.getValueAt(Grilla_Usu.getSelectedRow(),0).toString();
        }
        
//        if (Grilla_Usu.getSelectedRow()== -1){
//             
//            Usu= Grilla_Usu.getValueAt(0,0).toString();
//        }   
//        else{
//            Usu= Grilla_Usu.getValueAt(Grilla_Usu.getSelectedRow(),0).toString();
//        }
            
//        if (Grilla_Usu.getSelectedRow()== -1){
//            Grilla_Usu.changeSelection(0, 0 , false, false);
//        }   
//        Usu= Grilla_Usu.getValueAt(Grilla_Usu.getSelectedRow(),0).toString();
        
        
        
        Pos_Sel = Grilla_Usu.getSelectedRow();
        
        if (Usu.equals(""))
            fmMain.Mensaje("Debe seleccionar un usuario en la Grilla.!!");
        else
            busca_usu(Usu,Pos_Sel);
        grilla_usu_click();
     
//        ExeSql Sql = new ExeSql();
//        ResultSet Rs,RsCant;
//        String Query="", Query_Cant="", StUsuario = "";
//        limpiar();
//        carga_usuarios();
//        DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
//        int ContPagos=0;
//         BigInteger TotSeparadas = new BigInteger("0");
//        while(TableModel.getRowCount()>0)
//           TableModel.removeRow(0);        
//try {
//    
//Query = " select  tbase1.CodigoOrden,tbase1.fecha, tbase1.usuario, COUNT(tbase1.sku) Cant_Item, SUM(tbase1.cant_positivo) pos,\n" +
//        " SUM(tbase1.cant_negativo) neg,SUM(tbase1.cant_positivo)- SUM(tbase1.cant_negativo) tot \n" +
//        " from( \n" +
//        " select CAST(fecha AS VARCHAR(10)) fecha, s.codigo_oc || '-' || s.orden CodigoOrden, \n" +
//        " s.usuario, s.sku, \n" +
//        " CASE WHEN s.cantidad>0 THEN 1 ELSE 0 END cant_positivo,\n" +
//        " CASE WHEN s.cantidad<0 THEN 1 ELSE 0 END cant_negativo \n   from separacion s \n" +
//        " WHERE fecha is NOT NULL \n";
//         if(rbDesde.isSelected()){
//                Query = Query + " and  CAST(fecha AS VARCHAR(10)) between  '" + getDesde() + "' and '" + getHasta() + "'\n"; 
//         }            
//          
//                  StUsuario=   Grilla_Usu.getValueAt(Grilla_Usu.getSelectedRow(),0).toString();
//                 Query = Query +   " and s.usuario IN ('" + StUsuario + "')\n";  
//          
//       Query = Query +   " order by fecha,CodigoOrden,usuario ) tbase1  ";    
//       Query = Query +   " group by tbase1.fecha,tbase1.CodigoOrden,tbase1.usuario ";  
//    
//  
// 
//
// // EJECUTA CONSULTA
//            Rs = Sql.Select(Query);
//            
//            while(Rs.next()){
//              ContPagos++;
//              TotSeparadas = TotSeparadas.add(new BigInteger(Rs.getString("tot"))) ;
//              TableModel.addRow(new Object[]{Rs.getString("fecha").trim(), 
//                                               Rs.getString("codigoorden").trim(), 
//                                               fmMain.FormatoTotal(Rs.getDouble("tot"))});
//            }
//            
//                  lbTotalSeparadas.setText(fmMain.FormatoNumeroBig(TotSeparadas));
//                  lbReg.setText(fmMain.FormatoTotal(ContPagos));
//            
////            ChartPanel chartpanel = Barras3d();
////            chartpanel.setDomainZoomable(true);
////            jPanelGrafico.setLayout(new BorderLayout());
////            jPanelGrafico.add(chartpanel, BorderLayout.SOUTH);
//    }
//catch (Exception e) {
//            fmMain.Mensaje("Existe una inconsistencia en la información.");
//        }finally{
//            Sql.Close();
//        }
//     
    }//GEN-LAST:event_BtBuscarActionPerformed


private void busca_usu(String Usu,int pos )    {
        
    ExeSql Sql = new ExeSql();
        ResultSet Rs,RsCant;
        String Query="", Query_Cant="", StUsuario = "";
//        limpiar();
//        carga_usuarios();
        Grilla_Usu.changeSelection(pos, 0 , false, false);
        DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
        int ContPagos=0;
         BigInteger TotSeparadas = new BigInteger("0");
        while(TableModel.getRowCount()>0)
           TableModel.removeRow(0);        
try {
    
Query = " select  tbase1.CodigoOrden,tbase1.fecha, tbase1.usuario, COUNT(tbase1.sku) Cant_Item, SUM(tbase1.cant_positivo) pos,\n" +
        " SUM(tbase1.cant_negativo) neg,SUM(tbase1.cant_positivo)- SUM(tbase1.cant_negativo) tot \n" +
        " from( \n" +
        " select CAST(fecha AS VARCHAR(10)) fecha, s.codigo_oc || '-' || s.orden CodigoOrden, \n" +
        " s.usuario, s.sku, \n" +
        " CASE WHEN s.cantidad>0 THEN 1 ELSE 0 END cant_positivo,\n" +
        " CASE WHEN s.cantidad<0 THEN 1 ELSE 0 END cant_negativo \n   from separacion s \n" +
        " WHERE fecha is NOT NULL and s.recepcion = false \n";
         if(rbDesde.isSelected()){
                Query = Query + " and  CAST(fecha AS VARCHAR(10)) between  '" + getDesde() + "' and '" + getHasta() + "'\n"; 
         }            
         
                 Query = Query +   " and s.usuario = '" + Usu + "'\n";  
          
       Query = Query +   " order by fecha,CodigoOrden,usuario ) tbase1  ";    
       Query = Query +   " group by tbase1.fecha,tbase1.CodigoOrden,tbase1.usuario ";  

 // EJECUTA CONSULTA
            Rs = Sql.Select(Query);
            
            while(Rs.next()){
              ContPagos++;
              TotSeparadas = TotSeparadas.add(new BigInteger(Rs.getString("tot"))) ;
              TableModel.addRow(new Object[]{Rs.getString("fecha").trim(), 
                                               Rs.getString("codigoorden").trim(), 
                                               fmMain.FormatoTotal(Rs.getDouble("tot"))});
            }
            
                  lbTotalSeparadas.setText(fmMain.FormatoNumeroBig(TotSeparadas));
                  lbReg.setText(fmMain.FormatoTotal(ContPagos));
            

    }
catch (Exception e) {
            fmMain.Mensaje("Existe una inconsistencia en la información.");
        }finally{
            Sql.Close();
        }
     
    }   
    
    
private void carga_usuarios() {                                            
        ExeSql Sql = new ExeSql();
        ResultSet Rs,RsCant;
        String Query="", Query_Cant="";
        String NombrePersonal;
//        limpiar();
        DefaultTableModel TableModel = (DefaultTableModel) Grilla_Usu.getModel();
        int CantOrdenes=0;
        
        while(TableModel.getRowCount()>0)
           TableModel.removeRow(0);        
try {

//    Query_Cant = "select a.usu, COUNT(a.orden) Ordenes\n" +
//    " from \n" +
//    "     (select  \n" +
//    "     s.usuario usu,\n" +
//    "     s.codigo_oc || '-' || s.orden orden\n" +
//    "     from separacion s \n" +
//    "     WHERE fecha is NOT NULL \n";
//    if(rbDesde.isSelected()){
//            Query_Cant = Query_Cant + " and  CAST(fecha AS VARCHAR(10)) between  '" + getDesde() + "' and '" + getHasta() + "'\n"; 
//     }            
//    Query_Cant = Query_Cant + "  and recepcion = false  group by s.usuario,s.codigo_oc || '-' || s.orden) a\n";
//    Query_Cant = Query_Cant + " group by  a.usu";
    
    
Query_Cant = "select tbase1.usuario usu, count(tbase1.ordenes) ordenes  from \n" +
" (select distinct s.usuario, s.codigo_oc || '-' || s.orden ordenes\n" +
"   from separacion s \n" +
" WHERE fecha is NOT NULL and s.recepcion = false \n";
   if(rbDesde.isSelected()){
            Query_Cant = Query_Cant + " and  CAST(fecha AS VARCHAR(10)) between  '" + getDesde() + "' and '" + getHasta() + "') tbase1 \n"; 
     }         
    else {
    Query_Cant = Query_Cant + ") tbase1 \n";
    }   
 //" and  CAST(fecha AS VARCHAR(10)) between  '2017-09-22' and '2017-09-22')tbase1\n" +
   Query_Cant = Query_Cant + " group by tbase1.usuario";
    
    
    
    Rs = Sql.Select(Query_Cant);    
            while(Rs.next()){
              TableModel.addRow(new Object[]{Rs.getString("usu").trim(), 
                                               Rs.getString("ordenes").trim()});
              CantOrdenes= CantOrdenes +  Integer.valueOf(Rs.getString("ordenes").trim());
            }
            
            Tot_Ordenes.setText(String.valueOf(CantOrdenes));
            
    }
    catch (Exception e) {
            fmMain.Mensaje("Existe una inconsistencia en la información.");
        }finally{
            Sql.Close();
        }
        DefaultTableModel TableModels = (DefaultTableModel) Grilla_Usu.getModel();
        if(TableModels.getRowCount()>0){
            Grilla_Usu.setRowSelectionInterval(0, 0);
        }
     
}       
    
    
    
    
    private void GrillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaMouseClicked
        if(evt.getClickCount()==2 && !Grilla.getValueAt(Grilla.getSelectedRow(),0).toString().equals("Pendiente")){
            jdPagadoPrvCli Pagado = new jdPagadoPrvCli(null, true);
            Pagado.setLocationRelativeTo(null);
            Pagado.setTitle("Pagos Realizados");
            Pagado.CargaPagosPrv(Grilla.getValueAt(Grilla.getSelectedRow(), 12).toString().trim(),"");  
            Pagado.setVisible(true);
        }
    }//GEN-LAST:event_GrillaMouseClicked

    private void dtHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtHastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtHastaActionPerformed

    private void rbDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDesdeActionPerformed
        // TODO add your handling code here:
        if(rbDesde.isSelected()){
            dtDesde.setEnabled(true);
            dtHasta.setEnabled(true);
        }
    }//GEN-LAST:event_rbDesdeActionPerformed

    private void rbPeriodoTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPeriodoTodosActionPerformed
        // TODO add your handling code here:
        if(rbPeriodoTodos.isSelected()){
            dtDesde.setEnabled(false);
            dtHasta.setEnabled(false);
          }
    }//GEN-LAST:event_rbPeriodoTodosActionPerformed

    private void Grilla_DetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Grilla_DetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Grilla_DetMouseClicked

    private void Grilla_UsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Grilla_UsuMouseClicked
        // TODO add your handling code here:
     int Pos_Sel=0;
        String Usu="";    
        Usu= Grilla_Usu.getValueAt(Grilla_Usu.getSelectedRow(),0).toString();
        Pos_Sel = Grilla_Usu.getSelectedRow();
        if (Usu.equals(""))
            fmMain.Mensaje("Debe seleccionar un usuario en la Grilla.!!");
        else
            busca_usu(Usu,Pos_Sel);
    }//GEN-LAST:event_Grilla_UsuMouseClicked

    private void grilla_usu_click() {
       int Pos_Sel=0;
        String Usu="";    
        Usu= Grilla_Usu.getValueAt(Grilla_Usu.getSelectedRow(),0).toString();
        Pos_Sel = Grilla_Usu.getSelectedRow();
        if (Usu.equals(""))
            fmMain.Mensaje("Debe seleccionar un usuario en la Grilla.!!");
        else
            busca_usu(Usu,Pos_Sel);
}
    
    
    
    private void dtDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtDesdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtDesdeActionPerformed
//6700

    
//    public ChartPanel Barras3d()
//        {
//            ExeSql Sql = new ExeSql();
//            ResultSet Rs;
//             DefaultCategoryDataset dataset = new DefaultCategoryDataset();
//             
//            try {
//                Rs= Sql.Select("select count (distinct(codigo_oc||orden)) as ordenes, date(fecha) as fecha, usuario from separacion where recepcion=false and usuario = '"+CboUsuario.getSelectedItem().toString().trim()+"'  and fecha>='" + getDesde() + " 00:00' and  fecha<='" + getHasta() + " 23:59'\n" +
//                                "group by date(fecha), usuario order by fecha asc" );
//                while(Rs.next())
//                    {
//                    dataset.addValue(Rs.getDouble("ordenes"), Rs.getString("usuario"), Rs.getString("fecha"));
//                    }
//                
//            }   
//            catch (Exception e)
//            {
//                fmMain.Mensaje("Error al cargar datos grafico: "+e);
//            }
//            finally{
//              Sql.Close();
//            }
//            
//     
// 
//                JFreeChart barChart = ChartFactory.createBarChart3D(
//                                "Reporte de separacion",
//                                "Días",
//                                "OC Separadas",
//                                dataset,
//                                PlotOrientation.VERTICAL,
//                                true,
//                                true,
//                                false);
// 
//                ChartPanel panel = new ChartPanel(barChart);
// 
//                return panel;
// 
//        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBuscar;
    private javax.swing.JTable Grilla;
    private javax.swing.JTable Grilla_Det;
    private javax.swing.JTable Grilla_Usu;
    private javax.swing.JLabel Tot_Ordenes;
    private javax.swing.ButtonGroup buttonGroup1;
    private org.jdesktop.swingx.JXDatePicker dtDesde;
    private org.jdesktop.swingx.JXDatePicker dtHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JLabel lbReg;
    private javax.swing.JLabel lbReg_det;
    private javax.swing.JLabel lbTotalSeparadas;
    private javax.swing.JLabel lbTotalSeparadasDet;
    private javax.swing.JRadioButton rbDesde;
    private javax.swing.JRadioButton rbPeriodoTodos;
    // End of variables declaration//GEN-END:variables

   

    private static class CboUsuario {
        public CboUsuario() {
        }
    }

    public String getDesde() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return( sdf.format( (dtDesde.getDate()).getTime() ) );
    }
    public String getHasta() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return( sdf.format( (dtHasta.getDate()).getTime() ) );
    }
   
}
