/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Dialogos.jdBuscarCliPrv;
import static Dialogos.jdOC_PendientesFac.pano;
import static Dialogos.jdOC_PendientesFac.pmes;
import static Dialogos.jdOC_PendientesFac.pmes_oc;
import Dialogos.jdPagadoPrvCli;
import Dialogos.jdPagarPrv;
import Formularios.fmMain;
import static Formularios.fmMain.pnPestanas;
import Utilidades.Exporter;
import Utilidades.PanelTab;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.math.BigInteger;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author David Alcaman
 */
public class pfReporteVentasFinal extends javax.swing.JPanel {
    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
    /**
     * Creates new form pfReportePagosPrv
     */
    public pfReporteVentasFinal() {
        initComponents();
//        CargaVendedor();

        Calendar fecha = new GregorianCalendar();
        //Obtenemos el valor del año, mes, día,
        //hora, minuto y segundo del sistema
        //usando el método get y el parámetro correspondiente
        int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
       /* int dia = fecha.get(Calendar.DAY_OF_MONTH);
        int hora = fecha.get(Calendar.HOUR_OF_DAY);
        int minuto = fecha.get(Calendar.MINUTE);
        int segundo = fecha.get(Calendar.SECOND);*/
        
        String anox ="x";
        String mesx ="x";
        
        anox = String.valueOf(año);
        mesx = String.valueOf(mes+1);

        cboAgno.setSelectedItem(anox); 
        cboMes.setSelectedItem(mesx); 
                
          
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        Grilla.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
        Grilla.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
        Grilla.getColumnModel().getColumn(6).setCellRenderer(rightRenderer);
        Grilla.getColumnModel().getColumn(7).setCellRenderer(rightRenderer);
        Grilla.getColumnModel().getColumn(8).setCellRenderer(rightRenderer);
        
        
        int intNivelMnu = 100;
        int intNivelUsuario = fmMain.trae_nivel(fmMain.GetUsuario());
        if (intNivelUsuario<100){
            btExcel.setVisible(false);
        }
        btExcel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbReg = new javax.swing.JLabel();
        lbSumMontos = new javax.swing.JLabel();
        btExcel = new javax.swing.JButton();
        lbTotalFAC = new javax.swing.JLabel();
        lbTotalFEC = new javax.swing.JLabel();
        lblIva = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        lbTotalBOC = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        AGNO = new javax.swing.JPanel();
        cboAgno = new javax.swing.JComboBox<String>();
        cboMes = new javax.swing.JComboBox<String>();
        lblAgno = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CboTipoDoc = new javax.swing.JComboBox<String>();
        jLabel9 = new javax.swing.JLabel();
        btBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        registros = new javax.swing.JLabel();
        totales = new javax.swing.JLabel();

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nro Registros:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("FAC");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Pago Total");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("FEC");

        lbReg.setText("0.00");

        lbSumMontos.setText("0.00");

        btExcel.setText("Excel");
        btExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcelActionPerformed(evt);
            }
        });

        lbTotalFAC.setText("0.00");

        lbTotalFEC.setText("0.00");

        lblIva.setText("0.00");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("NCC");

        Grilla.setAutoCreateRowSorter(true);
        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Rut", "Cliente", "Tipo Docto", "Nro. Docto", "Afecto", "Exento", "Iva", "Total Docto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(0).setMinWidth(110);
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(110);
            Grilla.getColumnModel().getColumn(0).setMaxWidth(110);
            Grilla.getColumnModel().getColumn(1).setMinWidth(80);
            Grilla.getColumnModel().getColumn(1).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(1).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(2).setMinWidth(350);
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(320);
            Grilla.getColumnModel().getColumn(2).setMaxWidth(350);
            Grilla.getColumnModel().getColumn(3).setMinWidth(80);
            Grilla.getColumnModel().getColumn(3).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(3).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(4).setMinWidth(100);
            Grilla.getColumnModel().getColumn(4).setPreferredWidth(100);
            Grilla.getColumnModel().getColumn(4).setMaxWidth(100);
            Grilla.getColumnModel().getColumn(5).setMinWidth(85);
            Grilla.getColumnModel().getColumn(5).setPreferredWidth(85);
            Grilla.getColumnModel().getColumn(5).setMaxWidth(85);
            Grilla.getColumnModel().getColumn(6).setMinWidth(85);
            Grilla.getColumnModel().getColumn(6).setPreferredWidth(85);
            Grilla.getColumnModel().getColumn(6).setMaxWidth(85);
            Grilla.getColumnModel().getColumn(7).setMinWidth(80);
            Grilla.getColumnModel().getColumn(7).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(7).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(8).setMinWidth(80);
            Grilla.getColumnModel().getColumn(8).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(8).setMaxWidth(80);
        }

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("BOC");
        jLabel10.setToolTipText("");

        lbTotalBOC.setText("0.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbReg, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(346, 346, 346)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbTotalBOC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(lbTotalFAC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(lbTotalFEC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(lblIva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(lbSumMontos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(147, 147, 147)
                        .addComponent(btExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(12, 12, 12))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lbReg))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lbTotalBOC))
                        .addComponent(jLabel3)
                        .addComponent(lbTotalFAC)
                        .addComponent(jLabel5)
                        .addComponent(lbTotalFEC)
                        .addComponent(jLabel6)
                        .addComponent(lblIva)
                        .addComponent(jLabel4)
                        .addComponent(lbSumMontos))
                    .addComponent(btExcel))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        AGNO.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PERIODO VENCIMIENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        cboAgno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024" }));
        cboAgno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAgnoActionPerformed(evt);
            }
        });

        cboMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        lblAgno.setText("AÑO:");

        jLabel8.setText("MES:");

        CboTipoDoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Todos>", "FAC", "FEC", "FMC", "NCC", "NDC", "BOC" }));
        CboTipoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboTipoDocActionPerformed(evt);
            }
        });

        jLabel9.setText("TIPO DOC:");

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AGNOLayout = new javax.swing.GroupLayout(AGNO);
        AGNO.setLayout(AGNOLayout);
        AGNOLayout.setHorizontalGroup(
            AGNOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AGNOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AGNOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AGNOLayout.createSequentialGroup()
                        .addComponent(lblAgno)
                        .addGap(109, 109, 109)
                        .addComponent(cboAgno, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AGNOLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(79, 79, 79)
                        .addComponent(CboTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AGNOLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(111, 111, 111)
                        .addComponent(cboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        AGNOLayout.setVerticalGroup(
            AGNOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AGNOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AGNOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgno)
                    .addComponent(cboAgno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AGNOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(AGNOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CboTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btBuscar)
                .addGap(11, 11, 11))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Vendedor", "Total", "Codigo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(100);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(400);
            jTable1.getColumnModel().getColumn(1).setMinWidth(50);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(2).setMinWidth(0);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        jLabel2.setText("Total:");

        jLabel7.setText("Registros:");

        registros.setText("0");

        totales.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registros, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totales, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(registros)
                    .addComponent(totales))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AGNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(359, 359, 359)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AGNO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        AGNO.getAccessibleContext().setAccessibleName("PERIODO VENCIMIENTO1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
//    private void CargaVendedor(){
//        ExeSql Sql = new ExeSql();
//        ResultSet Rs;
//
//        try {
//            Rs = Sql.Select("select p.vendedor || ' - ' || \n" +
//                    " p.nombre || ' ' ||  p.apellidopaterno   || ' ' || p.apellidomaterno  as nombre\n" +
//                    " from personal p\n" +
//                    "left join usuario u on u.usuario = p.usuario\n"+
//                    " where p.vendedor >=0  and u.activo = true order by p.vendedor asc");
//            if(Sql.GetRowCount()==0) return;
//     
//           while(Rs.next()){
//          
//            CboVendedor.addItem( Rs.getString("nombre").trim());
//
//            //cbvenId.addItem(Rs.getInt("cod"));   
//            //btBuscar.doClick();
//           } 
//           
//           CboVendedor.setSelectedIndex(-1);
//
//           
//           
//        } catch (Exception e) {
//            System.out.println(e);
//        }
//        finally{
//            Sql.Close();
//        }
//    }
    
    
 
    
    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        String Query="";
        String NombrePersonal;
        String Str_totNC="";
        DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
        int ContPagos=0;
        double totNC=0.0;
//            BigInteger TotalAfecto    = new BigInteger("0");
//            BigInteger TotalExento    = new BigInteger("0");
//            BigInteger TotalNCC       = new BigInteger("0");
//            BigInteger TotalIva       = new BigInteger("0");
//            BigInteger Total          = new BigInteger("0");
  
        while(TableModel.getRowCount()>0)
           TableModel.removeRow(0);        
try {
                       


            String query = " select tot.vendedor, sum(tot.tipo), case when tot.codigo is null then 1000 else tot.codigo end as codigo\n" +
                            "from (select case when totales.Vendedor is null then 'SIN VENDEDOR' else totales.Vendedor end as vendedor,\n" +
                            "case \n" +
                            "	when totales.tipdocto IN ('FAC','BOC') then sum(totales.totalafecto)\n" +
                            "  	when totales.tipdocto = 'NCC' then -sum(totales.totNC)\n" +
                            "  	when totales.tipdocto = 'FEC' then sum(totales.totalexento)\n" +
                            "end as tipo,totales.codigo\n" +
                            "from\n" +
                            "(select  p.apellidopaterno || ' ' || p.nombre as Vendedor, c.tipdocto,oc.vendedor codigo,\n" +
                            "SUM(c.totalafecto )totalafecto,\n" +
                            "SUM(c.totalexento)totalexento,\n" +
                            "SUM(c.totaliva)totaliva,\n" +
                            "SUM(c.totaldocto) totaldocto, \n" +
                            "SUM(c.totalafecto + c.totalexento) totNC\n" +
                            "from ctactecli c\n" +
                            "left join occh oc on c.rut=oc.rut and c.codigo_oc=oc.codigo_oc and c.occh=oc.orden\n" +
                            "left join cliente cli on cli.rut=c.rut\n" +
                            "left join personal p on oc.vendedor=p.vendedor\n" +
                            " where extract(year from c.femision)= " + cboAgno.getSelectedItem().toString() + "\n" +
                            " and extract(month from c.femision)=" + cboMes.getSelectedItem().toString() + "\n";

            if(CboTipoDoc.getSelectedIndex() >0){
                query = query +   " and c.tipdocto in ('" + CboTipoDoc.getSelectedItem().toString() + "') \n";  
            } 
            else
            {
                query = query +   " and c.tipdocto in ('BOC','FAC','FEC','NCC') and  (p.apellidopaterno || ' ' || p.nombre) is not null \n";  
            }


            query = query + "Group by p.apellidopaterno || ' ' || p.nombre,c.tipdocto,oc.vendedor) totales\n" +
                            "group by totales.Vendedor ,totales.tipdocto,totales.codigo) tot\n" +
                            "group by tot.vendedor,tot.codigo";
            // EJECUTA CONSULTA
            DefaultTableModel modelo =(DefaultTableModel) jTable1.getModel();
            while(modelo.getRowCount()>0){
                modelo.removeRow(0);
            }
            double total = 0;
            int registros = 0;
            ResultSet Rs2 = Sql.Select(query);
            modelo.addRow(new Object[]{
               "TODOS",0,1001
            });
            for(int i = 0; Rs2.next(); i++){
                
                System.out.println("Vendedor : "+    Rs2.getString("Vendedor"));
                
                registros = registros + 1;
                total = total + Rs2.getDouble("sum");
                modelo.addRow(new Object[]{
                    Rs2.getString("Vendedor"),
                    fmMain.FormatoNumero(Rs2.getDouble("sum"))+ " $",
                    Rs2.getInt("codigo")
                });
            }
            this.registros.setText(String.valueOf(registros));
            this.totales.setText(fmMain.FormatoNumero(total));
            modelo.setValueAt(fmMain.FormatoNumero(total), 0, 1);
            jTable1.changeSelection(0, 0,false,false);
            jTable1.setRowSelectionInterval(0, 0);
            CargaVentas();
    }
    
    
    catch (Exception e) {
            fmMain.Mensaje(e.getMessage());
        }finally{
            Sql.Close();
        }
            
        
    }//GEN-LAST:event_btBuscarActionPerformed

    private void GrillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaMouseClicked
        if(evt.getClickCount()==2 && !Grilla.getValueAt(Grilla.getSelectedRow(),0).toString().equals("Pendiente")){
            jdPagadoPrvCli Pagado = new jdPagadoPrvCli(null, true);
            Pagado.setLocationRelativeTo(null);
            Pagado.setTitle("Pagos Realizados");
            Pagado.CargaPagosPrv(Grilla.getValueAt(Grilla.getSelectedRow(), 12).toString().trim(),"");  
            Pagado.setVisible(true);
        }
    }//GEN-LAST:event_GrillaMouseClicked

    private void btExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcelActionPerformed
//        if(Grilla.getRowCount()==0){
//            fmMain.Mensaje("Nada que exportar");
//            return;
//        }
//        
//        JFileChooser chooser = new JFileChooser();
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo Excel",".xls");
//        chooser.setFileFilter(filter);
//        chooser.setDialogTitle("Guardar Informe en Excel");
//        chooser.setMultiSelectionEnabled(false);
//        chooser.setAcceptAllFileFilterUsed(false);
//        
//        if(chooser.showSaveDialog(null)== JFileChooser.APPROVE_OPTION){
//            List<JTable> tb=new ArrayList<>();
//            List<String> nom=new ArrayList<>();
//            tb.add(Grilla);
//            nom.add("Ventas");
//            String file=chooser.getSelectedFile().toString().concat(".xls");
//            try {
//                Exporter e = new Exporter(new File(file), tb, nom);
//                if(e.export())
//                    fmMain.Mensaje("Datos Exportados");
//            } catch (Exception e) {
//                fmMain.Mensaje(e.getMessage());
//            }
//            
//            
//        }
        
   if(Grilla.getRowCount()==0){
            fmMain.Mensaje("Nada que exportar");
            return;
        }

            List<JTable> tb=new ArrayList<>();
            List<String> nom=new ArrayList<>();
            tb.add(Grilla);
            nom.add("Ventas");
            
            File folder = new File("c:/temp");
            if (!folder.exists())
            {
                folder.mkdir();
            }
            
             String file = "C:/temp/Ventas.xls";       
            
            
            try {
                Exporter e = new Exporter(new File(file), tb, nom);
                
                if(e.export())
                //fmMain.Mensaje("Datos Exportados");
                abrir(file);
                
            } catch (Exception e) {
                fmMain.Mensaje(e.getMessage());
            }        
        
    }//GEN-LAST:event_btExcelActionPerformed

        public void abrir(String file ){
        
       try {
           String url = file;
           ProcessBuilder p = new ProcessBuilder();
           p.command("cmd.exe", "/c",url);
           p.start();
       } catch (IOException ex) {
           Logger.getLogger(pfReporteVentasFinal.class.getName()).log(Level.SEVERE, null, ex);
       }
        
    }

    
    
    
    private void CboTipoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboTipoDocActionPerformed
      if (CboTipoDoc.getSelectedIndex() >0){
      
          jLabel6.setText("IVA"); 
      
      }else{
          
          jLabel6.setText("NCC");
      }  
      //btBuscar.doClick();
    }//GEN-LAST:event_CboTipoDocActionPerformed

    private void cboAgnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAgnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboAgnoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        CargaVentas();
    }//GEN-LAST:event_jTable1MouseClicked

    public void CargaVentas() {
        ExeSql Sql = new ExeSql();
         ResultSet Rs;
         String Query="";
         String NombrePersonal;
         String Str_totNC="";
         DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
         int ContPagos=0;
         double totNC=0.0;
        BigInteger TotalAfecto    = new BigInteger("0");
        BigInteger TotalAfecto2   = new BigInteger("0");
        BigInteger TotalExento    = new BigInteger("0");
        BigInteger TotalNCC       = new BigInteger("0");
        BigInteger TotalIva       = new BigInteger("0");
        BigInteger Total          = new BigInteger("0");

        while(TableModel.getRowCount()>0)
            TableModel.removeRow(0); 
                Query = " Select c.femision,cli.rut,cli.nombre,c.tipdocto, p.apellidopaterno || ' ' || p.nombre as Vendedor,\n" +
                        " c.nrodocto," +
                        "   SUM(c.totalafecto )totalafecto,SUM(c.totalexento)totalexento,SUM(c.totaliva)totaliva,SUM(c.totaldocto) totaldocto, \n" +
                        "SUM(c.totalafecto + c.totalexento) totNC " +        
                        " from ctactecli c\n" +
                        " left join occh oc on c.rut=oc.rut and c.codigo_oc=oc.codigo_oc and c.occh=oc.orden\n" +
                        " left join cliente cli on cli.rut=c.rut\n" +
                        " left join personal p on oc.vendedor=p.vendedor\n"+  
                        " where extract(year from c.femision)= " + cboAgno.getSelectedItem().toString() + "\n" +
                        " and extract(month from c.femision)=" + cboMes.getSelectedItem().toString() + "\n";

         if(CboTipoDoc.getSelectedIndex() >0){
            Query = Query +   " and c.tipdocto in ('" + CboTipoDoc.getSelectedItem().toString() + "') \n";  
         } 
           else
         {
            Query = Query +   " and c.tipdocto in ('BOC','FAC','FEC','NCC') and  (p.apellidopaterno || ' ' || p.nombre) is not null\n";  
         }

        if(Integer.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString().trim())<1000){
            Query = Query +   " and oc.vendedor in (" +jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString().trim() + ") \n";  
        }
        if(Integer.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString().trim())==1000){
            Query = Query +   " and oc.vendedor is null \n";  
        }
        if(Integer.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString().trim())==1001){
            Query = Query +   " \n";  
        }
    
        Query = Query + " Group by c.femision,cli.rut,cli.nombre,c.tipdocto, c.nrodocto,p.apellidopaterno || ' ' || p.nombre";
 // EJECUTA CONSULTA
 
    try {
            Rs = Sql.Select(Query);
    
            while(Rs.next()){
                
                ContPagos++;
                TableModel.addRow(new Object[]{Rs.getString("femision").trim(), 
                                               Rs.getString("rut").trim(), 
                                               Rs.getString("nombre").trim(),
                                               Rs.getString("tipdocto").trim(),
                                               Rs.getDouble("nrodocto"), 
                                               fmMain.SetGuardarEntero(Rs.getString("totalafecto")),
                                               fmMain.SetGuardarEntero(Rs.getString("totalexento")),
                                               fmMain.SetGuardarEntero(Rs.getString("totaliva")),
                                               fmMain.SetGuardarEntero(Rs.getString("totaldocto"))});
              
                if (CboTipoDoc.getSelectedIndex() ==0){
                    
                        if ( "BOC".equals(Rs.getString("tipdocto"))){
                            
                            TotalAfecto2 = TotalAfecto2.add(new BigInteger(Rs.getString("totalafecto"))) ;
                        
                        }else if ( "FAC".equals(Rs.getString("tipdocto"))){
                             
                            TotalAfecto = TotalAfecto.add(new BigInteger(Rs.getString("totalafecto"))) ;
                        
                        }else if ( "NCC".equals(Rs.getString("tipdocto"))){
                            
                            TotalNCC = TotalNCC.add(new BigInteger(Rs.getString("totNC")));
                            
                        }   
                        if ( "FEC".equals(Rs.getString("tipdocto"))){
                             TotalExento = TotalExento.add(new BigInteger(Rs.getString("totalexento"))) ;
                        }
                        
                        
                }else  if (CboTipoDoc.getSelectedIndex() >0) {
                                        
                        TotalAfecto = TotalAfecto.add(new BigInteger(Rs.getString("totalafecto"))) ;
                        TotalExento = TotalExento.add(new BigInteger(Rs.getString("totalexento"))) ;
                        TotalIva    = TotalIva.add(new BigInteger(Rs.getString("totaliva"))) ;
                        Total       = Total.add(new BigInteger(Rs.getString("totaldocto"))) ;  
                }     
            }
            
            
            
            
            if (CboTipoDoc.getSelectedIndex() >0){
                        
                        lbTotalFAC.setText(fmMain.FormatoNumeroBig(TotalAfecto));
                        lbTotalFEC.setText(fmMain.FormatoNumeroBig(TotalExento));
                        lblIva.setText(fmMain.FormatoNumeroBig(TotalIva));
                        lbSumMontos.setText(fmMain.FormatoNumeroBig(Total));
            }
            else  if (CboTipoDoc.getSelectedIndex() ==0){  
                        
                        lbTotalBOC.setText(fmMain.FormatoNumeroBig(TotalAfecto2));
                        lbTotalFAC.setText(fmMain.FormatoNumeroBig(TotalAfecto));
                        lbTotalFEC.setText(fmMain.FormatoNumeroBig(TotalExento));
                        lblIva.setText(fmMain.FormatoNumeroBig(TotalNCC));
                        Total = Total.add(TotalAfecto);
                        Total = Total.add(TotalAfecto2);
                        Total = Total.add(TotalExento);
                        Total = Total.subtract(TotalNCC);
                        lbSumMontos.setText(fmMain.FormatoNumeroBig(Total));
                   
            }
            
            
            lbReg.setText(fmMain.FormatoTotal(ContPagos));
 }
        catch (Exception e) {
            fmMain.Mensaje(e.getMessage());
        }finally{
            Sql.Close();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AGNO;
    private javax.swing.JComboBox<String> CboTipoDoc;
    private javax.swing.JTable Grilla;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btExcel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cboAgno;
    private javax.swing.JComboBox<String> cboMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JLabel lbReg;
    private javax.swing.JLabel lbSumMontos;
    private javax.swing.JLabel lbTotalBOC;
    private javax.swing.JLabel lbTotalFAC;
    private javax.swing.JLabel lbTotalFEC;
    private javax.swing.JLabel lblAgno;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel registros;
    private javax.swing.JLabel totales;
    // End of variables declaration//GEN-END:variables
}
