/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Formularios.fmMain;
import Dialogos.jdBuscarCliPrv;
import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

import org.apache.poi.EncryptedDocumentException;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.ss.usermodel.*;

/**
 *
 * @author Cdiaz
 */
public class pfReporteLicitaciones extends javax.swing.JPanel {
    
    int id_proveedor;
    int inicio = 0;
    int elige = 0;
    String TablaConvenio = "";
    
    public static Color DARK_GREEN = new Color(0,153,0);
    public static Color BLACK_GRAY = new Color(102,102,102);
    public static Color DARK_ORANGE = new Color(255,102,0);
    
        
    Calendar cal = Calendar.getInstance();
    int mesant = cal.get(Calendar.MONTH)+1;         // El Mes actual
    int anant = cal.get(Calendar.YEAR);             // El Año actual
        
    private String mes = String.valueOf(mesant);       
    private String agno = String.valueOf(anant);     
    
    SimpleDateFormat formatofecha =  new SimpleDateFormat("dd-MM-yyyy HH:mm");
   
    
    /**
     * Creates new form pfCompraVenta
     */
    public pfReporteLicitaciones() {
        
        initComponents();
        
      
        
        Grilla.getActionMap().put("copy", new AbstractAction(){   //Para copiar al portapapeles
      
          @Override
          public void actionPerformed(ActionEvent e) {
              
            String cellValue = Grilla.getModel().getValueAt(Grilla.getSelectedRow(), Grilla.getSelectedColumn()).toString();
            StringSelection stringSelection = new StringSelection(cellValue);
            Toolkit.getDefaultToolkit().getSystemClipboard().setContents(stringSelection, stringSelection);
           }
        });
        
        
        CargaVendedor();
        cbCodigoVendedor.setVisible(false);  
        
        btCargar.doClick();
    }
    
    

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cbRegion = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txFiltro = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();
        lbTotal = new javax.swing.JLabel();
        btCargar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txRut = new javax.swing.JTextField();
        btIr = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbVendedor = new javax.swing.JComboBox();
        cbCodigoVendedor = new javax.swing.JComboBox<String>();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbRegion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE REGIÓN", "TARAPACÁ", "ARICA Y PARINACOTA", "ANTOFAGASTA", "ATACAMA", "COQUIMBO", "VALPARAÍSO", "METROPOLITANA", "LIBERTADOR GRAL. BERNARDO OHIGGINS", "MAULE", "ÑUBLE", "BIOBÍO", "ARAUCANÍA", "LOS RÍOS", "LOS LAGOS", "AISÉN", "MAGALLANES Y DE LA ANTÁRTICA CHILENA" }));
        cbRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRegionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("REGION");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(cbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        jLabel12.setText("FILTRO:");

        txFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txFiltroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txFiltroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txFiltroKeyTyped(evt);
            }
        });

        Grilla.setAutoCreateRowSorter(true);
        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "LICITACION", "Nombre", "Fecha Publicación", "Fecha Cierre", "Organismo", "Región", "Cantidad", "Descripción", "idvendedor", "Vendedor", "ID", "Rut"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.setDragEnabled(true);
        Grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaMouseClicked(evt);
            }
        });
        Grilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GrillaKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(0).setMinWidth(110);
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(110);
            Grilla.getColumnModel().getColumn(0).setMaxWidth(110);
            Grilla.getColumnModel().getColumn(2).setMinWidth(0);
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(2).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(3).setMinWidth(110);
            Grilla.getColumnModel().getColumn(3).setPreferredWidth(110);
            Grilla.getColumnModel().getColumn(3).setMaxWidth(110);
            Grilla.getColumnModel().getColumn(5).setMaxWidth(100);
            Grilla.getColumnModel().getColumn(6).setMinWidth(80);
            Grilla.getColumnModel().getColumn(6).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(6).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(8).setMinWidth(0);
            Grilla.getColumnModel().getColumn(8).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(8).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(9).setMinWidth(70);
            Grilla.getColumnModel().getColumn(9).setPreferredWidth(170);
            Grilla.getColumnModel().getColumn(9).setMaxWidth(170);
            Grilla.getColumnModel().getColumn(10).setMinWidth(0);
            Grilla.getColumnModel().getColumn(10).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(10).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(11).setMinWidth(0);
            Grilla.getColumnModel().getColumn(11).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(11).setMaxWidth(0);
        }

        lbTotal.setText("Total Licitaciones  :");

        btCargar.setText("Cargar");
        btCargar.setToolTipText("");
        btCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCargarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Rut");

        txRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txRutKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txRutKeyTyped(evt);
            }
        });

        btIr.setText("Ir");
        btIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIrActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre : ");

        txNombre.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txNombre.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txRut, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btIr, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btIr)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Vendedor :");

        cbVendedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Vendedor" }));
        cbVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVendedorActionPerformed(evt);
            }
        });

        cbCodigoVendedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Codigo" }));
        cbCodigoVendedor.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCodigoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbCodigoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(txFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lbTotal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void txFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txFiltroKeyPressed


    }//GEN-LAST:event_txFiltroKeyPressed

    private void txFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txFiltroKeyReleased

        String filtraRegion =EligeRegion();
        String Texto = txFiltro.getText().trim();
            
        System.out.println("El filtraRegion ES :"+filtraRegion); 
        
        DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(TableModel);  
        ArrayList<RowFilter<TableModel,Object>> lista = new ArrayList<RowFilter<TableModel,Object>>();  
        
        
        if (Texto.length()==0){
            
            lista.add(RowFilter.regexFilter(""));
            
        }else {
        
            lista.add(RowFilter.regexFilter("(?i)"+Texto));  //(?i) ignora Mayúsculas y Minúsculas
        
        
        }
        
        
        lista.add(RowFilter.regexFilter(filtraRegion.trim(),5));
        
        RowFilter filtroAnd = RowFilter.andFilter(lista); // and de ambos filtros
        sorter.setRowFilter(filtroAnd);
       
       
       
       Grilla.setRowSorter(sorter);
       
       int row = Grilla.getRowCount();
       
       Suma_filtro(row); 
       
          
          
    }//GEN-LAST:event_txFiltroKeyReleased

    
    
    private void txFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txFiltroKeyTyped
        
        if (Character.isLowerCase(evt.getKeyChar()))
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_txFiltroKeyTyped

    private void GrillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaMouseClicked

        if (evt.getClickCount() == 2) {
           
                
            try {
                    
                    int columna = Grilla.getSelectedColumn(); // obtengo la columna seleccionada
            
                    if (columna == 0){
                    
                        String licitacion = Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString().trim();
                    
                        Desktop.getDesktop().browse(new URI("http://www.mercadopublico.cl/fichaLicitacion.html?idLicitacion="+licitacion));
                            
                    }    
            
            } catch (IOException ex) {
             
                Logger.getLogger(pfReporteLicitaciones.class.getName()).log(Level.SEVERE, null, ex);
            
            } catch (URISyntaxException ex) {
            
                Logger.getLogger(pfReporteLicitaciones.class.getName()).log(Level.SEVERE, null, ex);
            }
                
                
                
        } 
            

    }//GEN-LAST:event_GrillaMouseClicked

    private void GrillaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GrillaKeyTyped
        
        
    }//GEN-LAST:event_GrillaKeyTyped

    private void cbRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRegionActionPerformed
        
        String filtraRegion =EligeRegion();
        String Texto = txFiltro.getText().trim();
        
        
        
            
        System.out.println("El filtraRegion ES :"+filtraRegion); 
        
        
        
        DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(TableModel);  
        ArrayList<RowFilter<TableModel,Object>> lista = new ArrayList<RowFilter<TableModel,Object>>();  
        
       
       
        if (Texto.trim().length() > 0){
       
            lista.add(RowFilter.regexFilter(filtraRegion.trim(),5));
            lista.add(RowFilter.regexFilter("(?i)"+Texto)); //(?i) ignora Mayúsculas y Minúsculas
            RowFilter filtroAnd = RowFilter.andFilter(lista); // and de ambos filtros
                                                        
            sorter.setRowFilter(filtroAnd);
        
        
        }else{
        
            sorter.setRowFilter(RowFilter.regexFilter(filtraRegion.trim(),5));
        
        }
        
       
       
       
       
       Grilla.setRowSorter(sorter);
       
       int row = Grilla.getRowCount();
       
       Suma_filtro(row); 
        
    }//GEN-LAST:event_cbRegionActionPerformed

    
    
    
    private String EligeRegion(){
         
         String filtraRegion ="";         
         
        
        if (cbRegion.getSelectedIndex() == 1){
                  
                filtraRegion = "^I Región$";   //Filtra la cadena exacta
            
        
        }else if (cbRegion.getSelectedIndex() == 2){
        
                        
                filtraRegion = "^XV Región$";
            
            
        }else if (cbRegion.getSelectedIndex() == 3){
        
           
                        
                filtraRegion = "^II Región$";
            
            
        
        }else if (cbRegion.getSelectedIndex() == 4){
        
           
                        
                filtraRegion = "^III Región$";
            
            
        
        }else if (cbRegion.getSelectedIndex() == 5){
        
           
            
                filtraRegion = "^IV Región$";
            
           
        
        
        }else if (cbRegion.getSelectedIndex() == 6){
        
           
                        
                filtraRegion = "^V Región$";
            
            
        
        }else if (cbRegion.getSelectedIndex() == 7){
        
           
            
                filtraRegion = "^Región MP$";
                        
            
        
        }else if (cbRegion.getSelectedIndex() == 8){
        
            
                        
                filtraRegion = "^VI Región$";
            
            
        
        
        }else if (cbRegion.getSelectedIndex() == 9){
        
            
                       
                filtraRegion = "^VII Región$";
            
           
        
        }else if (cbRegion.getSelectedIndex() == 10){
        
            
                        
                filtraRegion = "^XVI Región$";
            
            
        
        
        }else if (cbRegion.getSelectedIndex() == 11){
        
           
            
                filtraRegion = "^VIII Región$";
            
            
        
            
        }else if (cbRegion.getSelectedIndex() == 12){
        
            
            
                filtraRegion = "^IX Región$";
            
            
            
            
        }else if (cbRegion.getSelectedIndex() == 13){
        
           
                        
                filtraRegion = "^XIV Región$";
            
            
        
        }else if (cbRegion.getSelectedIndex() == 14){
        
           
                        
                filtraRegion = "^X Región$";
            
           
            
        
        }else if (cbRegion.getSelectedIndex() == 15){
        
           
            
                filtraRegion = "^XI Región$";
            
           
        
        }else if (cbRegion.getSelectedIndex() == 16){
            
                filtraRegion = "^XII Región$";
            
        
        }
         
        return filtraRegion;
     
     
     }
    
    
    
    
    
    
    
    
    
    
    
    private void btCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCargarActionPerformed
        
       LEER("Licitaciones.xls");
      
        
    }//GEN-LAST:event_btCargarActionPerformed

    private void txRutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txRutKeyPressed

       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btIr.doClick();
        }
    }//GEN-LAST:event_txRutKeyPressed

    private void txRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txRutKeyTyped

        if(txRut.getText().length()>7) {
            evt.consume();
        }
        if(evt.getKeyChar() < '0' || evt.getKeyChar() > '9' ){
            evt.consume();
        }

    }//GEN-LAST:event_txRutKeyTyped

    private void btIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIrActionPerformed

        if(!txRut.getText().isEmpty()){
        
            busca_nombre(txRut.getText().trim());
            filtro_rut(txRut.getText().trim());
        
        }else{
           
            jdBuscarCliPrv BPC = new jdBuscarCliPrv(null, true);
            BPC.setLocationRelativeTo(null);
            BPC.setTitle("Buscar Cliente");
            BPC.SetTipo(1);
            BPC.setVisible(true);
            
            txRut.setText(BPC.GetRut());
            txNombre.setText(BPC.GetNom());
             
            filtro_rut(txRut.getText().trim());
            
            
        }
    }//GEN-LAST:event_btIrActionPerformed

    private void cbVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVendedorActionPerformed
        
        cbCodigoVendedor.setSelectedIndex(cbVendedor.getSelectedIndex());
        
        
        DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(TableModel);  
        
        
        if (cbVendedor.getSelectedIndex() > 0){
      
            sorter.setRowFilter(RowFilter.regexFilter("^"+cbCodigoVendedor.getSelectedItem().toString().trim()+"$",8));
            Grilla.setRowSorter(sorter);
       
       
        }else {
        
            sorter.setRowFilter(null);
            Grilla.setRowSorter(sorter);
        }
       
       int row = Grilla.getRowCount();
       
       Suma_filtro(row); 
        
        
        
        
    }//GEN-LAST:event_cbVendedorActionPerformed
    
    
    
    private void busca_nombre(String Rut){
    
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        
        
       
    
        try {
            
            String Query =  "select nombre\n" +
                        "from cliente p\n" +
                        "where rut =" + Rut.trim();
            Rs = Sql.Select(Query);
            
            if (Sql.GetRowCount() > 0){
            
                Rs.next();
                
                txNombre.setText(Rs.getString("nombre").toString().trim());
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(pfReporteLicitaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    
    
    }
    
    
    
    
    
    
    
    
    
    
    private void filtro_rut(String Rut){
    
    
        String filtraRut = "^"+Rut+"$";   //Filtra la cadena exacta
        
        
        DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(TableModel);  
        
       sorter.setRowFilter(RowFilter.regexFilter(filtraRut.trim(),11));
       Grilla.setRowSorter(sorter);
       
       
       int row = Grilla.getRowCount();
       
       Suma_filtro(row); 
    
    
    
    }
    
    
    
    private void LEER (String Licitacion) {
        
        txRut.setText("");
        txNombre.setText("");
        txFiltro.setText("");
        
        cbRegion.setSelectedIndex(0);
        
        int cont = 0;
        
        DefaultTableModel model = (DefaultTableModel) Grilla.getModel(); 

        while(model.getRowCount()>0)
        model.removeRow(0);
        
        try {
            
           // File f = new File("C://LICITACIONES/Licitaciones.xls");    
            
           File f = new File("//192.168.0.170/LICITACIONES/"+Licitacion);
           
            
            InputStream inp = new FileInputStream(f);
            Workbook wb = WorkbookFactory.create(inp);
            Sheet sheet = wb.getSheetAt(0);
            
            int iRow = 1;
            
            Row row = sheet.getRow(iRow); //En qué fila empezar ya dependerá también de si tenemos, por ejemplo, el título de cada columna en la primera fila
           
            while(row!=null) 
            
            {     
          
                Cell cell0 = row.getCell(0);  
                Cell cell1 = row.getCell(1);  
                Cell cell2 = row.getCell(2);  
                Cell cell3 = row.getCell(3);  
                Cell cell4 = row.getCell(4);  
                Cell cell5 = row.getCell(5);  
                Cell cell6 = row.getCell(6);  
                Cell cell7 = row.getCell(7);  
                Cell cell8 = row.getCell(8);  
                Cell cell9 = row.getCell(9);  
                Cell cell10 = row.getCell(10);  
                Cell cell11 = row.getCell(11);  
                
                String valor0 = cell0.getStringCellValue();
                String valor1 = cell1.getStringCellValue();
                String valor2 = cell2.getStringCellValue();
                String valor3 = cell3.getStringCellValue();
                String valor4 = cell4.getStringCellValue();
                String valor5 = cell5.getStringCellValue();
                String valor6 = cell6.getStringCellValue();
                String valor7 = cell7.getStringCellValue();
                String valor8 = cell8.getStringCellValue();
                String valor9 = cell9.getStringCellValue();
                String valor10 = cell10.getStringCellValue();
                String valor11 = cell11.getStringCellValue();
                
                
                model.addRow(new Object[]{valor0,valor1,valor2,valor3,valor4,valor5,valor6,valor7,valor8,valor9,valor10,valor11});
           
                iRow++;  
                row = sheet.getRow(iRow);
                cont++;
            }
            
            
           
            
            
            
            
        DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(TableModel);  
        
        sorter.setRowFilter(RowFilter.regexFilter(""));
        Grilla.setRowSorter(sorter);
         
        
        Grilla.setDefaultRenderer(Object.class, new Elrender()); 
             
        System.out.println("El Total Filas es :"+cont);
        lbTotal.setText("Total Licitaciones  : "+cont); 
            
            
            
            
        
        
        } catch (IOException ex) {
            Logger.getLogger(pfReporteLicitaciones.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidFormatException ex) {
            Logger.getLogger(pfReporteLicitaciones.class.getName()).log(Level.SEVERE, null, ex);
        } catch (EncryptedDocumentException ex) {
            Logger.getLogger(pfReporteLicitaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }
    
    
    private void Suma_filtro(int fila){
    
        
        int cont = 0;
       
        
        for (int i = 0; i < fila; i++) {
        
            cont++;
        
        
        }
        
        
       lbTotal.setText("Total Licitaciones  : "+cont); 
       
        
    
    
    }
    
    
    
     public void CargaVendedor() {
        ExeSql Sql= new ExeSql();
        ResultSet Rs;
           
        try{
            cbVendedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
            cbCodigoVendedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
            
            cbCodigoVendedor.addItem("Codigo");
            cbVendedor.addItem("Seleccione Vendedor");
           
            Rs = Sql.Select("SELECT nombre,\n"+
                            "case when apellidopaterno is null then ' ' else apellidopaterno end as apellido, \n"+
                            "case when apellidomaterno is null then ' ' else apellidomaterno end as apellido2, \n"+
                            "vendedor\n" +
                            "FROM personal\n" +
                            "WHERE tipo_vendedor IN (0,1) and activo = true and vendedor is not null ORDER BY vendedor asc ");
               
            while( Rs.next()){
                
                String[] Nombre = Rs.getString("nombre").split(" ");
                            
                String Vendedor = Nombre[0]+" "+Rs.getString("apellido")+" "+Rs.getString("apellido2");
                
                cbVendedor.addItem(Vendedor);
                cbCodigoVendedor.addItem(String.valueOf(Rs.getInt("vendedor")));  
            }
            
        }catch (Exception e){
                System.out.println(e.getMessage());
                fmMain.Mensaje("Error: "  + e);
        }finally{
                Sql.Close();
        }

    }
    
    
    
    
    
    
    class Elrender extends DefaultTableCellRenderer {
         
        @Override
        public Component getTableCellRendererComponent(JTable tabla, Object valor, boolean isSelected, boolean hasFocus, int fila, int columna) {
            
            super.getTableCellRendererComponent(tabla,valor,isSelected, hasFocus, fila, columna);
            
            
            if( tabla.getValueAt(fila,11).toString().trim().equals("0") ){
            
            
                 if(isSelected==true){
                
                    this.setForeground(Color.white);
                    this.setBackground(Color.red);    
                    this.setFont(new Font("Tahoma", Font.BOLD, 11));
                 
                 }else{
                  
                    this.setForeground(Color.red); 
                    this.setBackground(Color.white);   
                    
                    this.setFont(new Font("Tahoma", Font.BOLD, 11));
                 }
            
            }else { //no habilitados
                
                
                 if(isSelected==true){
                    
                    this.setForeground(Color.white);
                    this.setBackground(Color.blue);   
                     this.setFont(new Font("Tahoma", Font.BOLD, 11));
                    
                
                }else {
                
                    this.setForeground(Color.black);    
                    this.setBackground(Color.white);   
                   
                }
            
            }            
            
              
            
            return this;
        }
    } 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla;
    private javax.swing.JButton btCargar;
    public static javax.swing.JButton btIr;
    private javax.swing.JComboBox<String> cbCodigoVendedor;
    private javax.swing.JComboBox cbRegion;
    private javax.swing.JComboBox cbVendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTextField txFiltro;
    private javax.swing.JTextField txNombre;
    public static javax.swing.JTextField txRut;
    // End of variables declaration//GEN-END:variables
}
