/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Dialogos.jdBuscarCliPrv;
import Dialogos.jdOC_PendientesFac;
import static Dialogos.jdOC_PendientesFac.pano;
import static Dialogos.jdOC_PendientesFac.pmes;
import static Dialogos.jdOC_PendientesFac.pmes_oc;
import Dialogos.jdPagadoPrvCli;
import Dialogos.jdPagarPrv;
import Dialogos.jdProductosControl;
import Dialogos.jdRelacionadosReporte;
import Formularios.fmMain;
import static Formularios.fmMain.pnPestanas;
import Utilidades.Exporter;
import Utilidades.PanelTab;
import java.awt.event.KeyEvent;
import java.io.File;
import java.math.BigInteger;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.DefaultComboBoxModel;
import Utilidades.ComboCodigos;
import static Utilidades.DocElect.carpeta;
import Utilidades.TableCellRendererConvenio;
import java.awt.Color;
import static java.awt.SystemColor.text;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import static java.lang.Double.isNaN;
import java.net.URL;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.function.Function;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Popup;
import javax.swing.PopupFactory;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import static jdk.nashorn.internal.objects.NativeMath.round;
import org.apache.commons.math3.util.Precision;
import java.util.stream.*;
import java.awt.Toolkit;
    
/**
 *
 * @author David Alcaman
 */
public class pfReporteProveedorConvenio_2 extends javax.swing.JPanel {
    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
//    DecimalFormat formateador = new DecimalFormat("###,###.##");
    /**
     * Creates new form pfReportePagosPrv
     */
    public JPanel panel = new JPanel();
    Popup popup;   
    int id_proveedor, id_convenio;
    int verde, amarillo, blanco = 0;
    
    boolean Filtrado = false;
    public pfReporteProveedorConvenio_2() {

        //sku 030205002
                
        initComponents(); 
        dtDesde.setEnabled(false);
        dtHasta.setEnabled(false);
        SimpleDateFormat formater = new SimpleDateFormat("dd/MM/yyyy");
        dtDesde.setFormats(formater);
        CargaProveedor();
        CargaConvenio();
        jLabel11.setEnabled(false);
        margentotalventa.setEnabled(false);
        
        // Alinea a la derecha la grilla
//        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
//        Grilla.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
//         Grilla.getColumnModel().getColumn(11).setCellRenderer(rightRenderer);
//        Grilla.getColumnModel().getColumn(12).setCellRenderer(rightRenderer);
//        Grilla.getColumnModel().getColumn(13).setCellRenderer(rightRenderer);
//        Grilla.getColumnModel().getColumn(14).setCellRenderer(rightRenderer);
        
        
        
//         Calendar fecha = new GregorianCalendar();
//        //Obtenemos el valor del año, mes, día,
//        //hora, minuto y segundo del sistema
//        //usando el método get y el parámetro correspondiente
//        int año = fecha.get(Calendar.YEAR);
//        int mes = fecha.get(Calendar.MONTH);
//       /* int dia = fecha.get(Calendar.DAY_OF_MONTH);
//        int hora = fecha.get(Calendar.HOUR_OF_DAY);
//        int minuto = fecha.get(Calendar.MINUTE);
//        int segundo = fecha.get(Calendar.SECOND);*/
//        
//        String anox ="x";
//        String mesx ="x";
//        
//        anox = String.valueOf(año);
//        mesx = String.valueOf(mes+1);


        btExcel.setVisible(true);
        txRutProveedor.setVisible(false);
        CboProveedor.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        VerProducto = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        rbEspecificas = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        cbAno = new javax.swing.JComboBox<String>();
        jLabel10 = new javax.swing.JLabel();
        cbMes = new javax.swing.JComboBox<String>();
        rbFechaDesde = new javax.swing.JRadioButton();
        dtDesde = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();
        dtHasta = new org.jdesktop.swingx.JXDatePicker();
        rbFechaTodas = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMargen = new javax.swing.JLabel();
        margentotalventa = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        lblVendedor = new javax.swing.JLabel();
        CboConvenio = new javax.swing.JComboBox<String>();
        lblVendedor1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        lbcargando = new javax.swing.JLabel();
        btBuscar = new javax.swing.JButton();
        txProveedor = new javax.swing.JTextField();
        btIr = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btExcel = new javax.swing.JButton();
        chk_sinstock = new javax.swing.JCheckBox();
        chk_discon = new javax.swing.JCheckBox();
        chk_Oferta = new javax.swing.JCheckBox();
        chk_Publicado = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        lblReg = new javax.swing.JLabel();
        chkWeb = new javax.swing.JCheckBox();
        chkNoTransado = new javax.swing.JCheckBox();
        chkDesxPrecio = new javax.swing.JCheckBox();
        chkdeshabilitado = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jlbBlanco = new javax.swing.JLabel();
        jlbVerde = new javax.swing.JLabel();
        jlbAmarillo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txSku = new javax.swing.JTextField();
        txRutProveedor = new javax.swing.JTextField();
        CboProveedor = new javax.swing.JComboBox<String>();

        VerProducto.setText("Ver Producto");
        VerProducto.setToolTipText("");
        VerProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerProductoActionPerformed(evt);
            }
        });
        jPopupMenu1.add(VerProducto);

        jMenuItem1.setText("Copiar IDCH");
        jMenuItem1.setToolTipText("Copiar IDCH");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PROVEEDOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Márgenes Ventas"));

        buttonGroup4.add(rbEspecificas);
        rbEspecificas.setText("Específico");
        rbEspecificas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEspecificasActionPerformed(evt);
            }
        });

        jLabel8.setText("Año:");

        cbAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));

        jLabel10.setText("Mes:");

        cbMes.setMaximumRowCount(12);
        cbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        cbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesActionPerformed(evt);
            }
        });

        buttonGroup4.add(rbFechaDesde);
        rbFechaDesde.setText("Desde");
        rbFechaDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFechaDesdeActionPerformed(evt);
            }
        });

        dtDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtDesdeActionPerformed(evt);
            }
        });

        jLabel7.setText("Hasta");

        buttonGroup4.add(rbFechaTodas);
        rbFechaTodas.setSelected(true);
        rbFechaTodas.setText("Todas");
        rbFechaTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFechaTodasActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Margen Teórico: ");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Margen Real Venta:");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });

        txtMargen.setText("0");

        margentotalventa.setText("0");

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(39, 39, 39)
                        .addComponent(txtMargen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(23, 23, 23)
                        .addComponent(margentotalventa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbFechaTodas)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(rbEspecificas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbAno, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(rbFechaDesde)
                                .addGap(18, 18, 18)
                                .addComponent(dtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEspecificas)
                    .addComponent(jLabel8)
                    .addComponent(cbAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFechaDesde)
                    .addComponent(dtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(dtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(rbFechaTodas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMargen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(margentotalventa)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Proveedor"));

        lblVendedor.setText("Proveedor");

        CboConvenio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Todos>" }));
        CboConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboConvenioActionPerformed(evt);
            }
        });

        lblVendedor1.setText("Convenio");

        jLabel2.setText("Filtro Posición:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "20", "30", "Todos", "No nulos" }));
        jComboBox1.setSelectedIndex(14);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        lbcargando.setText("Cargando");
        lbcargando.setEnabled(false);

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        txProveedor.setToolTipText("");
        txProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txProveedorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txProveedorKeyReleased(evt);
            }
        });

        btIr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/search.png"))); // NOI18N
        btIr.setBorderPainted(false);
        btIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CboConvenio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVendedor1)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbcargando, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(lblVendedor)
                                .addGap(240, 240, 240))
                            .addComponent(txProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(btIr, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(btIr, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVendedor1))
                    .addComponent(txProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CboConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbcargando)
                    .addComponent(btBuscar)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btExcel.setText("Excel");
        btExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcelActionPerformed(evt);
            }
        });

        chk_sinstock.setText("Sin Stock");

        chk_discon.setText("Discontinuado");

        chk_Oferta.setText("Oferta");

        chk_Publicado.setText("Publicado");
        chk_Publicado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_PublicadoActionPerformed(evt);
            }
        });

        jLabel1.setText("Registros");

        lblReg.setText("0");

        chkWeb.setText("Web");
        chkWeb.setToolTipText("");

        chkNoTransado.setText("No Transado");

        chkDesxPrecio.setText("Des. x Precio");

        chkdeshabilitado.setText("Sin publicar");

        Grilla.setAutoCreateRowSorter(true);
        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Proveedor", "Sku", "IDCH", "Nombre", "S/Stock", "Stock", "Disc.", "Oferta", "Publicado", "Web", "Inicio", "Fin", "Pos", "$ Compra", "$ Primero", "Margen", "Sin publicar", "Total", "Promedio Venta", "Prv.Asociado", "Ctotal", "Primero", "Margen Venta Producto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        Grilla.setComponentPopupMenu(jPopupMenu1);
        Grilla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Grilla.getTableHeader().setReorderingAllowed(false);
        Grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GrillaMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(0).setMinWidth(200);
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(200);
            Grilla.getColumnModel().getColumn(0).setMaxWidth(350);
            Grilla.getColumnModel().getColumn(1).setMinWidth(75);
            Grilla.getColumnModel().getColumn(1).setPreferredWidth(75);
            Grilla.getColumnModel().getColumn(1).setMaxWidth(100);
            Grilla.getColumnModel().getColumn(2).setMinWidth(70);
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(70);
            Grilla.getColumnModel().getColumn(2).setMaxWidth(95);
            Grilla.getColumnModel().getColumn(3).setMinWidth(80);
            Grilla.getColumnModel().getColumn(3).setPreferredWidth(100);
            Grilla.getColumnModel().getColumn(3).setMaxWidth(400);
            Grilla.getColumnModel().getColumn(4).setMinWidth(50);
            Grilla.getColumnModel().getColumn(4).setPreferredWidth(50);
            Grilla.getColumnModel().getColumn(4).setMaxWidth(50);
            Grilla.getColumnModel().getColumn(5).setMinWidth(50);
            Grilla.getColumnModel().getColumn(5).setPreferredWidth(50);
            Grilla.getColumnModel().getColumn(5).setMaxWidth(50);
            Grilla.getColumnModel().getColumn(6).setMinWidth(35);
            Grilla.getColumnModel().getColumn(6).setPreferredWidth(35);
            Grilla.getColumnModel().getColumn(6).setMaxWidth(50);
            Grilla.getColumnModel().getColumn(7).setMinWidth(35);
            Grilla.getColumnModel().getColumn(7).setPreferredWidth(35);
            Grilla.getColumnModel().getColumn(7).setMaxWidth(50);
            Grilla.getColumnModel().getColumn(8).setMinWidth(35);
            Grilla.getColumnModel().getColumn(8).setPreferredWidth(35);
            Grilla.getColumnModel().getColumn(8).setMaxWidth(50);
            Grilla.getColumnModel().getColumn(9).setMinWidth(35);
            Grilla.getColumnModel().getColumn(9).setPreferredWidth(35);
            Grilla.getColumnModel().getColumn(9).setMaxWidth(50);
            Grilla.getColumnModel().getColumn(10).setMinWidth(90);
            Grilla.getColumnModel().getColumn(10).setPreferredWidth(90);
            Grilla.getColumnModel().getColumn(10).setMaxWidth(120);
            Grilla.getColumnModel().getColumn(11).setMinWidth(90);
            Grilla.getColumnModel().getColumn(11).setPreferredWidth(90);
            Grilla.getColumnModel().getColumn(11).setMaxWidth(120);
            Grilla.getColumnModel().getColumn(12).setMinWidth(30);
            Grilla.getColumnModel().getColumn(12).setPreferredWidth(30);
            Grilla.getColumnModel().getColumn(12).setMaxWidth(50);
            Grilla.getColumnModel().getColumn(13).setMinWidth(80);
            Grilla.getColumnModel().getColumn(13).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(13).setMaxWidth(120);
            Grilla.getColumnModel().getColumn(14).setMinWidth(80);
            Grilla.getColumnModel().getColumn(14).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(14).setMaxWidth(120);
            Grilla.getColumnModel().getColumn(15).setMinWidth(50);
            Grilla.getColumnModel().getColumn(15).setPreferredWidth(50);
            Grilla.getColumnModel().getColumn(15).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(16).setMinWidth(0);
            Grilla.getColumnModel().getColumn(16).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(16).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(19).setMinWidth(50);
            Grilla.getColumnModel().getColumn(19).setPreferredWidth(200);
            Grilla.getColumnModel().getColumn(19).setMaxWidth(500);
            Grilla.getColumnModel().getColumn(20).setMinWidth(0);
            Grilla.getColumnModel().getColumn(20).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(20).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(21).setMinWidth(0);
            Grilla.getColumnModel().getColumn(21).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(21).setMaxWidth(0);
        }

        jComboBox2.setMaximumRowCount(10);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0" }));

        jLabel12.setText("Posiciones:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(chk_sinstock)
                        .addGap(31, 31, 31)
                        .addComponent(chk_discon)
                        .addGap(18, 18, 18)
                        .addComponent(chk_Oferta)
                        .addGap(18, 18, 18)
                        .addComponent(chk_Publicado)
                        .addGap(18, 18, 18)
                        .addComponent(chkWeb)
                        .addGap(10, 10, 10)
                        .addComponent(chkNoTransado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkDesxPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkdeshabilitado)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblReg, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)
                        .addGap(19, 19, 19)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_sinstock)
                    .addComponent(chk_discon)
                    .addComponent(chk_Oferta)
                    .addComponent(chk_Publicado)
                    .addComponent(chkWeb)
                    .addComponent(chkNoTransado)
                    .addComponent(chkDesxPrecio)
                    .addComponent(chkdeshabilitado)
                    .addComponent(jLabel1)
                    .addComponent(lblReg)
                    .addComponent(btExcel)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "MARGEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 204, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(24, 16));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setPreferredSize(new java.awt.Dimension(24, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Margen mayor e igual al % 25");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Margen mayor e igual a % 15 y menor al % 25");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setPreferredSize(new java.awt.Dimension(24, 16));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Margen menor al % 15");

        jlbBlanco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbBlanco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbBlanco.setText("0");
        jlbBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlbVerde.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbVerde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbVerde.setText("0");
        jlbVerde.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlbAmarillo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbAmarillo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbAmarillo.setText("0");
        jlbAmarillo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("FILTRO:");

        txSku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txSkuKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txSkuKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txSkuKeyTyped(evt);
            }
        });

        txRutProveedor.setToolTipText("");

        CboProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Todos>" }));
        CboProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(38, 38, 38)
                                .addComponent(jlbAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(44, 44, 44)
                                .addComponent(jlbVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(40, 40, 40)
                                .addComponent(jlbBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txSku, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txRutProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CboProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txSku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txRutProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CboProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void CargaProveedor(){
        DefaultComboBoxModel value;
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        String Query="";
        CboProveedor.removeAllItems();
//        CboProveedor.addItem("<Todos>");  
//        CboProveedor.setSelectedIndex(0);
        value =new DefaultComboBoxModel();
       
        
        
        try {
            Query="select rut,nombre from proveedor\n" +
                    "order by nombre";
            Rs = Sql.Select(Query);
            if(Sql.GetRowCount()==0) return;
           value.addElement(new ComboCodigos("Seleccione",0));     
           while(Rs.next()){
            value.addElement(new ComboCodigos(Rs.getString("nombre").trim(),Rs.getInt("rut")));
           } 
           CboProveedor.setModel(value);
           CboProveedor.setSelectedIndex(0);

           
           
        } catch (Exception e) {
            System.out.println(e);
        }
        finally{
            Sql.Close();
        }
    }
    
    
   private void CargaConvenio(){
        DefaultComboBoxModel value;
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        String Query="";
        value =new DefaultComboBoxModel();
      
        
        
        try {
            Query="select codigo,convenio from par_convenio \n" +
                "order by codigo  ";
            Rs = Sql.Select(Query);
            if(Sql.GetRowCount()==0) return;
             value.addElement(new ComboCodigos("Seleccione",0));
             
           while(Rs.next()){
            value.addElement(new ComboCodigos(Rs.getString("convenio").trim(),Rs.getInt("codigo")));
           } 
           value.addElement(new ComboCodigos("TODOS",20));
           CboConvenio.setModel(value);
           CboConvenio.setSelectedIndex(0);

        } catch (Exception e) {
            System.out.println(e);
        }
        finally{
            Sql.Close();
        }
    }
    
    
    public void CargaMargenTabla() {
        double sum_valor = 0;
        double sum_costo = 0;
        ExeSql sql = new ExeSql();
        
        String query = "";
        double suma_costo_margen = 0;
        double suma_valor_margen = 0;
        for(int i = 0;i< Grilla.getRowCount(); i++){
                
                ResultSet rs = null;        
                if(!Grilla.getValueAt(i, 21).toString().trim().equals("0.0")) {
                    sum_valor = sum_valor + Double.valueOf(Grilla.getValueAt(i, 21).toString().trim());
                    sum_costo = sum_costo + Double.valueOf(Grilla.getValueAt(i, 20).toString().trim());
                    
                }
                String sku = Grilla.getValueAt(i, 1).toString().trim();
                query = "select det.sku, (det.cantidad*det.valorunitario) valor,p.rut_proveedor_asociado, (det.cantidad*(select case \n" +
                        "when p.valor_proveedor is null then p.valultcompra\n" +
                        "when p.valor_proveedor = 0 then p.valultcompra\n" +
                        "else p.valor_proveedor\n" +
                        "end as valor)) costo\n" +
                        "from ctacteclidet det\n" +
                        "left join ctactecli cli on cli.nrodocto = det.nrodocto and cli.tipdocto = det.tipdocto and cli.rut = det.rut\n" +
                        "left join producto p on p.sku = det.sku\n" +
                        "left join codchile cod on cod.sku = p.sku\n " +
                        "where det.tipdocto = 'FAC'\n" +
                        "and det.sku = '"+sku+"'\n";
                
//               if(!txProveedor.getText().isEmpty() || !txProveedor.getText().equals("")){
//                       
//                    query = query + "and p.rut_proveedor_asociado = '"+txRutProveedor.getText().trim()+"'\n";
//                }
                
                if(rbFechaDesde.isSelected()){
                    Calendar cals = Calendar.getInstance();
                    SimpleDateFormat formater = new SimpleDateFormat("dd/MM/yyyy");

                    String desde = formater.format(dtDesde.getDate());
                    String hasta = formater.format(dtHasta.getDate());
                    query = query +  "and cli.femision between to_date('"+desde+"', 'DD/MM/YYYY') and to_date('"+hasta+"', 'DD/MM/YYYY')\n";
                }
                if(rbEspecificas.isSelected()){
                    query = query + "and EXTRACT(YEAR FROM cli.femision) = '"+cbAno.getSelectedItem().toString().trim()+"' and EXTRACT(MONTH FROM cli.femision) = '"+(cbMes.getSelectedIndex()+1)+"' \n";
                }
                if(rbFechaTodas.isSelected()){

                }
                if(chk_Publicado.isSelected()){
                    query = query + "and cod.publicado is true\n";
                }
                else {

                }
                try {
                    rs = sql.Select(query);
                    for(int o = 0; rs.next(); o++){

                        suma_costo_margen = suma_costo_margen + rs.getDouble("costo");
                        suma_valor_margen = suma_valor_margen + rs.getDouble("valor");
                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(pfReporteProveedorConvenio_2.class.getName()).log(Level.SEVERE, null, ex);
                }
                finally {
                    
                }
                
        }
        sql.Close();
        double margen_fechas = ((suma_valor_margen - suma_costo_margen)/ suma_valor_margen)*100;
        double margen = ((sum_valor - sum_costo)/ sum_valor)*100;
        System.out.println(sum_valor);
        System.out.println(sum_costo);
        System.out.println("Margen: "+Math.round(margen));
        txtMargen.setText(Math.round(margen)+" %");
        margentotalventa.setText(Math.round(margen_fechas)+" %");
        System.out.println(suma_valor_margen);
        System.out.println(suma_costo_margen);
        System.out.println(Math.round(margen_fechas)+" %");
    }
    
    public void CargarTable() {
        ExeSql sql2 = new ExeSql();
        ExeSql sql3 = new ExeSql();
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        String Query="";
        String NombrePersonal;
        String nproveedor = "";
        String chilecodigo = "";
        String toferta = "";
        
        DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
        Boolean QryOK = false;
        int ContReg=0;
        double costo = 0;
        double margen = 0;
        double ctotal = 0;
        
        while(TableModel.getRowCount()>0)
            TableModel.removeRow(0);        
        
        try{

            Query= 
            "select\n" +
            "cc.cant_unidad as cunidad, \n" +        
            "p.convenio, \n" +
            "p.sku, \n" +
            "p.proveedor_asociado,\n" +             
            "inv.stock,  \n" +
            "cc.idch  as chilecodigo,\n" +
            "cc.oferta_inicio, \n" +
            "cc.oferta_fin,\n" +
            "p.nombre,\n" +
            "p.rutultprv,\n" +
            "pr.nombre nombre_proveedor,\n" + 
            "CASE WHEN cc.sinstock is true then 'SI'\n" +
            "ELSE 'NO'\n" +
            "END sinstock,\n" +
            "CASE WHEN cc.discontinuado is true then 'SI'\n" +
            "ELSE 'NO'\n" +
            "END discontinuado,\n" +
            "CASE WHEN cc.oferta is true then 'SI'\n" +
            "ELSE 'NO'\n" +
            "END oferta,\n" +
            "CASE WHEN cc.publicado is true then 'SI'\n" +
            "ELSE 'NO'\n" +
            "END publicado, \n" +
//            "CASE \n" +
//            "WHEN cc.sincompetencia is true then 'SI'\n" +
//            "ELSE 'NO'\n" +
//            "END sin_competencia , "+
            "CASE \n" +
            "WHEN cw.publicado is true then 'SI'\n" +
            "ELSE 'NO'\n" +
            "END AS web, "+       
            "\n" +
            "CASE \n" +
            "WHEN pp.posicion IS NULL \n" +
            "THEN '0'\n" +
            "ELSE pp.posicion\n" +
            "END as posicion,\n" +
            "\n" +
            "cc.sincompetencia,\n" +
            "pp.precio_primero,\n" +
            "CASE \n" +
            "WHEN pp.precio_primero IS NULL THEN 0\n" +
            "WHEN  pp.precio_primero=0  THEN 0\n" +
            "else  \n" +
            "((pp.precio_primero - p.costofinal)/pp.precio_primero)*100\n" +
            "END margen,\n" +
            "\n" +
            "p.costofinal,\n" +
            "cc.sin_publicar,\n" +
            "p.valor_proveedor,inv.stock,inv.ocp,inv.occ,inv.gdc, (select case when promedio is null then 0 when promedio = 0 then 0 else promedio end as promedio from promedio_venta where sku = p.sku) promedio \n" +
            "\n" +
            "from codproducto_rel cr \n" +
            "right join producto p on p.sku = cr.sku\n" +
            "left join codchile cc on p.sku = cc.sku or cc.sku = cr.sku_rel\n" +
            "left join producto_posicion pp on pp.id = cc.idch\n" +
            "left join par_convenio pc on p.convenio = pc.codigo\n" +
            "left join proveedor pr on pr.rut = p.rutultprv\n" +
            "left join inventario inv on p.sku = inv.sku\n" +
            "left join codweb cw on p.sku = cw.sku\n" +        
            "where p.es_cotiza = 0\n";
            
               
            if((!txProveedor.getText().isEmpty() || !txProveedor.getText().equals("")) &&
                 CboConvenio.getSelectedIndex() >0  && !CboConvenio.getSelectedItem().toString().equals("TODOS")){
                   
                Query = Query +   " and p.proveedor_asociado LIKE '%" + txProveedor.getText().trim() + "%' \n";  
                Query = Query +   " and p.convenio  = " + id_convenio + " \n";  
                QryOK = true;
            
            }else if(CboConvenio.getSelectedIndex() >0 && txProveedor.getText().isEmpty() &&
                        !CboConvenio.getSelectedItem().toString().equals("TODOS")) {
                
                        Query = Query +   " and p.convenio  = " + id_convenio + " \n";  
                        Query = Query +   " and (p.rutultprv  IS NULL or p.rutultprv >0) ";  
                        QryOK = true;
            
            }else if((!txProveedor.getText().isEmpty() || !txProveedor.getText().equals("")) &&
                       CboConvenio.getSelectedIndex() == 0   && !CboConvenio.getSelectedItem().toString().equals("TODOS")){
                          
                Query = Query +   " and p.proveedor_asociado LIKE '%" + txProveedor.getText().trim() + "%' \n";  
                QryOK = true;
            
            }else if (CboConvenio.getSelectedItem().toString().equals("TODOS")){
                Query = Query + "and p.convenio > 1\n";
                QryOK = true;
            }
 
            if (chk_sinstock.isSelected() && QryOK ) {
                Query = Query +   " and cc.sinstock  IS TRUE  and (p.rutultprv  IS NULL or p.rutultprv >0)  \n";  
                QryOK = true;
            }else if (chk_sinstock.isSelected() && QryOK.equals(false) ) {
                Query = Query +   " and cc.sinstock  IS TRUE and (p.rutultprv  IS NULL or p.rutultprv >0) \n";  
                QryOK = true;
            }     
 
            if (chk_discon.isSelected() && QryOK) {
                Query = Query +   " and cc.discontinuado  IS TRUE \n";  
                QryOK = true;
            }else if (chk_discon.isSelected() && QryOK.equals(false)) {
                Query = Query +   " and cc.discontinuado  IS TRUE \n";  
                QryOK = true;
            }
 
            if (chk_Publicado.isSelected() && QryOK) {
                Query = Query +   " and cc.publicado  IS TRUE \n";  
                QryOK = true;
            }else if (chk_Publicado.isSelected() && QryOK.equals(false)) {
                Query = Query +   " and cc.publicado  IS TRUE \n";  
                QryOK = true;
            } 
            if (chk_Oferta.isSelected() && QryOK) {
                Query = Query +   " and cc.oferta  IS TRUE and cc.oferta_fin>='TODAY' \n";  
                QryOK = true;
            }else  if (chk_Oferta.isSelected() && QryOK.equals(false)) {
                Query = Query +   " and cc.oferta  IS TRUE and cc.oferta_fin>='TODAY' \n";  
                QryOK = true;
            }
            

            
            if (chkWeb.isSelected() && QryOK) {
                Query = Query +   " and cw.publicado  IS TRUE \n";  
                QryOK = true;
            }else if (chkWeb.isSelected() && QryOK.equals(false)) {
                Query = Query +   " and cw.publicado  IS TRUE \n";  
                QryOK = true;
            }
            
  
            if (chkNoTransado.isSelected() && QryOK) {
                Query = Query +   " and cc.notransado  IS TRUE \n";  
                QryOK = true;
            }else  if (chkNoTransado.isSelected() && QryOK.equals(false)) {
                Query = Query +   " and cc.notransado  IS TRUE \n";  
                QryOK = true;
            }
 
            if (chkDesxPrecio.isSelected() && QryOK) {
                Query = Query +   " and cc.desxprecio  IS TRUE \n";  
                QryOK = true;
            }else  if (chkDesxPrecio.isSelected() && QryOK.equals(false)) {
                Query = Query +   " and cc.desxprecio  IS TRUE \n";  
                QryOK = true;
            }
 
            if (chkdeshabilitado.isSelected() && QryOK.equals(false)){
                Query = Query + "and cc.deshabilitado IS TRUE\n";
                QryOK = true;
            }else if (chkdeshabilitado.isSelected() && QryOK){
                Query = Query + "and cc.sin_publicar IS TRUE\n";
                QryOK = true;
            }


            if(jComboBox1.getSelectedItem().toString().equals("No nulos")){
                Query = Query + "and pp.posicion > 0\n";
            }else if(jComboBox1.getSelectedItem().toString().equals("0")){
                Query = Query + "and pp.posicion is null or pp.posicion = 0\n";
            }else if(jComboBox1.getSelectedItem().toString().equals("Todos")){
                Query = Query + "";
            }else {
                Query = Query + "and pp.posicion = "+jComboBox1.getSelectedItem().toString()+"\n";
            }
            
            
            if(!txSku.getText().trim().equals("")){
            
                Query = Query + "and pp.sku = '"+txSku.getText().trim()+"' \n";
            
            
            }
            
            
  /* Cramirez:
  Si existe algun filtro se puede consultar en caso contrario envia mensaje de error.
    
  */
            if( QryOK.equals(false) ){
                fmMain.Mensaje("Debe seleccionar un filtro...");
                return;
            }
  
    // EJECUTA CONSULTA
            Rs = Sql.Select(Query);
            
            while(Rs.next()){
                
                ContReg++;
           
                if (Rs.getString("chilecodigo") != null){
            
                    chilecodigo = Rs.getString("chilecodigo").trim();
           
                }else{
          
                    chilecodigo = "";
                }
           
               
                if (Rs.getString("nombre_proveedor") != null){
                   
                    nproveedor = Rs.getString("nombre_proveedor").trim();
                
                }else{
               
                    nproveedor = "";
                }
           
                if (Rs.getDouble("valor_proveedor") <=0 ){
            
                    ctotal = Rs.getDouble("costofinal") * Rs.getInt("cunidad");
                    double pprimero = Rs.getDouble("precio_primero");
                    margen  = ((pprimero - ctotal)  / pprimero) * 100; 
                
                }else if (Rs.getDouble("valor_proveedor")>0 ){
            
                    ctotal = Rs.getDouble("valor_proveedor") * Rs.getInt("cunidad");
                    double pprimero = Rs.getDouble("precio_primero");
                    margen =  ((pprimero - ctotal)  / pprimero) * 100; 
              
                }     
            
                if (isNaN(margen) || Rs.getDouble("precio_primero") == 0){    //Si no es un numero
                        
                    margen = 0; 
                }
            

                if(margen >= 25){
           
                    verde++;
                    jlbVerde.setText(""+verde);
        
                }else if(margen >= 15 && margen < 25 ){
                    
                    amarillo++;
                    jlbAmarillo.setText(""+amarillo);
                }else{
                    
                    blanco++;
                    jlbBlanco.setText(""+blanco);
                }
                
                String finicio = ""; 
                String ffin = ""; 

//              System.out.println("EL ID ES :"+chilecodigo+"  /  "+"LA OFERTA ES : "+Rs.getString("oferta")+" / LA FECHA ES :"+ Rs.getDate("oferta_inicio"));
                
                if (Rs.getString("oferta").equals("SI")){
                
                    finicio = Rs.getString("oferta_inicio");
                    ffin= Rs.getString("oferta_fin");
                    toferta = "Si";
                }
                else{ 
                    
                    finicio = "";
                    ffin = "";
                    toferta = "No";
                }

                
                String asociado = Rs.getString("proveedor_asociado");
                
                
                String query_3 = "select det.sku, round(((sum(det.cantidad*det.valorunitario)-sum(det.cantidad*(select case \n" +
                                 "                                        when p.valor_proveedor is null then p.valultcompra\n" +
                                 "                                        when p.valor_proveedor = 0 then p.valultcompra\n" +
                                 "                                        else p.valor_proveedor\n" +
                                 "                                        end as valor)))/sum(det.cantidad*det.valorunitario))*100) margen\n" +
                                "from ctacteclidet det\n" +
                                "left join ctactecli cli on cli.nrodocto = det.nrodocto and cli.tipdocto = det.tipdocto and cli.rut = det.rut\n" +
                                "left join producto p on p.sku = det.sku\n" +
                                "left join codchile cod on cod.sku = p.sku\n" + 
                                "where det.tipdocto = 'FAC'\n" +
                                "and det.sku = '"+Rs.getString("sku").trim()+"'\n";
                                
                                if(rbFechaDesde.isSelected()){
                                    Calendar cals = Calendar.getInstance();
                                    SimpleDateFormat formater = new SimpleDateFormat("dd/MM/yyyy");

                                    String desde = formater.format(dtDesde.getDate());
                                    String hasta = formater.format(dtHasta.getDate());
                                    query_3 = query_3 +  "and cli.femision between to_date('"+desde+"', 'DD/MM/YYYY') and to_date('"+hasta+"', 'DD/MM/YYYY')\n";
                                }
                                
                                if(rbEspecificas.isSelected()){
                                    query_3 = query_3 + "and EXTRACT(YEAR FROM cli.femision) = '"+cbAno.getSelectedItem().toString().trim()+"' and EXTRACT(MONTH FROM cli.femision) = '"+(cbMes.getSelectedIndex()+1)+"' \n";
                                }
                                
                                if(rbFechaTodas.isSelected()){
                                       
                                }
                                
//                                if(!txProveedor.getText().isEmpty() || !txProveedor.getText().equals("")){
//                                   
//                                    query_3 = query_3 + "and p.rut_proveedor_asociado = '"+txRutProveedor.getText().trim()+"'\n";
//                                }

                                query_3 = query_3 + "group by det.sku";
                                
                
                ResultSet rs_3 = sql3.Select(query_3);
                
                String margen_producto = "";
                
                if(rs_3.next()){
                    margen_producto =  rs_3.getString("margen");
                }
                else {
                    margen_producto = "NO";
                }
                
                double StockTotal = Rs.getDouble("stock") + Rs.getDouble("ocp") + Rs.getDouble("occ") + Rs.getDouble("gdc");
                
                TableModel.addRow(new Object[]{nproveedor, 
                                           Rs.getString("sku").trim(), 
                                           chilecodigo,
                                           Rs.getString("nombre").trim(), 
                                           Rs.getString("sinstock"),
                                           Rs.getInt("stock"),
                                           Rs.getString("discontinuado"),
                                           toferta,
                                           Rs.getString("publicado"),
                                           Rs.getString("web"),
                                           finicio,
                                           ffin,
                                           Rs.getInt("posicion"),
                                           fmMain.FormatoNumero(ctotal),
                                           fmMain.FormatoNumero(Rs.getDouble("precio_primero")),
                                           Precision.round(margen,1),
                                           Rs.getBoolean("sin_publicar"),StockTotal,Rs.getString("promedio"),
                                           asociado,
                                           ctotal,
                                           Rs.getDouble("precio_primero"),
                                           margen_producto
                                           
                });
            }
            
            
            if(rbEspecificas.isSelected()){
             
                 
                  TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(TableModel);
                  Grilla.setRowSorter(sorter);
                  String margenventa ="NO";
        
                  sorter.setRowFilter(RowFilter.notFilter(RowFilter.regexFilter(margenventa,22)));
            
                  ContReg = Grilla.getRowCount();
             
            }
            else if(rbFechaDesde.isSelected()){
             
                 
                  TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(TableModel);
                  Grilla.setRowSorter(sorter);
                  String margenventa ="NO";
        
                  sorter.setRowFilter(RowFilter.notFilter(RowFilter.regexFilter(margenventa,22)));
            
                  ContReg = Grilla.getRowCount();
             
            }else{
             
                 TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(TableModel);
                  Grilla.setRowSorter(sorter);
                  String margenventa =" ";
        
                  sorter.setRowFilter(RowFilter.notFilter(RowFilter.regexFilter(margenventa,22)));
            
                  ContReg = Grilla.getRowCount();
             
            }
            
            
            
            
            Grilla.setDefaultRenderer(Object.class, new TableCellRendererConvenio());
            
            lblReg.setText(String.valueOf(ContReg));
            Grilla.repaint();
            
        }catch (SQLException e) {
            fmMain.Mensaje("Existe una inconsistencia en la información: "+e);
            Logger.getLogger(pfReporteProveedorConvenio_2.class.getName()).log(Level.SEVERE, null, e);
        }finally{
            Sql.Close();
            sql2.Close();
            sql3.Close();
        }
        
    }
    
    private void GrillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaMouseClicked

    }//GEN-LAST:event_GrillaMouseClicked

    private void btExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcelActionPerformed
    
        if(Grilla.getRowCount()==0){
            fmMain.Mensaje("Nada que exportar");
            return;
        }

//        JFileChooser chooser = new JFileChooser();
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo Excel",".xls");
//        chooser.setFileFilter(filter);
//        chooser.setDialogTitle("Guardar Informe en Excel");
//        chooser.setMultiSelectionEnabled(false);
//        chooser.setAcceptAllFileFilterUsed(false);


        List<JTable> tb=new ArrayList<>();
        List<String> nom=new ArrayList<>();
        tb.add(Grilla);
        String str_convenio="conv";
        String str_proveedor="prov";

        ComboCodigos convenio = (ComboCodigos) CboConvenio.getSelectedItem() ;
        ComboCodigos proveedor = (ComboCodigos) CboProveedor.getSelectedItem() ;
        if (convenio.getId()>0){   
                  str_convenio = convenio.toString();
        }
        if (proveedor.getId()>0){   
            
            str_proveedor = proveedor.toString();
        }

        nom.add(str_convenio + '_' + str_proveedor);
        String os = System.getProperty("os.name").toString().toLowerCase();
        System.out.println(os);
        File folder = new File("c:/temp");
        String file = "";
        if(os.contains("win")){

            if (!folder.exists()){
                folder.mkdir();
            }
            file = "C:/temp/convenio_" + str_convenio + '_' + str_proveedor + ".xls";   
        }
        else  {
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de excel", "xls");
            chooser.setSelectedFile(new File("/user","convenio_" + str_convenio + '_' + str_proveedor + ".xls"));
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar archivo");
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                file = chooser.getSelectedFile().toString().concat(".xls");
                try {
                    Exporter e = new Exporter(new File(file), tb, nom);
                    if (e.export()) {
                        JOptionPane.showMessageDialog(null, "Los datos fueron exportados en el directorio seleccionado", "Mensaje de Informacion", JOptionPane.INFORMATION_MESSAGE);
                        abrir(file);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Hubo un error " + e.getMessage(), " Error", JOptionPane.ERROR_MESSAGE);
                }
           }


        }
                
            
        try {
            Exporter e = new Exporter(new File(file), tb, nom);

            if(e.export())
            //fmMain.Mensaje("Datos Exportados");
            abrir(file);

        } catch (Exception e) {
            fmMain.Mensaje(e.getMessage());
        }

    }//GEN-LAST:event_btExcelActionPerformed

    public void abrir(String file ){
        
        try {
           String url = file;
           ProcessBuilder p = new ProcessBuilder();
           p.command("cmd.exe", "/c",url);
           p.start();
        } catch (IOException ex) {//si no se cumplen la condicion 
           Logger.getLogger(jdOC_PendientesFac.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    private void VerProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerProductoActionPerformed
    
        System.out.println( Grilla.getValueAt(Grilla.getSelectedRow(), 1).toString().trim());
        pfProductos Pro = new pfProductos();
        Pro.setOpaque(false);
        pnPestanas.addTab("Producto", Pro);
        PanelTab btc = new PanelTab(pnPestanas, 0);
        pnPestanas.setTabComponentAt(pnPestanas.indexOfComponent(Pro), btc);
        pnPestanas.setSelectedIndex(pnPestanas.getTabCount() - 1);
        Pro.txSku.requestFocus();
        Pro.CargaProducto(Grilla.getValueAt(Grilla.getSelectedRow(), 1).toString().trim());        //
    }//GEN-LAST:event_VerProductoActionPerformed

    private void txSkuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSkuKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            TableRowSorter<TableModel>sorter = new TableRowSorter<TableModel>(Grilla.getModel());
            Grilla.setRowSorter(sorter);
            String sku = txSku.getText().trim();
            
            if (sku.length()==0)
            {
                sorter.setRowFilter(null);
                
                if (Filtrado){
                
     //***********************************************************************************************************************************************************               
                    Runnable miRunnable2 = new Runnable() {
                    public void run() {
                        try{
                            Grilla.clearSelection();
                            lbcargando.setEnabled(true);
                            lbcargando.setVisible(true);
                            Grilla.setRowSelectionAllowed(false);
                            btBuscar.setEnabled(false);
                        
                            System.out.println("LAS FILAS SON :"+Grilla.getRowCount());
                
                            double suma1 = 0; 
                            double suma2 = 0;
                            for(int i = 0;i <= Grilla.getRowCount()-1;i++){
                
                                suma1 = suma1 + Double.valueOf(Grilla.getValueAt(i, 20).toString().trim());  //040102000
                                suma2 = suma2 + Double.valueOf(Grilla.getValueAt(i, 21).toString().trim());  //040102000
                    
                    
                                System.out.println("LAS SUMA1 Es :"+suma1);
                                System.out.println("LAS SUMA2 Es :"+suma2);
                   
                            }
                
                            double margen_teo = ((suma2-suma1)/suma2)*100;
                  
                            //txtMargen.setText(Math.round(margen_teo)+" %");
                            CargaMargenTabla();
                            CargaCantidadPosicion();  
                            Filtrado = false;
                
                        
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                        finally {
                            lbcargando.setVisible(false);
                            lbcargando.setEnabled(false);
                            Grilla.setRowSelectionAllowed(true);
                            btBuscar.setEnabled(true);
                        }
                    }

            
                };
                Thread hilo2 = new Thread(miRunnable2);
                hilo2.start();
                    
     //***********************************************************************************************************************************************************               
               
             }
                
                
            }
            else{
                
                int cant=0;
                int ev=0;
                String precio = "";
              
                sorter.setRowFilter(RowFilter.regexFilter(sku));
                
                
                //***********************************************************************************************************************************************************               
                    Runnable miRunnable3 = new Runnable() {
                    public void run() {
                        try{
                            Grilla.clearSelection();
                            lbcargando.setEnabled(true);
                            lbcargando.setVisible(true);
                            Grilla.setRowSelectionAllowed(false);
                            btBuscar.setEnabled(false);
                        
                            
                            System.out.println("LAS FILAS SON :"+Grilla.getRowCount());
              
                            double suma1 = 0; 
                            double suma2 = 0;
                            for(int i = 0;i <= Grilla.getRowCount()-1;i++){
                
                                suma1 = suma1 + Double.valueOf(Grilla.getValueAt(i, 20).toString().trim());  //040102000
                                suma2 = suma2 + Double.valueOf(Grilla.getValueAt(i, 21).toString().trim());  //040102000
                                        
                                System.out.println("LAS SUMA1 Es :"+suma1);
                                System.out.println("LAS SUMA2 Es :"+suma2);
                   
                            }
                
                            double margen_teo = ((suma2-suma1)/suma2)*100;
                  
                            //txtMargen.setText(Math.round(margen_teo)+" %");
                  
                            CargaMargenTabla();
                            CargaCantidadPosicion();  
                
                            Filtrado = true;
                        
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                        finally {
                            lbcargando.setVisible(false);
                            lbcargando.setEnabled(false);
                            Grilla.setRowSelectionAllowed(true);
                            btBuscar.setEnabled(true);
                        }
                    }

            
                };
                Thread hilo3 = new Thread(miRunnable3);
                hilo3.start();
                    
                //***********************************************************************************************************************************************************      
                
            }
        }
    }//GEN-LAST:event_txSkuKeyPressed

    private void txSkuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSkuKeyTyped
        // TODO add your handling code here:
        if (Character.isLowerCase(evt.getKeyChar()))
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_txSkuKeyTyped

    private void txSkuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSkuKeyReleased
        TableRowSorter<TableModel>sorter = new TableRowSorter<TableModel>(Grilla.getModel());
            Grilla.setRowSorter(sorter);
            String sku = txSku.getText().trim();
            if (sku.length()==0)
            {
                sorter.setRowFilter(null);
            }
            else{
                int cant=0;
                int ev=0;
                String precio = "";
                sorter.setRowFilter(RowFilter.regexFilter(sku));
                
               
                
                
                
            }        // TODO add your handling code here:

    }//GEN-LAST:event_txSkuKeyReleased

    private void GrillaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_GrillaMouseEntered

    private void rbFechaDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFechaDesdeActionPerformed
        if(rbFechaTodas.isSelected()){
            dtDesde.setEnabled(false);
            dtHasta.setEnabled(false);
            
        }
        else{
            dtDesde.setEnabled(true);
            dtHasta.setEnabled(true);
        }
        jLabel11.setEnabled(true);
        margentotalventa.setEnabled(true);
        jLabel6.setEnabled(false);
        txtMargen.setEnabled(false);
    }//GEN-LAST:event_rbFechaDesdeActionPerformed

    private void rbFechaTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFechaTodasActionPerformed
        if(rbFechaTodas.isSelected()){
            dtDesde.setEnabled(false);
            dtHasta.setEnabled(false);

        }
        else{
            dtDesde.setEnabled(true);
            dtHasta.setEnabled(true);

        }
        jLabel11.setEnabled(false);
        margentotalventa.setEnabled(false);
        jLabel6.setEnabled(true);
        txtMargen.setEnabled(true);
    }//GEN-LAST:event_rbFechaTodasActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        Runnable miRunnable = new Runnable() {
            public void run() {
                try{
                    Grilla.clearSelection();
                    lbcargando.setEnabled(true);
                    lbcargando.setVisible(true);
                    Grilla.setRowSelectionAllowed(false);
                    btBuscar.setEnabled(false);
                    CargarTable();

                    CargaCantidadPosicion();
                    //Grilla.changeSelection(0, 0 , false, false);

                } catch (Exception e) {
                    e.printStackTrace();
                }
                finally {
                    lbcargando.setVisible(false);
                    lbcargando.setEnabled(false);
                    Grilla.setRowSelectionAllowed(true);
                    btBuscar.setEnabled(true);
                }
            }

            
        };
        Thread hilo = new Thread(miRunnable);
        hilo.start();

        verde = 0;
        amarillo = 0;
        blanco = 0;

        lbcargando.setText("Cargando.....");
        URL urlInfo =  this.getClass().getResource("/Iconos16/wait.gif");
        ImageIcon IconoInfo =  new ImageIcon(urlInfo);
        lbcargando.setIcon(IconoInfo);
        lbcargando.setForeground(Color.red);
    }//GEN-LAST:event_btBuscarActionPerformed
    private void CargaCantidadPosicion() {
        jComboBox2.removeAllItems();
        List<String> list = new ArrayList<>();
        for(int i =0; i<Grilla.getRowCount(); i++){
            list.add(Grilla.getValueAt(i, 12).toString().trim());
        } 
        Map<String, Long> counted = list.stream().collect(Collectors.groupingBy(Function.identity(), Collectors.counting()));
        int suma = 0;
        String value = "";
        for (Map.Entry<String, Long> entry : counted.entrySet()) {
            System.out.println();
            if(Integer.valueOf(entry.getKey())<7 && Integer.valueOf(entry.getKey())!=1020){
                jComboBox2.addItem(entry.getKey() + ":  " + entry.getValue().toString());
            }
            if(Integer.valueOf(entry.getKey())>=7 && Integer.valueOf(entry.getKey())!=1020){
                suma = suma + Integer.valueOf(entry.getValue().toString());
            }
            if(entry.getKey().equals("1020")){
                value = (entry.getKey() + ":  " + entry.getValue());
            }
        }
        if (suma>0){
            jComboBox2.addItem(">=7:  " + suma);
        }
        if(!value.equals("")){
            jComboBox2.addItem(value);
        }

        
    }
    private void CboConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboConvenioActionPerformed
        // TODO add your handling code here:
        ComboCodigos convenio = (ComboCodigos) CboConvenio.getSelectedItem() ;
        if (CboConvenio.getSelectedItem()!= null){
            id_convenio = convenio.getId();
        }

        //btBuscar.doClick();
    }//GEN-LAST:event_CboConvenioActionPerformed

    private void CboProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboProveedorActionPerformed

        try{
            ComboCodigos proveedor = (ComboCodigos) CboProveedor.getSelectedItem() ;

            if (CboProveedor.getSelectedItem()!= null){
                id_proveedor = proveedor.getId();
            }
            //btBuscar.doClick();
        } catch (Exception e) {
            fmMain.Mensaje(e.getMessage());
        }
    }//GEN-LAST:event_CboProveedorActionPerformed

    private void dtDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtDesdeActionPerformed

        System.out.println(dtDesde.getDate());

    }//GEN-LAST:event_dtDesdeActionPerformed

    private void cbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMesActionPerformed

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered

    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited

    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        JOptionPane.showMessageDialog(null, "Margen total productos en tabla");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        JOptionPane.showMessageDialog(null, "Margen total de ventas de productos en tabla"); 
    }//GEN-LAST:event_jLabel11MousePressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String ctc = Grilla.getValueAt(Grilla.getSelectedRow(), 2).toString().trim();
        StringSelection stringSelection = new StringSelection(ctc);
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
        clpbrd.setContents(stringSelection, null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void rbEspecificasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEspecificasActionPerformed
        jLabel11.setEnabled(true); 
        margentotalventa.setEnabled(true);
        jLabel6.setEnabled(false);
        txtMargen.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_rbEspecificasActionPerformed

    private void chk_PublicadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_PublicadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_PublicadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Runnable miRunnable = new Runnable() {
            public void run() {
                try{
                    Grilla.clearSelection();
                    lbcargando.setEnabled(true);
                    lbcargando.setVisible(true);
                    Grilla.setRowSelectionAllowed(false);
                    btBuscar.setEnabled(false);
                    CargaMargenTabla();

                } catch (Exception e) {
                    e.printStackTrace();
                }
                finally {
                    lbcargando.setVisible(false);
                    lbcargando.setEnabled(false);
                    Grilla.setRowSelectionAllowed(true);
                    btBuscar.setEnabled(true);
                }
            }

            
        };
        Thread hilo = new Thread(miRunnable);
        hilo.start();

        verde = 0;
        amarillo = 0;
        blanco = 0;

        lbcargando.setText("Cargando.....");
        URL urlInfo =  this.getClass().getResource("/Iconos16/wait.gif");
        ImageIcon IconoInfo =  new ImageIcon(urlInfo);
        lbcargando.setIcon(IconoInfo);
        lbcargando.setForeground(Color.red);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIrActionPerformed

        Dialogos.jdBuscarCliPrv BPC = new Dialogos.jdBuscarCliPrv(null, true);
        BPC.setLocationRelativeTo(null);
        BPC.setTitle("Buscar Proveedor");
        BPC.SetTipo(1);
        BPC.setVisible(true);

        txProveedor.setText(BPC.GetNom());
        txRutProveedor.setText(BPC.GetRut());
        btBuscar.doClick();

    }//GEN-LAST:event_btIrActionPerformed

    private void txProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txProveedorKeyReleased
        txProveedor.setText(txProveedor.getText().toUpperCase());
    }//GEN-LAST:event_txProveedorKeyReleased

    private void txProveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txProveedorKeyPressed
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
            btBuscar.doClick();
        
        
    }//GEN-LAST:event_txProveedorKeyPressed
//6700

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboConvenio;
    private javax.swing.JComboBox<String> CboProveedor;
    private javax.swing.JTable Grilla;
    private javax.swing.JMenuItem VerProducto;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btExcel;
    private javax.swing.JButton btIr;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> cbAno;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JCheckBox chkDesxPrecio;
    private javax.swing.JCheckBox chkNoTransado;
    private javax.swing.JCheckBox chkWeb;
    private javax.swing.JCheckBox chk_Oferta;
    private javax.swing.JCheckBox chk_Publicado;
    private javax.swing.JCheckBox chk_discon;
    private javax.swing.JCheckBox chk_sinstock;
    private javax.swing.JCheckBox chkdeshabilitado;
    private org.jdesktop.swingx.JXDatePicker dtDesde;
    private org.jdesktop.swingx.JXDatePicker dtHasta;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JLabel jlbAmarillo;
    private javax.swing.JLabel jlbBlanco;
    private javax.swing.JLabel jlbVerde;
    private javax.swing.JLabel lbcargando;
    private javax.swing.JLabel lblReg;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JLabel lblVendedor1;
    private javax.swing.JLabel margentotalventa;
    private javax.swing.JRadioButton rbEspecificas;
    private javax.swing.JRadioButton rbFechaDesde;
    private javax.swing.JRadioButton rbFechaTodas;
    private javax.swing.JTextField txProveedor;
    private javax.swing.JTextField txRutProveedor;
    private javax.swing.JTextField txSku;
    private javax.swing.JLabel txtMargen;
    // End of variables declaration//GEN-END:variables


}
