/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;


import Conexion.ExeSql;
import Dialogos.jd_ValorDespacho;
import Formularios.fmMain;
import Utilidades.ComboCodigos;
import Utilidades.Exporter;
import Utilidades.POI_excel;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luvaly
 */
public class PreciosDEspacho extends javax.swing.JPanel {
   DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
    private Object GrillaOCS;
    public static int pano; 
    public static int pmes;
    public static int pmes_oc;
    int id_trans=-1;
    /**
     * Creates new form PreciosDEspacho
     */
    public PreciosDEspacho() {
        initComponents();
         //Setea fecha inicial Desde y Hasta
        Date date = new Date();
//        dtDesde.setDate(date);
//        dtHasta.setDate(date);
//        dtDesde.setEnabled(true);
//        dtHasta.setEnabled(true);
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        Grilla.getColumnModel().getColumn(1).setCellRenderer(rightRenderer);
        CargaTransporte();
        //CargaBultos_tnt();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtExcel = new javax.swing.JButton();
        lblFecha1 = new javax.swing.JLabel();
        CboTransporte = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        txPeso = new javax.swing.JTextField();
        bt_cargar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblTotalDesp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotalBulto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTotalPeso = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtExcel.setText("Excel");
        BtExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcelActionPerformed(evt);
            }
        });
        add(BtExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, 68));

        lblFecha1.setText("Ciudad");
        add(lblFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, 70, -1));

        CboTransporte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Todos>" }));
        CboTransporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CboTransporteMouseClicked(evt);
            }
        });
        CboTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboTransporteActionPerformed(evt);
            }
        });
        add(CboTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 74, 732, -1));

        jLabel4.setText("Peso");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, -1, -1));

        txPeso.setText("0");
        txPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txPesoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txPesoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txPesoKeyTyped(evt);
            }
        });
        add(txPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 112, 54, -1));

        bt_cargar.setText("Cargar");
        bt_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cargarActionPerformed(evt);
            }
        });
        add(bt_cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(769, 112, -1, -1));

        Grilla.setAutoCreateRowSorter(true);
        Grilla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transporte", "Precio", "Ciudad", "Peso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Grilla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 141, 824, 219));

        jLabel1.setText("Tnt");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 392, -1, -1));

        lblTotalDesp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTotalDesp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalDesp.setText("0");
        add(lblTotalDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 412, 79, -1));

        jLabel2.setText("Samex");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 392, 60, -1));

        lblTotalBulto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTotalBulto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalBulto.setText("0");
        add(lblTotalBulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 412, 76, -1));

        jLabel3.setText("Blue");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 392, -1, -1));

        lblTotalPeso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTotalPeso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalPeso.setText("0");
        add(lblTotalPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 412, 95, -1));
    }// </editor-fold>//GEN-END:initComponents

    
        private void CargaTransporte(){
        DefaultComboBoxModel value;
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        String Query="";
        int i=0;
        CboTransporte.removeAllItems();
        
        value =new DefaultComboBoxModel();
       
        
        
        try {
            Query=" select comuna\n" +
            " from g_comunas \n" +
            " order by comuna";
            Rs = Sql.Select(Query);
            if(Sql.GetRowCount()==0) return;
           value.addElement(new ComboCodigos("Seleccione",0));     
           while(Rs.next()){
            value.addElement(new ComboCodigos(Rs.getString("comuna").trim(),i));
            System.out.println(Rs.getString("comuna").trim());
            i++;
           } 
           CboTransporte.setModel(value);
           CboTransporte.setSelectedIndex(0);

           
           
        } catch (Exception e) {
            System.out.println(e);
        }
        finally{
            Sql.Close();
        }
    }
      
      
      
    public double  CargaBultos_tnt(String ciudad, String Speso ){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        double nMinimo =0;
        int SumaDespachos = 0;
        int SumaBultos = 0;
        int SumaPeso = 0;
        double nPrecio =-1;
                lblTotalPeso.setText(String.valueOf(SumaPeso));
                lblTotalBulto.setText(String.valueOf(SumaBultos));
                lblTotalDesp.setText(String.valueOf(SumaDespachos));
        
        
        if (Speso.equals("0")){
            fmMain.Mensaje("Debe ingresar el peso del bulto");
            return -1;
        }
        
        
//         while(TableModel.getRowCount()>0)
//             TableModel.removeRow(0);
        try {
            
            // Trae el precio de Tnt
 
            String Query = "select tnt.ciudad, tnt.troncal_ramal, tnt.codigo,p_tnt.precio, p_tnt.minimo\n" +
            " from pd_ciudades_tnt tnt\n" +
            " left join pd_precios_tnt p_tnt\n" +
            " on p_tnt.codigo = tnt.codigo\n" +
            " where trim(tnt.ciudad) ='" + ciudad.trim() + "'\n " +
            " and p_tnt.inicio <= " + Speso + "  and p_tnt.fin >= " + Speso + ";";
            
            Double peso = Double.valueOf(Speso);
             
            Rs = Sql.Select(Query);
            if (Rs.next()){ 
                     nPrecio = Double.valueOf(Rs.getString("precio"));
                     nMinimo= Double.valueOf(Rs.getString("minimo"));
                    if(peso >=100){
                        nPrecio = nPrecio * peso;
                    }    
                    else
                    {
                       nPrecio = Double.valueOf(Rs.getString("precio")); 
                    }
                    nPrecio = Math.round(nPrecio);
                    
                    if(nPrecio < nMinimo ){
                        nPrecio = nMinimo;
                    }
                    
                    nPrecio =  Math.round(nPrecio);
                    
                
            }
            
        } catch (Exception e) {
          
        } finally{
            Sql.Close();
            return nPrecio;
        }
        
    }   
    
    
    public double  CargaBultos_Samex(String ciudad, String Speso ){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
      
        int SumaDespachos = 0;
        int SumaBultos = 0;
        int SumaPeso = 0;
        double nPrecio =-1;
        double nMinimo =0;
                lblTotalPeso.setText(String.valueOf(SumaPeso));
                lblTotalBulto.setText(String.valueOf(SumaBultos));
                lblTotalDesp.setText(String.valueOf(SumaDespachos));
        
        
        if (Speso.equals("0")){
            fmMain.Mensaje("Debe ingresar el peso del bulto");
            return -1;
        }
        
         Double peso = Double.valueOf(Speso);
        
        if (peso <1 && peso >0){
            peso=1.0;
            Speso="1";
        }

        try {
            
             String Query = "select samex.nombre, samex.base, samex.zona_influencia,p_samex.precio,p_samex.minimo\n" +
            " from pd_ciudades_samex samex\n" +
            " left join pd_precios_samex p_samex\n" +
             "on samex.zona_influencia = p_samex.zi\n" +
            " and  p_samex.base = samex.base \n" +
             " where upper(trim(samex.nombre))='" + ciudad.toUpperCase().trim() + "'\n "+         
            //" where trim(samex.nombre)='" + ciudad.trim() + "'\n "+
            //" and  samex.zona_influencia not in ('ZE','ZME') --- Fijo\n" +  //No se vera transporte para estas zonas
            " and p_samex.inicio <= " + Speso + "  and p_samex.fin >= " + Speso + ";";
            
         
             
            Rs = Sql.Select(Query);
            if (Rs.next()){ 
                    nPrecio = Double.valueOf( Rs.getDouble("precio"));
                    nMinimo = Rs.getDouble("minimo");
                    
                    nPrecio = nPrecio * peso;
                    if(nPrecio < nMinimo ){
                        nPrecio = nMinimo;
                    }
                    
                    nPrecio =  Double.valueOf(Math.round(nPrecio));
                    
            }
            
        } catch (Exception e) {
          
        } finally{
            Sql.Close();
            return nPrecio;
        }
        
    } 
    
    public double  CargaBultos_Blue(String ciudad, String Speso ){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
      
        int SumaDespachos = 0;
        int SumaBultos = 0;
        int SumaPeso = 0;
        double nPrecio =-1;
        double nMinimo =0;
                lblTotalPeso.setText(String.valueOf(SumaPeso));
                lblTotalBulto.setText(String.valueOf(SumaBultos));
                lblTotalDesp.setText(String.valueOf(SumaDespachos));
        
        
        if (Speso.equals("0")){
            fmMain.Mensaje("Debe ingresar el peso del bulto");
            return -1;
        }

        try {
            
             String Query = "select * \n" +
            " from pd_zonageografica_blue blue \n" +
            " left join pd_precios_blue p_blue\n" +
             "on trim(blue.zona) = trim(p_blue.zona)\n" +
            " and  trim(blue.posta)= trim(p_blue.base)  \n" +
            " where trim(blue.localidad) =  '" + ciudad.trim() + "'";          

            
            Double peso = Double.valueOf(Speso);
             
            Rs = Sql.Select(Query);
            if (Rs.next()){ 
//                if (peso>= 3.1 && peso <=6 ){
//                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p3c1_6")));
//                }
//                else if (peso>= 6.1 && peso <=10 ){
//                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p6c1_10")));
//                }
//                else if (peso>= 10.1 && peso <=20.9 ){
//                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p10c1_20")));
//                }
//                else if (peso>= 21 && peso <=50.9 ){
//                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p21_50")));
//                }
//                else if (peso>= 51 && peso <=100.9 ){
//                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p51_100")));
//                }
//                
//                 else if (peso>= 101 && peso <=200.9 ){
//                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p101_200")));
//                }
//                else if (peso>= 201 && peso <=400.9 ){
//                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p201_400")));
//                }
//                else if (peso>= 401 && peso <=600.9 ){
//                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p401_600")));
//                }
//                
//                else if (peso>= 601 && peso <=1000.9 ){
//                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p601_1000")));
//                }
//                else if (peso>= 1001 && peso <=2000.9){
//                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p1001_2000")));
//                }
//                else if (peso>= 2001 && peso <=3500.9){
//                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p2001_3500")));
//                }
//                
//                   else if (peso>= 3501 && peso <=5000.9 ){
//                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p3501_5000")));
//                }
//                else if (peso>=5001 && peso <=10000.9 ){
//                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p5001_10000")));
//                }
//                else if (peso>=10001 && peso <=18000.9 ){
//                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p10001_18000")));
//                }
                if (peso>= 3.1 && peso <=6 ){
                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p3c1_6")));
                }
                else if (peso>= 6.1 && peso <=10 ){
                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p6c1_10")));
                }
                else if (peso>= 10.1 && peso <=20 ){
                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p10c1_20")));
                    //nPrecio = Rs.getDouble("p10c1_20");
                }
                else if (peso>= 20.1 && peso <=50 ){
                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p21_50")));
                }
                else if (peso>= 50.1 && peso <=100 ){
                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p51_100")));
                }
                
                 else if (peso>= 100.1 && peso <=200.9 ){
                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p101_200")));
                }
                else if (peso>= 201 && peso <=400.9 ){
                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p201_400")));
                }
                else if (peso>= 401 && peso <=600.9 ){
                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p401_600")));
                }
                
                else if (peso>= 601 && peso <=1000.9 ){
                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p601_1000")));
                }
                else if (peso>= 1001 && peso <=2000.9){
                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p1001_2000")));
                }
                else if (peso>= 2001 && peso <=3500.9){
                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p2001_3500")));
                }
                
                   else if (peso>= 3501 && peso <=5000.9 ){
                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p3501_5000")));
                }
                else if (peso>=5001 && peso <=10000.9 ){
                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p5001_10000")));
                }
                else if (peso>=10001 && peso <=18000.9 ){
                    nPrecio = Double.valueOf( fmMain.FormatoTotal(Rs.getDouble("p10001_18000")));
                }
                   
                    nMinimo = Rs.getDouble("min_a_cobrar");
                    
                    if (nPrecio >0)
                    nPrecio = nPrecio * peso;
                    
                    if(nPrecio < nMinimo ){
                        nPrecio = nMinimo;
                    }
                    
                    
                    nPrecio =  Math.round(nPrecio);
                    
            }
            
        } catch (Exception e) {
          
        } finally{
            Sql.Close();
            return nPrecio;
        }
        
    } 
    
    
    
    
    
    
    
    
    public void abrir(String file ){
        
       try {
           String url = file;
           ProcessBuilder p = new ProcessBuilder();
           p.command("cmd.exe", "/c",url);
           p.start();
       } catch (IOException ex) {
           Logger.getLogger(jd_ValorDespacho.class.getName()).log(Level.SEVERE, null, ex);
       }
        
    }
    
    
    
    private void CboTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboTransporteActionPerformed
        
    }//GEN-LAST:event_CboTransporteActionPerformed

    private void txPesoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPesoKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txPesoKeyPressed

    private void txPesoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPesoKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        bt_cargar.doClick();
    }//GEN-LAST:event_txPesoKeyReleased

    private void txPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPesoKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txPesoKeyTyped

    private void bt_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cargarActionPerformed
        // TODO add your handling code here:
        double nPrecio_tnt =0, nPrecio_samex =0, nPrecio_blue  =0;

        nPrecio_tnt= CargaBultos_tnt(CboTransporte.getSelectedItem().toString(),txPeso.getText());
        nPrecio_samex= CargaBultos_Samex(CboTransporte.getSelectedItem().toString(),txPeso.getText());
        nPrecio_blue= CargaBultos_Blue(CboTransporte.getSelectedItem().toString(),txPeso.getText());
        DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();

        while(TableModel.getRowCount()>0)
        TableModel.removeRow(0);
        TableModel.addRow(new Object[]{
            "TNT",
            String.valueOf(nPrecio_tnt),
            CboTransporte.getSelectedItem(), txPeso.getText()
        });
        lblTotalDesp.setText(String.valueOf(nPrecio_tnt));

        TableModel.addRow(new Object[]{
            "SAMEX",
            String.valueOf(nPrecio_samex),
            CboTransporte.getSelectedItem(), txPeso.getText()
        });
        lblTotalBulto.setText(String.valueOf(nPrecio_samex));

        TableModel.addRow(new Object[]{
            "BLUE",
            String.valueOf(nPrecio_blue),
            CboTransporte.getSelectedItem(), txPeso.getText()
        });
        lblTotalPeso.setText(String.valueOf(nPrecio_blue));

    }//GEN-LAST:event_bt_cargarActionPerformed

    private void BtExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcelActionPerformed
        // TODO add your handling code here:

        //        if(Grilla.getRowCount()==0){
            //            fmMain.Mensaje("Nada que exportar");
            //            return;
            //        }
        //
        //        JFileChooser chooser = new JFileChooser();
        //        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo Excel",".xls");
        //        chooser.setFileFilter(filter);
        //        chooser.setDialogTitle("Guardar Informe en Excel");
        //        chooser.setMultiSelectionEnabled(false);
        //        chooser.setAcceptAllFileFilterUsed(false);
        //
        //        if(chooser.showSaveDialog(null)== JFileChooser.APPROVE_OPTION){
            //            List<JTable> tb=new ArrayList<>();
            //            List<String> nom=new ArrayList<>();
            //            tb.add(Grilla);
            //            nom.add("Año: " + pano + " Mes: " + pmes + " Mes_OC: "+ pmes_oc);
            //            String file=chooser.getSelectedFile().toString().concat(".xls");
            //            try {
                //                Exporter e = new Exporter(new File(file), tb, nom);
                //
                //                if(e.export())
                //                fmMain.Mensaje("Datos Exportados");
                //                abrir(file);
                //
                //            } catch (Exception e) {
                //                fmMain.Mensaje(e.getMessage());
                //            }
            //
            //
            //        }

        if(Grilla.getRowCount()==0){
            fmMain.Mensaje("Nada que exportar");
            return;
        }

        //        JFileChooser chooser = new JFileChooser();
        //        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo Excel",".xls");
        //        chooser.setFileFilter(filter);
        //        chooser.setDialogTitle("Guardar Informe en Excel");
        //        chooser.setMultiSelectionEnabled(false);
        //        chooser.setAcceptAllFileFilterUsed(false);

        List<JTable> tb=new ArrayList<>();
        List<String> nom=new ArrayList<>();
        tb.add(Grilla);
        nom.add("Agno->" + pano + " Mes->" + pmes + " Mes_OC->"+ pmes_oc);

        File folder = new File("c:/temp");
        if (!folder.exists())
        {
            folder.mkdir();
        }

        String file = "C:/temp/convenio" + pano + "-" + pmes + "-"+ pmes_oc +".xls";

        try {
            Exporter e = new Exporter(new File(file), tb, nom);

            if(e.export())
            //fmMain.Mensaje("Datos Exportados");
            abrir(file);

        } catch (Exception e) {
            fmMain.Mensaje(e.getMessage());
        }
    }//GEN-LAST:event_BtExcelActionPerformed

    private void CboTransporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CboTransporteMouseClicked
        // TODO add your handling code here:
        
        bt_cargar.doClick();
        
    }//GEN-LAST:event_CboTransporteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtExcel;
    private javax.swing.JComboBox<String> CboTransporte;
    private javax.swing.JTable Grilla;
    private javax.swing.JButton bt_cargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFecha1;
    private javax.swing.JLabel lblTotalBulto;
    private javax.swing.JLabel lblTotalDesp;
    private javax.swing.JLabel lblTotalPeso;
    private javax.swing.JTextField txPeso;
    // End of variables declaration//GEN-END:variables
}
