/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Dialogos.jdOC_PendientesFac;
import Formularios.fmMain;
import static Formularios.fmMain.pnPestanas;
import Utilidades.ComboCodigos;
import Utilidades.Exporter;
import Utilidades.MyTableModel;
import Utilidades.PanelTab;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Cdiaz
 */
public class pfCompraValorizado extends javax.swing.JPanel {
    int id_proveedor;
    String Predeterminados = "91868000, 79921700, 79757520, 76215357, 96679310, 81031100, 77248430,\n" +
                        "85969100,78415390, 83574800, 78110590, 76182753, 96777810, 78615470, 96853390, 91947000, 84419800, 76012152,\n" +
                        "76242324, 81756300, 93626000, 93333000, 96671320, 96512030, 93912000, 78922590, 96548020, 95050000, 76495316,\n" +
                        "52002072, 89689900, 92264000, 83162400, 76492690, 93631000, 96889950, 84915900, 91476000, 86882300, 91335000";
    int inicio = 0;
    /**
     * Creates new form pfCompraVenta
     */
    public pfCompraValorizado() {
        initComponents();
        Date date = new Date();
        dtDesde.setDate(date);
        dtHasta.setDate(date);
        CargaProveedor();
        btRut.setVisible(false);
        txRutProveedor.setVisible(false);
        
    }

    private void CargaProveedor(){
        DefaultComboBoxModel value;
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        String Query="";
        cbProveedor.removeAllItems();
//        CboProveedor.addItem("<Todos>");  
//        CboProveedor.setSelectedIndex(0);
        value =new DefaultComboBoxModel();
       
        
        
        try {
            Query="select rut,nombre from proveedor\n" +
                    "order by nombre";
            Rs = Sql.Select(Query);
            if(Sql.GetRowCount()==0) return;
           value.addElement(new ComboCodigos("Seleccione",0));     
           while(Rs.next()){
            value.addElement(new ComboCodigos(Rs.getString("nombre").trim(),Rs.getInt("rut")));
           } 
           cbProveedor.setModel(value);
           cbProveedor.setSelectedIndex(0);
           txRutProveedor.setText("");

           
           
        } catch (Exception e) {
            System.out.println(e);
        }
        finally{
            Sql.Close();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbProveedor = new javax.swing.JComboBox<String>();
        txRutProveedor = new javax.swing.JTextField();
        btRut = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Agrupados = new javax.swing.JTable();
        txSku = new javax.swing.JTextField();
        btFiltro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dtDesde = new org.jdesktop.swingx.JXDatePicker();
        dtHasta = new org.jdesktop.swingx.JXDatePicker();
        btExcel = new javax.swing.JButton();

        cbProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProveedorActionPerformed(evt);
            }
        });

        btRut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/Go.png"))); // NOI18N
        btRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRutActionPerformed(evt);
            }
        });

        Agrupados.setAutoCreateRowSorter(true);
        Agrupados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "RUT", "NOMBRE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Agrupados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgrupadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Agrupados);
        if (Agrupados.getColumnModel().getColumnCount() > 0) {
            Agrupados.getColumnModel().getColumn(0).setMinWidth(60);
            Agrupados.getColumnModel().getColumn(0).setPreferredWidth(80);
            Agrupados.getColumnModel().getColumn(0).setMaxWidth(80);
            Agrupados.getColumnModel().getColumn(1).setMinWidth(200);
            Agrupados.getColumnModel().getColumn(1).setPreferredWidth(420);
            Agrupados.getColumnModel().getColumn(1).setMaxWidth(450);
        }

        txSku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txSkuKeyPressed(evt);
            }
        });

        btFiltro.setText("Filtrar");
        btFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFiltroActionPerformed(evt);
            }
        });

        jLabel1.setText("PROVEEDOR:");

        jLabel3.setText("FILTRO:");

        jLabel2.setText("RANGO:");

        dtDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtDesdeActionPerformed(evt);
            }
        });

        dtHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtHastaActionPerformed(evt);
            }
        });

        btExcel.setText("Excel");
        btExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txSku, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btFiltro)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btExcel))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txRutProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(btRut, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addComponent(btRut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txSku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btFiltro)
                        .addComponent(dtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btExcel))
                    .addComponent(txRutProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProveedorActionPerformed
        
        ComboCodigos proveedor = (ComboCodigos) cbProveedor.getSelectedItem() ;
             
        if (cbProveedor.getSelectedItem()!= null){
            id_proveedor = proveedor.getId();
            txRutProveedor.setText(String.valueOf(id_proveedor).trim());
            
            if (Predeterminados.contains(String.valueOf(id_proveedor).trim()) && inicio>=1)
            {
                if(fmMain.OkCancel(cbProveedor.getSelectedItem().toString().trim()+" ya esta en el listado, desea quitarlo?")== JOptionPane.OK_OPTION){
                Predeterminados = Predeterminados.replace(String.valueOf(id_proveedor).trim()+",", "");
                txRutProveedor.setText("");
                }
            }
            inicio++;
            //CargaGrilla();
            CargaGrillaAgrupados();
        }
        
    }//GEN-LAST:event_cbProveedorActionPerformed

    private void btFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFiltroActionPerformed
        
        TableRowSorter<TableModel>sorter = new TableRowSorter<TableModel>(Agrupados.getModel());
        Agrupados.setRowSorter(sorter);
        
        String sku = txSku.getText().trim();
        if (sku.length()==0)
        {
            sorter.setRowFilter(null);
        }
        else{
            int cant=0;
            int ev=0;
            String precio="";
            sorter.setRowFilter(RowFilter.regexFilter(sku));
            for(int i = 0; i < Agrupados.getRowCount(); i++)
                {
                cant = cant +Integer.parseInt(Agrupados.getValueAt(i, 7)+"");
                ev = ev+Integer.parseInt(Agrupados.getValueAt(i, 8)+"");
                precio = Agrupados.getValueAt(i, 3)+"";
                }
//            lbCantidad.setText("CANTIDAD: "+cant);
//            lbEventos.setText("EVENTOS: "+ev);
//            lbPrecio.setText("PRECIO: "+precio);
        }
    }//GEN-LAST:event_btFiltroActionPerformed

    private void AgrupadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgrupadosMouseClicked
         if(evt.getClickCount()==2){
            
            if(evt.isAltDown())
                {
                pfProductos Pro = new pfProductos();
                Pro.setOpaque(false);
                pnPestanas.addTab("Producto", Pro);
                PanelTab btc = new PanelTab(pnPestanas, 0);
                pnPestanas.setTabComponentAt(pnPestanas.indexOfComponent(Pro), btc);
                pnPestanas.setSelectedIndex(pnPestanas.getTabCount() - 1);
                Pro.txSku.requestFocus();
                Pro.CargaProducto(Agrupados.getValueAt(Agrupados.getSelectedRow(), 1).toString()); 
                }
            
            else{
              if(Agrupados.getValueAt(Agrupados.getSelectedRow(), 1)!=null)
                {
                       txSku.setText(Agrupados.getValueAt(Agrupados.getSelectedRow(), 1).toString().trim());
                       btFiltro.doClick();
                }
            }
         }
    }//GEN-LAST:event_AgrupadosMouseClicked

    private void btRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRutActionPerformed
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
            try{
                String Qy="select rut,nombre from proveedor where rut="+txRutProveedor.getText().trim()+"\n" +
                    "order by nombre";
                Rs = Sql.Select(Qy);
                
                if(Rs.next())
                    {
                    cbProveedor.getModel().setSelectedItem(Rs.getString("nombre").trim());
                    }
        }
        catch (Exception e){
            fmMain.Mensaje("El rut no existe - "+e);
        }
         finally{
            Sql.Close();
        }
   
    }//GEN-LAST:event_btRutActionPerformed

    private void dtHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtHastaActionPerformed
        
            CargaGrillaAgrupados();
        
    }//GEN-LAST:event_dtHastaActionPerformed

    private void dtDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtDesdeActionPerformed
                    CargaGrillaAgrupados();
        
    }//GEN-LAST:event_dtDesdeActionPerformed

    private void txSkuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSkuKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                //btIr.doClick();     
                btFiltro.doClick();
              } 
    }//GEN-LAST:event_txSkuKeyPressed

    private void btExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcelActionPerformed
        String nombre = "Ventas x SKU - Proveedor";    
        
        if(Agrupados.getRowCount()==0){
            fmMain.Mensaje("Nada que exportar");
            return;
        }

//        JFileChooser chooser = new JFileChooser();
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo Excel",".xls");
//        chooser.setFileFilter(filter);
//        chooser.setDialogTitle("Guardar Informe en Excel");
//        chooser.setMultiSelectionEnabled(false);
//        chooser.setAcceptAllFileFilterUsed(false);


            List<JTable> tb=new ArrayList<>();
            List<String> nom=new ArrayList<>();
            tb.add(Agrupados);
                     
          
          
            nom.add(nombre);
            
            File folder = new File("c:/temp");
            if (!folder.exists())
            {
                folder.mkdir();
            }
            
             String file = "C:/temp/" + nombre + ".xls";       
            
            
            try {
                Exporter e = new Exporter(new File(file), tb, nom);
                
                if(e.export())
                //fmMain.Mensaje("Datos Exportados");
                abrir(file);
                
            } catch (Exception e) {
                fmMain.Mensaje(e.getMessage());
            }
    }//GEN-LAST:event_btExcelActionPerformed

//    public void CargaGrilla(){
//        ExeSql Sql = new ExeSql();
//        ResultSet Rs;
//        
//        try{
//            String Qry = "select case when cc.idch is null then '-' else cc.idch end, o.sku, case when cb.codbar is null then '-' else cb.codbar end, \n" +
//                        "p.nombre, p.valultcompra,  i.stock, (extract (month from (cast (o.fecha_insert as date)))) as mes, \n" +
//                        "(extract (year from (cast (o.fecha_insert as date)))) as agno, o.cantidad from occhdet o \n" +
//                        "left join producto p on o.sku=p.sku \n" +
//                        "left join codchile cc on o.sku=cc.sku \n" +
//                        "left join inventario i on o.sku=i.sku \n" +
//                        "left join codbar cb on o.sku=cb.sku and cb.rutprv=96726970 \n" +
//                        "where o.sku in (select sku from ctacteprvdet d \n" +
//                        " where d.rut="+txRutProveedor.getText().trim()+" and d.tipdocto='OCP')  and o.fecha_insert between '2017-09-01 00:00' and '2018-02-28 23:59' \n"+
//                        " order by agno, mes";
//            
//            Rs = Sql.Select(Qry);
//            
//            DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
//            while(TableModel.getRowCount()>0)
//                TableModel.removeRow(0);   
//            
//            while(Rs.next()){
//                TableModel.addRow(new Object[]{Rs.getString("idch").trim(), 
//                                               Rs.getString("sku").trim(), 
//                                               Rs.getString("codbar"),
//                                               Rs.getString("nombre"),
//                                               Rs.getString("valultcompra"),
//                                               Rs.getString("stock"),
//                                               Rs.getString("mes"),
//                                               Rs.getString("agno"),
//                                               Rs.getString("cantidad"),
//                                               });
//                
//            }
//            
//        }
//        catch (Exception e){
//            fmMain.Mensaje("Error al cargar detalle: "+e);
//        }
//        finally{
//            Sql.Close();
//        }
//    }
    
    public void CargaGrillaAgrupados(){
        ExeSql Sql = new ExeSql();
        ExeSql Sql2 = new ExeSql();
        ResultSet Rs, Rs2;
        
        try{
              
            String des = getDesde();
            String has = getHasta();   
            
                        
            if (!txRutProveedor.getText().trim().equals(""))
                {
                  if (!Predeterminados.contains(txRutProveedor.getText().trim()))
                    {
                Predeterminados = Predeterminados+","+txRutProveedor.getText().trim();
                     }   
                }
            
            String Qry = "select p.rut, p.nombre from proveedor p \n" +
                        "where p.rut in ("+Predeterminados+")\n" +
                        "group by p.rut, p.nombre order by p.nombre";
                       
                                   
            Rs = Sql.Select(Qry);
            
            DefaultTableModel TableModel = (DefaultTableModel) Agrupados.getModel();
            while(TableModel.getRowCount()>0)
                TableModel.removeRow(0);  
            
            String agno_desde= des.substring(0,4);
            String agno_hasta= has.substring(0,4);
            
            String mes_desde= des.substring(5,7);
            String mes_hasta= has.substring(5,7);
            
            int agno_desde_numerico = Integer.valueOf(agno_desde);
            int agno_hasta_numerico = Integer.valueOf(agno_hasta);
            
            int mes_desde_numerico = Integer.valueOf(mes_desde);
            int mes_hasta_numerico = Integer.valueOf(mes_hasta);
            
            System.out.println("Desde: "+mes_desde_numerico);
            System.out.println("Hasta: "+agno_hasta+mes_hasta);
            
            int columnas=0;
            int filas=0;
           TableModel.setColumnCount(2);
            if (Integer.valueOf(agno_desde+mes_desde)<Integer.valueOf(agno_hasta+mes_hasta))
                {   
                    while (agno_desde_numerico < agno_hasta_numerico)
                        {
                        for(int x=mes_desde_numerico; x<=12; x++)
                            {
                            TableModel.addColumn(x+"-"+agno_desde);
                            columnas++;
                            }
                        agno_desde_numerico++;
                        mes_desde_numerico=1;
                         }
                    
                     if (agno_desde_numerico == agno_hasta_numerico)
                        {
                            
                        for(int x=mes_desde_numerico; x<=mes_hasta_numerico; x++)
                            {
                            TableModel.addColumn(x+"-"+agno_hasta);
                            columnas++;
                            }
                        }
                 TableModel.addColumn("TOTAL");                      
                }
            
            while(Rs.next()){
                
                TableModel.addRow(new Object[]{Rs.getString("rut").trim(), 
                                               Rs.getString("nombre").trim(), 
                                               });
                if (columnas >0)
                    {
                                     
                    Rs2 = Sql2.Select("select sum (c.totalafecto) as monto, \n" +
                                    "(extract (month from (cast (c.femision as date)))) || '-' ||(extract (year from (cast (c.femision as date)))) as fe_cha from ctacteprv c \n" +
                                    "left join proveedor p on c.rut=p.rut \n" +
                                    "where c.tipdocto='OCP' and c.rut="+ Rs.getString("rut").trim()+" \n" +
                                    "and c.femision between '"+des+"' and '"+has+"' \n" +
                                    "group by c.rut, p.nombre, fe_cha");
                    int cantidad=0;
                    int eventos=0;
                    String cantidad_s ="";
                    String eventos_s = "";
                    while (Rs2.next())
                        {
                            
                            String fecha_columna = Rs2.getString("fe_cha");
                             for (int z=2; z<=1+columnas;z++)
                                {
                                    if (fecha_columna.equals(Agrupados.getColumnName(z)))
                                            {
                                            TableModel.setValueAt(Rs2.getString("monto"), filas, z);
                                                                                       
                                            cantidad = cantidad + Rs2.getInt("monto");
                                              
                                            
                                            }
                                }
                              TableModel.setValueAt(cantidad, filas, 2+columnas);
                        }

                       
                    }
                filas++;
            }
            
            
        }
        catch (Exception e){
            fmMain.Mensaje("Error al cargar Agrupacion: "+e);
        }
        finally{
            Sql.Close();
        }
    }

     public String getDesde() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd 00:00");
        return( sdf.format( (dtDesde.getDate()).getTime() ) );
    }
    public String getHasta() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd 23:59");
        return( sdf.format( (dtHasta.getDate()).getTime() ) );
    }
    
     public void abrir(String file ){
        
       try {
           String url = file;
           ProcessBuilder p = new ProcessBuilder();
           p.command("cmd.exe", "/c",url);
           p.start();
       } catch (IOException ex) {
           Logger.getLogger(jdOC_PendientesFac.class.getName()).log(Level.SEVERE, null, ex);
       }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Agrupados;
    private javax.swing.JButton btExcel;
    private javax.swing.JButton btFiltro;
    private javax.swing.JButton btRut;
    private javax.swing.JComboBox<String> cbProveedor;
    private org.jdesktop.swingx.JXDatePicker dtDesde;
    private org.jdesktop.swingx.JXDatePicker dtHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txRutProveedor;
    private javax.swing.JTextField txSku;
    // End of variables declaration//GEN-END:variables
}
