/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import java.sql.ResultSet;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David Alcaman
 */
public class pfConta_Movimientos extends javax.swing.JPanel {
    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();    
    /**
     * Creates new form pfMovimientosContables
     */
    public pfConta_Movimientos() {
        initComponents();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        Grilla.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
        Grilla.getColumnModel().getColumn(6).setCellRenderer(rightRenderer);
        CargaMovimientos();
    }
    private void CargaMovimientos(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel Model = (DefaultTableModel) Grilla.getModel();
        String LastGlosa="";
        int LastFolio=0;
        String Folio;
        String Glosa;
        String Fecha;
        
        while(Model.getRowCount()>0)
              Model.removeRow(0);
        
        try {
            Rs = Sql.Select("select cast(a.fecha as date) as fecha, a.folio,a.glosa,p.nombre,d.debe,d.haber\n" +
                            "from conta_asientodiario a \n" +
                            "left join conta_asientodiariodet d on a.folio=d.folio\n" +
                            "left join conta_plan p on d.cuenta=p.codigo order by a.folio");
            while(Rs.next()){
                if(!LastGlosa.equals(Rs.getString("glosa"))){
                    
                    LastGlosa=Rs.getString("Glosa");
                    Glosa = Rs.getString("Glosa");
                    Fecha = Rs.getDate("fecha").toString().trim();
                }
                else{
                    Folio = "";
                    Glosa = "";
                    Fecha = "";
                    }
                if(LastFolio != Rs.getInt("Folio")){
                    Folio=Rs.getString("Folio");
                    LastFolio = Rs.getInt("Folio");
                }
                else
                    Folio = "";
                    
                    
                if(Rs.getInt("debe")>0)
                Model.addRow(new Object[]{
                                        Fecha,
                                        Glosa,
                                        Folio,
                                        Rs.getString("nombre").trim(),
                                        "",
                                        Rs.getInt("debe"),
                                        ""
                                        });
                else
                    Model.addRow(new Object[]{
                                        Fecha,    
                                        Glosa,
                                        Folio,
                                        "",
                                        Rs.getString("nombre").trim(), "",
                                        Rs.getInt("haber"),
                                        });
            }
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally{
            Sql.Close();
        }
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();

        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Glosa", "Folio", "Cuenta Debe", "Cuenta Haber", "Debe", "Haber"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.setGridColor(new java.awt.Color(0, 0, 102));
        jScrollPane1.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(0).setMinWidth(75);
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(75);
            Grilla.getColumnModel().getColumn(0).setMaxWidth(75);
            Grilla.getColumnModel().getColumn(1).setMinWidth(300);
            Grilla.getColumnModel().getColumn(1).setPreferredWidth(300);
            Grilla.getColumnModel().getColumn(1).setMaxWidth(300);
            Grilla.getColumnModel().getColumn(2).setMinWidth(75);
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(75);
            Grilla.getColumnModel().getColumn(2).setMaxWidth(75);
            Grilla.getColumnModel().getColumn(5).setMinWidth(80);
            Grilla.getColumnModel().getColumn(5).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(5).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(6).setMinWidth(80);
            Grilla.getColumnModel().getColumn(6).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(6).setMaxWidth(80);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 995, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
