/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Dialogos.jdAbrirCartola;
import Dialogos.jdProtestos;
import Formularios.fmMain;
import static Formularios.fmMain.pnPestanas;
import Utilidades.PanelTab; 
import java.awt.Color;
import java.awt.Font;
import java.net.URL;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David Alcaman
 */
public class pfCXC_CartolaAbonos extends javax.swing.JPanel {
    private boolean Cargando;
    JTable Tabla = new JTable();
    DefaultTableModel Modelo = new DefaultTableModel();
    int MontoBuscado;
    int bandera = 0;

    /**
     * Creates new form pfCXC_CartolaAbonos
     */
    public pfCXC_CartolaAbonos() {
        initComponents();
        CargaProtestos();
        btDetenHilo.setEnabled(false);
        CargaBancos();
        cbBancoId.setVisible(false);
        cbCuentaId.setVisible(false);
        Tabla.setModel(Modelo);
        Modelo.addColumn("Factura");
        Modelo.addColumn("Monto");
        Grilla.getTableHeader().setFont(new Font("Arial", Font.BOLD, 10));
        GrillaRelacion.getTableHeader().setFont(new Font("Arial", Font.BOLD, 10));
        Grilla.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            //Se ejecuta automáticamente cada vez que se hace una nueva selección. 
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(Grilla.getSelectedRowCount()>0 && (Boolean)Grilla.getValueAt(Grilla.getSelectedRow(), 7)==true){
                    btRelaciones.setEnabled(false);
                    btPagar.setEnabled(false);
                    btLiberar.setEnabled(true);
                    CargaDocPagados();
                }
                else if(Grilla.getSelectedRowCount()>0 && (Boolean)Grilla.getValueAt(Grilla.getSelectedRow(), 7)==false){
                    btRelaciones.setEnabled(true);
                    btPagar.setEnabled(false);
                    btLiberar.setEnabled(false);
                    fmMain.LimpiaGrilla((DefaultTableModel)GrillaRelacion.getModel());
                }
                    
                    
            }

        });
        GrillaRelacion.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            //Se ejecuta automáticamente cada vez que se hace una nueva selección. 
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if((Boolean)Grilla.getValueAt(Grilla.getSelectedRow(), 7)==false && 
                        Grilla.getSelectedRowCount()>0 && 
                        GrillaRelacion.getSelectedRowCount()>0){
                    btPagar.setEnabled(true);
                }
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        MnuIndividual = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        MesFecha = new org.jdesktop.swingx.JXMonthView();
        chkFecha = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();
        lbFacturasRelacionadas = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        GrillaRelacion = new javax.swing.JTable();
        btBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cbBanco = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbCuenta = new javax.swing.JComboBox();
        cbBancoId = new javax.swing.JComboBox();
        cbCuentaId = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        rbPagadas = new javax.swing.JRadioButton();
        rbLibres = new javax.swing.JRadioButton();
        rbTodas = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        btRelaciones = new javax.swing.JButton();
        rbIndividual = new javax.swing.JRadioButton();
        rbGrupal = new javax.swing.JRadioButton();
        btDetenHilo = new javax.swing.JButton();
        rbEspecifica = new javax.swing.JRadioButton();
        txEspecifica = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btPagar = new javax.swing.JButton();
        btLiberar = new javax.swing.JButton();
        btProtestos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Peso16.png"))); // NOI18N
        jMenuItem2.setText("Pagar");
        jPopupMenu2.add(jMenuItem2);

        jMenuItem3.setText("Ver Detalles");
        jPopupMenu2.add(jMenuItem3);

        MnuIndividual.setText("jMenuItem1");
        jPopupMenu1.add(MnuIndividual);

        jMenuItem4.setText("jMenuItem4");
        jPopupMenu1.add(jMenuItem4);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        MesFecha.setAutoscrolls(true);
        MesFecha.setEnabled(false);
        MesFecha.setTraversable(true);
        MesFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesFechaActionPerformed(evt);
            }
        });

        chkFecha.setText("Fecha");
        chkFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkFecha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(MesFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MesFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        Grilla.setAutoCreateRowSorter(true);
        Grilla.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Banco", "FECHA", "OFICINA", "NUMERO", "DETALLE", "$ Cargo", "$ ABONO", "Asoc.", "id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.setAutoscrolls(false);
        Grilla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(0).setMinWidth(0);
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(0).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(1).setMinWidth(75);
            Grilla.getColumnModel().getColumn(1).setPreferredWidth(75);
            Grilla.getColumnModel().getColumn(1).setMaxWidth(75);
            Grilla.getColumnModel().getColumn(2).setMinWidth(200);
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(200);
            Grilla.getColumnModel().getColumn(2).setMaxWidth(200);
            Grilla.getColumnModel().getColumn(3).setMinWidth(85);
            Grilla.getColumnModel().getColumn(3).setPreferredWidth(85);
            Grilla.getColumnModel().getColumn(3).setMaxWidth(85);
            Grilla.getColumnModel().getColumn(5).setMinWidth(0);
            Grilla.getColumnModel().getColumn(5).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(5).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(6).setMinWidth(90);
            Grilla.getColumnModel().getColumn(6).setPreferredWidth(90);
            Grilla.getColumnModel().getColumn(6).setMaxWidth(90);
            Grilla.getColumnModel().getColumn(7).setMinWidth(50);
            Grilla.getColumnModel().getColumn(7).setPreferredWidth(50);
            Grilla.getColumnModel().getColumn(7).setMaxWidth(50);
            Grilla.getColumnModel().getColumn(8).setMinWidth(0);
            Grilla.getColumnModel().getColumn(8).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(8).setMaxWidth(0);
        }

        lbFacturasRelacionadas.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lbFacturasRelacionadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFacturasRelacionadas.setText("FACTURAS RELACIONADAS");
        lbFacturasRelacionadas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        GrillaRelacion.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        GrillaRelacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ESTADO", "RUT", "CLIENTE", "CODIGO OC", "FACTURA(S)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(GrillaRelacion);
        if (GrillaRelacion.getColumnModel().getColumnCount() > 0) {
            GrillaRelacion.getColumnModel().getColumn(0).setMinWidth(90);
            GrillaRelacion.getColumnModel().getColumn(0).setPreferredWidth(90);
            GrillaRelacion.getColumnModel().getColumn(0).setMaxWidth(90);
            GrillaRelacion.getColumnModel().getColumn(1).setMinWidth(90);
            GrillaRelacion.getColumnModel().getColumn(1).setPreferredWidth(90);
            GrillaRelacion.getColumnModel().getColumn(1).setMaxWidth(90);
            GrillaRelacion.getColumnModel().getColumn(2).setMinWidth(300);
            GrillaRelacion.getColumnModel().getColumn(2).setPreferredWidth(300);
            GrillaRelacion.getColumnModel().getColumn(2).setMaxWidth(500);
            GrillaRelacion.getColumnModel().getColumn(3).setMinWidth(70);
            GrillaRelacion.getColumnModel().getColumn(3).setPreferredWidth(70);
            GrillaRelacion.getColumnModel().getColumn(3).setMaxWidth(90);
            GrillaRelacion.getColumnModel().getColumn(4).setMinWidth(150);
            GrillaRelacion.getColumnModel().getColumn(4).setPreferredWidth(150);
        }

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/search.png"))); // NOI18N
        btBuscar.setText("   BUSCAR");
        btBuscar.setEnabled(false);
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbBanco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBancoActionPerformed(evt);
            }
        });

        jLabel1.setText("Banco");

        jLabel2.setText("Cuenta");

        cbCuenta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCuenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbCuentaFocusLost(evt);
            }
        });
        cbCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCuentaMouseClicked(evt);
            }
        });
        cbCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCuentaActionPerformed(evt);
            }
        });

        cbBancoId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbCuentaId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cbBancoId, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbCuentaId, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbBanco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbCuenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBancoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCuentaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(rbPagadas);
        rbPagadas.setText("Pagados");

        buttonGroup1.add(rbLibres);
        rbLibres.setSelected(true);
        rbLibres.setText("Libres");

        buttonGroup1.add(rbTodas);
        rbTodas.setText("Todos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbLibres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(rbPagadas)
                .addGap(18, 18, 18)
                .addComponent(rbTodas)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPagadas)
                    .addComponent(rbTodas)
                    .addComponent(rbLibres))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "FACTURAS RELACIONADAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        btRelaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/search16.png"))); // NOI18N
        btRelaciones.setText("Buscar Relación");
        btRelaciones.setEnabled(false);
        btRelaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelacionesActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbIndividual);
        rbIndividual.setSelected(true);
        rbIndividual.setText("Individual");
        rbIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIndividualActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbGrupal);
        rbGrupal.setText("Grupal");
        rbGrupal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGrupalActionPerformed(evt);
            }
        });

        btDetenHilo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/disable16.png"))); // NOI18N
        btDetenHilo.setText("Detener Busqueda");
        btDetenHilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDetenHiloActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbEspecifica);
        rbEspecifica.setText("Especifica");
        rbEspecifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEspecificaActionPerformed(evt);
            }
        });

        txEspecifica.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txEspecifica.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbIndividual)
                    .addComponent(rbGrupal)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rbEspecifica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txEspecifica, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btRelaciones)
                .addGap(26, 26, 26)
                .addComponent(btDetenHilo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDetenHilo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRelaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(rbIndividual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbGrupal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEspecifica)
                    .addComponent(txEspecifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PAGOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        btPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Peso16.png"))); // NOI18N
        btPagar.setText("Pagar");
        btPagar.setEnabled(false);
        btPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPagarActionPerformed(evt);
            }
        });

        btLiberar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/erase16.png"))); // NOI18N
        btLiberar.setText("Liberar");
        btLiberar.setEnabled(false);
        btLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLiberarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btLiberar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btLiberar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btProtestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cheque.png"))); // NOI18N
        btProtestos.setText("CHEQUES PROTESTADOS");
        btProtestos.setEnabled(false);
        btProtestos.setPreferredSize(new java.awt.Dimension(191, 31));
        btProtestos.setRequestFocusEnabled(false);
        btProtestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProtestosActionPerformed(evt);
            }
        });

        jButton1.setText("Abrir Cartola");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btProtestos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3)
                    .addComponent(lbFacturasRelacionadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btProtestos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(lbFacturasRelacionadas, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBancoActionPerformed
        if(!Cargando){
            cbBancoId.setSelectedIndex(cbBanco.getSelectedIndex());
            CargaCuentas();
        }
    

    }//GEN-LAST:event_cbBancoActionPerformed
    private void CargaDocPagados(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel Model = (DefaultTableModel) GrillaRelacion.getModel();
        String Facturas="";
        
        fmMain.LimpiaGrilla(Model);
        try {
            Rs = Sql.Select("select c.rut,c.nombre,cxc.codigo_oc,cxc.nrodocto\n" +
                            "from cli_pagos p\n" +
                            "left join cli_cuentasxcobrar cxc on p.cuenta=cxc.id\n" +
                            "left join cliente c on cxc.rut=c.rut \n" +
                            "where p.id_cartola=" + Grilla.getValueAt(Grilla.getSelectedRow(),8).toString().trim());
            if(Sql.GetRowCount()>0){
                while(Rs.next()){
                    Facturas = Facturas + Rs.getString("nrodocto") + " - ";
                }
                Rs.first();
                Facturas = Facturas.substring(0, Facturas.length()-2);
                Model.addRow(new Object[] {
                        "PAGADO",
                        Rs.getString("rut").trim(),
                        Rs.getString("nombre").trim(),
                        Rs.getString("codigo_oc").trim(),
                        Facturas
                });
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally{
            Sql.Close();
        }
    }
    
    private void CargaCuentas(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        
        cbCuenta.removeAllItems();
        cbCuentaId.removeAllItems();
        
        try {
            Rs = Sql.Select("select id,cuenta\n" +
                            "from bco_cuentas \n" +
                            "where banco="+ cbBancoId.getSelectedItem().toString().trim() +"\n" +
                            "and cxc=true");
            if(Sql.GetRowCount()>0)
                btBuscar.setEnabled(true);
            else
                btBuscar.setEnabled(false);
            
            while(Rs.next()){
                cbCuentaId.addItem(Rs.getString("id"));
                cbCuenta.addItem(Rs.getString("cuenta"));
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally{
            Sql.Close();
        }
    }
    private void CargaCartola(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel Model = (DefaultTableModel) Grilla.getModel();
        DefaultTableModel ModelRel = (DefaultTableModel) GrillaRelacion.getModel();
        fmMain.LimpiaGrilla(Model);
        fmMain.LimpiaGrilla(ModelRel);
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String Query="";
        
        if(cbBanco.getSelectedIndex()<0){
            fmMain.Mensaje("Debe seleccionar un BANCO");
            return;
        }
        
        Query = "select ba.nombre, ca.fecha,ca.oficina,ca.nrodocumento,ca.detalle,ca.cargo,ca.abono,ca.id,ca.asociado\n" +
                "from bco_cartola ca\n" +
                "left join bco_cuentas cu on ca.cuenta=cu.id\n" +
                "left join bco_bancos ba on ba.id = cu.banco\n" + 
                "where cu.id=" + cbCuentaId.getSelectedItem().toString().trim() + "\n" ;
        
        if(rbLibres.isSelected())
            Query = Query + "and asociado = false \n";
        if(rbPagadas.isSelected())
            Query = Query + "and asociado = true \n";
                
        if(chkFecha.isSelected())
            Query = Query + 
                    "and fecha=cast('"+ sdf.format(MesFecha.getSelectionDate()) +"' as date) \n"; 
        Query = Query + "and ca.abono>0";

        try {
            
            Rs = Sql.Select(Query);
            
            while(Rs.next()){
                Model.addRow(new Object[]{
                                Rs.getString("Nombre").trim(),
                                Rs.getString("Fecha").trim(),
                                Rs.getString("Oficina").trim(),
                                Rs.getString("nrodocumento").trim(),
                                Rs.getString("detalle").trim(),
                                Rs.getInt("Cargo"),
                                Rs.getInt("abono"),
                                Rs.getBoolean("asociado"),
                                Rs.getInt("id")
                });
            }
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally{
            Sql.Close();
        }
    }
    private void MesFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesFechaActionPerformed
        CargaCartola();
    }//GEN-LAST:event_MesFechaActionPerformed
    private void CargaBancos(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        
        cbBanco.removeAllItems();
        cbBancoId.removeAllItems();
        
        try {
            Rs = Sql.Select("select id,nombre\n" +
                            "from bco_bancos where id>0\n" +
                            "order by id");
            while(Rs.next()){
                cbBancoId.addItem(Rs.getInt("id"));
                cbBanco.addItem(Rs.getString("nombre"));
            }
            cbBanco.setSelectedIndex(-1);
            cbBancoId.setSelectedIndex(-1);
        } catch (Exception e) {
            fmMain.Mensaje("Error");
        } finally{
            Sql.Close();
        }
    }
    private void chkFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFechaActionPerformed
        if(chkFecha.isSelected())
            MesFecha.setEnabled(true);
        else
            MesFecha.setEnabled(false);
    }//GEN-LAST:event_chkFechaActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
              CargaCartola();
    }//GEN-LAST:event_btBuscarActionPerformed
    private void BuscarGrupal(){
        MontoBuscado = (Integer) Grilla.getValueAt(Grilla.getSelectedRow(), 6);
        Runnable miRunnable = new Runnable() {
            public void run() {
                try{
                        CargaRelacion();
                        
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        };
        Thread hilo = new Thread(miRunnable);
        hilo.start();
        lbFacturasRelacionadas.setText("CARGANDO  -  CARGANDO  -  CARGANDO  -  CARGANDO ");
        URL urlInfo =  this.getClass().getResource("/Iconos16/wait.gif");
        ImageIcon IconoInfo =  new ImageIcon(urlInfo); 
        lbFacturasRelacionadas.setIcon(IconoInfo);
        lbFacturasRelacionadas.setForeground(Color.red);
        Grilla.setEnabled(false);
    }
    private void BuscarIndividual(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel ModeloRelacion = (DefaultTableModel) GrillaRelacion.getModel();
        
        while(ModeloRelacion.getRowCount()>0)
              ModeloRelacion.removeRow(0);
        
        try {
            Rs = Sql.Select("select cxc.rut,c.nombre,cxc.codigo_oc,cxc.nrodocto,cxc.monto-cxc.pagado as saldo \n" +
                            "from cli_cuentasxcobrar cxc\n" +
                            "left join cliente c on c.rut=cxc.rut\n" +
                            "where cxc.estado <>3\n" +
                            "and cxc.monto-cxc.pagado BETWEEN  "+ (Integer) Grilla.getValueAt(Grilla.getSelectedRow(), 6) +" -1 AND "+ (Integer) Grilla.getValueAt(Grilla.getSelectedRow(), 6) +"  + 1\n" +
                            "and cxc.codigo_oc>=1\n" +
                            "order by cxc.rut,cxc.codigo_oc,saldo asc");
            
            while(Rs.next()){
                ModeloRelacion.addRow(new Object[]{"PENDIENTE", Rs.getString("Rut").trim(),Rs.getString("nombre").trim(),Rs.getString("Codigo_Oc").trim(),Rs.getInt("nrodocto")});
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally{
            Sql.Close();
        }
      
    }
    
    private void BuscarEspecifica(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel ModeloRelacion = (DefaultTableModel) GrillaRelacion.getModel();
        
        while(ModeloRelacion.getRowCount()>0)
              ModeloRelacion.removeRow(0);
        
        try {
            Rs = Sql.Select("select cxc.rut,c.nombre,cxc.codigo_oc, string_agg(to_char(cxc.nrodocto, '99999999'), ',') as nrodoctos ,sum(cxc.monto-cxc.pagado) as saldo  \n" +
                            "from cli_cuentasxcobrar cxc\n" +
                            "left join cliente c on c.rut=cxc.rut\n" +
                            "where cxc.estado <>3\n" +
                            "and cxc.nrodocto in ("+txEspecifica.getText().trim()+") \n" +
                            "and cxc.codigo_oc>=1\n" +
                            "group by cxc.rut,c.nombre,cxc.codigo_oc");
            
            while(Rs.next()){
                ModeloRelacion.addRow(new Object[]{"PENDIENTE", Rs.getString("Rut").trim(),Rs.getString("nombre").trim(),Rs.getString("Codigo_Oc").trim(),Rs.getString("nrodoctos").replaceAll("\\s+","")});
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally{
            Sql.Close();
        }
      
    }
    
    private void btRelacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelacionesActionPerformed
        if(rbGrupal.isSelected()){
            BuscarGrupal();
        }
        else if(rbEspecifica.isSelected()){
            BuscarEspecifica();
        }
        else{
            BuscarIndividual();
        }
    }//GEN-LAST:event_btRelacionesActionPerformed

    private void btPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPagarActionPerformed
        pfCLI_EstadoCXC CxC = new pfCLI_EstadoCXC();
        CxC.CargaFacturas(GrillaRelacion.getValueAt(GrillaRelacion.getSelectedRow(), 1).toString().trim(),
                GrillaRelacion.getValueAt(GrillaRelacion.getSelectedRow(), 3).toString().trim(),
                GrillaRelacion.getValueAt(GrillaRelacion.getSelectedRow(), 4).toString().trim(), (Integer) Grilla.getValueAt(Grilla.getSelectedRow(), 8));

        pnPestanas.addTab("Cuentas por Cobrar", CxC);
        PanelTab btc = new PanelTab(pnPestanas, 0);
        pnPestanas.setTabComponentAt(pnPestanas.indexOfComponent(CxC), btc);
        pnPestanas.setSelectedIndex(pnPestanas.getTabCount() - 1);
        if(rbEspecifica.isSelected()){
            CxC.chkAutorizacion.setSelected(true);
        }
    }//GEN-LAST:event_btPagarActionPerformed

    private void btLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLiberarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLiberarActionPerformed

    private void btDetenHiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDetenHiloActionPerformed
                 bandera = 1;
                 System.out.println("HILO CERRADO");
                 btBuscar.setEnabled(true);
    }//GEN-LAST:event_btDetenHiloActionPerformed

    private void btProtestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProtestosActionPerformed
        jdProtestos Protesto = new jdProtestos(null, true);
        Protesto.setLocationRelativeTo(null);
        Protesto.setTitle("Cheques Protestados");
        Protesto.setVisible(true);
        
    }//GEN-LAST:event_btProtestosActionPerformed

    private void rbEspecificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEspecificaActionPerformed
        txEspecifica.setEnabled(true);
    }//GEN-LAST:event_rbEspecificaActionPerformed

    private void rbGrupalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGrupalActionPerformed
        txEspecifica.setText("");
        txEspecifica.setEnabled(false);
    }//GEN-LAST:event_rbGrupalActionPerformed

    private void rbIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIndividualActionPerformed
        txEspecifica.setText("");
        txEspecifica.setEnabled(false);
    }//GEN-LAST:event_rbIndividualActionPerformed

    private void cbCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCuentaActionPerformed
        // TODO add your handling code here:
           
    }//GEN-LAST:event_cbCuentaActionPerformed

    private void cbCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCuentaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCuentaMouseClicked

    private void cbCuentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbCuentaFocusLost
        // TODO add your handling code here:
         cbCuentaId.setSelectedIndex(cbCuenta.getSelectedIndex());
    }//GEN-LAST:event_cbCuentaFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        jdAbrirCartola Cartola = new jdAbrirCartola(null, true);
        Cartola.setLocationRelativeTo(null);
        Cartola.setTitle("Cartolas");
        Cartola.setVisible(true);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    
    private String Funcion(int Suma, int Indice, int Monto ){
        String Retorno="";
        for (int i = Indice; i < Tabla.getRowCount(); i++) {
            if((Integer) Tabla.getValueAt(i, 1) > Monto && bandera==0)
                return "";
            
            else if( (Integer) Tabla.getValueAt(i, 1)  + Suma == Monto && bandera==0){
                return Tabla.getValueAt(i, 0).toString().trim();
            }
            else if((Integer) Tabla.getValueAt(i, 1) + Suma < Monto && Indice<Tabla.getRowCount() && bandera==0){
                    Retorno=Funcion(Suma + (Integer) Tabla.getValueAt(i, 1),i+1,Monto);
                if(!Retorno.isEmpty() && bandera==0)
                    return Tabla.getValueAt(i, 0).toString().trim() + "," + Retorno;
            }
            
                
        }
        return "";
    }
    private void CargaRelacion(){
        btBuscar.setEnabled(false);
        btDetenHilo.setEnabled(true);
        bandera = 0;
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        String Rut="";
        String Nombre="";
        String Codigo_Oc="";
        String Facturas="";
        DefaultTableModel ModeloRelacion = (DefaultTableModel) GrillaRelacion.getModel();
        while(ModeloRelacion.getRowCount()>0)
              ModeloRelacion.removeRow(0);
                
        
        try {
            
            Rs = Sql.Select("select *\n" +
                            "from fn_cxc_search("+ MontoBuscado +")");
            
            while(Rs.next() && bandera==0){
                if(Codigo_Oc.isEmpty() && bandera==0){
                    Rut=Rs.getString("Rut").trim();
                    Nombre = Rs.getString("Nombre");
                    Codigo_Oc = Rs.getString("Codigo_Oc").trim();
                    while(Modelo.getRowCount()>0)
                        Modelo.removeRow(0);
                }
                
                if(!Codigo_Oc.equals(Rs.getString("Codigo_Oc").trim()) && bandera==0){
                    for(int i=0; i< Tabla.getRowCount() ;i ++){
                        Facturas = Funcion(0,i,MontoBuscado);
                        if(!Facturas.isEmpty())
                            //System.out.println(Rut + " " + Nombre + " " + Codigo_Oc + " *" + Facturas);
                            AgregaResultado(Rut,Nombre,Codigo_Oc,Facturas);
                    }
                    Rut=Rs.getString("Rut").trim();
                    Nombre = Rs.getString("Nombre");
                    Codigo_Oc = Rs.getString("Codigo_Oc").trim();
                    while(Modelo.getRowCount()>0 && bandera==0)
                        Modelo.removeRow(0);
                    Modelo.addRow(new Object[]{Rs.getInt("nrodocto"),Rs.getInt("Saldo")});
                }
                else{
                    Modelo.addRow(new Object[]{Rs.getInt("nrodocto"),Rs.getInt("Saldo")});
                }
            }
            for(int i=0; i< Tabla.getRowCount() ;i ++){
                        Facturas = Funcion(0,i,MontoBuscado);
                        if(!Facturas.isEmpty() && bandera==0)
                            AgregaResultado(Rut,Nombre,Codigo_Oc,Facturas);
                    }
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
           
        } finally{
            Sql.Close();
            btDetenHilo.setEnabled(false);
            lbFacturasRelacionadas.setIcon(null);
            lbFacturasRelacionadas.setText("FACTURAS RELACIONADAS");
            lbFacturasRelacionadas.setForeground(Color.black);
            Grilla.setEnabled(true);
        }
        
    }
    private void AgregaResultado(String Rut, String Nombre,String Codigo_Oc,String Facturas){
        boolean Existe=false;
        DefaultTableModel Model = (DefaultTableModel) GrillaRelacion.getModel();
        for (int i = 0; i < GrillaRelacion.getRowCount(); i++) {
            if(Facturas.equals(GrillaRelacion.getValueAt(i,4).toString().trim()))
                Existe=true;
        }
        if(!Existe){
            Model.addRow(new Object[]{"PENDIENTE",Rut,Nombre.trim(),Codigo_Oc,Facturas});
        }
        
    }
    
    private void CargaProtestos(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel ModeloRelacion = (DefaultTableModel) GrillaRelacion.getModel();
        
        while(ModeloRelacion.getRowCount()>0)
              ModeloRelacion.removeRow(0);
        
        try {
            Rs = Sql.Select("select count(id) as cuantos from bco_cartola where asociado=false and cargo>0 and abono=0 and detalle like '%Revers%' or detalle like '%PROTES%'");
            Rs.next();
            if (Rs.getInt("cuantos")>=1)
            {
            btProtestos.setEnabled(true);
            }
            else
            {
            btProtestos.setEnabled(false);   
            }
            
        } catch (Exception e) {
            fmMain.Mensaje("Error al cargar protestos: "+e);
        } finally{
            Sql.Close();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla;
    private javax.swing.JTable GrillaRelacion;
    private org.jdesktop.swingx.JXMonthView MesFecha;
    private javax.swing.JMenuItem MnuIndividual;
    private javax.swing.JButton btBuscar;
    public javax.swing.JButton btDetenHilo;
    private javax.swing.JButton btLiberar;
    private javax.swing.JButton btPagar;
    private javax.swing.JButton btProtestos;
    private javax.swing.JButton btRelaciones;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cbBanco;
    private javax.swing.JComboBox cbBancoId;
    private javax.swing.JComboBox cbCuenta;
    private javax.swing.JComboBox cbCuentaId;
    private javax.swing.JCheckBox chkFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbFacturasRelacionadas;
    private javax.swing.JRadioButton rbEspecifica;
    private javax.swing.JRadioButton rbGrupal;
    private javax.swing.JRadioButton rbIndividual;
    private javax.swing.JRadioButton rbLibres;
    private javax.swing.JRadioButton rbPagadas;
    private javax.swing.JRadioButton rbTodas;
    private javax.swing.JTextField txEspecifica;
    // End of variables declaration//GEN-END:variables
}
