/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Formularios.fmMain;
import Utilidades.ImgTabla;
import Utilidades.LogError;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.net.URL;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author David Alcaman
 */
public class pfOcchPortal extends javax.swing.JPanel {

    boolean Cargando;
    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();

    /**
     * Creates new form pfBco_Cartolas
     */
    public pfOcchPortal() {
        initComponents();
        Cargando = true;
        CargaBancos();
        Cargando = false;
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        Grilla.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        GrillaCompara.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
        GrillaTotales.getColumnModel().getColumn(1).setCellRenderer(rightRenderer);
        //Grilla.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
        //Grilla.getColumnModel().getColumn(6).setCellRenderer(rightRenderer);
        btCancelar.setVisible(false);
        btGuardar.setVisible(false);
        
        TxHistorial.setLineWrap(true);
        TxHistorial.setWrapStyleWord(true);
        jScrollPane5.setHorizontalScrollBarPolicy(HORIZONTAL_SCROLLBAR_NEVER);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Mes = new javax.swing.JLabel();
        cbMes = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cbAnio = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btCancelar = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();
        btNuevoIngreso = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Mes1 = new javax.swing.JLabel();
        cbMesCompara = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cbAnioCompara = new javax.swing.JComboBox();
        btCompara = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        GrillaCompara = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        GrillaTotales = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        GrillaBlog = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        TxHistorial = new javax.swing.JTextArea();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Fecha Ingreso"));

        Mes.setText("Mes");

        cbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        cbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesActionPerformed(evt);
            }
        });

        jLabel5.setText("Año");

        cbAnio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2017", "2018", "2019", "2020", "2021" }));
        cbAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAnioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(Mes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbMes, 0, 123, Short.MAX_VALUE)
                    .addComponent(cbAnio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mes))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        Grilla.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo OC", "Orden", "Tipo", "$ Total Orden"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.setAutoscrolls(false);
        jScrollPane1.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(0).setMinWidth(80);
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(0).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(1).setMinWidth(80);
            Grilla.getColumnModel().getColumn(1).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(1).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(2).setMinWidth(80);
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(2).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(3).setMinWidth(100);
            Grilla.getColumnModel().getColumn(3).setPreferredWidth(100);
            Grilla.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ingreso Ordenes"));

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Cancel16.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/ok_16.png"))); // NOI18N
        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        btNuevoIngreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/New.png"))); // NOI18N
        btNuevoIngreso.setText("Nuevo Ingreso");
        btNuevoIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoIngresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btCancelar)
                        .addGap(26, 26, 26)
                        .addComponent(btGuardar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btNuevoIngreso)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btNuevoIngreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btGuardar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Fecha Comparacion"));

        Mes1.setText("Mes");

        cbMesCompara.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        cbMesCompara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesComparaActionPerformed(evt);
            }
        });

        jLabel6.setText("Año");

        cbAnioCompara.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2017", "2018", "2019", "2020", "2021" }));
        cbAnioCompara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAnioComparaActionPerformed(evt);
            }
        });

        btCompara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/derecha16.png"))); // NOI18N
        btCompara.setText("Comparar");
        btCompara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComparaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(Mes1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbMesCompara, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbAnioCompara, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btCompara)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMesCompara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mes1))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAnioCompara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btCompara)
                .addContainerGap())
        );

        GrillaCompara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo OC", "Orden", "Diferencia"
            }
        ));
        GrillaCompara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaComparaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(GrillaCompara);
        if (GrillaCompara.getColumnModel().getColumnCount() > 0) {
            GrillaCompara.getColumnModel().getColumn(0).setMinWidth(100);
            GrillaCompara.getColumnModel().getColumn(0).setPreferredWidth(100);
            GrillaCompara.getColumnModel().getColumn(0).setMaxWidth(100);
            GrillaCompara.getColumnModel().getColumn(1).setMinWidth(100);
            GrillaCompara.getColumnModel().getColumn(1).setPreferredWidth(100);
            GrillaCompara.getColumnModel().getColumn(1).setMaxWidth(100);
            GrillaCompara.getColumnModel().getColumn(2).setMinWidth(100);
            GrillaCompara.getColumnModel().getColumn(2).setPreferredWidth(100);
            GrillaCompara.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        GrillaTotales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Convenio", "Total Venta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(GrillaTotales);
        if (GrillaTotales.getColumnModel().getColumnCount() > 0) {
            GrillaTotales.getColumnModel().getColumn(1).setMinWidth(90);
            GrillaTotales.getColumnModel().getColumn(1).setPreferredWidth(90);
            GrillaTotales.getColumnModel().getColumn(1).setMaxWidth(90);
        }

        jLabel1.setText("TOTAL :");

        lbTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTotal.setText("0");

        GrillaBlog.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        GrillaBlog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Historial", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GrillaBlog.setToolTipText("Tool");
        GrillaBlog.setGridColor(new java.awt.Color(255, 255, 255));
        GrillaBlog.setRowHeight(20);
        GrillaBlog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaBlogMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(GrillaBlog);

        TxHistorial.setColumns(20);
        TxHistorial.setRows(10);
        jScrollPane5.setViewportView(TxHistorial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane5)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lbTotal))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CargaBancos() {

    }

    private void CargaCuentas(String Banco) {

    }
    private void cbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesActionPerformed


    }//GEN-LAST:event_cbMesActionPerformed

    private void cbAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAnioActionPerformed

    }//GEN-LAST:event_cbAnioActionPerformed


    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        if (fmMain.OkCancel("¿Descartar los datos copiados ?") == JOptionPane.OK_OPTION) {
            LimpiaGrilla((DefaultTableModel) Grilla.getModel());
            btGuardar.setVisible(false);
            btCancelar.setVisible(false);
            btNuevoIngreso.setVisible(true);
            cbMes.setEnabled(true);
            cbAnio.setEnabled(true);
        }
    }//GEN-LAST:event_btCancelarActionPerformed

    private void LimpiaGrilla(DefaultTableModel Model) {
        while (Model.getRowCount() > 0) {
            Model.removeRow(0);
        }
    }
    
    
    
    private void CargaBlog(){

        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        String Query ="";
        GrillaBlog.setDefaultRenderer(Object.class, new ImgTabla());
        DefaultTableModel tm = (DefaultTableModel) GrillaBlog.getModel();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy - hh:mm");
        SimpleDateFormat sdf2 = new SimpleDateFormat("dd-MMM-yyyy");
        
        fmMain.LimpiaGrilla(tm);
        
        
        TxHistorial.setText("");
        JLabel lbCall = new JLabel();
        JLabel lbMail = new JLabel();
        JLabel lbFin  = new JLabel();
        JLabel lbIni  = new JLabel();
        JLabel lbInfo = new JLabel();
        
        URL urlCall = this.getClass().getResource("/Iconos/Llamada.png");  
        URL urlMail = this.getClass().getResource("/Iconos/email.png");  
        URL urlIni =  this.getClass().getResource("/Iconos22/Go.png");  
        URL urlFin =  this.getClass().getResource("/Iconos/camion.png");  
        URL urlInfo =  this.getClass().getResource("/Iconos/info.png");
         
        ImageIcon IconoCall =  new ImageIcon(urlCall); 
        ImageIcon IconoMail =  new ImageIcon(urlMail); 
        ImageIcon IconoIni  =  new ImageIcon(urlIni); 
        ImageIcon IconoFin  =  new ImageIcon(urlFin); 
        ImageIcon IconoInfo =  new ImageIcon(urlInfo); 
        
        lbCall.setIcon(IconoCall);
        lbMail.setIcon(IconoMail);
        lbIni.setIcon(IconoIni);
        lbFin.setIcon(IconoFin);
        lbInfo.setIcon(IconoInfo);
        
        try {
            
            Query = "SELECT id,fecha,usuario,texto,tipo,compromiso,fcompromiso\n" +
                            " FROM blog_occ\n" +
                            " where \n " +
                            " codigo_oc = " + Integer.valueOf(GrillaCompara.getValueAt(GrillaCompara.getSelectedRow(), 0).toString().trim())  + " \n" + 
                            " and orden='" + GrillaCompara.getValueAt(GrillaCompara.getSelectedRow(), 1).toString().trim().toLowerCase() + "' order by fecha desc";
            // "rut=" + Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString().trim() + "\n" +
            
            Rs = Sql.Select(Query);
            
            while(Rs.next()){
                 //Tipo 0 = Llamada
                if(Rs.getInt("tipo")==1){
                    tm.addRow(new Object[]{lbCall,sdf.format(Rs.getTimestamp("fecha"))+ "   [" + Rs.getString("usuario").trim().toUpperCase() + "]",Rs.getString("id")});
                    
                }
                //Tipo 1 = Correo
                else if(Rs.getInt("tipo")==2) {
                    tm.addRow(new Object[]{lbMail,sdf.format(Rs.getTimestamp("fecha"))+ "   [" + Rs.getString("usuario").trim().toUpperCase() + "]",Rs.getString("id")});
                }
                // Tipo 2 = Bloque
                else if(Rs.getInt("tipo")==3) {
                    tm.addRow(new Object[]{lbIni,sdf.format(Rs.getTimestamp("fecha"))+ "   [" + Rs.getString("usuario").trim().toUpperCase() + "]",Rs.getString("id")});
                }
                // Tipo 3 = Desbloqueo
                else if(Rs.getInt("tipo")==4) {
                    tm.addRow(new Object[]{lbFin,sdf.format(Rs.getTimestamp("fecha"))+ "   [" + Rs.getString("usuario").trim().toUpperCase() + "]",Rs.getString("id")});
                }
                
                else if(Rs.getInt("tipo")==5) {
                    tm.addRow(new Object[]{lbInfo,sdf.format(Rs.getTimestamp("fecha"))+ "   [" + Rs.getString("usuario").trim().toUpperCase() + "]",Rs.getString("id")});
                }
                
                 //Mensaje
                tm.addRow(new Object[]{" ",Rs.getString("texto"),Rs.getString("id")});
//                if(Rs.getBoolean("compromiso"))
//                    tm.addRow(new Object[]{" ", "Compromiso: " + sdf2.format(Rs.getTimestamp("fcompromiso"))});
                    
            }
            
        } catch (Exception e) {
            fmMain.Mensaje("Ha ocurrido un error");
            LogError.Guardar(this.getClass().getSimpleName(),e.getMessage());
        } finally {
            Sql.Close();
        }
    }

    
    

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        //Validaciones
        try {
            Rs = Sql.Select("select count(*) as existe\n"
                    + "from occh_portal\n"
                    + "where mes=" + cbMes.getSelectedIndex() + "\n"
                    + "and agno =" + cbAnio.getSelectedItem() + ")");
            Rs.next();
            if (Rs.getInt("existe") > 0) {
                fmMain.Mensaje("Ya existen datos para este mes y año. No se puede Guardar");
                Sql.Close();
                return;
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        if (fmMain.OkCancel("¿Desea guardar los datos?") == JOptionPane.OK_OPTION) {
            
            try {
                Sql.ExeSql("delete from occh_portal where mes="+ cbMes.getSelectedIndex() + " and agno="+ cbAnio.getSelectedItem().toString().trim());
                
                for (int i = 0; i < Grilla.getRowCount(); i++) {
                    Sql.ExeSql("insert into occh_portal\n"
                            + "(codigo_oc,orden,totaldoc,mes,agno) values\n"
                            + "(" + fmMain.SetGuardarEntero(Grilla.getValueAt(i, 0).toString().trim()) + ",'"
                            + Grilla.getValueAt(i, 1).toString().trim() +"-"+Grilla.getValueAt(i, 2).toString().trim()+ "',"
                            + fmMain.SetGuardarEntero(Grilla.getValueAt(i, 3).toString().trim()) +","
                            + cbMes.getSelectedIndex() +  ","
                            + cbAnio.getSelectedItem().toString().trim() + ")");
                }
                Sql.Commit();
                fmMain.Mensaje("Datos Guardados");
                btGuardar.setVisible(false);
                btCancelar.setVisible(false);
                btNuevoIngreso.setVisible(true);
                LimpiaGrilla((DefaultTableModel) Grilla.getModel());
                cbMes.setEnabled(true);
                cbAnio.setEnabled(true);
            } catch (Exception e) {
                fmMain.Mensaje("Error al Guardar: " + e.getMessage());
            } finally {
                Sql.Close();
            }
        }


    }//GEN-LAST:event_btGuardarActionPerformed


    private void btNuevoIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoIngresoActionPerformed
        //Validaciones
        if (cbMes.getSelectedIndex() <= 0) {
            fmMain.Mensaje("Debe seleccionar un mes");
            return;
        }

        if (fmMain.OkCancel("¿Desea cargar un listado de Ordenes para el mes de " + cbMes.getSelectedItem().toString().trim() + " del año " + cbAnio.getSelectedItem().toString().trim() + " ?") == JOptionPane.OK_OPTION) {
            String LINE_BREAK = "\n";
            String CELL_BREAK = "\t";
            Clipboard CLIPBOARD = Toolkit.getDefaultToolkit().getSystemClipboard();
            String pasteString = "";

            String Codigo_oc = "";
            String Orden = "";
            String Tipo = "";
            String OrdenG = "";
            String TotalDoc = "";

            DefaultTableModel Model = (DefaultTableModel) Grilla.getModel();

            while (Model.getRowCount() > 0) {
                Model.removeRow(0);
            }

      
            try {
                pasteString = (String) (CLIPBOARD.getContents(this).getTransferData(DataFlavor.stringFlavor));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error", "El elemento copiado es invalido", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                String[] lines = pasteString.split(LINE_BREAK);
                for (int i = 0; i < lines.length; i++) {

                    String[] cells = lines[i].split(CELL_BREAK);
                    Codigo_oc = cells[0];
                    OrdenG = cells[1] + "-" + cells[2];
                    Orden = cells[1];
                    Tipo = cells[2];
                    TotalDoc = cells[3];
                    TotalDoc = fmMain.SetGuardar(TotalDoc);
                    if (TotalDoc.isEmpty()) {
                        TotalDoc = "$ 0";
                    }

                    Model.addRow(new Object[]{Codigo_oc, Orden, Tipo, TotalDoc});
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            btGuardar.setVisible(true);
            btCancelar.setVisible(true);
            btNuevoIngreso.setVisible(false);
            cbMes.setEnabled(false);
            cbAnio.setEnabled(false);
        }

    }//GEN-LAST:event_btNuevoIngresoActionPerformed

    private void cbMesComparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesComparaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMesComparaActionPerformed

    private void cbAnioComparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAnioComparaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAnioComparaActionPerformed

    private void btComparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComparaActionPerformed
        
        if (cbMesCompara.getSelectedIndex() <= 0) {
        
            fmMain.Mensaje("Debe seleccionar un mes");
            return;
        }
        
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        ResultSet Rs2;
        ResultSet Rs3;
        
        DefaultTableModel Model = (DefaultTableModel) GrillaCompara.getModel();
        DefaultTableModel Model2 = (DefaultTableModel) GrillaTotales.getModel();
        
        while (Model.getRowCount() > 0) {
        
            Model.removeRow(0);
        }
        
        while (Model2.getRowCount() > 0) {
        
            Model2.removeRow(0);
        }
        
        try{
            
            Rs = Sql.Select("select a.codigo_oc as codigo_sistema, a.orden as orden_sistema, o.codigo_oc as codigo_ch, o.orden as orden_ch,\n" +
                            " a.totaldocto, a.femision, o.totaldoc, \n" +
                            " CASE WHEN cast(round(cast((o.totaldoc-a.totaldocto) as numeric), 0) as varchar) is null THEN 'No Ingresado' ELSE cast(round(cast((o.totaldoc-a.totaldocto) as numeric), 0) as varchar) END as diferencia from occh_portal o\n" +
                            " left outer join occh a on o.codigo_oc=a.codigo_oc and LOWER(o.orden)=LOWER(a.orden) where o.mes="+cbMesCompara.getSelectedIndex()+" and o.agno="+cbAnioCompara.getSelectedItem().toString().trim()+" \n" +
                            " and o.totaldoc>0 and ((o.totaldoc-a.totaldocto)>2 or (o.totaldoc-a.totaldocto)<-2 or (o.totaldoc-a.totaldocto) is null) order by (o.totaldoc-a.totaldocto) desc");
            while (Rs.next())
            {
                Model.addRow(new Object[]{Rs.getString("codigo_ch"), 
                                          Rs.getString("orden_ch"), 
                                          Rs.getString("diferencia")});                
            }
            
            Rs2 = Sql.Select("select convenio, sum(totventa) as total from (select c.femision, p.convenio as codcon, conv.convenio as convenio, sum(d.cantidad), p.nombre, p.valultcompra,  p.costopromedio,round(d.valorunitario), round(CAST((sum(round(d.cantidad))*d.valorunitario) as numeric)) as totventa\n" +
                            "from occh c\n" +
                            "left join occhdet d on c.rut=d.rut and c.orden=d.orden and c.codigo_oc=d.codigo_oc \n" +
                            "left join producto p on d.sku=p.sku \n" +
                            "left join par_convenio conv on conv.codigo=p.convenio \n" +
                            "right join occh_portal op on c.codigo_oc = op.codigo_oc and c.orden = lower(op.orden) \n" +
                            "where op.mes = "+cbMesCompara.getSelectedIndex()+" and op.agno = "+cbAnioCompara.getSelectedItem().toString().trim()+" and extract(year from cast(c.femision as date))="+cbAnioCompara.getSelectedItem().toString().trim()+" \n" +
                            "and extract(month from cast(c.femision as date))="+cbMesCompara.getSelectedIndex()+" \n" +
                            "group by c.femision, p.convenio, conv.convenio, nombre, p.valultcompra,  p.costopromedio,d.valorunitario) as sel group by convenio");
            
           
            long total=0;
            
            while (Rs2.next()){
                
                Model2.addRow(new Object[]{Rs2.getString("convenio"),Rs2.getString("total")}); 
                
                total= total+Rs2.getLong("total");
            }
            
            lbTotal.setText(String.valueOf(total));
           
        }catch (Exception e){
         
            fmMain.Mensaje("Error: "+e);

        }
        finally{
            Sql.Close();
        }
    }//GEN-LAST:event_btComparaActionPerformed

    private void GrillaBlogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaBlogMouseClicked
        // TODO add your handling code here:
        TxHistorial.setText(GrillaBlog.getValueAt(GrillaBlog.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_GrillaBlogMouseClicked

    private void GrillaComparaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaComparaMouseClicked
        // TODO add your handling code here:
         CargaBlog();
    }//GEN-LAST:event_GrillaComparaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla;
    private javax.swing.JTable GrillaBlog;
    private javax.swing.JTable GrillaCompara;
    private javax.swing.JTable GrillaTotales;
    private javax.swing.JLabel Mes;
    private javax.swing.JLabel Mes1;
    private javax.swing.JTextArea TxHistorial;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCompara;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btNuevoIngreso;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbAnio;
    private javax.swing.JComboBox cbAnioCompara;
    private javax.swing.JComboBox cbMes;
    private javax.swing.JComboBox cbMesCompara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbTotal;
    // End of variables declaration//GEN-END:variables
}
